let data_ko_ta = [
  {
    cNm: '他減 物質',
    eNm: 'allelochemicals',
    hNm: '타감물질',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '他給營養生物',
    eNm: 'heterotroph',
    explain: '엽록소가 없고 유기탄소화합물을 영양원으로 이용하는 생물',
    hNm: '타급영양생물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '他給營養窒酸化昨用 ',
    eNm: 'heterotrophic nitrification',
    explain: '타급(종속)영양미생물에 의한 질산화작용 ',
    hNm: '타급영양질산화작용',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Theis formula',
    explain:
      '피압대수층에 설치된 완전관통정에 양수작업을 수행할때 비정상상태에서 관정 주변 대수층에서 일어나는 수두저하를 바탕으로 저류계수와 투수량계수를 구하기 위해Charles. V. Theis가 만들어낸 공식',
    hNm: '타이스의 공식',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Theis formula',
    explain:
      '피압대수층에 설치된 완전관통정에 양수작업을 수행할때 비정상상태에서 관정 주변 대수층에서 일어나는 수두저하를 바탕으로 저류계수와 투수량계수를 구하기 위해Charles. V. Theis가 만들어낸 공식',
    hNm: '타이스의 공식',
    rgsdt: '2023-10-20',
  },
  {
    eNm: 'Theis solution ',
    hNm: '타이스해법 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '濁度',
    eNm: 'turbidity',
    explain:
      '수중에서 부유물질이나 미립자들에 의해 빛이 분산되거나 흡수되어 물이 흐려진 정도',
    hNm: '탁도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '濁度計',
    eNm: 'turbidity meter',
    explain: '물의 탁한 정도를 측정하는 기기',
    hNm: '탁도계',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '濁水灌漑',
    eNm: 'turbid irrigation',
    explain:
      '부유물을 많이 포유하고 있는 물을 관개하여 부유물을 침전시키기 위한 방법',
    hNm: '탁수관개',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '卓越波 ',
    eNm: 'prevailing wave',
    hNm: '탁월파',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '卓越風',
    eNm: 'prevailing wind',
    explain: '특정 지역에서 특정 기간동안 가장 우세한 풍향의 바람',
    hNm: '탁월풍',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '濁質',
    eNm: 'turbid matter',
    explain: '탁도를 야기하는 물질',
    hNm: '탁질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '炭酸',
    eNm: 'carbonic acid  ',
    explain: '이산화탄소가 물에 녹은 후 생성된 산',
    hNm: '탄산',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'carbonic acid gas',
    explain: '기체의 상태로 존재하는 이산화탄소 CO2',
    hNm: '탄산가스',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '炭酸硬度',
    eNm: 'carbonic acid hardness',
    explain:
      '칼슘이나 마그네슘이온이 (HCO3)- 와 같은 탄산경도와 결합해 있는 것을 의미함',
    hNm: '탄산경도',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'sodium carbonate',
    explain: '나트륨(Na)과 탄산이 만나서 이루어진 화합물',
    hNm: '탄산나트륨',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'sodium carbonate',
    explain: '탄산나트륨으로 소다라고도 불리며 Na2CO3로 표현되는 화합물',
    hNm: '탄산소다',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '炭酸水',
    eNm: 'carbonated water',
    explain: '이산화탄소(탄산가스)를 용해한 단순한 음료',
    hNm: '탄산수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '炭酸水素',
    eNm: 'bicarbonate',
    explain: '탄산 화합물이 수소 원자 하나를 잃어 형성된 화합물',
    hNm: '탄산수소',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'bicarbonate alkalinity',
    explain: 'HCO3-에 의한 알칼리도 ',
    hNm: '탄산수소알칼리도',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'hydrogen carbonate ion',
    explain: '중탄산이라고도 불리우며, HCO3-로 표현되는 화합물',
    hNm: '탄산수소이온',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '炭酸亞鉛',
    eNm: 'zinc carbonate',
    explain:
      '탄산의 아연염으로 천연으로도 산출되며, 화학식은 ZnCO3로 표현되는 화합물',
    hNm: '탄산아연',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'carbonate alkalinity, carbonic alkalinity',
    explain: '용존된 CO2의 계열인 HCO3-, CO32-에 의해 주로 생성되는 알칼리도',
    hNm: '탄산알칼리도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '炭酸鹽',
    eNm: 'carbonate',
    explain:
      '이산화탄소와 금속산화물로 되어 있는 염으로 탄산(H2CO3) 중 수소가 금속으로 치환되어 생기는 염을 의미',
    hNm: '탄산염',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '炭酸鹽硬度',
    eNm: 'carbonate hardness',
    explain:
      '물의 세기인 경도를 나타내는 물질 중에 탄산염에 의해 나타나는 경도',
    hNm: '탄산염 경도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '炭酸―當量 ',
    eNm: 'calcium carbonate equivalent',
    hNm: '탄산칼슘당량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '彈性波層序學',
    eNm: 'seismic stratigraphy',
    explain: '지진파의 속도 대비로 층을 나누는 방법',
    hNm: '탄성파층서학',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '低速度層',
    eNm: 'seismic survey',
    explain: '지진파를 이용해 지구 내부를 조사하는 지구 물리 탐사 방법',
    hNm: '탄성파탐사',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '炭素同化作用',
    eNm: 'carbon dioxide assimilation',
    explain:
      '엽록체를 가진 녹색식물이 공기 중에서 흡수한 이산화탄소와 뿌리에서 흡수한 물, 그리고 광 에너지를 이용하여 탄수화물을 만드는 작용',
    hNm: '탄소동화작용',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '彈塑性 生物化學的 酸素要求量',
    eNm: 'carbonaceous biochemical oxygen demand, CBOD',
    explain:
      '물속에 있는 영양물 중 탄소화합물질이 분해될 때 발생하는 생물화학적 산소요구량',
    hNm: '탄소성 생물화학적 산소요구량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '炭素循環',
    eNm: 'carbon cycle',
    hNm: '탄소순환',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '炭素循環',
    eNm: 'carbon cycle',
    hNm: '탄소순환',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '炭水化物',
    eNm: 'carbohydrates',
    explain: '탄소(C)·수소(H)·산소(O)의 세 원소로 구성되어져 있는 화합물',
    hNm: '탄수화물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '炭窒比',
    eNm: 'carbon-nitrogen ratio',
    explain: '탄소와 질소간의 물질 비율',
    hNm: '탄질비',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '炭化水素',
    eNm: 'hydrocarbon',
    explain: '탄소와 수소로만 구성되어져 있는 유기화합물의 총칭',
    hNm: '탄화수소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫氣',
    eNm: 'deaeration',
    explain:
      '수중에 용존된 탄산가스, 암모니아 등의 기체 성분을 제거하는 것을 말함',
    hNm: '탈기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫氣法',
    eNm: 'air stripping',
    explain:
      '오염된 물이나 폐수 등 복원에 사용되는 기술로 기체를 공급하여 질소, 탄소 가스 등을 제거하는 것',
    hNm: '탈기법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫氣塔',
    eNm: 'deaeration tower',
    explain: '탈기에 사용하는 탑',
    hNm: '탈기탑',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫離液',
    eNm: 'supernatant liquid',
    explain:
      '하수를 활성슬러지법으로 처리할 때 발생하는 잉여슬러지를 혐기성분해하고 남은 액체를 의미함',
    hNm: '탈리액',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫砒素',
    eNm: 'dearsenic',
    explain: '물속에 함유되어 있는 비소를 제거하는 것을 의미함',
    hNm: '탈비소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫酸',
    eNm: 'deoxidation',
    explain: '용융상태에 있는 금속 안에 녹아 있는 산소를 제거하는 일',
    hNm: '탈산 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫酸素',
    eNm: 'deoxygenation  ',
    explain: '수중의 용존산소가 소비되는 현상',
    hNm: '탈산소 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫酸素係數',
    eNm: 'deoxygenation coefficient',
    explain: '미생물이 유기물을 분해하는데 소비되는 산소요구량',
    hNm: '탈산소계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫酸素係數',
    eNm: 'deoxygenation coefficient',
    explain: '미생물이 유기물을 분해하는데 소비되는 산소요구량',
    hNm: '탈산소계수',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '脫酸素反應',
    eNm: 'deoxygenation reaction',
    hNm: '탈산소반응(하천수의)',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '脫酸素反應',
    eNm: 'deoxygenation reaction',
    hNm: '탈산소반응(하천수의)',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '脫酸素反應',
    eNm: 'deoxygenation reaction',
    hNm: '탈산소반응(하천수의)',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '脫水',
    eNm: 'dewatering',
    hNm: '탈수',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '脫水',
    eNm: 'dewatering',
    hNm: '탈수',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '脫水性',
    eNm: 'dewaterability',
    explain: '슬러지 탈수에 있어서 슬러지의 고액 분리성',
    hNm: '탈수성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫水性',
    eNm: 'dewaterability',
    explain: '슬러지 탈수에 있어서 슬러지의 고액 분리성',
    hNm: '탈수성',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '脫水汚泥',
    eNm: 'dewatered sludge, sludge cake',
    explain: '고형물로서 취급할 수 있을 정도까지 탈수된 슬러지',
    hNm: '탈수슬러지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫水濾過',
    eNm: 'dewatering filtration',
    explain: '슬러지에서 수분을 뺏기 위해 여과하는 것을 의미함',
    hNm: '탈수여과',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫水濾液',
    eNm: 'filtered water',
    hNm: '탈수여액',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '脫水濾液',
    eNm: 'filtered water',
    hNm: '탈수여액',
    rgsdt: '2023-10-10',
  },
  {
    eNm: 'dewatered cake',
    hNm: '탈수케이크',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'dewatered cake',
    hNm: '탈수케이크',
    rgsdt: '2023-10-10',
  },
  {
    eNm: 'deamination',
    explain:
      '아미노기를 갖는 화합물로부터 아미노기를 떼어내 암모니아를 생성하는 생화학 반응',
    hNm: '탈아미노반응',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫鹽',
    eNm: 'desalination, leaching',
    explain: '시료, 특히 액체 시료에 포함되어 있는 염류를 제거하는 것',
    hNm: '탈염',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫鹽素',
    eNm: 'dechlorination',
    explain: '물속에 존재하는 잔류염소를 제거하는 것을 의미함',
    hNm: '탈염소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫鹽水',
    eNm: 'desalted water',
    explain: '물속에 용존하는 대부분의 염류의 제거한 정제수',
    hNm: '탈염수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫鹽化作用',
    eNm: 'desalinization',
    explain:
      '토양 속에 집적된 가용성 염류가 토층 내의 아래쪽으로의 수분이동에 의해 제거되는 것',
    hNm: '탈염화작용',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'deionization',
    explain: '물속에 용해되어 있는 이온들을 모두 제거하는 것',
    hNm: '탈이온',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫燐',
    eNm: 'phosphorus removal',
    explain: '하수나 폐수와 같은 물이나 시료 등에서 인(P)을 제거하는 것',
    hNm: '탈인',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫燐法',
    eNm: 'phosphorus removal',
    explain: '인을 제거하는 방법을 말함',
    hNm: '탈인법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫窒',
    eNm: 'denitrification',
    explain:
      '질산염이 탈질세균에 의해 환원되어 N2O나 N2의 기체 상태로 공기 중으로 돌아가는 것',
    hNm: '탈질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫窒反應',
    eNm: 'denitrification',
    hNm: '탈질반응',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '脫窒細菌',
    eNm: 'deniturfying bacteria',
    explain: '탈질을 일으키는 세균을 의미함',
    hNm: '탈질세균',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫窒素作用',
    eNm: 'denitrification',
    explain: '질산 또는 아질산으로 질소가스를 생성해 대기 중으로 방출하는 작용',
    hNm: '탈질소작용',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '脫窒速度',
    eNm: 'denitrification rate',
    explain: '탈질세균에 의해 질산염이 탈질되는 속도',
    hNm: '탈질속도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫窒作用',
    eNm: 'denitrification',
    explain: '질산 또는 아질산을 질소가스를 생성해 대기 중으로 방출하는 작용',
    hNm: '탈질작용',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫窒裝置',
    eNm: 'deniturification equipment',
    explain:
      '암모늄이나 유기질소 및 질산 가스 등을 N2나 N2O로 만들어 공기 중으로 날려 보내는 장치를 의미함',
    hNm: '탈질장치',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫着',
    eNm: 'desorption',
    explain:
      '활성탄과 같은 흡착제에 흡착된 피흡착질이 흡착제로부터 분리되는 현상',
    hNm: '탈착',
    rgsdt: '2016-04-15',
  },
  {
    cNm: ' 脫臭法',
    eNm: 'deodorization method',
    explain:
      '유지가 가지는 냄새를 제거하는 것을 탈취라 하고 탈취하는 여러 가지 방법들을 탈취법이라 함',
    hNm: '탈취법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫臭法',
    eNm: 'deodorization method',
    explain:
      '유지가 가지는 냄새를 제거하는 것을 탈취라 하고 탈취하는 여러 가지 방법들을 탈취법이라 함',
    hNm: '탈취법',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '脫臭制',
    eNm: 'deodorant',
    explain: '악취 제거를 위해 사용되는 약제',
    hNm: '탈취제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫炭酸',
    eNm: 'decarbonization; decarbonation',
    explain: '물속에 존재하는 탄산가스를 제거하는 것',
    hNm: '탈탄산',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '脫炭酸',
    eNm: 'decarbonization; decarbonation',
    explain: '물속에 존재하는 탄산가스를 제거하는 것',
    hNm: '탈탄산',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '脫黃',
    eNm: 'desulfurization',
    explain:
      '여러 가지 물질에서 황(S)원자나 황 화합물 등을 제거하는 것을 탈황이라 함',
    hNm: '탈황',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脫黃裝置 ',
    eNm: 'desulfurization equipment',
    explain: '액체 또는 기체 속에 포함된 황 성분을 제거하는 장치',
    hNm: '탈황장치',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '探査地質學',
    eNm: 'exploration geology',
    explain:
      '지구물리적/화학적/생물학적 방법을 이용하여 지구의 여러 특성을 규명하는 지질학의 한 분야',
    hNm: '탐사지질학',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '太陽界',
    eNm: 'solar system',
    explain: '태양과 태양 주변을 공전하는 천체들로 이루어진 계',
    hNm: '태양계',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '太陽高度',
    eNm: 'solar altitude, solar elevation, sun’s altitude',
    explain: '태양의 수평면으로부터의 각거리',
    hNm: '태양고도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '太陽氣候',
    eNm: 'solar climate',
    explain: '복사량을 결정하기 위한 수리기후학의 방법인 가상 기후',
    hNm: '태양기후',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '太陽輻射',
    eNm: 'solar radiation, insolation',
    explain: '태양으로부터 복사되는 전자기파',
    hNm: '태양복사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '太陽輻射收支',
    eNm: 'balance of solar radiation',
    hNm: '태양복사수지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '太陽常數',
    eNm: 'solar constant',
    hNm: '태양상수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '太陽日',
    eNm: 'solar day',
    explain: '지구가 태양에 대해 자전하는데 걸리는 시간',
    hNm: '태양일',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '太陽紫外輻射',
    eNm: 'solar ultraviolet radiation',
    hNm: '태양자외복사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '太陽電池',
    eNm: 'solar cell',
    hNm: '태양전지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '太陽風',
    eNm: 'solar wind',
    explain: '태양에 의해 방출되는 전기를 띤 입자들의 흐름',
    hNm: '태양풍',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '太陽黑點',
    eNm: 'sunspot',
    explain: '태양표면에 검게 나타나는 부분',
    hNm: '태양흑점',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '颱風',
    eNm: 'typhoon',
    explain:
      '북태평양 남서부에서 발생하여 아시아 동부로 불어오는 중심최대풍속이 17m/s 이상(세계기상기구 기준 33m/s)인 맹렬한 열대저기압',
    hNm: '태풍',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '颱風',
    eNm: 'typhoon',
    explain:
      '북태평양 남서부에서 발생하여 아시아 동부로 불어오는 중심최대풍속이 17m/s 이상(세계기상기구 기준 33m/s)인 맹렬한 열대저기압',
    hNm: '태풍',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '颱風經路',
    eNm: 'track of typhoon, typhoon track',
    explain: '태풍이 발생 초기부터 소멸하는 최종 단계까지 움직이는 경로',
    hNm: '태풍경로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '颱風警報',
    eNm: 'typhoon warning',
    hNm: '태풍경보',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'eye of typhoon',
    explain: '비교적 안정된 기상현상이 나타나는 태풍의 중심 부분',
    hNm: '태풍의 눈',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '台形貯溜',
    eNm: 'prism storage',
    explain: '저류하는 하도에서 하상에 평행한 선 이하의 부분',
    hNm: '태형저류',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'tank model',
    hNm: '탱크모형',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'tank model',
    hNm: '탱크모형',
    rgsdt: '2023-06-29',
  },
  {
    cNm: '洗滌水',
    eNm: 'tank washing water',
    explain:
      '탱크가 석유를 양육한 다음에 선창을 해수, 소다액, 스팀 등으로 세척한 물',
    hNm: '탱크세척수',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'tunnel spillway',
    hNm: '터널여수로',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'turbine, hydraulic turbine, water turbine, water wheel, wheel',
    explain:
      '물 가스 증기 등의 유체가 가지는 에너지를 기계적인 동력에너지로 변환시키는 것',
    hNm: '터빈 ',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'tainter gate',
    explain: '상하로 회전하여 열고 닫는 부채모양의 수문',
    hNm: '테인터 게이트',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'tetralchloroethene',
    explain: 'IUPAC에서 사용하는 이름으로 화학식 CCl2 =CCl2 인 사염화에틸렌',
    hNm: '테트라클로로에틴',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'tetrachloroethylene',
    explain: '화학식 CCl2 =CCl2 인 사염화에틸렌',
    hNm: '테트라클로로에틸렌',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吐口',
    eNm: 'sewer outlet, outfall, outfall works',
    hNm: '토구',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '吐口',
    eNm: 'sewer outlet, outfall, outfall works',
    hNm: '토구',
    rgsdt: '2023-06-29',
  },
  {
    eNm: 'tornado',
    explain:
      '넓은 평지나 바다에서 주로 발생하는 깔때기 모양의 매우 강력한 회오리 바람',
    hNm: '토네이도',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'tornado',
    explain:
      '넓은 평지나 바다에서 주로 발생하는 깔때기 모양의 매우 강력한 회오리 바람',
    hNm: '토네이도',
    rgsdt: '2023-10-20',
  },
  {
    eNm: 'Torricelli’s tube',
    explain: '한쪽이 닫힌 형태로 대기압 측정용 실험 유리관',
    hNm: '토리첼리관',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '定理',
    eNm: "Torricelli's theorem",
    explain:
      '질점(material point)이 중력의 작용으로 자유낙하 할 때 의 속도와 높이와의 관계를 나타낸 식입니다.',
    hNm: '토리첼리의 정리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '定理',
    eNm: "Torricelli's theorem",
    explain:
      '질점(material point)이 중력의 작용으로 자유낙하 할 때 의 속도와 높이와의 관계를 나타낸 식입니다.',
    hNm: '토리첼리의 정리',
    rgsdt: '2023-10-20',
  },
  {
    eNm: 'Torricellian vacuum',
    explain:
      '한쪽이 닫힌 유리관에 수은주를 넣어 세웠을 때 그 윗부분에 발생한 진공',
    hNm: '토리첼리진공',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Thomas-Camp’s equation',
    hNm: '토머스캠프식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土性',
    eNm: 'soil texture',
    explain: '토양 내 모래, 실트, 점토 입자의 상대적인 비율을 의미',
    hNm: '토성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土性',
    eNm: 'soil texture',
    explain: '토양 내 모래, 실트, 점토 입자의 상대적인 비율을 의미',
    hNm: '토성',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '土深',
    eNm: 'soil depth',
    explain: '표토로부터 기반암까지 토양의 수직적 깊이',
    hNm: '토심',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤水分未洽量',
    eNm: 'soil moisture deficit',
    hNm: '토앙수분미흡량',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '土壤水分未洽量',
    eNm: 'soil moisture deficit',
    hNm: '토앙수분미흡량',
    rgsdt: '2023-06-29',
  },
  {
    cNm: '土壤',
    eNm: 'soil',
    explain: '흙이라고도 하며, 대부분 암석의 풍화물로 구성',
    hNm: '토양',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤 孔隙',
    eNm: 'soil pores',
    explain: '토양체를 구성하는 토양 및 유기물 입자 사이의 빈 공간',
    hNm: '토양 공극',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤 緩衝力',
    eNm: 'soil buffering',
    hNm: '토양 완충력',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '土壤 貯藏水',
    eNm: 'soil storage',
    explain: '토양입자와 물분자 사이의 인력에 의해 토양에 유지되는 물',
    hNm: '토양 저장수',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '土壤 貯藏水',
    eNm: 'soil storage',
    explain: '토양입자와 물분자 사이의 인력에 의해 토양에 유지되는 물',
    hNm: '토양 저장수',
    rgsdt: '2023-09-18',
  },
  {
    eNm: 'soil drought',
    explain:
      '지속되는 건조기후로 토양 내의 수분의 함량이 식물이 사용할 수 없을 정도로 낮아진 상태',
    hNm: '토양가뭄',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'soil gas',
    explain: '토양에서 발생하는 가스를 의미',
    hNm: '토양가스',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤剛度',
    eNm: 'soil strength',
    hNm: '토양강도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤改良',
    eNm: 'soil amendment',
    explain: '작물 재배에 알맞게 흙을 개량하는 것',
    hNm: '토양개량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤改良劑',
    eNm: 'soil conditioner, soil improvement additive',
    explain:
      '토양의 물리화학적 성질을 식물생육에 알맞게 개선하여 생산성을 높이기 위해 사용되는 거름 등의 여러 가지 제품',
    hNm: '토양개량제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤檢定',
    eNm: 'soil test',
    explain:
      '과학적 근거에 의한 작물의 시비량을 결정하기 위하여 포장에서 채취한 토양시료를 대상으로 유효양분함량 또는 석회소요량을 측정하는 분석 작업',
    hNm: '토양검정',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤固有微生物',
    eNm: 'autochthonous microorganism',
    explain: '고유의 생식 장소에서 변화가 적은 미생물 집단',
    hNm: '토양고유미생물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤空隙性質',
    eNm: 'pore nature of soil',
    explain: '토양에 존재하는 공극 표면의 물리적 성질',
    hNm: '토양공극성질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤空氣 ',
    eNm: 'soil atmosphere, soil air',
    explain: '토양 중의 존재하는 기체를 토양공기라고 함',
    hNm: '토양공기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤構造',
    eNm: 'soil structure',
    explain: '흙 입자의 결합 상태나 공간 배열 상태',
    hNm: '토양구조',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤保全',
    eNm: 'soil conservation',
    hNm: '토양보전',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤腐蝕',
    eNm: 'soil corrosion',
    explain: '토양으로 인해 금속이 부식되는 것 ',
    hNm: '토양부식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤肥沃度',
    eNm: 'soil fertility',
    explain: '토양에 유기물과 영양염류가 포함되어져 있는 정도를 나타내는 용어 ',
    hNm: '토양비옥도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤酸度',
    eNm: 'soil acidity',
    explain: '토양의 산성정도',
    hNm: '토양산도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤三象',
    eNm: 'three phases of soil',
    explain:
      '토양체를 구성하고 있는 고체 입자와 공극을 채우고 있는 물과 기체를 의미함',
    hNm: '토양삼상',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤疏水性',
    eNm: 'soil hydrophobicity',
    explain: '물과의 친화성이 적은 토양이 수화에 저항하려는 성질',
    hNm: '토양소수성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤水',
    eNm: 'soil moisture , soil water',
    explain: '토양을 구성하는 기상, 액상, 고상의 3성분 중 액상으로 존재하는 것',
    hNm: '토양수',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '土壤水',
    eNm: 'soil moisture , soil water',
    explain: '토양을 구성하는 기상, 액상, 고상의 3성분 중 액상으로 존재하는 것',
    hNm: '토양수',
    rgsdt: '2023-09-18',
  },
  {
    cNm: '土壤水 特性曲線',
    eNm: 'soil water characteristic curve',
    hNm: '토양수 특성곡선',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '土壤水 特性曲線',
    eNm: 'soil water characteristic curve',
    hNm: '토양수 특성곡선',
    rgsdt: '2023-06-29',
  },
  {
    cNm: '土壤水帶',
    eNm: 'soil water zone',
    explain: '지하환경에서 비포화대 또는 통기대의 최상부층',
    hNm: '토양수대',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤水分',
    eNm: 'soil moisture',
    explain: '토양 내부에 존재하는 물',
    hNm: '토양수분',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤水分量',
    eNm: 'soil moisture content',
    explain: '건조한 토양에 포함되어 있는 모든 수분의 함유량',
    hNm: '토양수분량',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '土壤水分 保有曲線',
    eNm: 'water retention curve',
    explain: '토양수분장력과 토양수분함량 간의 함수관계를 나타내는 곡선',
    hNm: '토양수분보유곡선',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '土壤水分不足',
    eNm: 'deficit of water',
    explain: '토양에서 함유한 수분이 부족하여 생리기작이 장해를 받는 상태',
    hNm: '토양수분부족',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '土壤水分常數',
    eNm: 'soil moisture constant',
    explain: '？특정 조건에서의 토양내 물의 함량을 나타내는 상수들을 말한다.',
    hNm: '토양수분상수',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '土壤水分壓',
    eNm: 'soil water pressure',
    hNm: '토양수분압',
    rgsdt: '2016-11-23',
  },
  {
    hNm: '토양수분응력',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '土壤水分張力',
    eNm: 'soil moisture tension',
    explain:
      '토양입자표면과 흡착되어 있는 수분사이의 결합력을 압력단위로 표시한 것',
    hNm: '토양수분장력',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '土壤水分張力',
    eNm: 'soil moisture tension',
    explain:
      '토양입자표면과 흡착되어 있는 수분사이의 결합력을 압력단위로 표시한 것',
    hNm: '토양수분장력',
    rgsdt: '2023-09-18',
  },
  {
    cNm: '土壤水分追跡法',
    eNm: 'soil moisture tracking method',
    hNm: '토양수분추적법',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '土壤水分追跡法',
    eNm: 'soil moisture tracking method',
    hNm: '토양수분추적법',
    rgsdt: '2023-06-29',
  },
  {
    eNm: 'soil water potential',
    hNm: '토양수분퍼텐셜',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '土壤汚染',
    eNm: 'soil pollution',
    explain:
      '토양에 존재하는 생태계의 건전성을 저해하고 토양 고유의 자연환경요소로서의 기능을 상실하게 하는 물질들이 토양에 유입되는 것',
    hNm: '토양오염',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤有機物 ',
    eNm: 'soil organic matter',
    explain:
      '동식물의 사체 및 배설물 등이 미생물에 의해 분해되어 부식으로 변환된 토양 중의 유기물을 의미',
    hNm: '토양유기물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤流失',
    eNm: 'soil loss',
    explain:
      '비와 바람에 의한 침식에 의해 토양입자가 날아가 토양에 흙이 줄어드는 것',
    hNm: '토양유실',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤酸性化',
    eNm: 'acidification of soil',
    explain: '자연적 또는 인위적 현상에 의해 토양의 pH가 감소하는 현상',
    hNm: '토양의 산성화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤殘留性農藥',
    eNm: 'soil residual pesticide',
    explain:
      '농작물의 병해충방제 또는 제초를 위해 농작물, 목초 또는 토양에 살포한 후 분해되지 않고 농작물 중에 남아있는 농약',
    hNm: '토양잔류성농약',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤殘留性農藥',
    eNm: 'soil residual pesticide',
    explain:
      '농작물의 병해충방제 또는 제초를 위해 농작물, 목초 또는 토양에 살포한 후 분해되지 않고 농작물 중에 남아있는 농약',
    hNm: '토양잔류성농약',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '土壤淨化法',
    eNm: 'soil remediation',
    explain:
      '토양권에 서식하는 토양미생물이 유기물을 분해하는 기능을 활용한 처리공법',
    hNm: '토양정화법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤質',
    eNm: 'soil quality',
    explain: '특정한 생태학적 기능을 수행할 수 있는 토양의 능력을 나타내는 말',
    hNm: '토양질',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '土壤浸蝕',
    eNm: 'soil erosion',
    explain: '강수나 바람에 의해서 토양이 이동하여 유실되는 현상',
    hNm: '토양침식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤浸透處理',
    eNm: 'land filtration, ground leaching',
    explain:
      '오염된 물을 토양으로 침투시켜서 물이 공극을 통해 이동하는 과정에서 여과작용으로 정화되게 하는 것',
    hNm: '토양침투처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤透水性',
    eNm: 'soil permeability',
    explain: '토양이 그 매체를 통해서 물을 흘려보내는 능력',
    hNm: '토양투수성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤表面溫度',
    eNm: 'temperature of the soil surface',
    explain: '토양 표면의 온도',
    hNm: '토양표면온도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤被覆 ',
    eNm: 'soil cover',
    explain:
      '토양에 존재하는 수분의 증발이나 비바람에 의한 흙의 손실 등을 막기 위해 토양표면에 다른 물질들을 피복하는 것',
    hNm: '토양피복',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤含水率',
    eNm: 'soil moisture content',
    explain:
      '토양에 함유되어 있는 물의 체적 또는 질량과 건조토양 체적 또는 질량과의 비율',
    hNm: '토양함수율',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土壤還元',
    eNm: 'land application',
    explain:
      '토양처리의 일종으로 토양에 있는 미생물을 이용하여 유기물질을 처리하는 방법',
    hNm: '토양환원',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土地界汚染源',
    eNm: 'land pollutant source',
    hNm: '토지계오염원',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '土地利用 ',
    eNm: 'land use',
    explain: '주거지, 상업용지, 주택지, 도로, 주차장 등으로 토지를 이용하는 것',
    hNm: '토지이용',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土地處理 ',
    eNm: 'land treatment',
    explain:
      '하수 또는 하수슬러지를 토양에 살포한 후 미생물의 분해기능에 의해 처리되도록 하는 처리법의 일종',
    hNm: '토지처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土質力學',
    eNm: 'soil mechanics',
    explain: '건축, 토목 등의 설계와 시공을 목적으로 한 토질공학의 기초이론',
    hNm: '토질역학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土質調査',
    eNm: 'soil exploration, soil investigation, soil surveying',
    explain:
      '구조물을 만들 때에 필요한 지반구성, 흙의 역학적·공학적 성질을 얻기 위한 조사의 총칭',
    hNm: '토질조사',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'earth curtain wall',
    explain: '진흙,모래, 자갈 등 토질재료를 이용하여 만든 차수벽',
    hNm: '토질차수벽',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '土出管',
    eNm: 'delivery pipe, discharge pipe',
    hNm: '토출관',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'toluene',
    explain: '벤젠에 있는 1개의 수소원자를 메틸기로 치환한 화합물',
    hNm: '톨루엔',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '？管',
    eNm: 'drainage conduit',
    hNm: '통관',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '通管',
    eNm: 'drainage conduit',
    hNm: '통관',
    rgsdt: '2023-06-29',
  },
  {
    cNm: '通氣帶',
    eNm: 'vadose zone',
    explain:
      '지하수의 수직적 분포에서 지하수면 위쪽에 공극이 지하수로 포화되지 않은 토양층.',
    hNm: '통기대',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '通氣帶',
    eNm: 'vadose zone',
    explain:
      '지하수의 수직적 분포에서 지하수면 위쪽에 공극이 지하수로 포화되지 않은 토양층.',
    hNm: '통기대',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '通門',
    eNm: 'sluiceway, sluice',
    explain: '하천용수의 취수 및 하천 배수를 위한 수문',
    hNm: '통문',
    rgsdt: '2016-04-15',
  },
  {
    hNm: '통선 수문',
    rgsdt: '2016-11-25',
  },
  {
    hNm: '통선 수문',
    rgsdt: '2023-06-29',
  },
  {
    hNm: '통선로',
    rgsdt: '2016-11-25',
  },
  {
    hNm: '통선로',
    rgsdt: '2023-06-29',
  },
  {
    cNm: '通性嫌氣性菌',
    eNm: 'facultative anaerobic bacteria',
    explain:
      '미생물 중 산소가 존재하는 호기성이나 산소가 없는 혐기성 조건 모두에서 살아갈 수 있는 미생물',
    hNm: '통성혐기성균(통성혐기성세균)',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '通水距離',
    eNm: 'reduced distance',
    hNm: '통수거리',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '通水距離',
    eNm: 'reduced distance',
    hNm: '통수거리',
    rgsdt: '2023-06-29',
  },
  {
    cNm: '通水能',
    eNm: 'discharge capacity',
    explain:
      '주어진 경사에서 수로의 통수능력, 즉 얼마나 큰 유량으로 물이 흐를 수 있는지를 나타내는 척도로 수로단면이 클수록, 조도계수가 작을수록 큰 값을 가짐',
    hNm: '통수능',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '通水斷面績',
    eNm: 'flow area',
    hNm: '통수단면적',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '通水斷面績',
    eNm: 'flow area',
    hNm: '통수단면적',
    rgsdt: '2023-06-29',
  },
  {
    cNm: '通水倍量',
    eNm: 'contact volume',
    explain: '충전탑을 통과하여 나온 배출액의 부피를 충전물의 부피로 나눈것',
    hNm: '통수배량',
    rgsdt: '2016-11-23',
  },
  {
    hNm: '통합환경관리',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '堆肥 ',
    eNm: 'Compost',
    explain: '짚이나 잡초, 낙엽, 동물의 변 등을 퇴적하여 발효시킨 비료',
    hNm: '퇴비',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '堆肥化',
    eNm: 'Composting',
    explain: '슬러지와 쓰레기를 분뇨 등의 처리방법으로 이용하는 방법',
    hNm: '퇴비화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '堆砂位',
    eNm: 'Sediment Water Level',
    hNm: '퇴사위',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '堆砂位',
    eNm: 'Sediment Water Level',
    hNm: '퇴사위',
    rgsdt: '2023-06-29',
  },
  {
    cNm: '堆積',
    eNm: 'deposit, deposition',
    explain: '다른 지역에서 운반되어 온 고체물들이 지표면에 쌓이는 현상',
    hNm: '퇴적',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '堆積物 安定化',
    eNm: 'stabilization of sediment',
    hNm: '퇴적물 안정화',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '堆積物 浚渫',
    hNm: '퇴적물 준설',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '堆積物 浚渫',
    hNm: '퇴적물 준설',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '堆積物 被服',
    hNm: '퇴적물 피복',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '堆積物 被服',
    hNm: '퇴적물 피복',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '堆積岩 ',
    eNm: 'sedimentary rock ',
    explain: '퇴적물들이 낮은 지면이나 해양에 쌓여 과화작용을 받아 굳어진 암석',
    hNm: '퇴적암 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '堆積層',
    eNm: 'accumulation layer',
    explain: '퇴적작용에 의해 만들어지는 지층',
    hNm: '퇴적층',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '退化',
    eNm: 'degeneration',
    explain: '어떤 생명체의 특정 기관이 사라지거나 그 기능을 잃어버리는 것',
    hNm: '퇴화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '透過性',
    eNm: 'permeability',
    explain: '막이 유체, 이온, 용질, 용매 등을 투과시키는 성질',
    hNm: '투과성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '透過損失',
    eNm: 'transmission loss',
    explain: '차음 재료의 음을 차단하는 효과를 나타내는 값',
    hNm: '투과손실',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '透過水製',
    eNm: 'permeable spur',
    hNm: '투과수제',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '透過水製',
    eNm: 'permeable spur',
    hNm: '투과수제',
    rgsdt: '2023-06-29',
  },
  {
    cNm: '透明度',
    eNm: 'transparency',
    explain: '액체의 투명한 정도를 나타낸 것',
    hNm: '투명도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '透析',
    eNm: 'dialysis',
    explain:
      '막에 의해 분리된 용액속의 용질을, 그 농도차를 구동력으로 해서 막을 투과시키는 것',
    hNm: '투석',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '透析',
    eNm: 'dialysis',
    explain:
      '막에 의해 분리된 용액속의 용질을, 그 농도차를 구동력으로 해서 막을 투과시키는 것',
    hNm: '투석',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '透析膜',
    eNm: 'dialyzing diaphragm',
    explain: '투석법에 사용하는 막을 총칭',
    hNm: '투석막',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '透析法',
    eNm: 'dialysis',
    hNm: '투석법',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '透析法',
    eNm: 'dialysis',
    hNm: '투석법',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '透析法',
    eNm: 'dialysis',
    hNm: '투석법',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '透水係數',
    eNm: 'permeability coefficient',
    explain:
      '유체(일반적으로 물)가 토양이나 암석 등의 다공성 매체를 통과하는데 있어서 그 용이도를 나타내는 척도',
    hNm: '투수계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '透水係數',
    eNm: 'permeability coefficient',
    explain:
      '유체(일반적으로 물)가 토양이나 암석 등의 다공성 매체를 통과하는데 있어서 그 용이도를 나타내는 척도',
    hNm: '투수계수',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '透水度 ',
    eNm: 'permeability ',
    explain: '암석이나 토양에서 물이 통과 할수 있는 정도',
    hNm: '투수도 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '透水量係數',
    eNm: 'transmissivity',
    explain:
      '포화대의 두께에 수리전도도를 곱한 값으로 대수층에 대한 물의 투수도를 나타내는 계수',
    hNm: '투수량계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '透水性',
    eNm: 'permeability',
    explain: '토양의?구조를?손상하지?않고?물이나 유체를?통과시키는?성질',
    hNm: '투수성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '透水性巖盤',
    eNm: 'transmissibility bedrock',
    hNm: '투수성 암반',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '透水性巖盤',
    eNm: 'transmissibility bedrock',
    hNm: '투수성 암반',
    rgsdt: '2023-09-18',
  },
  {
    cNm: '透水性地層',
    eNm: 'transmissibility stratum',
    explain: '물을 통과 시킬 수 있는 투수성을 가진 지층',
    hNm: '투수성 지층',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '透水性河床',
    eNm: 'transmissibility river bed',
    explain: '물을 통과시킬 수 있는 투수성을 가진 하상',
    hNm: '투수성 하상',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '透水性護岸',
    eNm: 'transmissibility bank protection',
    explain: '물을 통과시킬 수 있는 투수성을 가진 호안',
    hNm: '투수성 호안',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'permeable block',
    hNm: '투수성블럭',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'permeable block',
    hNm: '투수성블럭',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '透水性鋪裝',
    eNm: 'permeable pavement',
    hNm: '투수성포장',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '透水性鋪裝',
    eNm: 'permeable pavement',
    hNm: '투수성포장',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '透水試驗 ',
    eNm: 'permeability test',
    explain: '토양의 투수계수를 구하기 위해 수행하는 시험',
    hNm: '투수시험',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '透水率',
    eNm: 'coefficient of water permeability',
    explain: '극을 포함하는 여재를 유체가 잘 통과하는지를 나타낸 것',
    hNm: '투수율',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '透水測定器',
    eNm: 'permeameter',
    hNm: '투수측정기',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '透視圖',
    eNm: 'transparency',
    explain: '시료의 맑은 정도를 표시하는 지표',
    hNm: '투시도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '透視度計',
    eNm: 'transparency meter',
    explain: '투시도를 측정하는 계측기',
    hNm: '투시도계',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'transparency and turbidity',
    explain:
      '투시도는 물의 맑음을 나타내며, 탁도는 물의 흐림 정도를 나타내는 것',
    hNm: '투시도와 탁도',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'tundra climate',
    explain:
      '냉대기후에 가까우며 동토기후라고도 하며 수목이 없는 평야지대를 말한다.',
    hNm: '툰드라기후',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'trap',
    hNm: '트랩 ',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'trumpet joint',
    hNm: '트럼펫이음',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'trench drain',
    hNm: '트렌치 배수구',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'trichloramine',
    explain:
      '트리클로라민의 화학식은 NCl3으로 표현된다. 정수처리에서 암모니아가 포함된 물에 염소를 주입하여 소독하면 발생되는 클로라민의 한 형태',
    hNm: '트리클로라민',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'trichlorobenzene',
    explain:
      '벤젠고리에서 3개의 수소가 염소(Cl)로 치환된 화합물로서 C6H3Cl3으로 표현되는 화합물',
    hNm: '트리클로로벤젠',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'trichloroacetonitrile',
    explain:
      '수돗물 염소소독 시 유기전구물질로부터 생성되며 물에서 가수분해 되어 휘발성 물질을 생성하는 화합물.  C2Cl3N으로 표시함',
    hNm: '트리클로로아세토니트릴',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'trichloroethene',
    explain:
      '주로 금속의 기름제거 작업에 사용이 되는 물질로 C2HCl3의 화학식으로 표현되는 화합물 ',
    hNm: '트리클로로에텐',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'trichloroethylene',
    explain:
      '주로 금속의 기름제거 작업에 사용이 되는 물질로 C2HCl3의 화학식으로 표현되는 화합물 ',
    hNm: '트리클로로에틸렌',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'trichloroacetic acid',
    explain:
      '아세트산의 메틸기에 있는 3개의 수소가 모두 염소로 치환된 것으로 카복실산 중 하나이며, 매우 강한 산성을 나타내는 물질',
    hNm: '트리클로로초산',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'trichlorfon',
    explain:
      'O, O-디메틸-2, 2, 2-트리클로로-1-히드록시에틸포스폰산염으로 무색 결정질의 물질',
    hNm: '트리클로르폰',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'trihalomethane; THM',
    explain:
      '수도수속의 트리할로메탄은 수도원수속에 존재하는 휴민질 등의 유기물을 전구물질로 하여 염소처리에 의해 생성',
    hNm: '트리할로메탄',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'trihalomethane formation potential',
    explain:
      '20℃, pH 7.0±0.2의 조건하에서 24±2시간 정치(靜置) 후 잔류염소가 1～2㎎ /L이 되도록 염소처리 한 검수의 트리할로메탄의 농도',
    hNm: '트리할로메탄생성능',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'trihalomethane precursor',
    explain:
      '에틸알코올, 아세톤, 풀빅산 및 휴믹산 등 정수과정에서 원수에 염소소독을 실시하였을 때 소독부산물을 생성하는 원인물질들 ',
    hNm: '트리할로메탄전구물질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '特性曲線法',
    eNm: 'method of characteristics',
    hNm: '특성곡선법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '特定物質',
    eNm: 'specified substance',
    explain: '환경용어로서 법으로 정해놓은 28종의 물질을 의미 ',
    hNm: '특정물질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '特定水質有害物質',
    hNm: '특정수질유해물질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '特定水質有害物質',
    hNm: '특정수질유해물질',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '特定有害物質',
    eNm: 'designated hazardous substances',
    explain: '환경용어로서 법으로 정해놓은 28종의 물질을 의미 ',
    hNm: '특정유해물질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '特定有害産業廢棄物',
    eNm: 'specified hazardous industrial waste',
    explain:
      '폐기물이란, 먼지, 쓰레기, 탄재, 하수슬러지, 분뇨(糞尿), 폐유, 폐산, 폐알칼리, 동물사체, 기타 오물 또는 불필요한 물건들이며 고형상 또는 액상인 것',
    hNm: '특정유해산업폐기물',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'crepuscular ray',
    explain: '대기 중 입자에 의한 태양빛의 산란에 의해 나타나는 효과',
    hNm: '틈새빛살',
    rgsdt: '2016-11-21',
  },
  {
    eNm: 'Thiessen method',
    explain:
      '다수의 우량관측소가 있는 유역에서 관측소간 연결선의 수직이등분선들로 구성된 티센다각형의 면적비를 가중치로 대상유역의 면적평균강우량을 산정하는 방법',
    hNm: '티센법',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'TLm : median tolerance limit',
    explain:
      '어류를 급성 독성물질이 들어있는 배수의 희석 액 중에 일정 시간 사육하고, 그 사이에 공시어의 50%가 살아남는 배수 농도',
    hNm: '티엘엠',
    rgsdt: '2016-04-15',
  },
];

export default data_ko_ta;
