let data_ko_ha = [
  {
    cNm: '下降氣流',
    eNm: 'downdraft',
    explain: '상층에서 아래로 불어내리는 바람',
    hNm: '하강기류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下降流',
    eNm: 'downwelling',
    explain: '해수가 표층에서 아래쪽으로 침강하는 것을 하강류라고 함',
    hNm: '하강류',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Hagen-Poiseuille flow',
    explain: '층류에서 관내 유체의 유량에 관한 법칙',
    hNm: '하겐-푸아죄유 흐름',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Hagen-Poiseuille law',
    explain: '층류에서 관내 유체의 유량에 관한 법칙',
    hNm: '하겐-푸아죄유법칙',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河谷',
    eNm: 'valley',
    hNm: '하곡',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '河谷',
    eNm: 'valley',
    hNm: '하곡',
    rgsdt: '2023-03-21',
  },
  {
    cNm: '河口',
    eNm: 'estuary',
    explain: '바다나 호수로 유입되는 하천의 하류 끝부분 지역',
    hNm: '하구',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河口',
    eNm: 'estuary',
    explain: '바다나 호수로 유입되는 하천의 하류 끝부분 지역',
    hNm: '하구',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '河口干拓',
    eNm: 'estuary reclamation',
    hNm: '하구간척',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'estuary bank',
    explain:
      '강의 하류에 해수의 침입을 막고, 담수수자원을 확보하기 위하여 쌓은 둑',
    hNm: '하구둑',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'estuary bank',
    explain:
      '강의 하류에 해수의 침입을 막고, 담수수자원을 확보하기 위하여 쌓은 둑',
    hNm: '하구둑',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '河口堰',
    eNm: 'estuary weir, estuary barrage, tidal weir',
    explain:
      '하구에서 해수의 침입을 방지하기 위해 하천흐름을 횡단하여 설치하는 둑',
    hNm: '하구언',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河口湖',
    eNm: 'estuary reservoir',
    explain: '하구언 설치에 따라 인공적으로 만들어진 호수',
    hNm: '하구호',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河道',
    eNm: 'channel, fluvial channel, river channel, river course, stream channel',
    hNm: '하도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河道植生',
    eNm: 'channel vegetation',
    explain: '하천의 강바닥이나 수로에 자라는 식물군집을 이르는 말',
    hNm: '하도식생',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河道貯留',
    eNm: 'channel storage',
    hNm: '하도저류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河道追跡',
    eNm: 'channel routing',
    hNm: '하도추적',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '河道追跡',
    eNm: 'channel routing',
    hNm: '하도추적',
    rgsdt: '2023-06-26',
  },
  {
    eNm: 'Hady-Cross method',
    explain:
      '배수관망의 설계계산에서 관로유량을 미지수로서 계산하는 유량계산법의 일종',
    hNm: '하디크로스법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河路',
    eNm: 'River Course',
    hNm: '하로',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '河路',
    eNm: 'River Course',
    hNm: '하로',
    rgsdt: '2023-06-26',
  },
  {
    cNm: '下流',
    eNm: 'downstream',
    hNm: '하류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下流水位流量曲線',
    eNm: 'tailwater rating curve, ',
    hNm: '하류수위유량곡선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下流流速',
    eNm: 'velocity of retreat',
    hNm: '하류유속',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '下流流速',
    eNm: 'velocity of retreat',
    hNm: '하류유속',
    rgsdt: '2023-06-26',
  },
  {
    cNm: '下盤移動層狀斷層',
    eNm: 'underthrust',
    explain: '지괴가 다른 지괴 밑으로 일려 들어가는 형태의 변형',
    hNm: '하반이동 층상단층',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'Haber’s law',
    explain: '유해물질지수를 나타나는 값',
    hNm: '하버법칙',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Hubbert’s potential',
    hNm: '하버트 유체퍼텐셜',
    rgsdt: '2016-11-26',
  },
  {
    eNm: 'Hubbert’s potential',
    hNm: '하버트 유체퍼텐셜',
    rgsdt: '2023-06-26',
  },
  {
    cNm: '下部集水裝置',
    eNm: 'underdrain system, lower catchment',
    explain: '여과 과정에서 여과수를  모으는 장치',
    hNm: '하부집수장치',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河床間隙水域',
    eNm: 'hyporheic zone',
    explain: '하천수와 지하수가 합류되는 지역',
    hNm: '하상간극수역',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河床句配',
    eNm: 'gradient of river regime, river bed slope',
    hNm: '하상구배',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河床洗掘',
    eNm: 'bed scour, river bed scour',
    explain: '하천바닥의 토사가 씻겨 유실되는 현상',
    hNm: '하상세굴',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河床浸蝕',
    eNm: 'river-bed erosion',
    explain: '하천 바닥에서의 침식현상',
    hNm: '하상침식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河床被覆',
    eNm: 'bed armoring',
    hNm: '하상피복',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河線砂洲',
    eNm: 'beach dreft',
    explain: '하천의 유사들이 연안류의 운반으로 퇴적되어 생기는 지형',
    hNm: '하선사주',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'calcination',
    hNm: '하소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下水',
    eNm: 'raw sewage, sewage',
    explain:
      '일상생활을 기준으로 물을 이용하고 난 이후 버려지는 물이며 하수처리장으로 배수하여 공공처리후 자연으로 방류됨',
    hNm: '하수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下水渠',
    eNm: 'sewer',
    hNm: '하수거',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '下水管',
    eNm: 'sewer pipe',
    explain: '하수를 집수하여 하수처리장까지 이송시키는 관',
    hNm: '하수관',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下水管渠',
    eNm: 'sewer pipe, sewer',
    hNm: '하수관거',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下水管의 管種',
    eNm: 'material of sewers',
    explain: '하수관을 만드는데 사용되는 물질에 따른 하수관의 종류',
    hNm: '하수관의 관종',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下水道',
    eNm: 'drainage system',
    explain:
      '산업이나 생활에 의해 형성된 우수 또는 오수를 처리하기 위해 설치된 도관, 기타의 공작물과 시설을 총칭하는 말이다.',
    hNm: '하수도',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '下水道普及率',
    eNm: 'percentage of sewered population',
    hNm: '하수도보급률',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下水道普及人口',
    eNm: 'population served by sewer, sewered population',
    explain: '하수처리가 이루어지는 지역 내 거주 인구',
    hNm: '하수도보급인구',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下水排除方式',
    eNm: 'sewage removal system',
    explain:
      '도시에서 물을 이용한 뒤, 하수 배제는 하수관거를 매설하여 각 가정에서 집수하고 이를 하수처리장까지 배수하며, 배제방식에는 분류식과 합류식의 두가지 방식이 있음',
    hNm: '하수배제방식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下水收集',
    eNm: 'wastewater collection system, wastewater conveyance facilities',
    hNm: '하수수집시스템',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下水汚泥',
    eNm: 'sewage sludge, biosolids',
    explain:
      '하수처리의 각 공정에서 발생하여 집수된 슬러지로 상수슬러지에 비하여 유기물질 농도가 높음',
    hNm: '하수슬러지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下水汚泥土壤處理',
    eNm: 'sewage sludge disposal in soil',
    hNm: '하수슬러지토양처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下水終末處理施設',
    eNm: 'wastewater treatment plant, sewage treatment plant',
    explain:
      '하수를 최종적으로 처리하여 하천과 그 외의 해역에 방류하기 위한 처리시설',
    hNm: '하수종말처리시설',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下水集水槽',
    hNm: '하수집수조',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '下水集水槽',
    hNm: '하수집수조',
    rgsdt: '2023-09-26',
  },
  {
    cNm: '下水集水槽',
    hNm: '하수집수조',
    rgsdt: '2023-09-26',
  },
  {
    cNm: '下水集水槽',
    hNm: '하수집수조',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '下水處理',
    eNm: 'sewage disposal',
    explain:
      '하수를 하수관거로 수집하고 하천과 해역 등으로의 방류에 적합한 수질로 정화하는 것',
    hNm: '하수처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下水處理水',
    eNm: 'treated wastewater',
    hNm: '하수처리수',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '下水處理水 再利用',
    eNm: 'reuse of treated waste water',
    hNm: '하수처리수 재이용',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '下水處理水 再利用',
    eNm: 'reuse of treated waste water',
    hNm: '하수처리수 재이용',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '下水處理施設',
    eNm: 'sewage treatment equipment',
    explain: '하수처리를 위해 설치된 시설',
    hNm: '하수처리시설',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '河身',
    eNm: 'Center of a Stream in the River',
    hNm: '하신',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '河身',
    eNm: 'Center of a Stream in the River',
    hNm: '하신',
    rgsdt: '2023-06-26',
  },
  {
    cNm: '河岸',
    eNm: 'bank',
    explain:
      '하천, 호수, 바다와 육지의 경계에 자연상태 또는 인공으로 형성된 둑',
    hNm: '하안',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河岸段丘',
    eNm: 'river terrace',
    hNm: '하안단구',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '河岸段丘',
    eNm: 'river terrace',
    hNm: '하안단구',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '河岸安定',
    eNm: 'river bank stabilization',
    explain: '하천의 흐름에서 더 이상 세굴이 발생하지 않는 상태',
    hNm: '하안안정',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河岸貯留',
    eNm: 'bank storage',
    hNm: '하안저류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河岸浸蝕',
    eNm: 'stream bank erosion',
    explain: '하안이 깍여 나가는 현상',
    hNm: '하안침식',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Huygens’s principle',
    explain: ' 빛의 파동성에 근거하여 빛이 전파하는 방법을 기술하는 원리',
    hNm: '하위헌스의 원리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '荷電粒子',
    eNm: 'charged particle',
    hNm: '하전입자',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '荷電粒子',
    eNm: 'charged particle',
    hNm: '하전입자',
    rgsdt: '2023-10-19',
  },
  {
    eNm: 'open levee',
    explain: '홍수 피해 경감을 위해 설치하는 제방',
    hNm: '하제 ',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Hazen-Williams Formula',
    explain: '관수로 단면에 대한 평균유속을 구하기 위한 공식',
    hNm: '하젠-윌리엄스공식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '夏至',
    eNm: 'summer solstice',
    explain: '북반구에서 태양의 남중고도가 가장 높은 날',
    hNm: '하지',
    rgsdt: '2016-11-21',
  },
  {
    cNm: '夏至',
    eNm: 'summer solstice',
    explain: '북반구에서 태양의 남중고도가 가장 높은 날',
    hNm: '하지',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '河川改修',
    eNm: 'river improvement',
    explain: '홍수시 피해를 막기 위해 통수능을 증대시키는 하천공사',
    hNm: '하천개수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川骨材 ',
    eNm: 'river aggregate',
    explain: '하천지역에서 채취하는 골재',
    hNm: '하천골재',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川工事',
    eNm: 'river control work',
    explain: '하천 기능 향상을 위한 공사',
    hNm: '하천공사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川工學',
    eNm: 'river engineering',
    explain: '하천을 적극적으로 활용하기 위해 하천을 연구하는 학문',
    hNm: '하천공학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川管理',
    eNm: 'river management;river administration',
    explain:
      '범람, 건천화 등을 대비하기 위한 하천 정비와 취수, 방류 등 하천시설관리',
    hNm: '하천관리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川區間',
    eNm: 'river reach',
    explain:
      '하천에서 물이 흐르는 구간. 하천에서 수리학적 특성이 유사한 범위로 유량규모와 횡단면구성으로 판단.',
    hNm: '하천구간',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川屈曲比',
    eNm: 'tortuosity ratio',
    explain: '하천의 굽어진 정도',
    hNm: '하천굴곡비',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'river barrage',
    hNm: '하천둑',
    rgsdt: '2016-04-15',
  },
  {
    hNm: '하천모델',
    rgsdt: '2016-11-23',
  },
  {
    hNm: '하천모델',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '河川密度',
    eNm: 'drainage density, river density',
    explain: '유역의 단위면적내 평균 유로길이',
    hNm: '하천밀도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川密度',
    eNm: 'drainage density, river density',
    explain: '유역의 단위면적내 평균 유로길이',
    hNm: '하천밀도',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '河川密度',
    eNm: 'drainage density, river density',
    explain: '유역의 단위면적내 평균 유로길이',
    hNm: '하천밀도',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '河川法',
    eNm: 'river law',
    explain: '하천으로 인한 피해 예방과 이익 증진을 위해 제정된 법률',
    hNm: '하천법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川敷地',
    eNm: 'river location, river reservation',
    explain: '하천에서 유수가 흐르는 토지 및 그 주변 토지',
    hNm: '하천부지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川狀',
    eNm: 'river regimen',
    hNm: '하천상',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川水理學',
    eNm: 'fluvial hydraulics, river hydraulics',
    explain:
      '하천의 불규칙한 단면형상을 고려하여 하천흐름의 역학을 연구하는 학문',
    hNm: '하천수리학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川水位',
    eNm: 'river stage',
    explain: '정해진 기준면에서부터 하천수면까지의 높이',
    hNm: '하천수위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川連續性槪念',
    eNm: 'river continuum concept',
    explain: '하천생물종과 하천특성이 하천상류부터 하류까지 이어진다는 개념',
    hNm: '하천연속성개념',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川豫報',
    eNm: 'river forecasting',
    hNm: '하천예보',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川汚染',
    eNm: 'river pollution',
    explain:
      '하천이 생활하수나 공장폐수, 비점오염원 등에 의해 오염되는 것을 의미',
    hNm: '하천오염',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川流量',
    eNm: 'river discharge',
    explain: '하천의 어느 지점에서 흐르는 유량',
    hNm: '하천유량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川流砂',
    eNm: 'river sediment',
    explain: '하천에서 이동하는 흙의 입자',
    hNm: '하천유사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川流域',
    eNm: 'river basin',
    explain: '하천에 물이 모이는 경계 내부의 영역',
    hNm: '하천유역',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川流域管理',
    eNm: 'river basin management',
    hNm: '하천유역관리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川維持 ',
    eNm: 'river maintenace',
    explain:
      '하천 또는 그 부속 공작물을 수선, 보수를 하여 양호한 상태로 유지하기 위한 행위',
    hNm: '하천유지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川維持用水',
    explain:
      '하천 유지용수는 하천의 유수가 정상적인 기능을 유지하기 위해 필요한 물',
    hNm: '하천유지용수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川流出',
    eNm: 'stream flow',
    explain: '지표유출과 구분하여 하천수로 내에서 흐르는 유출',
    hNm: '하천유출',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川 自淨作用',
    eNm: 'self-purification',
    hNm: '하천의 자정작용',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '河川 自淨作用',
    eNm: 'self-purification',
    hNm: '하천의 자정작용',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '河川作用',
    eNm: 'fluvial process, fluviation',
    hNm: '하천작용',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川堤防',
    eNm: 'river levee',
    explain: '하천의 물범람을 막기 위해 쌓아놓은 뚝',
    hNm: '하천제방',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川縱斷(圖)',
    eNm: 'river profile',
    explain:
      '하천에서 주흐름방향 유하거리를 횡축으로하여 종측에 제방고, 최심하상고 등 단면특성의 표시한 단면도.',
    hNm: '하천종단(도)',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川次數',
    eNm: 'stream order',
    explain: '하천의 규모, 분기 정도를 구분하기 위하여 부여한 수치',
    hNm: '하천차수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川次數',
    eNm: 'stream order',
    explain: '하천의 규모, 분기 정도를 구분하기 위하여 부여한 수치',
    hNm: '하천차수',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '河川次數',
    eNm: 'stream order',
    explain: '하천의 규모, 분기 정도를 구분하기 위하여 부여한 수치',
    hNm: '하천차수',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '河川測量',
    eNm: 'river surveying',
    explain: '하천공사를 하기위해 필요한 값들을 측량하는 것',
    hNm: '하천측량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川洪水',
    eNm: 'stream flood',
    hNm: '하천홍수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '河川回復',
    eNm: 'Rehabilitation',
    hNm: '하천회복',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '河川回復',
    eNm: 'Rehabilitation',
    hNm: '하천회복',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '河川橫斷面積',
    eNm: 'river cross sectional area',
    hNm: '하천횡단면적',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下層雲',
    eNm: 'low clouds',
    explain: '지상 2,000m 이하에 발생하는 구름을 총칭',
    hNm: '하층구름',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'low-level jet',
    explain: '대기 하층의 700∼850hPa 부근에 나타나는 강풍대',
    hNm: '하층제트',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下廢水處理水 再利用施設',
    hNm: '하폐수처리수 재이용시설',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '下廢水處理水 再利用施設',
    hNm: '하폐수처리수 재이용시설',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '河幅',
    eNm: 'river width',
    explain: '하천의 너비',
    hNm: '하폭',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下限界流速',
    eNm: 'lower critical velocity',
    hNm: '하한계유속',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'downward filtration',
    hNm: '하향류여과',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '下向濾過',
    eNm: 'downward filtration',
    hNm: '하향여과',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '下向濾過',
    eNm: 'downward filtration',
    hNm: '하향여과',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '限界降雨期間',
    eNm: 'critical storm period',
    hNm: '한계강우기간',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '限界降雨期間',
    eNm: 'critical storm period',
    hNm: '한계강우기간',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '限界傾斜',
    eNm: 'critical slope',
    hNm: '한계경사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '限界傾斜曲線',
    eNm: 'critical slope curve',
    hNm: '한계경사곡선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '限界動水傾斜',
    eNm: 'critical hydraulic gradient',
    hNm: '한계동수경사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '限界等流',
    eNm: 'critical uniform flow',
    hNm: '한계등류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '限界流',
    eNm: 'critical flow',
    explain: '한계수심일 때의 흐름',
    hNm: '한계류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '限界流水路',
    eNm: 'critical flow flume',
    hNm: '한계류수로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '限界掃流力',
    eNm: 'critical tractive force',
    explain:
      '하상입자를 바닥에서 이동시키기 시작할 때 수류에 의해 수로 바닥에 작용하는 전단력',
    hNm: '한계소류력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '限界水分量',
    eNm: 'irreducible water content',
    hNm: '한계수분량',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '限界水分量',
    eNm: 'irreducible water content',
    hNm: '한계수분량',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '限界水深',
    eNm: 'critical depth',
    hNm: '한계수심',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '限界流速',
    eNm: 'critical velocity',
    explain: '수심이 한계 수심일 때의 평균 유속',
    hNm: '한계유속',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '限界剪斷應力',
    eNm: 'critical shear stress',
    hNm: '한계전단응력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '限界臭氣數',
    eNm: 'threshold odor, TO',
    explain:
      '물시료를 무취수를 사용하여 연속적으로 희석한 후, 검수의 취기가 최종 검출되는 점',
    hNm: '한계취기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '限界沈降速度',
    eNm: 'critical settling velocity',
    explain:
      '입자가 층류를 이루는 유동체에서 침강할 때, 중력과 저항력이 균형을 이루고 등속도 운동이 되어 침강하는 최종 속도',
    hNm: '한계침강속도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '韓國氣象學會',
    eNm: 'Korean Meteorological Society',
    explain: '기상학에 대한 연구활동 등을 목적으로 하는 학술단체',
    hNm: '한국기상학회',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '韓國水道協會',
    eNm: 'Korea Water and Wastewater Association, KWWA',
    explain: '수도법에 의해 법정법인으로 설립되어 현재 물산업 전문기관',
    hNm: '한국상하수도협회',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '韓國海洋學會',
    eNm: 'The Korean Society of Oceanography',
    explain: '해양학 및 관련 학문의 연구를 위한 학술단체',
    hNm: '한국해양학회',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '寒冷氣團',
    eNm: 'cold air mass',
    explain: '따뜻한 지방으로 이동하는 공기덩어리',
    hNm: '한냉기단',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '寒帶大陸氣團',
    eNm: 'polar continental air (mass)',
    hNm: '한대대륙기단',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'polar night jet stream',
    explain: '겨울철 극지방 성층권 안에서 부는 제트류',
    hNm: '한대야간제트류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '寒冷前線',
    eNm: 'cold front',
    explain:
      '밀도가 크고 온도가 낮은 기단과 상대적으로 밀도가 작고 온도가 높은 기단 사이에 형성되는 비교적 좁은 전이대',
    hNm: '한랭전선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '寒冷前線',
    eNm: 'cold front',
    explain:
      '밀도가 크고 온도가 낮은 기단과 상대적으로 밀도가 작고 온도가 높은 기단 사이에 형성되는 비교적 좁은 전이대',
    hNm: '한랭전선',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '限時性 浮遊生物',
    eNm: 'meroplankton',
    hNm: '한시성 플랑크톤',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '限外濾過',
    eNm: 'ultrafiltration',
    explain:
      '막 여과법에 있어서 한외여과막을 사용하여 분할 원리에 기초해 분자크기로 분리하는 여과방법',
    hNm: '한외여과',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '限外濾過膜',
    eNm: 'ultrafiltration membrane',
    explain: '한외여과법에 사용하는 막',
    hNm: '한외여과막',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '限外濾過法',
    eNm: 'ultrafiltration',
    explain:
      '막 여과법에 있어서 한외여과막을 사용하여 오래된 분할원리에 기초해 분자크기로 분리 하는 여과방법',
    hNm: '한외여과법',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '限外濾過法',
    eNm: 'ultrafiltration',
    explain:
      '막 여과법에 있어서 한외여과막을 사용하여 오래된 분할원리에 기초해 분자크기로 분리 하는 여과방법',
    hNm: '한외여과법',
    rgsdt: '2023-09-27',
  },
  {
    hNm: '한장회공식',
    rgsdt: '2016-11-26',
  },
  {
    hNm: '한장회공식',
    rgsdt: '2023-06-26',
  },
  {
    cNm: '寒波',
    eNm: 'cold wave',
    explain: '기온이 급속히 떨어지는 현상',
    hNm: '한파',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '割當負荷量',
    hNm: '할당부하량',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '割當負荷量',
    hNm: '할당부하량',
    rgsdt: '2023-09-27',
  },
  {
    eNm: 'organic halide',
    explain:
      '할로겐화 이온이나 할로겐 원소의 원자를 함유하고 있는 유기물의 총칭하여 일컫는 말',
    hNm: '할로겐화유기물',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'haloacetonitrile; HAN',
    explain: '할로겐 원소에 의해 아세토니트릴의 수소원자 1~3개가 치환된 것',
    hNm: '할로아세토니트릴',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'haloacetic acids',
    explain: '천연유기물과 염소의 반응으로 형성된 유기화합물',
    hNm: '할로아세트산',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'haloform',
    explain: '메탄분자의 4개 수소중 3개가 할로겐 원소로 치환된 화합물',
    hNm: '할로포름',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '割丁字管',
    eNm: 'divided T-type pipe',
    explain: "기존 관을 덮을 수 있도록 분할된 ‘丁’(한자), ‘T'(영문) 모양의 관",
    hNm: '할정자관',
    rgsdt: '2023-06-26',
  },
  {
    eNm: 'deflation formula pen',
    hNm: '함몰식증발접시',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'deflation formula pen',
    hNm: '함몰식증발접시',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '含水比 ',
    eNm: 'water content',
    explain: '건조중량에 대한 재료의 수분량의 백분율',
    hNm: '함수비',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '含水率',
    eNm: 'percentage of moisture content',
    explain:
      '재료가 함유하고 있는 수분의 비율을 중량비율과 용적비율로 표시한 것',
    hNm: '함수율',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '涵養',
    eNm: 'recharge',
    explain:
      '지표수가 지하로 침투하여 지하수가 형성하는 것을 말하는 수리학적 현상',
    hNm: '함양',
    rgsdt: '2016-04-15',
  },
  {
    explain: '지표로부터 공급되어 지하수의 일부가 되는 물의 양',
    hNm: '함양 수량',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '涵養境界 ',
    eNm: 'recharge boundary ',
    hNm: '함양경계 ',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'recharge well',
    explain:
      '지하수위 유지를 위해 인공적으로 물을 땅속으로 공급하기 위해 설치된 우물',
    hNm: '함양우물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '函養井',
    eNm: 'recharge well',
    explain:
      '지하수위 유지를 위해 대수층 내로 물을 인공적으로 공급하기 위해 설치된 우물',
    hNm: '함양정',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '涵養地域 ',
    eNm: 'recharge area ',
    explain:
      '지하수가 함양되는 지역으로 침투수가 대수층을 함양 할 수 있는 지역',
    hNm: '함양지역 ',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Joint Typhoon Warning Center',
    explain:
      '열대저기압에 대한 분석과 예보를 하며, 태평양과 인도양 등에서 발생하는 열대저기압의 활동을 감시하는 역할을 하는 곳',
    hNm: '합동태풍경보센터',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Joint Typhoon Warning Center',
    explain:
      '열대저기압에 대한 분석과 예보를 하며, 태평양과 인도양 등에서 발생하는 열대저기압의 활동을 감시하는 역할을 하는 곳',
    hNm: '합동태풍경보센터',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '合流式',
    eNm: 'combined sewer system',
    hNm: '합류식 하수도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '合流式',
    eNm: 'combined sewer system',
    hNm: '합류식 하수도',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '合流式',
    eNm: 'combined sewer system',
    hNm: '합류식 하수도',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '合流式 配水',
    eNm: 'combined drain',
    hNm: '합류식배수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '合流式下水道 ',
    eNm: 'combined system of sewage',
    explain:
      '오수와 우수를 하나의 관로에서 동시에 배제하는 방식의 재래식 하수도',
    hNm: '합류식하수도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '合流式下水道越流水',
    eNm: 'combined sewer overflows',
    hNm: '합류식하수도월류수(CSOs)',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '合流式下水道越流水',
    eNm: 'combined sewer overflows',
    hNm: '합류식하수도월류수(CSOs)',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '合理式',
    eNm: 'rational method',
    explain: '우수관거 설계시 대표적으로 사용되는 방법',
    hNm: '합리식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '合理式',
    eNm: 'rational method',
    explain: '우수관거 설계시 대표적으로 사용되는 방법',
    hNm: '합리식',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '合成單位圖',
    eNm: 'synthetic unit hydrograph',
    explain: '유역 및 하천의 특성을 이용해 유도한 단위도',
    hNm: '합성단위도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '合成纖維排水',
    eNm: 'synthetic fiber effluents',
    explain:
      '폴리에스텔, 나일론, 아크릴 등의 합성 섬유 공장에서 배출되는 유기 배수',
    hNm: '합성섬유배수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '合成洗劑 ',
    eNm: 'synthetic detergent',
    explain: '세정 작용을 하는 계면 활성제',
    hNm: '합성세제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '合成水文曲線',
    eNm: 'synthetic hydrograph',
    explain:
      '시간에 따라 변화하는 강우량에 의한 유출량을 시간에 따라 표시한 유량수문곡선',
    hNm: '합성수문곡선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '合成汚泥',
    eNm: 'synthetic sludge',
    hNm: '합성슬러지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '港口 ',
    eNm: 'harbor entrance',
    explain: '선박의 안전한 출입을 위하여 설치되는 시설',
    hNm: '항구',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '港口燈臺',
    eNm: 'harbor light',
    hNm: '항구등대',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '港內共振',
    eNm: 'harbor resonance',
    explain: '항내 파가 반사 등으로 인하여 합성되어 진폭이 증가되는 현상',
    hNm: '항내공진',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '港內振動',
    eNm: 'harbor oscillation',
    explain: '항의 내부에서 발생하는 진동',
    hNm: '항내진동',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '抗力',
    eNm: 'drag force, drag',
    hNm: '항력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '抗力係數',
    eNm: 'drag coefficient',
    explain: '항력을 나타내는 계수',
    hNm: '항력계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '航路 ',
    eNm: 'ocean passage, ocean lane',
    explain: '배가 다니는 길',
    hNm: '항로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '航路 ',
    eNm: 'ocean passage, ocean lane',
    explain: '배가 다니는 길',
    hNm: '항로',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '恒流',
    eNm: 'permanent current',
    explain: '일정 기간동안 변화가 없는 흐름',
    hNm: '항류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '恒流川',
    eNm: 'perennial stream',
    explain: '항상 물이 흐르는 하천',
    hNm: '항류천',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '港灣',
    eNm: 'port, harbor',
    explain:
      '선박의 안전한 출입 및 정박이 가능하며 여객 및 화물을 안전하게 싣고 내릴 수 있는 장소',
    hNm: '항만',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '港灣',
    eNm: 'port, harbor',
    explain:
      '선박의 안전한 출입 및 정박이 가능하며 여객 및 화물을 안전하게 싣고 내릴 수 있는 장소',
    hNm: '항만',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '港灣工學',
    eNm: 'harbor engineering',
    explain: '항만시설의 설계 및 유지관리를 위해 연구하는 학문',
    hNm: '항만공학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '港灣施設',
    eNm: 'port facilities',
    explain:
      '항만의 목적에 필요한 외각시설, 계류시설, 임항교통시설, 여객시설, 화물보관 및 처리시설 등을 총칭함.',
    hNm: '항만시설',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '港灣測量',
    eNm: 'harbor survey',
    hNm: '항만측량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '抗酸菌',
    eNm: 'acid-fast bacteria',
    explain:
      '염색할 때 가온염색 등의 처리를 필요로 하지만, 염색 후에는 산이나 알코올로 탈색되기 어려운 성질을 가진 세균',
    hNm: '항산균',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '抗生物質',
    eNm: 'antibiotics',
    explain:
      '미생물에 의해 만들어진 물질로서, 세균이나 기타 미생물을 파괴하거나 발육을 억제하는 물질',
    hNm: '항생물질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '抗原抗體反應',
    eNm: 'antigen-antibody reaction',
    explain:
      '면역 반응에서 세포에서 생성된 항체와 항원간의 화학적 상호작용을 말하며, 감염균과 그로 인한 화학적 유독성 등 이질적인 물질들로부터 자신을 지키려는 체내의 기초 반응',
    hNm: '항원항체반응',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '港入口',
    eNm: 'harbor entrance',
    hNm: '항입구',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海丘',
    eNm: 'trench',
    explain:
      '해양지각이 대륙지각 밑으로 섭입할 때 만들어지는 섭입대와 평행하며 수심이 깊은 선형의 계곡',
    hNm: '해구',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '骸泥',
    eNm: 'organic ooze',
    explain: '호수 아래 퇴적물의 일종으로 유기니라고도 함',
    hNm: '해니',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海嶺',
    eNm: 'oceanic ridge',
    explain: '깊은 바다에 있는 길고 좁지만 높게 선형으로 형성된 해저 산맥',
    hNm: '해령',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '海流',
    eNm: 'ocean current',
    explain:
      '바람, 밀도차, 수면경사 등의 다양한 원인에 의하여 바닷물이 일정한 방향으로 흐르는 것을 말함',
    hNm: '해류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海流曲線',
    eNm: 'current curve',
    hNm: '해류곡선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海流圖',
    eNm: 'current diagram',
    hNm: '해류도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海流力 ',
    eNm: 'current force',
    explain: '해수의 흐름에 의해 작용하는 힘.',
    hNm: '해류력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海流力 ',
    eNm: 'current force',
    explain: '해수의 흐름에 의해 작용하는 힘.',
    hNm: '해류력',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '海流流速 ',
    eNm: 'current velocity',
    hNm: '해류유속',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海陸風',
    eNm: 'land and sea breeze',
    explain:
      '해안가에서 발생하는 국지풍으로 하루를 주기로 바람의 방향이 바뀌며 그 원인은 해수면과 지표면 사이의 기온 차에 의해서 발생하는 국지 순환에 의해 발생',
    hNm: '해륙풍',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海陸風',
    eNm: 'land and sea breeze',
    explain:
      '해안가에서 발생하는 국지풍으로 하루를 주기로 바람의 방향이 바뀌며 그 원인은 해수면과 지표면 사이의 기온 차에 의해서 발생하는 국지 순환에 의해 발생',
    hNm: '해륙풍',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '海陸風前線',
    eNm: 'land and sea breeze front',
    explain: '해풍과 육풍의 경계에 나타나는 국지적으로 나타나는 전선',
    hNm: '해륙풍전선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '解離',
    eNm: 'dissociation',
    explain:
      '분자가 더 작은 분자로 쪼개지거나 그 분자를 구성 성분인 각각의 원자 또는 이온 등으로 나누어지는 현상',
    hNm: '해리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '解離',
    eNm: 'dissociation',
    explain:
      '분자가 더 작은 분자로 쪼개지거나 그 분자를 구성 성분인 각각의 원자 또는 이온 등으로 나누어지는 현상',
    hNm: '해리',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '解離',
    eNm: 'dissociation',
    explain:
      '분자가 더 작은 분자로 쪼개지거나 그 분자를 구성 성분인 각각의 원자 또는 이온 등으로 나누어지는 현상',
    hNm: '해리',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '海面干拓',
    eNm: 'tidal land reclamation',
    explain: '조석의 차이를 이용하여 간척작업을 하는 것',
    hNm: '해면간척',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海面上昇',
    eNm: 'rising sea level',
    hNm: '해면상승',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海面狀態',
    eNm: 'sea state',
    hNm: '해면상태',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海面粗度',
    eNm: 'sea surface roughness',
    hNm: '해면조도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海面風速',
    eNm: 'sea surface wind velocity',
    hNm: '해면풍속',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海濱',
    eNm: 'beach, seashore',
    explain: '조류나 해파로 인해 만들어진 퇴적지대',
    hNm: '해빈',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海濱',
    eNm: 'beach, seashore',
    explain: '조류나 해파로 인해 만들어진 퇴적지대',
    hNm: '해빈',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '海濱流',
    eNm: 'littoral current/ nearshore',
    hNm: '해빈류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海濱維持',
    eNm: 'beach maintenance',
    hNm: '해빈유지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海濱浸蝕 ',
    eNm: 'beach erosion',
    hNm: '해빈침식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海濱堆積',
    eNm: 'beach accretion',
    hNm: '해빈퇴적',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '解氷期點檢',
    eNm: 'Ice detection period',
    hNm: '해빙기점검',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '解氷期點檢',
    eNm: 'Ice detection period',
    hNm: '해빙기점검',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '海砂',
    eNm: 'beach sand',
    hNm: '해사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海上狀態',
    eNm: 'marion condition',
    hNm: '해상상태',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海成層',
    eNm: 'marion deposit',
    hNm: '해성층',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海成土',
    eNm: 'marine soil',
    hNm: '해성토',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海水',
    eNm: 'sea water',
    explain: '염분이 있는 바닷물로 지구상 물의 약 97%가 이에 해당됨',
    hNm: '해수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海水淡水化',
    eNm: 'seawater desalination',
    explain: '해수에 있는 염분을 제거하여 담수상태로 만드는 것',
    hNm: '해수담수화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海水淡水化裝置',
    eNm: 'sea water desalination equipment',
    explain: '해수의 염분을 제거하여 담수로 제조하는 장치',
    hNm: '해수담수화장치',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海水面 ',
    eNm: 'sea level',
    explain: '해양수면의 평균적인 높이',
    hNm: '해수면',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海水面上昇',
    eNm: 'setup',
    hNm: '해수면상승',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海水汚染',
    eNm: 'sea water pollution',
    explain:
      '해양에 투기되거나 배출된 오염물질이 바닷물을 오염시키는 것을 의미',
    hNm: '해수오염',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海水侵入',
    eNm: 'sea water intrusion',
    explain: '해안지역 대수층으로 해수가 침투하는 현상',
    hNm: '해수침입',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'gnomon, sundial',
    explain:
      '지구의 자전으로 물체의 그림자가 이동하는 것으로 시간을 측정하는 것으로 인류가 가장 먼저 이용한 시계',
    hNm: '해시계',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海蝕作用',
    eNm: 'coastal[wave] erosion',
    explain: '해수의 운동에 의한 육지가 침식되는 작용',
    hNm: '해식작용',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海蝕絶壁',
    eNm: 'sea cliff',
    explain: '파도의 침식작용으로 생성된 절벽',
    hNm: '해식절벽',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸',
    eNm: 'shore, coast',
    explain: '육지와 바다면의 경계',
    hNm: '해안',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸 護岸',
    eNm: 'sea wall',
    hNm: '해안 호안',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸工學',
    eNm: 'coastal engineering',
    explain:
      '해안에 작용하는 외력 등을 공학적인 관점에서 해석하고 연구하는 학문',
    hNm: '해안공학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸構造物',
    eNm: 'coastal structures',
    hNm: '해안구조물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸段丘',
    eNm: 'coastal terrace',
    explain: '과거 계단식 해면이 융기하여 육지화된 지형',
    hNm: '해안단구',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸突堤',
    eNm: 'groyne',
    explain: '해안침식을 막고 모래를 퇴적시키기 위한 구조물',
    hNm: '해안돌제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸砂丘 ',
    eNm: 'coastal sand dune',
    explain: '해풍으로 인해 육지로 이동되는 모래가 장애물에 걸려 형성된 지역',
    hNm: '해안사구',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸砂丘 ',
    eNm: 'coastal sand dune',
    explain: '해풍으로 인해 육지로 이동되는 모래가 장애물에 걸려 형성된 지역',
    hNm: '해안사구',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '海岸砂防工',
    eNm: 'dune fixation',
    hNm: '해안사방공',
    rgsdt: '2016-04-15',
  },
  {
    cNm: ' 海岸線',
    eNm: 'shoreline',
    explain: '육지면과 해수면이 접하는 경계선',
    hNm: '해안선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸線',
    eNm: 'shoreline',
    explain: '육지면과 해수면이 접하는 경계선',
    hNm: '해안선',
    rgsdt: '2023-10-19',
  },
  {
    cNm: ' 海岸線',
    eNm: 'shoreline',
    explain: '육지면과 해수면이 접하는 경계선',
    hNm: '해안선',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '海岸線 後退',
    eNm: 'beach regression',
    explain:
      '해안의 모래가 파도 및 바람에 지속적으로 침식되어 해안선이나 해빈이 육지 쪽으로 이동하는 것',
    hNm: '해안선 후퇴',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸線區間',
    eNm: 'shore span',
    hNm: '해안선구간',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸線形態',
    eNm: 'shoreline feature',
    explain: '바다와 육지의 경계선의 형태',
    hNm: '해안선형태',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸汚染',
    eNm: 'coastal pollution',
    explain: '각종 오염물질에 의해 해안이 오염되는 것을 의미',
    hNm: '해안오염',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸堤防',
    eNm: 'coastal levee',
    explain: '해수의 침습 피해를 방지하기 위해 설치하는 제방',
    hNm: '해안제방',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸地帶',
    eNm: 'coastal zone',
    hNm: '해안지대',
    rgsdt: '2016-04-15',
  },
  {
    cNm: ' 海岸地形 ',
    eNm: 'coastal topography',
    explain: '파도에 의한침식과 퇴적작용으로 형성되는 해안선 주변의 각종 지형',
    hNm: '해안지형 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸地形 ',
    eNm: 'coastal topography',
    explain: '파도에 의한침식과 퇴적작용으로 형성되는 해안선 주변의 각종 지형',
    hNm: '해안지형 ',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '海岸測量',
    eNm: 'coastal survey',
    hNm: '해안측량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸浸蝕',
    eNm: 'coastal erosion',
    explain: '해안의 모래와 자갈이 유실되어 해안이 육지쪽으로 후퇴하는 현상',
    hNm: '해안침식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸堆積',
    eNm: 'coastal accretion',
    hNm: '해안퇴적',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸平野',
    eNm: 'coastal plain',
    hNm: '해안평야',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸標砂',
    eNm: 'coastal drift',
    hNm: '해안표사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸港',
    eNm: 'seacoast harbor',
    explain: '방파제 등의 구조물을 축조하여 인위적으로 정온수역을 확보한 항만',
    hNm: '해안항',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海岸浩',
    eNm: 'coastal lake',
    hNm: '해안호',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋工學',
    eNm: 'ocean engineering',
    explain:
      '연안에서 떨어진 먼바다의 하류순환, 해양지질 등 해양개발에 관련된 공학의 통칭',
    hNm: '해양공학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋觀測所',
    eNm: 'marine observatory, ocean station',
    explain: '해안의 기상현상을 파악하기 위한 관측지점',
    hNm: '해양관측소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋構造物 ',
    eNm: 'marine structure',
    explain: '해양의 자연환경에 따라 해양에 설치되는 구조물',
    hNm: '해양구조물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋大循環',
    eNm: 'general circulation of ocean',
    explain: '해양의 흐름을 특징짓는 해수순환의총체적 운동',
    hNm: '해양대순환',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋排出',
    eNm: 'sea discharge',
    explain: '수용성 유기질 폐기물을 배출할 수 있게 하는 제도',
    hNm: '해양배출',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋生態系 ',
    eNm: 'marine ecosystem',
    explain: '해양생물과 주변환경의 유기적 물질순환계',
    hNm: '해양생태계',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋生態系 ',
    eNm: 'marine ecosystem',
    explain: '해양생물과 주변환경의 유기적 물질순환계',
    hNm: '해양생태계',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '海洋生態系 ',
    eNm: 'marine ecosystem',
    explain: '해양생물과 주변환경의 유기적 물질순환계',
    hNm: '해양생태계',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '海洋生態學',
    eNm: 'marine ecology',
    hNm: '해양생태학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋性 氣團',
    eNm: 'maritime air mass',
    explain: '해양에서 발생하는 공기 덩어리',
    hNm: '해양성 기단',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋性氣候',
    eNm: 'oceanic climate',
    explain:
      '해양의 영향을 받아 기온의 일교차와 연교차가 비교적 작으며, 비가 잦고 따뜻한 기후',
    hNm: '해양성기후',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋循環',
    eNm: 'ocean circulation, oceanic circulation',
    explain: '해양에서 발생하는 대규모의 해수의 순환',
    hNm: '해양순환',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋循環',
    eNm: 'ocean circulation, oceanic circulation',
    explain: '해양에서 발생하는 대규모의 해수의 순환',
    hNm: '해양순환',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '海洋施設',
    eNm: 'offshore facility',
    explain:
      '해역에서 사람의 수용, 물건의 처리 및 수송 그리고 보관용으로 사용되는 공작물',
    hNm: '해양시설',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋深層水',
    eNm: 'deep sea water',
    explain: '해수면 아래 깊은 바다에서 나타나는 염수',
    hNm: '해양심층수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋汚染',
    eNm: 'marine pollution',
    explain: '오염물질의 유출에 의해 바닷물이 오염되는 일을 의미',
    hNm: '해양오염',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋溫度差發電 ',
    eNm: 'oceanthermal energy conversion',
    explain:
      '해양의 표층의 온도와 수 백 m 깊이의 해수 온도차를 이용한 발전 방식',
    hNm: '해양온도차발전',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'oil pollution of marine',
    explain: '바닷물이 석유와 같은 기름에 의해 오염되는 것을 의미',
    hNm: '해양의 석유오염',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋測量',
    eNm: 'sea surveying',
    explain:
      '해양에서 지형과 물리·화학·생물학적 특성을 파악하는데 필요한 기초자료를 수집 및 조사하는 것',
    hNm: '해양측량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋投棄',
    eNm: 'oceam dumping',
    explain:
      '육지나 바다 등에서 발생된 폐기물을 고의로 해양에 폐기처분하는 행위 ',
    hNm: '해양투기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋學',
    eNm: 'oceanography',
    explain:
      '지구환경을 이해하기 위해 물리, 화학, 지질학, 생물학적인 방면으로 연구하는 학문',
    hNm: '해양학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋擴散',
    eNm: 'marine diffusion',
    explain: '유동 및 확산을 통한 해양 내물질 수송에 대한 물리적 추적법',
    hNm: '해양확산',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海洋環境',
    eNm: 'marine environment',
    explain:
      '염분, 온도, 혼합, 유동, 영양염류의 분포, 생물 등 해양의 환경을 의미',
    hNm: '해양환경',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海域',
    eNm: 'shore region',
    explain: '육지와 바다가 닿아있는 부분',
    hNm: '해역',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海淵',
    eNm: 'fore deep',
    explain: '해구 가운데 깊이 파여 움푹한 곳',
    hNm: '해연',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海溢',
    eNm: 'surge',
    explain:
      '폭풍, 지진 등이 원인이 되어 해수면의 높이가 갑자기 높아져 바다의 큰 물결이 육지로 올라와 넘치는 현상',
    hNm: '해일',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海溢',
    eNm: 'surge',
    explain:
      '폭풍, 지진 등이 원인이 되어 해수면의 높이가 갑자기 높아져 바다의 큰 물결이 육지로 올라와 넘치는 현상',
    hNm: '해일',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '海溢防波堤',
    eNm: 'storm surge barrier',
    explain: '해일로 인한 해안선의 피해를 방지하기 위하여 만든 방파제',
    hNm: '해일방파제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海底油田',
    eNm: "offshore oil field' submarine oil field",
    explain: '바닷속에 있는 유전',
    hNm: '해저유전',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海底資源',
    eNm: 'submarine resources',
    explain: '바다에 존재하는 광물자원과 생물자원의 총칭',
    hNm: '해저자원',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海底峽谷',
    eNm: 'submarine canyon',
    explain: '대양분저의 협곡지형',
    hNm: '해저협곡',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海底峽谷',
    eNm: 'submarine canyon',
    explain: '대양분저의 협곡지형',
    hNm: '해저협곡',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '海底火山',
    eNm: 'submarine volcano',
    explain: '해저에 분포하는 화산으로 분출구가 해수면 아래 존재함',
    hNm: '해저화산',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海底火山',
    eNm: 'submarine volcano',
    explain: '해저에 분포하는 화산으로 분출구가 해수면 아래 존재함',
    hNm: '해저화산',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '海中林',
    eNm: 'sea-jungle',
    explain: '해조류 등의 집단 서식지로 바다생물의 산란 장소로 최적의 장소',
    hNm: '해중림',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '害蟲',
    eNm: 'injurious insects',
    explain: '인간 생활에 직접적 또는 간접적으로 피해를 주는 생물',
    hNm: '해충',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '害蟲防除',
    eNm: 'insect pest control',
    explain:
      '인간에게 피해를 주는 벌레에 의한 해를 감소시키기 위한 일련의 행위 ',
    hNm: '해충방제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '海風逆轉',
    eNm: 'sea-breeze inversion',
    explain: '아침에 해풍에 의한 전선면에 생기는 역전',
    hNm: '해풍역전',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '海峽',
    eNm: 'strait, narrows',
    explain: '양 쪽 두개의 해역 사이에 끼여 있는 좁은 바다',
    hNm: '해협',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '向流',
    eNm: 'counter flow, counter crrent',
    explain:
      '2개의 유체사이에서 열이나 물질의 이동이 있을 경우 이 유체들이 서로 반대로 흐르는 경우',
    hNm: '향류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '許容灌漑面積',
    eNm: 'permissible area',
    hNm: '허용관개면적',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '許容灌漑面積',
    eNm: 'permissible area',
    hNm: '허용관개면적',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '許容濃度',
    eNm: 'acceptable concentration',
    hNm: '허용농도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '許容湛水深',
    eNm: 'allowable ponding depth',
    explain: '논지대의 경비 절감을 위해 허용하는 담수의 수심',
    hNm: '허용담수심',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '許容負荷量',
    eNm: 'allowable pollution load',
    hNm: '허용부하량',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '許容負荷量',
    eNm: 'allowable pollution load',
    hNm: '허용부하량',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '許容掃流力',
    eNm: 'permissible tractive force',
    hNm: '허용소류력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '許容汚染負荷量 ',
    eNm: 'allowable pollution',
    hNm: '허용오염부하량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '許容誤差',
    eNm: 'allowable error, tolerance',
    explain: '허용할 수 있는 최대의 오차를 의미',
    hNm: '허용오차',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '許容流速',
    eNm: 'Permissible Velocity',
    hNm: '허용유속',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '許容流速',
    eNm: 'Permissible Velocity',
    hNm: '허용유속',
    rgsdt: '2023-09-12',
  },
  {
    eNm: 'head sludge',
    explain: '수면 바닥에 쌓여 있는 부드러운 슬러지',
    hNm: '헤드로 ',
    rgsdt: '2016-04-15',
  },
  {
    eNm: "Henry's law",
    explain:
      '1803년 헨리(W. Henry)가 발견한 법칙으로, 용해도는 용매와 평형을 이루고 있는 그 기체의 부분압력에 비례한다는 법칙',
    hNm: '헨리의 법칙',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Helium',
    explain: '원소주기율표 상에서 1주기 18족에 속하는 비활성기체',
    hNm: '헬륨',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '懸垂接觸酸化法 ',
    eNm: 'hanging biological contactor',
    explain:
      '생물막법의 HBC Ring이라는 새로운 접촉제를 개발하여 생물막법의 장점을 최대한 살리면서 단점을 어느 정도 저감시킨 공법',
    hNm: '현수접촉산화법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '現場揚水試驗',
    eNm: 'field pumping test',
    explain: '대수층의 투수량계수나 저류계수를 구하기 위한 시험',
    hNm: '현장양수시험',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '懸濁液',
    eNm: 'suspension',
    explain:
      '흙탕물처럼 물에 콜로이드 입자보다도 큰 고체 입자가 분산되어 있는 상태',
    hNm: '현탁액',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '懸濁粒子',
    eNm: 'suspension particle',
    explain:
      '액체 속에 현미경으로 보일 정도로 가는 고체 입자가 분산하고 있는 상태를 현탁상태라고 하며, 이와 같은 미세한 고체 입자',
    hNm: '현탁입자',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '懸濁質',
    eNm: 'suspensoid',
    explain: '액체 중에 콜로이드 입자가 분산되어 있는 액',
    hNm: '현탁질',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'anaerobic-anoxic-oxic process',
    explain: '질소와 인을 제거하기 위해 A/O공법을 개량한 공법',
    hNm: '혐기-무산소-호기공법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '嫌氣好氣濾床法',
    eNm: 'biological anaerobic-aerobic filter process',
    hNm: '혐기-호기여상법',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '嫌氣-好氣處理法',
    eNm: 'anaerobic-aerobic treatment process',
    hNm: '혐기-호기처리법',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'anaerobic-oxic activated sludge process',
    hNm: '혐기-호기활성슬러지법',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'anaerobic-oxic activated sludge process',
    hNm: '혐기-호기활성슬러지법',
    rgsdt: '2023-09-27',
  },
  {
    eNm: 'anaerobic-oxic activated sludge process',
    hNm: '혐기-호기활성슬러지법',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '嫌忌量',
    eNm: 'dislike value',
    explain:
      '물속의 유해 성분에 따라 어류가 기피 행동을 일으키는 값으로, 치사량의 1/10 정도의 값',
    hNm: '혐기량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '嫌氣性',
    eNm: 'anaerobic',
    explain:
      '물속에 공기 중에서 산소가 녹아 형성된 용존산소, 질산이온이나 황산이온과 같은 무기 결합산소가 존재하지 않은 상태',
    hNm: '혐기성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '嫌氣性醱酵',
    eNm: 'methane fermentation process',
    explain:
      '혐기성 세균에 의해 산소가 전혀 없는 상태에서 효소에 의해 일어나는 발효반응',
    hNm: '혐기성 발효',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '嫌氣性消化',
    eNm: 'anaerobic digestion',
    explain:
      '혐기성 세균에 의하여 고농도의 유기성 고형물을 분해하는 것으로, 하수슬러지를 산소공급 없이 처리하는 공정',
    hNm: '혐기성 소화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '嫌氣性 消化槽',
    eNm: 'anaerobic digenestion tank',
    explain:
      '혐기성 세균에 의해 고농도의 유기물을 분해하고 감량화하기 위한 밀폐된 탱크',
    hNm: '혐기성 소화조',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '嫌氣性濾床法',
    eNm: 'anaerobic filter process',
    hNm: '혐기성 여상법',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '嫌氣性濾床法',
    eNm: 'anaerobic filter process',
    hNm: '혐기성 여상법',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '嫌氣性處理方式',
    eNm: 'anaerobic treatment process',
    explain:
      '용존산소 등 분자 상 산소가 존재하지 않는 혐기조건에서 폐수를 생물학적으로 처리하는 방식',
    hNm: '혐기성 처리방식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '嫌氣性菌',
    eNm: 'anaerobic bacteria',
    explain: '산소가 존재하지 않는 환경에서 생장하는 세균',
    hNm: '혐기성균',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '嫌氣性泥土',
    eNm: 'anaerobic mud',
    explain: '혐기성 퇴적환경에서 형성된 모래, 실트, 점토의 혼합물',
    hNm: '혐기성니토',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '嫌氣性分解',
    eNm: 'anaerobic decomposition',
    explain:
      '혐기성 미생물에 의한 유기물의 분해를 뜻하며 혐기성 분해를 통한 최종산물은 온전히 무기화되지 않아 중간 생성물 형태로 에너지를 갖는 유기물 또는 가스상 물질로 나타남',
    hNm: '혐기성분해',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '嫌氣性菌 ',
    eNm: 'anaerobic bacteria',
    explain: '산소가 존재하지 않은 환경(혐기상태)에서 생육하는 세균',
    hNm: '혐기성세균',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '嫌氣性消化',
    eNm: 'anaerobic digestion',
    hNm: '혐기성소화',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '嫌氣性消化',
    eNm: 'anaerobic digestion',
    hNm: '혐기성소화',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '嫌氣性 消化',
    eNm: 'anaerobic digestion  tank',
    explain: '산소공급 없이 하수슬러지를 처리하는 공정에서 사용되는 탱크',
    hNm: '혐기성소화탱크',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '嫌氣性安定池',
    eNm: 'anaerobic pond',
    explain:
      '수심을 3m이상으로 하여 외부에서 용존산소의 전달이 없는 상태에서 혐기성 분해가 일어나도록 한 연못',
    hNm: '혐기성안정지',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'anaerobic sludge',
    hNm: '혐기성오니',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '嫌氣性原生動物',
    eNm: 'anaerobic protozoa',
    explain: '오니의 내부와 같은 혐기성 환경에서 사는 원생동물',
    hNm: '혐기성원생동물',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '嫌氣性原生動物',
    eNm: 'anaerobic protozoa',
    explain: '오니의 내부와 같은 혐기성 환경에서 사는 원생동물',
    hNm: '혐기성원생동물',
    rgsdt: '2023-09-26',
  },
  {
    cNm: '嫌氣性處理',
    eNm: 'anaerobic treatment  ',
    explain:
      '슬러지 또는 하수 중의 유기물을 용존산소와 분자상 산소가 전혀 없는 상태에서 혐기적 분해하는 처리법',
    hNm: '혐기성처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '嫌氣性呼吸',
    eNm: 'anaerobic respiration',
    explain: '산소가 없는 환경에서 기질을 분해하는 대사작용',
    hNm: '혐기성호흡',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '嫌氣槽',
    eNm: 'anaerobic tank',
    explain:
      '혐기성 세균에 의해 고농도의 유기물을 분해하고 감량화하기 위한 밀폐된 탱크',
    hNm: '혐기조',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '嫌氣槽',
    eNm: 'anaerobic tank',
    explain:
      '혐기성 세균에 의해 고농도의 유기물을 분해하고 감량화하기 위한 밀폐된 탱크',
    hNm: '혐기조',
    rgsdt: '2023-09-26',
  },
  {
    eNm: 'anaerobic tank',
    hNm: '혐기탱크',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'anaerobic tank',
    hNm: '혐기탱크',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '挾雜物',
    eNm: 'debris',
    hNm: '협잡물',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '挾雜物',
    eNm: 'debris',
    hNm: '협잡물',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '形狀係數',
    eNm: 'shape factor',
    explain: '소성모멘트의 항복모멘트에 대한 비',
    hNm: '형상계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好氣性',
    eNm: 'aerobic',
    explain:
      '공기나 유리상태의 산소가 있는 상태 또는 필요한 상태를 뜻하며 혐기성의 반대 의미',
    hNm: '호기성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好氣性 消火處理',
    eNm: 'aerobic digestion treatment',
    explain:
      '폐수를 처리하는 방법으로 호기 상태의 미생물을 이용하고 혐기성 소화의 상대 개념으로 다른 말로 호기성 분해라고도 함',
    hNm: '호기성 소화처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好氣性汚泥消化',
    eNm: 'aerobic sludge digestion',
    explain:
      '호기성 미생물을 이용하여 슬러지의 안정성 촉진 및 슬러지 부피감소를 목적으로 함',
    hNm: '호기성 슬러지소화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好氣性 濾床法',
    eNm: 'biological aerated filter',
    explain:
      '모래 또는 합성수지로 만들어진 담체에 부착된 미생물을 이용하여 유기물을 호기성 상태에서 산화분해하거나 생물막으로 생흡착하여 하수를 처리하는 공법',
    hNm: '호기성 여상법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好氣性 處理',
    eNm: 'aerobic treatment',
    explain: '호기성균을 이용하여 하수 등의 오염 성분을 처리하는 방법',
    hNm: '호기성 처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好氣性 脫窒',
    eNm: 'aerobic denitrification',
    explain:
      'Thiosphaera pantotropa와 같은 균에 의해 호기성 탈질은 호기성조건에서 최종 전자수용체로서 O2와 NO3-N을 동시에 사용하여 용존산소가 높은 조건에서도 탈질이 가능한 것을 의미',
    hNm: '호기성 탈질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好氣性 呼吸',
    eNm: 'aerobic respiration',
    explain:
      '공기 중의 산소를 섭취하여 체내에서 이용하고 대신 공기 중에 이산화탄소를 배출하는 가스 교환을 의미',
    hNm: '호기성 호흡',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好氣性-嫌氣性安定化池',
    eNm: 'aerobic-anaerobic pond',
    hNm: '호기성-혐기성안정화지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好氣性菌',
    eNm: 'aerobe, aerobic bacteria',
    explain: '산소가 있는 곳에서 생육, 번식하는 균으로 산소성 세균이라고도 함',
    hNm: '호기성균',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好氣性微生物',
    eNm: 'Aerobe',
    explain: '산소를 전자수용체로 사용하는 반응을 통해 성장하는 미생물',
    hNm: '호기성미생물',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '好氣性醱酵',
    eNm: 'aerobic fermentation',
    explain: '산소가 있는 상태에서 산화효소에 의해 일어나는 발효반응',
    hNm: '호기성발효',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好氣性分解 ',
    eNm: 'aerobic decompositon',
    explain:
      '호기성 미생물에 의하여 높은 분자량의 유기물을 낮은 분자량의 유기물 또는 최종 무기성 산물로 변환되는 것을 의미하며, 미생물은 고준위 에너지를 함유한 물질로 부터 에너지를 섭취하고 최종 생성물은 에저지가 낮거나 없는 상태로 배출됨',
    hNm: '호기성분해',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好氣性消化',
    eNm: 'aerobic digestion',
    explain:
      '호기성 세균에 의하여 고농도의 유기성 고형물을 분해하는 것으로 통상 하수슬러지에 산소를 공급하여 처리하는 공정',
    hNm: '호기성소화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好氣性安定池',
    eNm: 'aerobic pond',
    hNm: '호기성안정화지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好氣性自己固定和活性汚泥法',
    eNm: 'self-granular activated sludge',
    explain:
      '미생물에서 분비되는 점착성 물질을 사용하여 활성슬러지 입자의 크기를 키우는 방법',
    hNm: '호기성자기고정화활성슬러지법',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '好氣性 處理法',
    eNm: 'aerobic treatment method',
    explain: '호기성균을 이용하여 하수 등의 오염 성분을 처리하는 방법',
    hNm: '호기성처리법',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'aerobic tank',
    hNm: '호기탱크',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '好冷性微生物',
    eNm: 'psychrophilic microbes',
    hNm: '호냉성미생물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好冷細菌',
    eNm: 'psychrophilic bacteria',
    hNm: '호냉세균',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'reservoir water quality model',
    hNm: '호소모델',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '湖沼生態系',
    eNm: 'lake ecosystem',
    explain:
      '호소 안에서 여러 가지 생물들과 빛, 기후, 토양 등의 비 생물적 요소 등 모든 요소들이 어우러져 살아가는 것을 의미',
    hNm: '호소생태계',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '湖沼生態系',
    eNm: 'lake ecosystem',
    explain:
      '호소 안에서 여러 가지 생물들과 빛, 기후, 토양 등의 비 생물적 요소 등 모든 요소들이 어우러져 살아가는 것을 의미',
    hNm: '호소생태계',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '湖沼學',
    eNm: 'limnology',
    explain: '호나 저수지의 환경 분석을 하며 수문학적 현상을 취급하는 학문',
    hNm: '호소학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '湖沼環境基準',
    eNm: 'pond environmental standard',
    explain:
      '호수의 수질을 보호하기 위해 환경정책기본법 시행령으로 기준을 정해놓은 것을 의미',
    hNm: '호소환경기준',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '湖水浮遊生物',
    eNm: 'limnoplankton',
    explain: '호수에 사는 플랑크톤을 의미 ',
    hNm: '호수플랑크톤',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '護岸',
    eNm: 'revetment',
    explain:
      '하안이나 해안, 제방을 유수에 의한 침식을 방지하기 위해 경사면에 설치하는 구조물',
    hNm: '호안',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '護岸工',
    eNm: 'band protection works',
    hNm: '호안공',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '護岸工事',
    eNm: 'sea defence work',
    hNm: '호안공사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好壓性細菌',
    eNm: 'barophilic bacteria',
    explain:
      '높은 압력 조건에서 자라는 세균으로써 수압이나 기압이 높은 환경에서도 생육이 가능한 세균을 칭함',
    hNm: '호압성세균',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '好熱性微生物',
    eNm: 'thermophilic microbes, thermophiles',
    explain: '호열성미생물은 35∼75℃(55∼65℃최적)에서 잘 성장하는 미생물을 칭함',
    hNm: '호열성미생물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '豪雨',
    eNm: 'heavy rain',
    explain: '일반적으로 큰비와 같은 뜻으로 사용',
    hNm: '호우',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'storm cell',
    explain: '호우를 형성하는 구름 대 속의 작은 구름덩이',
    hNm: '호우세포',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '豪雨轉移',
    eNm: 'storm transposition',
    hNm: '호우전이',
    rgsdt: '2016-04-15',
  },
  {
    eNm: "Heygens' principal",
    explain: '층서 구조를 주행하는 탄성파의 거동을 이해하는 이론',
    hNm: '호이겐스 원리',
    rgsdt: '2016-11-26',
  },
  {
    eNm: 'hopper',
    explain: '어떠한 시설 내에서 각종 재료나 배출물들을 일시적으로 저장하는 곳',
    hNm: '호퍼',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'polyphase flow',
    hNm: '혼상류',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'polyphase flow',
    hNm: '혼상류',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '混成防波堤',
    eNm: 'composite breakwater',
    explain: '하부와 상부가 다른재료로 시공된 방파제',
    hNm: '혼성방파제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '混濁度',
    eNm: 'turbidity',
    hNm: '혼탁도',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '混合距離',
    eNm: 'mixing length',
    hNm: '혼합거리',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '混合距離',
    eNm: 'mixing length',
    hNm: '혼합거리',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '混合汚泥',
    eNm: 'mixed sludge',
    explain: '하수처리장의 1, 2차 침전지에서 형성된 슬러지를 혼합한 것',
    hNm: '혼합슬러지',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '混合式 配管法',
    eNm: 'piping process of mixed type ',
    explain: '상향과 하향식 급수를 혼합하는 방식',
    hNm: '혼합식배관법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '混合液',
    eNm: 'mixed liquor',
    explain: '수질에서는 폭기조 내의 혼합액을 말함',
    hNm: '혼합액',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '混合液 濃度',
    eNm: 'mixed liquor concentration',
    explain:
      '활성슬러지 처리를 받는 폐수 중의 활성슬러지 및 유기물의 혼합액 농도를 뜻함',
    hNm: '혼합액 농도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '混合液 浮遊物質 濃度',
    eNm: 'mixed liquor suspended solid',
    explain: ' 활성 슬러지 처리 공정에서 폭기조중의 부유물질(SS)농도를 말함',
    hNm: '혼합액 부유물질농도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '混合液 縣濁固形物',
    eNm: 'mixed liquor suspended solid, MLSS',
    explain:
      '활성 슬러지 처리 공정 중에서 폭기조 내에 함유되어 있는 부유물질(SS)농도',
    hNm: '혼합액 현탁고형물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '混合液 縣濁固形物 負荷',
    eNm: 'mixed liquor suspended solid loading',
    explain:
      '활성슬러지법에 있어서 폭기조 내의 활성슬러지(MLSS로 보아도 무방함) 1㎏으로 하루에 처리할 수 있는 BOD의 ㎏수를 말함',
    hNm: '혼합액 현탁고형물의 부하',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '混合液 揮發性 浮遊物質量',
    eNm: 'mixed liquor volatile suspended solid, MLVSS',
    explain: 'MLSS에 함유된 휘발성 성분의 양',
    hNm: '혼합액 휘발성 부유물질량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '混合處理',
    eNm: 'joint treatment',
    explain:
      '수질 특성이 다른 두 종류의 물을 혼합하여 처리하는 것으로, 가정하수와 공장폐수를 혼합 처리하는 방식이나 산성 폐수와 알칼리성 폐수를 혼합하여 처리하는 방법',
    hNm: '혼합처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '混合形 密度流',
    eNm: 'density flow with mixing',
    hNm: '혼합형 밀도류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '混和池',
    eNm: 'mixing tank',
    explain: '정수처리를 위하여 필요한 약품을 원수에 혼합하는 탱크',
    hNm: '혼화지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水',
    eNm: 'flood',
    explain:
      '강우나 눈이 녹아 발생하는 큰물로 하천 수위가 상승해 하천범람등 위험이 예상되는 큰 물',
    hNm: '홍수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水',
    eNm: 'flood',
    explain:
      '강우나 눈이 녹아 발생하는 큰물로 하천 수위가 상승해 하천범람등 위험이 예상되는 큰 물',
    hNm: '홍수',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '洪水警報',
    eNm: 'flood warning',
    explain: '홍수를 예측해 피해지역에 사전에 알려주는 행동',
    hNm: '홍수경보',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水系列',
    eNm: 'flood series',
    hNm: '홍수계열',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '洪水系列',
    eNm: 'flood series',
    hNm: '홍수계열',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '洪水其 制限水位',
    eNm: 'Ruling Water Level',
    hNm: '홍수기 제한수위',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '洪水其 制限水位',
    eNm: 'Ruling Water Level',
    hNm: '홍수기 제한수위',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '洪水帶',
    eNm: 'flood zones',
    hNm: '홍수대',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '洪水帶',
    eNm: 'flood zones',
    hNm: '홍수대',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '洪水到達時間',
    eNm: 'flood arrival time',
    hNm: '홍수도달시간',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '洪水到達時間',
    eNm: 'flood arrival time',
    hNm: '홍수도달시간',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '洪水路',
    eNm: 'floodway',
    explain: '초과홍수유량을 원활히 배출시키기 위한 수로',
    hNm: '홍수로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水氾濫地圖',
    eNm: 'flooding map',
    hNm: '홍수범람지도',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '洪水氾濫地圖',
    eNm: 'flooding map',
    hNm: '홍수범람지도',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '洪水壁',
    eNm: 'flood wall',
    hNm: '홍수벽',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水邊',
    eNm: 'flood fringe',
    hNm: '홍수변',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '洪水邊',
    eNm: 'flood fringe',
    hNm: '홍수변',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '洪水頻度',
    eNm: 'flood frequency',
    explain: '특정기간 동안에 홍수가 나타날 수 있는 평균적인 횟수',
    hNm: '홍수빈도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水事象',
    eNm: 'flood event',
    explain:
      '시간적으로 독립된 강우사상으로 인해 하천유역에서 발생하는 수리·수문학적 현상.',
    hNm: '홍수사상',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水豫報',
    eNm: 'flood forecasting',
    explain: '홍수 발생을 예측하여 미리 알리는 행위',
    hNm: '홍수예보',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水豫報',
    eNm: 'flood forecasting',
    explain: '홍수 발생을 예측하여 미리 알리는 행위',
    hNm: '홍수예보',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '洪水位',
    eNm: 'flood elevation',
    explain:
      '홍수시 하천수위를 통칭하며, 특정지점에서 제방의 안전을 보장할 수 있는 최대 홍수위를 설계홍수위라 함.',
    hNm: '홍수위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水位',
    eNm: 'flood elevation',
    explain:
      '홍수시 하천수위를 통칭하며, 특정지점에서 제방의 안전을 보장할 수 있는 최대 홍수위를 설계홍수위라 함.',
    hNm: '홍수위',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '洪水位縱斷圖',
    eNm: 'flood profile',
    explain:
      '하천 종단면도상에 홍수 발생위험을 빈도별 홍수위로 표시한 하천수위 구분도',
    hNm: '홍수위종단도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水流出',
    eNm: 'flood runoff',
    hNm: '홍수유출',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '洪水流出',
    eNm: 'flood runoff',
    hNm: '홍수유출',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '洪水調節',
    eNm: 'flood control',
    explain:
      '급격한 홍수위 증가 및 과도한 홍수량 유하로 인한 홍수피해를 막기 위해 홍수량의 시· 공분포를 조정하여 홍수의 집중에 의한 피해를 줄이는 행위.',
    hNm: '홍수조절',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水調節構造物',
    eNm: 'flood detention structure',
    explain:
      '홍수 시 하천의 유량 조절기능을 가져 홍수향을 경감할 수 있는 구조물',
    hNm: '홍수조절구조물',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'flood control dam',
    explain: '홍수 피해를 최소화하기 위해 설치하는 댐',
    hNm: '홍수조절댐',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'flood control dam',
    explain: '홍수 피해를 최소화하기 위해 설치하는 댐',
    hNm: '홍수조절댐',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '洪水調節容量',
    eNm: 'flood control capacity',
    explain: '상시만수위와 홍수위 또는 홍수기 제한수위와 설계홍수위사이의 용량',
    hNm: '홍수조절용량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水調節池',
    eNm: 'flood control reservoir',
    explain: '홍수조절댐이라고도 하며 홍수피해를 저감하기 위해 설치함',
    hNm: '홍수조절지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水追跡',
    eNm: 'flood routing',
    explain: '하류측으로 홍수파의 전파상황을 계산하는 것.',
    hNm: '홍수추적',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水터',
    eNm: 'overbank, flood plain',
    explain: '홍수시 저수로를 넘쳐 물이 흐르는 구역',
    hNm: '홍수터',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水波',
    eNm: 'flood wave',
    explain: '수위가 최대치로 상승하였다가 저하되는 홍수시 수면의 진동현상',
    hNm: '홍수파',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水確率',
    eNm: 'flood probability',
    hNm: '홍수확률',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洪水痕迹',
    eNm: 'flood marks',
    hNm: '홍수흔적',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '紅藻類',
    eNm: 'red algae, Rhodophyta',
    explain:
      '진핵조류 (eukaryotic algae) 중 가장 오래된 종류 중 하나로 붉은색을 띰',
    hNm: '홍조류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '花崗岩',
    eNm: 'granite',
    explain:
      '석영(SiO2)이 주성분이며 석영, 장석, 운모 등이 들어있는 규장질 심성암 중에 흔히 발견되는 암석',
    hNm: '화강암',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '花崗岩',
    eNm: 'granite',
    explain:
      '석영(SiO2)이 주성분이며 석영, 장석, 운모 등이 들어있는 규장질 심성암 중에 흔히 발견되는 암석',
    hNm: '화강암',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '花崗岩',
    eNm: 'granite',
    explain:
      '석영(SiO2)이 주성분이며 석영, 장석, 운모 등이 들어있는 규장질 심성암 중에 흔히 발견되는 암석',
    hNm: '화강암',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '火口湖',
    eNm: 'crater lake',
    explain: '화산 활동으로 생긴 분화구에 물이 괴어져 있는 호수',
    hNm: '화구호',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '火力發電所',
    eNm: 'thermal-power station',
    explain:
      '석유나 석탄 같은 화석에너지에 의해 증기를 발생시켜 전기를 생산하는 곳',
    hNm: '화력발전소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '火山',
    eNm: 'volcano',
    explain:
      '지구 내부 마그마가 지구조적운동에 의해 지표를 뚫고 나와 분출하여 만들어진 지형',
    hNm: '화산',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'volcanic gas',
    explain:
      '화산 분화 시에 나오는 가스로 주로 수증기로 구성되어 있으며, 그 외에 이산화탄소, 질소, 아황산가스, 수소, 일산화탄소, 황, 염소 등을 포함',
    hNm: '화산가스',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'volcanic gas',
    explain:
      '화산 분화 시에 나오는 가스로 주로 수증기로 구성되어 있으며, 그 외에 이산화탄소, 질소, 아황산가스, 수소, 일산화탄소, 황, 염소 등을 포함',
    hNm: '화산가스',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '火山噴出雲',
    eNm: 'cloud from volcanic eruptions',
    explain:
      '일반적인 화산재보다 작은 입자사이즈를 가지며 구름 형태로 퍼져나감',
    hNm: '화산분출구름',
    rgsdt: '2016-04-15',
  },
  {
    hNm: '화산쇄설 퇴적암',
    rgsdt: '2016-11-23',
  },
  {
    hNm: '화산쇄설 퇴적암',
    rgsdt: '2023-09-18',
  },
  {
    cNm: '火山災',
    eNm: 'ash',
    explain:
      '화산 활동으로 인한 충격이나 화산 가스의 침식 등으로 부서진 상태로 방출되는 암편들을 화산쇄설물이라 하며, 이 중 화산에서 분출된 용암의 부스러기 가운데 크기가 0.25~4mm 정도의 작은 알갱이들의 퇴적물을 화산재라 한다.',
    hNm: '화산재',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '火山災',
    eNm: 'ash',
    explain:
      '화산 활동으로 인한 충격이나 화산 가스의 침식 등으로 부서진 상태로 방출되는 암편들을 화산쇄설물이라 하며, 이 중 화산에서 분출된 용암의 부스러기 가운데 크기가 0.25~4mm 정도의 작은 알갱이들의 퇴적물을 화산재라 한다.',
    hNm: '화산재',
    rgsdt: '2023-09-18',
  },
  {
    cNm: '化石燃料',
    eNm: 'compound fuel',
    explain:
      '과거에 서식했던 동식물의 유해가 땅속에 묻혀 오랜 시간동안 높은 압력과 열을 받아 형성된 연료',
    hNm: '화석연료',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '火成岩 ',
    eNm: 'igneous rock ',
    explain: '지구 내부의 마그마가 식어서 형성된 암석',
    hNm: '화성암 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '華氏溫度',
    eNm: 'Fahrenheit',
    hNm: '화씨온도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '華氏溫度計',
    eNm: 'Fahrenheit thermometer',
    explain: '화씨온도를 측정할 수 있는 온도계',
    hNm: '화씨온도계',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '火焰滅菌',
    eNm: 'flame sterilization, flaming',
    explain:
      '멸균하고자 하는 물체를 불꽃에 직접 접촉시켜 피 멸균품의 표면에 붙어 있는 미생물을 태워서 멸균시키는 방법',
    hNm: '화염멸균',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學量論',
    eNm: 'stoichiometry',
    explain:
      '원소, 화합물에 대하여 수량적으로 나타낸 성질 사이의 관계를 연구하는 화학의 한 부문',
    hNm: '화학량론',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學反應',
    eNm: 'chemical reaction',
    hNm: '화학반응',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學反應速度論',
    eNm: 'chemical kinetics',
    explain:
      '원자나 분자 등이 화학결합 및 분해 할 때의 반응 속도에 관한 학문분야',
    hNm: '화학반응속도론',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學有機營養性細菌',
    eNm: 'chemoorganotroph',
    hNm: '화학유기영양성세균',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學的 酸素要求量',
    eNm: 'chemical oxygen demand, COD',
    explain:
      '오염물질을 산화제로 하여 산화하여 분해하는데 있어 필요한 산소량으로써 물의 오염정도를 나타내는 기준으로 사용',
    hNm: '화학적 산소요구량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學的 酸素要求量 試驗法',
    eNm: 'COD, chemical oxygen demand method',
    explain:
      '수중에서 망간 또는 크롬과 같은 산화제에 의해 오염물질을 산화할 때 요구되어 지는 산소의 양을 측정하는 방법',
    hNm: '화학적 산소요구량 시험법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學的 凝集',
    eNm: 'chemical coagulation',
    explain:
      '현탁입자와 응집제가 화학적 결합력에 의해 서로 뭉쳐지고 더 큰 물질로 합쳐지는 것',
    hNm: '화학적 응집',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學的 淨化',
    eNm: 'chemical purification',
    explain: '화학 약품을 주입하여 물을 정화하는 것을 의미한다',
    hNm: '화학적 정화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學的 處理',
    eNm: 'chemical treatment',
    explain:
      '화학약품을 사용하여 물을 처리하는 것. 염소 소독, 석회-소다법과 같은 물의 연수화, 부유물질 및 탁도 제거를 위한 응집제 주입, 침전에 의한 중금속 및 인의 제거, 이온교환 등에 화학 약품을 이용하여 물을 처리하는 것들을 의미',
    hNm: '화학적 처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學的 沈澱',
    eNm: 'chemical precipitation',
    explain:
      '물속의 오염물질의 제거하기 위해 약품을 주입하여 오염물질을 중력에 의해 가라앉을 수 있는 크기로 응집시키고, 침전하여 제거하는 것',
    hNm: '화학적 침전',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學的 風化',
    eNm: 'chemical weathering',
    explain:
      '암석이 산화, 환원, 가수분해, 탄산화작용 등의 반응에 의해 분해되는 과정',
    hNm: '화학적 풍화',
    rgsdt: '2016-04-15',
  },
  {
    explain:
      '혼합물 1에 포함되어 있는 A성분의 활동도를 a1라고 하고, A의 퓨가시티를 f1, 순수한 상태로 존재하는 물질 A의 퓨가시티를 f0라고 하면 다음과 같이 정의된다.a1=f1/f0',
    hNm: '화학적 활동도',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '化學的單位工程',
    eNm: 'chemical unit process',
    hNm: '화학적단위공정',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學的防除 ',
    eNm: 'chemical insect control',
    hNm: '화학적방제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學的酸化(法)',
    eNm: 'chemical oxidation',
    explain:
      '물 속에 화학적 산화제를 주입하여 오염물질을 처리하는 방법으로, 염소, 오존, 차아염소산등에 의한 유기물의 산화제거, 세포의 소독 등이 해당됨',
    hNm: '화학적산화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學的酸化(法)',
    eNm: 'chemical oxidation',
    explain:
      '물 속에 화학적 산화제를 주입하여 오염물질을 처리하는 방법으로, 염소, 오존, 차아염소산등에 의한 유기물의 산화제거, 세포의 소독 등이 해당됨',
    hNm: '화학적산화',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '化學的汚泥改良',
    eNm: 'chemical sludge conditioning',
    explain:
      '슬러지의 개량은 슬러지의 안정화 및 탈수성 향상을 위해 행하는 것으로, 화학적 개량은 약품처리라고도 하며 하수슬러지 탈수의 전처리법으로 가장 일반화되어 있는 방법임',
    hNm: '화학적슬러지개량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學的脫燐法',
    eNm: 'chemical phosphorus removal',
    explain:
      '폐수중에 존재하는 인의 제거에 미생물을 이용하지 않고 석회 또는 응집제 등의 화학약품을 통하여 인을 제거하는 방법',
    hNm: '화학적탈인법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '化學吸着',
    eNm: 'chemical adsorption, chemisorption',
    explain:
      '화학적 결합에 의한 흡착으로, 전자 이동을 수반하는 화학반응과 유사',
    hNm: '화학흡착',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '擴大損失',
    eNm: 'enlargement',
    hNm: '확대손실',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '擴大損失',
    eNm: 'enlargement',
    hNm: '확대손실',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '確率降雨强度',
    eNm: 'probable rainfall intensity',
    explain: '확률강우량을 지속시간으로 나누어 강우강도로 환산한 값.',
    hNm: '확률강우강도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '確率分布',
    eNm: 'probability distribution',
    explain: '확률변수가 특정값을 가지게 되는 확률을 표현한 함수',
    hNm: '확률분포',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '擴散 ',
    eNm: 'diffusion',
    explain: '유체에서 농도구배의 반대 방향으로 물질이 퍼져나가는 현상',
    hNm: '확산',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '擴散二重層',
    eNm: 'diffuse double layer',
    explain:
      '확산이란 열운동에 의해 물질의 분자가 가능한 한 넓은 공간으로 퍼지는 것으로 이 때의 비례상수를 확산계수라 함',
    hNm: '확산 이중층',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '擴散係數',
    eNm: 'diffusivity',
    explain:
      '물과 같은 액체나 공기 중에 어떠한 물질이 유입되어 퍼져 나가는 것을 의미',
    hNm: '확산계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '擴散過程',
    eNm: 'diffusion process',
    hNm: '확산과정',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'diffusion mechanism',
    explain:
      '점토나 콜로이드와 같은 매우 미세한 입자 표면 근처에 입자 표면의 부전화와 균형을 이루기 위해 약간의 음이온과 양이온이 액상 속을 확산적으로 분포된 확산층과 고착층이 형성',
    hNm: '확산메커니즘',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'diffusion mechanism',
    explain:
      '점토나 콜로이드와 같은 매우 미세한 입자 표면 근처에 입자 표면의 부전화와 균형을 이루기 위해 약간의 음이온과 양이온이 액상 속을 확산적으로 분포된 확산층과 고착층이 형성',
    hNm: '확산메커니즘',
    rgsdt: '2023-10-19',
  },
  {
    eNm: 'diffusion mechanism',
    explain:
      '점토나 콜로이드와 같은 매우 미세한 입자 표면 근처에 입자 표면의 부전화와 균형을 이루기 위해 약간의 음이온과 양이온이 액상 속을 확산적으로 분포된 확산층과 고착층이 형성',
    hNm: '확산메커니즘',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '確定論的流出模型',
    eNm: 'deterministic runoff model',
    explain: '확정론적으로 모의할 수 있는 수문강우유출모형',
    hNm: '확정론적유출모형',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境',
    eNm: 'environment',
    explain:
      '사전적 의미로 생물에게 직ㆍ간접으로 영향을 주는 자연적 조건이나 사회적 상황을 포괄적으로 칭함',
    hNm: '환경',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境減率',
    eNm: 'Environmental Lapse Rate',
    hNm: '환경감률',
    rgsdt: '2016-11-18',
  },
  {
    cNm: '環境減率',
    eNm: 'Environmental Lapse Rate',
    hNm: '환경감률',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '環境改善負擔金制度',
    eNm: 'environment improvement pays institution',
    explain:
      '오염물질을 배출한 자가 오염원인자 부담원칙에 의해 처리비용을 부담하도록 하는 제도',
    hNm: '환경개선부담금제도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境管理公團',
    eNm: 'environmental management industry0',
    explain:
      '1987년 11월 환경오염 방지사업 수행을 목적으로 설립된 환경처 산하 기관으로 2015년 현재 한국환경공단으로 변경됨',
    hNm: '환경관리공단',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'environmental management system',
    explain:
      '환경시설물관리, 자연자원관리, 폐기물관리 등 속성데이터와 지리 데이터를 상호 연결하여 계획 및 예측 모델링을 수행하는 체계',
    hNm: '환경관리시스템',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境基準',
    eNm: 'environmental standard',
    explain:
      '각종 오염물질에 대한 위해성을 판단하고 자연 환경의 오염 여부 및 정도를 판단하기 위한 기준으로 인간의 건강 보호와 생활환경을 보존하기 위해 대기, 수질, 토양, 소음 진동 등의 환경조건을 규제하는데 적용되는 허용 기준',
    hNm: '환경기준',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'environmental monitoring',
    explain:
      '대기, 물, 토양 및 지하수로 구성된 환경요소의 오염상황을 탐지해내는 행위나 기술을 뜻함',
    hNm: '환경모니터링',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境問題',
    eNm: 'environmental problem',
    hNm: '환경문제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境保全',
    eNm: 'preservation of environment',
    explain:
      '자연이 가진 본래의 깨끗한 상태를 유지하기 위해 인간이 환경을 보호, 정비, 관리하는 일',
    hNm: '환경보전',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境保全法',
    eNm: 'environmental protection law',
    hNm: '환경보전법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境保護',
    eNm: 'environmental protection',
    explain:
      '자연이 가진 환경의 균형유지에 인간의 활동으로 인한 나쁜 영향을 미치지 않도록 보호하는 조치',
    hNm: '환경보호',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境保護廳',
    eNm: 'Environmental Protection Agency, EPA',
    explain:
      '환경오염과 오염방지를 위한 여러 가지의 대책들을 통일하고, 환경정책을 추진하는 기관',
    hNm: '환경보호청',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境復元',
    eNm: 'remediation',
    hNm: '환경복원',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境收容力',
    eNm: 'Environmental capacit',
    explain:
      '환경이 수용할 수 있는 범위로 한 생태계에서 개체군의 수가 증가할 수 있는 최대치를 의미하기도 하고, 인간이 환경을 오염시켰을 때 환경이 자정작용을 할 수 있는 최대치의 오염범위를 의미하기도 함',
    hNm: '환경수용력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境惡化',
    eNm: 'environmental deterioration',
    explain:
      '수질, 대기오염 등 자연환경이 오염되거나 오염 또는 소음, 진동 등 생활환경의 질이 떨어지는 것과 같이 오염이나 파괴로  환경의 질이 떨어지는 것',
    hNm: '환경악화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境影響',
    eNm: 'environmental impact',
    explain:
      '인간행위 및 기술적용이 사람을 둘러싼 자연환경에 주는 변화, 영향을 말함',
    hNm: '환경영향',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境影響評價',
    eNm: 'environmental impact assessment',
    explain:
      '환경에 영향을 미치는 실시계획·시행계획 등의 허가·인가·승인·면허 또는 결정 등을 할 때에 해당 사업이 환경에 미치는 영향을 미리 조사·예측·평가하여 해로운 환경영향을 피하거나 제거 또는 감소시킬 수 있는 방안을 마련하는 것을 말함',
    hNm: '환경영향평가',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境汚染 ',
    eNm: 'environmental pollution',
    explain:
      '모든 자연환경이 자연계가 스스로의 회복능력을 넘어서 악영향을 주는 모든 것이 배출에 의해 일어나는 오염을 말한다. 인공과 천연의 것이 있고 이중 인공오염은 인류의 경제활동에 의해 발생하는 것으로 최근에는 산업활동과 인구집중 등이 주원인으로 작용하고 있음',
    hNm: '환경오염',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境要因',
    eNm: 'environmental factor',
    explain: '환경을 구성하는 다양한 요소를 의미',
    hNm: '환경요인',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境要因',
    eNm: 'environmental factor',
    explain: '환경을 구성하는 다양한 요소를 의미',
    hNm: '환경요인',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '環境容量',
    eNm: 'environmental acceptable capacity',
    explain:
      '일정한 지역에서 환경오염 또는 환경훼손에 대해 환경이 스스로 수용, 정화 및 복원하여 환경의 질을 유지할 수 있는 한계',
    hNm: '환경용량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境用水',
    explain:
      '환경용수는 수질보전, 경관보전, 생태계보전 등을 위하여 공급하는 물을 말함',
    hNm: '환경용수',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '環境容量',
    eNm: 'environmental volume',
    explain: '환경이 정화할 수 있는 오염허용량',
    hNm: '환경용적',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境危害性',
    eNm: 'environmental risk',
    explain: '어떤 물질이 인체나 생물에 가하는 위해 정도를 평가하는 것',
    hNm: '환경위해성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境流量',
    hNm: '환경유량',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '環境流量',
    hNm: '환경유량',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '環境破壞',
    eNm: 'environmental destruction',
    explain:
      '자연에 여러 가지 오염물질을 배출하거나 도시건설, 도로개발, 광산개발, 유전개발 등 물리적으로 변화할 수 있는 힘을 가하여 자연이 파괴되는 것을 의미',
    hNm: '환경파괴',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '環境評價',
    eNm: 'environmental assessment',
    explain:
      '전략환경평가, 환경영향평가 등 정책 계층구조와 관계있는 정책, 행정계획, 사업 등이 환경에 미칠 영향을 종합적으로 예측하고 분석·평가하는 과정',
    hNm: '환경평가',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'environmental hormone, endocrine disrupters',
    explain:
      '몸에서 정상적으로 만들어지는 호르몬이 아닌 산업 활동을 통해 만들어진 화학물질이 체내에 유입되어 정상적으로 생산된 호르몬처럼 역할을 하는 물질',
    hNm: '환경호르몬',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '還元',
    eNm: 'reduction',
    explain: '화학반응에서 전자를 얻는 것을 의미',
    hNm: '환원',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '還元灌漑',
    eNm: 'reduction irrigation',
    hNm: '환원관개',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '還元灌漑',
    eNm: 'reduction irrigation',
    hNm: '환원관개',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '還元水',
    eNm: 'return flow',
    explain:
      '농지에 관개한 물은 일부는 이용되지만 일부는 지표 배수로나 지하흐름을 통하여 하류로 흘러가게 됨',
    hNm: '환원수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '滑降風',
    eNm: 'katabatic wind',
    explain: '고도가 높은 곳에서 차가운 공기가 중력에 의해 아래로 흐르는 바람',
    hNm: '활강바람',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '滑面境界',
    eNm: 'smooth boundary',
    hNm: '활면경계',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '滑面境界',
    eNm: 'smooth boundary',
    hNm: '활면경계',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '活酸度',
    eNm: 'active acidity',
    explain: '토양 용액의 수소이온 농도',
    hNm: '활산도',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '活性生物膜濾床',
    eNm: 'activated biofilter process',
    explain:
      '고율 살수여상과 비슷하나 최종침전지의 슬러지를 살수여상에 반송시키는 점이 차이가 있음',
    hNm: '활성생물막여상',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '活性汚泥',
    eNm: 'activated sludge',
    explain: '하수나 폐수에 생기는 세균 등의 미생물로 이루어진 슬러지',
    hNm: '활성슬러지 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '活性汚泥工法',
    eNm: 'activated sludge process',
    explain:
      '폐수처리에서 생물학적 방법을 통해 폐수와 활성슬러지의 혼합물에 공기를 주입하여 폐수를 처리하는 방법을 말한다.',
    hNm: '활성슬러지공법',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '活性汚泥濃度',
    eNm: 'activated sludge density',
    hNm: '활성슬러지농도',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '活性汚泥法',
    eNm: 'activated sludge process',
    explain:
      '폐수처리에 사용되는 생물학적 방법으로 폐수와 활성슬러지와의 혼합물을 혼합시켜 공기를 불어 넣음으로써 생물적으로 폐수를 처리하는 방법',
    hNm: '활성슬러지법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '活性汚泥生物',
    eNm: 'activated sludge organism',
    explain: '활성슬러지 중에 생식하는 세균, 균류, 미소동물을 말함',
    hNm: '활성슬러지생물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '活性汚泥循環變法',
    eNm: 'nitrified liquor recycle single-sludge nitrification',
    explain:
      '반응조의 전단에 무산소반응조, 후단에 호기반응조를 설치하여, 후단의 질산화액을 전단에 순환시켜 생물학적 탈질을 행하는 방법',
    hNm: '활성슬러지순환변법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '活性汚泥汚泥膨化 ',
    eNm: 'bulking',
    explain:
      '생물반응조(포기조)를 거쳐 침전지로 유입된 하폐수중에 함유된 생물학적 플록의 침강성이 불량하여 고액분리효율이 낮아지는 상태를 말하며 주로 사상성 균류의 증식에 의하여 유발됨.',
    hNm: '활성슬러지의 팽화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '活性層',
    eNm: 'active layer',
    hNm: '활성층',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '活性炭',
    eNm: 'activated carbon, AC',
    explain:
      '미세한 구멍으로 인한 표면적이 매우 넓게 되도록 만들어진 숯을 의미',
    hNm: '활성탄',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '活性炭工法',
    eNm: 'activated carbon process',
    explain: '오염된 물을 처리하는데 있어 활성탄을 사용하여 처리하는 방법',
    hNm: '활성탄공법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '活性炭再生',
    eNm: 'activated carbon regenetation',
    explain:
      '흡착능력을 잃은 활성탄을 재차 흡착조작이 유용하도록 하는 하는 조작 ',
    hNm: '활성탄재생',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '活性炭再生爐',
    eNm: 'activated carbor regenerator',
    explain:
      '흡착이 포화에 달한 활성탄의 재생을 행하는 노로, 로타리킬른, 다단로 등이 사용되고 있음',
    hNm: '활성탄재생로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '活性炭再生法',
    eNm: 'regeneration of spent carbon, reactivation of spent carbon',
    explain:
      '활성탄의 재생은 흡착에 사용한 활성탄이 흡착물질을 흡착하고 거의 흡착능력을 잃은 활성탄에 흡착물질을 제거하여 재차 흡착조작에 유용하게 쓰이도록 하는 조작',
    hNm: '활성탄재생법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '活性炭再生裝置',
    eNm: 'activated carbon regeneration facility',
    explain: '흡착능력을 잃은 활성탄을 재차 흡착조작이 유용하도록 하는 시설',
    hNm: '활성탄재생장치',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '活性炭再生裝置',
    eNm: 'activated carbon regeneration facility',
    explain: '흡착능력을 잃은 활성탄을 재차 흡착조작이 유용하도록 하는 시설',
    hNm: '활성탄재생장치',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '活性炭處理',
    eNm: 'activated carbon treatment',
    explain: '활성탄을 사용하여 오염물질을 제거하는 것',
    hNm: '활성탄처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '活性炭吸着法',
    eNm: 'activated carbon absorption process',
    explain: '용해성 유기물을 활성탄을 사용하여 흡착, 제거하는 방법',
    hNm: '활성탄흡착법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '活性炭吸着施設',
    eNm: 'activated carbon absorption facilities',
    explain:
      '분말활성탄 교반기와 배관 및 투입펌프 등의 제반 시설이나 입상활성탄의 충전탑과 유입유출 펌프와 배관 등의 시설',
    hNm: '활성탄흡착시설',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'activation energy',
    explain: '화학 물질이 반응을 일으키는데 있어 필요한 최소한의 에너지',
    hNm: '활성화 에너지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '活性化劑',
    eNm: 'activator',
    explain:
      '촉매의 활성을 도와 반응촉진작용을 증대시키는 물질 또는 형인광체에 발광성을 가지도록 가해지는 물질',
    hNm: '활성화제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '滑昇霧',
    eNm: 'upslope fog',
    explain:
      '습윤한 공기가 산비탈을 따라 빠르게 상승하면서 냉각되고 포화되어 응결에 의해 형성되는 안개',
    hNm: '활승안개',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '黃酸',
    eNm: 'sulfuric acid',
    explain: '비휘발성의 강한 산으로 무색의 액체이다.',
    hNm: '황산',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '黃酸工場排水',
    eNm: 'sulphuric acid industry sewage',
    explain: '황산공장에서 아황산가스의 냉각 세정에 사용한 물',
    hNm: '황산공장배수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '黃酸銅處理',
    eNm: 'copper sulfate treatment',
    hNm: '황산동처리',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '黃酸銅處理',
    eNm: 'copper sulfate treatment',
    hNm: '황산동처리',
    rgsdt: '2023-09-27',
  },
  {
    eNm: 'aluminium sulfate',
    hNm: '황산알루미늄',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'aluminium sulfate',
    hNm: '황산알루미늄',
    rgsdt: '2023-09-27',
  },
  {
    eNm: 'sulfate-reducing bacteria',
    hNm: '황산염환원세균',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'sulfate-reducing bacteria',
    hNm: '황산염환원세균',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '黃酸第二鐵',
    eNm: 'ferric sulfate',
    explain: '수중의 알칼리와 반응하여 수산화물을 생성하는 응집제',
    hNm: '황산제이철',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '黃酸第一鐵',
    eNm: 'ferrous sulfate',
    explain: '널리 사용되는 응집제로 소석회와 함께 사용',
    hNm: '황산제일철',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '黃色鞭毛藻類',
    eNm: 'Chrysophyceae',
    explain:
      '황조강에 속하는 조류의 총칭으로 황금색조류, 황색편모조류, 황갈색조류 로도 불림',
    hNm: '황색편모조류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '黃色葡萄狀球菌',
    eNm: 'staphylococcus aureus',
    explain:
      '포도상구균의 종류로써 생육함에 따라 덩어리(세포집괴)를 형성하는 그람양석의 통성 혐기성 세균',
    hNm: '황색포도상구균',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '黃細菌',
    eNm: 'sulphur bacteria',
    explain:
      '황 또는 무기화합물을 산화함으로써 성장에 필요한 에너지를 얻는 세균',
    hNm: '황세균',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '黃細菌',
    eNm: 'sulphur bacteria',
    explain:
      '황 또는 무기화합물을 산화함으로써 성장에 필요한 에너지를 얻는 세균',
    hNm: '황세균',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '黃細菌',
    eNm: 'sulphur bacteria',
    explain:
      '황 또는 무기화합물을 산화함으로써 성장에 필요한 에너지를 얻는 세균',
    hNm: '황세균',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '黃化物',
    eNm: 'sulfide',
    explain: '황보다 양성인 원소와 황이 화학결합을 한 화합물의 총칭',
    hNm: '황화물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '黃化物凝集沈澱法',
    eNm: 'sulfide coagulative precipitation method',
    explain:
      '배수 중에 포함되는 금속이온을 황화 금속의 형태로 침전시키고 응집 제거하는 배수처리 방법',
    hNm: '황화물 응집침전법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '黃化水素',
    eNm: 'hydrogen sulfide',
    explain: '수소와 황이 만나 결합한 것으로 악취를 가진 무색의 유독한 기체',
    hNm: '황화수소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '回歸分析',
    eNm: 'regression analysis',
    hNm: '회귀분석',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '回歸分析',
    eNm: 'regression analysis',
    hNm: '회귀분석',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '回分式反應槽',
    eNm: 'batch reactor',
    explain:
      '연속 유입식이 아니라 1회 처리량을 반응조 받아서 처리 후 일정량을 배출시키는 시스템',
    hNm: '회분식반응조',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '回分沈降曲線',
    eNm: 'batch precipitation curve',
    explain:
      '현탁액을 직경 5㎝이상, 높이 100㎝이상의 투명 실린더에 넣고 수 처리를 할 때, 시간 t에 따라 현탁액의 높이 H가 감소하는 경향을 나타낸 그래프 ',
    hNm: '회분침강곡선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '回轉生物膜接觸機',
    eNm: 'rotating biological contactor, RBC',
    hNm: '회전(판)생물막 접촉기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '回轉乾燥燒却爐 ',
    eNm: 'rotary kiln',
    explain:
      '회전하는 원통형 소각로이며, 슬러리와 같은 폐기물을 소각할 때 사용',
    hNm: '회전건조소각로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '回轉生物接觸法',
    eNm: 'rotating biological contactor',
    explain:
      '생물학적 하폐수처리공법의 하나로써, 독일에서 개발된 방법으로 포기장치를 이용하여 동력으로 산소를 공급하는 활성슬러지법과는 달리 미생물이 부착된 원판을 회전시켜 별도의 공기공급장치 없이 산소를 공급받도록 하는 하폐수 처리방법, 회전원판법이라고도 함',
    hNm: '회전생물접촉법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '回轉生物接觸法',
    eNm: 'rotating biological contactor',
    explain:
      '생물학적 하폐수처리공법의 하나로써, 독일에서 개발된 방법으로 포기장치를 이용하여 동력으로 산소를 공급하는 활성슬러지법과는 달리 미생물이 부착된 원판을 회전시켜 별도의 공기공급장치 없이 산소를 공급받도록 하는 하폐수 처리방법, 회전원판법이라고도 함',
    hNm: '회전생물접촉법',
    rgsdt: '2023-10-19',
  },
  {
    eNm: 'rotating strainer, revolving strainer',
    explain:
      '회전하는 망 형태의 스트레이너를 통하여 원수에 함유된 입자를 체거름으로 제거하는 장치',
    hNm: '회전스트레이너',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '回轉式撒水機',
    eNm: 'rotary distributor',
    explain: '살수여상에 물을 분사하는 장치로써 회전하는 형태의 살수장치',
    hNm: '회전식살수기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '回轉圓板法',
    eNm: 'rotating biological contactor, RBC',
    explain:
      '생물막을 이용하여 하수를 처리하는 방식으로 회전원판이 폐수면 아래 40% 정도가 수면에 잠기도록 설치하여,원판을 회전시키면서 회전판위에 발생하는 호기성생물을 이용하여 하수를 처리하는 방법',
    hNm: '회전원판법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '回折',
    eNm: 'diffraction',
    explain:
      '파동이 좁은 틈이나 굴곡진 곳 등을 통과할 때 좁은 틈 옆의 막혀진 부분까지 파가 전달되는 현상',
    hNm: '회절',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '回折波',
    eNm: 'diffraction wave',
    explain: '전파가 장애물에 막혔을 때 돌아서 장애물의 배후까지 도달하는 파',
    hNm: '회절파',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '回折現象',
    eNm: 'diffraction phenomenon',
    explain: '파동이 장애물이 있을 때 직진하지 않고 휘어서 진행하는 현상',
    hNm: '회절현상',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '橫斷工法',
    eNm: 'pipe-crossing method',
    hNm: '횡단공법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '橫斷面',
    eNm: 'cross-section',
    hNm: '횡단면',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '橫流式 沈澱池',
    eNm: 'lateral flow sedimentation basin',
    explain:
      '장방형 침전지에서 물의 흐름이 상하류가 아닌 횡류로 흐르는 층류 침전지',
    hNm: '횡류식 침전지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '橫流濾過',
    eNm: 'cross-flow filtration',
    explain:
      '수평 방향으로 원수를 흘려서 여과하는 방법 또는 여과층(막)과 평행한 방향으로 흐르며 여과되는 방식',
    hNm: '횡류여과',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '橫越流',
    eNm: 'side overflow',
    hNm: '횡월류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '橫流入流',
    eNm: 'lateral inflow',
    hNm: '횡유입류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '橫波',
    eNm: 'cross wave, transverse wave',
    explain: '파의 진행과 매질의 진동방향이 수직인 파',
    hNm: '횡파',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '橫波',
    eNm: 'cross wave, transverse wave',
    explain: '파의 진행과 매질의 진동방향이 수직인 파',
    hNm: '횡파',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '酵素反應',
    eNm: 'enzyme reaction',
    explain: '생체내에서 물질의 합성이나 분해 등 효소가 작용하는 반응을 칭함',
    hNm: '효소반응',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '酵素分解',
    eNm: 'zymolysis',
    hNm: '효소분해',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '酵素電極',
    eNm: 'enzyme electrode',
    hNm: '효소전극',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '後生動物',
    eNm: 'metazoa',
    explain:
      '다세포 체제를 갖는 동물의 총칭이며 단세포성인 원생동물과는 반대말',
    hNm: '후생동물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '後石灰處理',
    eNm: 'lime post-treatment',
    explain: '탈수처리 후 슬러지의 pH 상승을 목적으로 석회를 혼합하는 조작',
    hNm: '후석회처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '後鹽素注入',
    eNm: 'post chlorination',
    explain:
      '정수처리과정에 있어 급수 직전에 일반 가정의 수도꼭지에서 물이 나올 때까지 소독제인 염소를 잔류시킬 목적으로 소독하는 것',
    hNm: '후염소주입',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '後鹽素處理',
    eNm: 'post chlorination',
    explain:
      '정수처리과정에 있어 급수 직전에 일반 가정의 수도꼭지에서 물이 나올 때까지 소독제인 염소를 잔류시킬 목적으로 소독하는 것',
    hNm: '후염소처리',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'post-ozonization',
    explain:
      '오존의 특성 중 하나인 강한 산화, 분해 작용에 의해 수중의 오염물질을 정화하는 방식으로 폐수의 최종처리에 이용함',
    hNm: '후오존처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '後沈澱',
    eNm: 'post precipitation',
    explain:
      '정수처리공정에서 응집에 필요한 알칼리도를 높이기 위하여 투입된 과잉의 소석회가 송배수과정에서 수도관이나 배수지 등에서 탄산칼슘으로 침전되는 현상',
    hNm: '후침전',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '後曝氣',
    eNm: 'post aeration',
    explain:
      '주로 하폐수처리공정에서 실시되는 조작으로 생물학적 처리후 낮아진 용존산소를 높여주기 위한 포기 ',
    hNm: '후포기',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'hook gauge',
    explain: '훅 모양의 굽은 바늘이 있는 수면 측정 장치의 일종 ',
    hNm: '훅 게이지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '燻煙',
    eNm: 'fume',
    explain:
      '금속 산화물과 같이 가스상 물질이 승화, 증류 및 화학반응 과정에서 응축될 때 주로 생성되는 고체 입자',
    hNm: '훈연',
    rgsdt: '2016-11-18',
  },
  {
    cNm: '揮發酸',
    eNm: 'volatile acid',
    explain:
      '슬러지 소화에 있어서 복잡한 유기물이 혐기성 분해될 때의 중간생성물',
    hNm: '휘발산',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '揮發性固形物 ',
    eNm: 'volatile solid, VS',
    explain:
      '시료를 550℃의 전기로에서 15시료를 550℃의 전기로에서 15~20분간 작열하여 생긴 감량',
    hNm: '휘발성 고형물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '揮發性物質',
    eNm: 'volatile substance',
    explain: '일반적인 상온에서 기화하기 쉬운 물질',
    hNm: '휘발성 물질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '揮發性浮遊固形物 ',
    eNm: 'volatile suspended solids, VSS',
    explain:
      '유리섬유 여과지를 통과하지 않고 잔류하는 총부유고형물(TSS) 중 550±50℃를 기준으로 분류하였을 때 기체로 휘발되어 날아간 성분으로 VSS라 함',
    hNm: '휘발성 부유고형물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '揮發性有機物質',
    eNm: 'volatile organic compound, VOC',
    explain:
      '높은 증기압을 가지고 있어 대기 중으로 쉽게 증발되는 성질을 가진 기체나 액세상의 유기화합물의 총칭',
    hNm: '휘발성 유기물질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '揮發性有機酸',
    eNm: 'volatile organic acid',
    explain: '수중에서 휘발하기 쉬운 유기산을 총칭하는 단어',
    hNm: '휘발성 유기산',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '揮發性有機炭素',
    eNm: 'volatile organic carbon',
    explain: '유기물을 구성하는 탄소분 중 휘발성이 있는 것',
    hNm: '휘발성 유기탄소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '揮發性有機化合物汚染',
    eNm: 'pollution by volatile organic carbon',
    explain:
      '정유, 도장공사, 석유화학 제조와 저장과정, 페인트 등에서 발생하는 휘발성 유기화합물에 의한 오염',
    hNm: '휘발성 유기화합물 오염',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '揮發性脂肪酸',
    eNm: 'volatile fatty acids(VFA’s)',
    explain: '낙산, 초산과 같이 휘발하는 성질을 가진 저급지방산',
    hNm: '휘발성 지방산',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '揮發性 有機化合物',
    eNm: 'Volatile Organic  Compound, VOC',
    explain: '대기중으로쉽게증발되는액체또는기체상유기화합물',
    hNm: '휘발성유기화합물',
    rgsdt: '2016-11-18',
  },
  {
    cNm: '式濾床',
    eNm: 'wheeler bottom underdrains',
    explain: '급속여과지의 하부 집수장치의 일종',
    hNm: '휠식여상',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '携帶用檢針裝置',
    eNm: 'portable meter reading device',
    hNm: '휴대용검침장치',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'humic acid',
    explain:
      '토양에 포함되는 생물 이외의 유기물 총체, 부식질 중 용제에 제거되지 않고 남아 있는 갈색이나 흑색의 산성유기물',
    hNm: '휴믹산',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'hume pipe',
    explain:
      '원심력 회전으로 조성된 콘크리트관으로 벽체 내에 종선 및 나선 등의 철선을 삽입하여 제조한 관',
    hNm: '흄관',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'flow',
    explain: '물이 움직이는 상태',
    hNm: '흐름',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'stream function',
    explain: '유체의 흐름을 일컫는 함수',
    hNm: '흐름함수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '黑泥土',
    eNm: 'muck soil',
    hNm: '흑니토',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'black alkali',
    hNm: '흑색 알칼리',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '黑體輻射',
    eNm: 'black body radiation',
    explain: '완전 흑체에서 나온 전자기 복사를 의미',
    hNm: '흑체복사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吃水',
    eNm: 'Draft',
    hNm: '흘수',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '吃水',
    eNm: 'Draft',
    hNm: '흘수',
    rgsdt: '2023-09-12',
  },
  {
    eNm: 'earth dam',
    explain:
      '흙을 사다리꼴 모양으로 쌓아올린 댐으로 홍수중 월류시 댐 붕괴 우려가 있으므로 홍수로를 꼭 설치해야 함',
    hNm: '흙댐',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'earth dam',
    explain:
      '흙을 사다리꼴 모양으로 쌓아올린 댐으로 홍수중 월류시 댐 붕괴 우려가 있으므로 홍수로를 꼭 설치해야 함',
    hNm: '흙댐',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '吸光光度分析法 ',
    eNm: 'absorptiometry',
    explain:
      '용액 속의 용질 농도에 의한 흡광도를 분석 기기로 정량적으로 측정하는 방법 ',
    hNm: '흡광 광도 분석법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸光光度法',
    eNm: 'absorption spectrophotometry',
    explain:
      '광원으로 나오는 빛을 단색화장치 또는 필터에 의하여 좁은 파장범위의 빛을 선택하여 액층을 통과시킨 다음 광전측광으로 흡광도를 측정하여 목적 성분의 농도를 정량하는 방법',
    hNm: '흡광광도법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸水渠',
    eNm: 'lateral drain',
    hNm: '흡수거',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '吸水渠',
    eNm: 'lateral drain',
    hNm: '흡수거',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '吸水曲線',
    eNm: 'wetting curve',
    hNm: '흡수곡선',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '吸水曲線',
    eNm: 'wetting curve',
    hNm: '흡수곡선',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '吸濕曲線',
    eNm: 'imbibition curve',
    hNm: '흡습곡선',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '吸濕曲線',
    eNm: 'imbibition curve',
    hNm: '흡습곡선',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '吸熱反應',
    eNm: 'endothermic reaction',
    explain:
      '생성 물질의 에너지가 반응물질의 에너지보다 큰 경우 주위로부터 열을 흡수하며 진행되는 반응',
    hNm: '흡열반응',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸入管',
    eNm: 'suction pipe',
    explain:
      '물의 이송과정에서 펌프에 유입되는 물을 빨아들이는 데에 사용되는 관',
    hNm: '흡입관',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸入比速度 ]',
    eNm: 'suction specific speed',
    explain: '펌프의 캐비테이션의 발생한계를 판정하기 위한 계수',
    hNm: '흡입비속도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸入水槽',
    eNm: 'suction cistern',
    explain: '펌프 양수를 위하여 흡입관을 설치하는 수조',
    hNm: '흡입수조',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pump submergence',
    hNm: '흡입실양정',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸入揚程',
    eNm: 'suction head',
    hNm: '흡입양정',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'suction pump',
    hNm: '흡입펌프',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸着',
    eNm: 'adsorption',
    explain:
      '액체-고체, 기체-고체, 기체-액체 등 서로 다른 두 상(phase)의 경계면에서 어떤 물질이 경계면에 부착되거나 농축되는 현상',
    hNm: '흡착',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸濕係數',
    eNm: 'hygroscopic coefficient',
    explain:
      '수증기로 포화된 대기와 평형상태에 있는 토양에 흡착되어 유지될 수 있는 수분 함량',
    hNm: '흡착계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸着空間速度',
    eNm: 'adsorption space velocity, SV',
    hNm: '흡착공간속도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸着等溫線',
    eNm: 'adsorption isotherm',
    explain:
      '흡착 등온선은 주어진 온도에서 유체상에서 흡착층의 농도와 흡착제 입자 속의 흡착질 농도간의 평형관계를 나타내는 곡선',
    hNm: '흡착등온선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸着等溫線',
    eNm: 'adsorption isotherm',
    explain:
      '흡착 등온선은 주어진 온도에서 유체상에서 흡착층의 농도와 흡착제 입자 속의 흡착질 농도간의 평형관계를 나타내는 곡선',
    hNm: '흡착등온선',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '吸着線速度',
    eNm: 'adsorption linear velocity, LV',
    hNm: '흡착선속도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸着水',
    eNm: 'hygroscopic water, absorbed water',
    explain:
      '토양콜로이드에 흡착된 수분. 다공질 매체에 흡착력 또는 모세관장력으로 고정된 수분.',
    hNm: '흡착수',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '吸着水',
    eNm: 'hygroscopic water, absorbed water',
    explain:
      '토양콜로이드에 흡착된 수분. 다공질 매체에 흡착력 또는 모세관장력으로 고정된 수분.',
    hNm: '흡착수',
    rgsdt: '2023-09-18',
  },
  {
    cNm: '吸着濾過 ',
    eNm: 'adsorption filtration',
    explain: '여과에 흡착 기능을 결합한 여과방식',
    hNm: '흡착여과',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸着容量',
    eNm: 'adsorptive capacity',
    hNm: '흡착용량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸着接觸時間',
    eNm: 'adsorption contact time, CT',
    hNm: '흡착접촉시간',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸着劑',
    eNm: 'adsorbent',
    explain:
      '흡착의 원리를 이용하여 용액의 분리조작을 할 때 사용하는 고체로써 대표적인 흡착제는 활성탄, 실리카겔, 활성알루미나 등이 해당함',
    hNm: '흡착제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸着層高',
    eNm: 'adsorption bed height',
    explain: '활성탄층의 높이와 같이 흡착탑에서 흡착제를 충진한 높이를 지칭함',
    hNm: '흡착층고',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸着塔',
    eNm: 'adsorption tower',
    explain: '흡착공정에서 흡착제를 충진하여 사용하는 수직형 탱크 또는 반응기',
    hNm: '흡착탑',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸着平衡',
    eNm: 'adsorption equilibrium',
    explain:
      '흡착공정에서 기체-고체, 액체-고체, 기체-액체상의 계면에 일어나는 두 개 상의 평형상태로 일정한 온도에서 흡착제(다공성 메디아)에 흡착된 기체나 고형물질이 그 압력이나 농도가 평형을 이루는 상태',
    hNm: '흡착평형',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '吸着布',
    hNm: '흡착포',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '吸着布',
    hNm: '흡착포',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '吸着型凝集',
    eNm: 'sweep 2',
    hNm: '흡착형 응집',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '吸着型凝集',
    eNm: 'sweep 2',
    hNm: '흡착형 응집',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '稀釋',
    eNm: 'dilution',
    explain:
      '농도가 다른 두 기체 또는 액체가 섞여 전체적으로 농도가 낮아지는 현상',
    hNm: '희석',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '稀釋度',
    eNm: 'rate of dilution',
    hNm: '희석도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '稀釋放流法',
    eNm: 'dilution discharge',
    hNm: '희석방류법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '稀釋倍數値',
    eNm: 'threshold odor number',
    explain: '약칭은 TO이며, 물의 냄새의 강약을 측정하는 데 사용함',
    hNm: '희석배수치',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '稀釋倍率',
    eNm: 'dilution factor',
    hNm: '희석배율',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '稀釋法',
    eNm: 'dilution method',
    explain:
      '농도가 높은 오염물질이나 폐수를 물로 희석하여 오염정도를 낮추거나 분석이 가능한 정도로 농도를 낮추는 방법',
    hNm: '희석법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '稀釋水',
    eNm: 'dilution water',
    explain:
      '하수나 폐수의 처리를 위한 희석, 고농도 원수의 측정을 위한 희석, 냄새측정 등에서 시료에 첨가하는 물',
    hNm: '희석수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '稀釋曝氣方式',
    eNm: 'diluting aeration process',
    hNm: '희석포기방식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '白霜',
    eNm: 'hoarfrost, white  frost',
    explain: '지면의 복사냉각에 의해 지면에 생기는 얼음 결정',
    hNm: '흰서리',
    rgsdt: '2016-11-23',
  },
];

export default data_ko_ha;
