let data_ko_ca = [
  {
    cNm: '借景',
    hNm: '차경',
    rgsdt: '2016-11-24',
  },
  {
    cNm: '借景',
    hNm: '차경',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '遮斷 ',
    eNm: 'interception',
    explain:
      '강수가 지표에 도달하지 못하고 수목의 엽면이나 구조물상부 등에 의해 저류되는 현상.',
    hNm: '차단',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '遮斷綠地 ',
    eNm: 'interception green land',
    explain:
      '재해의 발생 우려가 높은 지역으로부터 사람이 생활하는 지역에 미칠 환경상의 영향을 최소화하기 위하여 설정된 수림대',
    hNm: '차단녹지',
    rgsdt: '2016-04-15',
  },
  {
    hNm: '차수 매립지',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '遮水壁',
    eNm: 'cut off wall',
    explain: '침투 방지를 위한 불투수성 벽',
    hNm: '차수벽',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '遮水壁',
    eNm: 'cut off wall',
    explain: '침투 방지를 위한 불투수성 벽',
    hNm: '차수벽',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '遮水壁',
    eNm: 'cut off wall',
    explain: '침투 방지를 위한 불투수성 벽',
    hNm: '차수벽',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '遮水壁',
    eNm: 'cut off wall',
    explain: '침투 방지를 위한 불투수성 벽',
    hNm: '차수벽',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '遮水壁',
    eNm: 'cut off wall',
    explain: '침투 방지를 위한 불투수성 벽',
    hNm: '차수벽',
    rgsdt: '2023-10-18',
  },
  {
    cNm: '遮水板',
    eNm: 'water stop',
    explain: '새는물을 막는 판',
    hNm: '차수판',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '次亞鹽素酸',
    eNm: 'hypochlorous acid, HClO',
    explain: '높은 반응성으로 세균 및 미생물을 죽이는데 사용하는 화학약품',
    hNm: '차아염소산',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'sodium hypochlorite, NaOCl',
    explain:
      '수산화나트륨 용액 등에 염소가스를 이용해 만든 염소제로 차아염소산염 중 하나',
    hNm: '차아염소산 나트륨',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'sodium hypochlorite',
    explain: '염소냄새를 야기하는 강력한 산화제 ',
    hNm: '차아염소산소다',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '次亞鹽素酸鹽',
    eNm: 'hypochlorite',
    explain:
      'HClO에서 수소 대신 나트륨 또는 칼륨 등의 알칼리 금속이 치환된 것으로 차아염소산나트륨, 차아염소산칼륨 등이 있음',
    hNm: '차아염소산염',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'calcium hypochlorite',
    explain: 'HClO에서 수소 대신 칼슘이 치환된 것으로 Ca(OCl)2로 표현',
    hNm: '차아염소산칼슘',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '差壓밸브',
    eNm: 'differential pressure type level gauge',
    explain:
      '관로내의 수압을 동력원으로 작동하고, 소정의 압력을 제어하는 밸브의 총칭',
    hNm: '차압밸브',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '差流量累加曲線',
    eNm: 'differential discharge mass curve',
    explain: '평균유량과 월별유량의 차이를 이용하여 누가곡선을 그린 그래프',
    hNm: '차유량누가곡선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '遮集管渠',
    eNm: 'intercepting sewer',
    explain: '차집을 위해 관을 설치한 하수도 또는 수로',
    hNm: '차집관거',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '遮集渠',
    eNm: 'sewer system',
    explain:
      '오수나 빗물 등의 배수를 차집하는 구조로써 분류식과 합류식으로 구분',
    hNm: '차집구조',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '遮集率',
    eNm: 'intercepting rate',
    explain: '강우시와 비강우시의 최대 하수 유입량의 비율',
    hNm: '차집률',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '遮集排水渠',
    eNm: 'intercepting drain pipe',
    hNm: '차집배수거',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '遮集排水溝',
    eNm: 'intercepting drain hole',
    hNm: '차집배수구',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '遮集水路',
    eNm: 'intercepting channel',
    hNm: '차집수로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '遮集式',
    eNm: 'intercepting system',
    explain:
      '간선 하수거로 유하한 하수를 차집거로 차집하여 하수종말처리장에 유하하도록 하는 방식',
    hNm: '차집식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '遮集容量',
    eNm: 'intercepting sewer capacity, interceptor capacity',
    explain:
      '하수관거나 강우유출수 처리시설 등이 있을 때 시설이 받아들일 수 있는 용량',
    hNm: '차집용량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '着色懸濁物',
    eNm: 'colored suspended matter',
    hNm: '착색 현탁물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '着生',
    eNm: 'attached growth',
    hNm: '착생',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '着手井',
    eNm: 'receiving well',
    explain:
      '수자원으로부터 유입되는 원수의 수량을 조절하고 이후 수처리 과정을 원활하기 위해 설치되는 시설',
    hNm: '착수정',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '錯鹽',
    eNm: 'complex salt1',
    explain: '착이온을 함유하는 염',
    hNm: '착염',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '錯鹽法',
    eNm: 'complex salt method',
    explain:
      '칼슘, 마그네슘 이온 및 철 등과 착화합물을 형성하는 약품(중합 인산소다, EDTA(ethylene diamine tetracetic acid) 등)을 첨가하여 경수를 연수화시키는 방법',
    hNm: '착염법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '鑿井',
    eNm: 'well drilling, well sinking',
    explain: '천공기계를 사용하여 우물을 파는 것',
    hNm: '착정',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'removable submersible pump',
    explain: '수중 펌프 중 탈착이 가능하도록 설치한 펌프',
    hNm: '착탈식수중펌프',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '錯化合物',
    eNm: 'complex compound',
    explain: '착이온을 포함하는 물질',
    hNm: '착화합물',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'wetted masonry dam',
    hNm: '찰쌓기댐',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '漲潮流',
    eNm: 'flooding tide, rising tide',
    hNm: '창조류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '採水',
    eNm: 'sampling of water',
    explain: '시험분석용 물을 채취하는 것',
    hNm: '채수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '採水器',
    eNm: 'water sampler',
    explain: '정해진 깊이에서 시험용 물을 채취하는 데 쓰이는 기구',
    hNm: '채수기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '採水地點',
    eNm: 'water sampling point',
    explain:
      '물을 측정하기 위한 지점으로 면이나 수직(수심)의 지점을 고려해야 함',
    hNm: '채수지점',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '處女水 ',
    eNm: 'juvenile water ',
    explain:
      '마그마 내부, 또는 마그마로부터 기원한 휘발성 유체에 포함되어 있던 물이 지표로 나온 것',
    hNm: '처녀수 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '處理目標水質',
    eNm: 'effluent quality target',
    explain: '법으로 규정된 처리수의 허용 오염물질 농도',
    hNm: '처리목표수질',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '處理水',
    eNm: 'treated water',
    hNm: '처리수',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '處理場',
    eNm: 'treatment facility',
    hNm: '처리장',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '穿孔',
    eNm: 'boring, drilling, perforation',
    hNm: '천공',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'bored well, drilled well',
    hNm: '천공우물',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'thunder',
    explain: '공기 중의 높은 전압차로 인해 발생하는 방전현상에서 나는 소리',
    hNm: '천둥',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'thunder shower',
    explain: '강한 비를 동반한 뇌우',
    hNm: '천둥소나기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '天文薄明',
    eNm: 'astronomical twilight',
    explain: '태양의 고도가 12~18도일 때 지표가 밝게 나타나는 현상',
    hNm: '천문박명',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '天水',
    eNm: 'rain water',
    explain: '수증기가 기상순환에 의해 응결되어 지상에 떨어지는 물',
    hNm: '천수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '天水',
    eNm: 'rain water',
    explain: '수증기가 기상순환에 의해 응결되어 지상에 떨어지는 물',
    hNm: '천수',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '淺水理論',
    eNm: 'shallow water theory',
    hNm: '천수 이론',
    rgsdt: '2016-11-24',
  },
  {
    cNm: '淺水理論',
    eNm: 'shallow water theory',
    hNm: '천수 이론',
    rgsdt: '2023-09-12',
  },
  {
    eNm: 'natural gas',
    explain: '자연적으로 산출되는 가스 중 탄화수소를 주성분으로 하는 가스',
    hNm: '천연가스',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '天然高分子凝集劑',
    eNm: 'natural organic polymer coagulant',
    explain:
      '생물 근원의 고분자와 녹말제품, 셀롤로오스 유도체, 알긴산염 등에서 만든 것',
    hNm: '천연고분자응집제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '天然放射能',
    eNm: 'natural radioactivity',
    explain: '자연에 존재하는 물질이 방사선을 내는 경우 그러한 성질',
    hNm: '천연방사능',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '天然有機物',
    eNm: 'natural organic matter',
    explain: '일반적으로는 자연계에 존재하는 유기물질을 일컫는 말',
    hNm: '천연유기물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '天然資源',
    eNm: 'natural resource',
    explain: '현대 문명에 이용될 수 있는 자연에 존재하는 물질이나 힘을 총칭',
    hNm: '천연자원',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '遷移',
    eNm: 'succession',
    hNm: '천이',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '遷移',
    eNm: 'succession',
    hNm: '천이',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '遷移水域',
    eNm: 'transitional water intermediate depth water',
    hNm: '천이수역',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '天井川',
    eNm: 'ceiling river',
    explain: '토사의 퇴적으로 하천바닥이 제내지 지면보다 높아진 하천',
    hNm: '천정천',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '天井川',
    eNm: 'ceiling river',
    explain: '토사의 퇴적으로 하천바닥이 제내지 지면보다 높아진 하천',
    hNm: '천정천',
    rgsdt: '2024-03-15',
  },
  {
    cNm: '天井川',
    eNm: 'ceiling river',
    explain: '토사의 퇴적으로 하천바닥이 제내지 지면보다 높아진 하천',
    hNm: '천정천',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '淺井戶',
    eNm: 'shallow well',
    explain:
      '지표와 가까운 대수층에서 물을 끌어올리기 위해 설치된 깊이가 얕은 우물',
    hNm: '천정호',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '天體',
    eNm: 'heavenly body',
    explain: '우주를 구성하는 물질의 총칭',
    hNm: '천체',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '淺層水',
    eNm: 'Sub-surface Water',
    hNm: '천층수',
    rgsdt: '2016-11-24',
  },
  {
    cNm: '淺層水',
    eNm: 'Sub-surface Water',
    hNm: '천층수',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '淺海',
    eNm: 'shallow sea',
    hNm: '천해',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '淺海波',
    eNm: 'shallow water wave',
    hNm: '천해파',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '鐵 除去法',
    eNm: 'iron removal method',
    explain: '수중에 있는 용해성 철을 제거하는 방법',
    hNm: '철 제거법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '鐵管',
    eNm: 'iron pipe',
    hNm: '철관',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'reinforced concrete pipe(RCP)',
    explain:
      '콘크리트를 철근으로 보강하고, 외력에 대응하여 양자가 하나가 되어 작용하는 것을 철근콘크리트라 하고 이것을 응용한 관',
    hNm: '철근콘크리트관',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '鐵細菌',
    eNm: 'iron bacteria',
    explain:
      '2가의 철을 3가의 철로 산화해서 균체의 내외에 침착(沈着), 축적해 증식하는 세균의 총칭',
    hNm: '철박테리아',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '鐵鹽',
    eNm: 'iron salt',
    explain: '철의 염류를 말하며 제1철염과 제2철염이 존재',
    hNm: '철염',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '尖頭發生時間',
    eNm: 'time to peak',
    hNm: '첨두발생시간',
    rgsdt: '2016-11-24',
  },
  {
    cNm: '尖頭發生時間',
    eNm: 'time to peak',
    hNm: '첨두발생시간',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '尖頭負荷',
    eNm: 'peak load',
    explain: '1일간 나타난 부하량 중 최댓값을 나타내는 부하량',
    hNm: '첨두부하',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '尖頭負荷發電所',
    eNm: 'peak load plant',
    hNm: '첨두부하발전소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '尖頭水位計',
    eNm: 'crest stage gauge',
    hNm: '첨두수위계',
    rgsdt: '2016-11-24',
  },
  {
    cNm: '尖頭水位計',
    eNm: 'crest stage gauge',
    hNm: '첨두수위계',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '尖頭流量',
    eNm: 'peak flow',
    explain: '수문곡선 상에서 가장 유량이 높은 지점을 의미',
    hNm: '첨두유량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '尖頭流出量',
    eNm: 'peak rate of runoff',
    explain:
      '1일 또는 일정 기간에 대해 시간에 따른 유출량 곡선을 작성했을 때 유출량이 가장 높은 지점',
    hNm: '첨두유출량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '尖頭因子',
    eNm: 'peaking factor',
    explain:
      '첨두유량과 평균유량의 비(첨두인자)를 하수거 계통의 각 시설이나 각종유량에 대해 예측할 수 있음',
    hNm: '첨두인자',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '尖頭洪水',
    eNm: 'peak flood',
    explain: '최대 홍수 혹은 설계홍수량을 뜻함',
    hNm: '첨두홍수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '尖頭洪水量',
    eNm: 'flood peak',
    explain: '홍수 기간 동안에 발생하는 유량의 최댓값',
    hNm: '첨두홍수량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '捷水路',
    eNm: 'shortcut',
    hNm: '첩수로',
    rgsdt: '2016-11-24',
  },
  {
    cNm: '捷水路',
    eNm: 'shortcut',
    hNm: '첩수로',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '淸耕栽培',
    eNm: 'clean-tilled crops',
    explain: '토양을 이용하지 않는 재배',
    hNm: '청경재배',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '靑酸 ',
    eNm: 'prussic acid',
    hNm: '청산',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '靑色症',
    eNm: 'methemoglobinemia',
    explain:
      '오염된 물속에 포함된 질산염(NO3)이 혈액 속의 헤모글로빈과 결합해 산소 공급을 어렵게 해서 나타나는 질병',
    hNm: '청색증',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '淸水性',
    eNm: 'katharobic, katharobity',
    hNm: '청수성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '淸淨渡等級',
    eNm: 'cleanliness class',
    explain: '입자에 다른 등급표시와 균수와의 관계의 표준치 규격',
    hNm: '청정도등급',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '淸淨生産技術',
    eNm: 'clean technology',
    explain:
      '생산 현장에서 공정을 개선하여 제조과정에서 오염물질 발생 자체를 줄인다든가 발생된 오염물질을 처리한 후 다시 사용하는 등의 기술',
    hNm: '청정생산기술',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '靑潮',
    eNm: 'blue tide',
    hNm: '청조',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '靑潮',
    eNm: 'blue tide',
    hNm: '청조',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '靑藻現狀',
    hNm: '청조현상',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '靑藻現狀',
    hNm: '청조현상',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '淸澄濾過',
    eNm: 'clarifying filtration',
    explain:
      '수중의 현탁물질의 농도가 낮을 때에는 여과층의 내부에서 제거하는 여과',
    hNm: '청징여과',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '淸澄劑',
    eNm: 'clarificant, clarifying agent',
    explain:
      '오염된 물속의 부유고형물이나 콜로이드 입자를 응집제거하여 물을 깨끗이 만들기 위해 첨가하는 화학약품',
    hNm: '청징제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '淸澄化 ',
    eNm: 'clarification',
    explain: '청징기(靑澄器) 내에서 행해지는 정화 작용을 의미',
    hNm: '청징화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '篩分離',
    eNm: 'Sieve-analysis',
    hNm: '체가름',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '體感條件',
    eNm: 'windchill factor',
    explain:
      '체감온도라고도 하며 사람이 덥거나 춥다고 느끼는 정도를 나타내는 온도',
    hNm: '체감조건',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '滯留時間',
    eNm: 'residence time, retention period,',
    hNm: '체류시간',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '體積濃度',
    eNm: 'volume concentration, volume fraction',
    explain: '단위체적 중에 포함되는 오염물질의 체적',
    hNm: '체적농도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '體積力',
    eNm: 'body force, volume force',
    hNm: '체적력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '體積密度',
    eNm: 'bulk density',
    hNm: '체적밀도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '體積壓縮性',
    eNm: 'volume compressibility',
    explain: '물체가 외력에 의하여 체적·밀도를 변화시키는 성질',
    hNm: '체적압축성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '體積粘性係數',
    eNm: 'bulk viscosity',
    hNm: '체적점성계수',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Chezy formula',
    explain: '개수로의 등류흐름에 적용가능하도록 Chezy가 개발한 평균유속공식',
    hNm: '체지공식',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Chezy formula',
    explain: '개수로의 등류흐름에 적용가능하도록 Chezy가 개발한 평균유속공식',
    hNm: '체지공식',
    rgsdt: '2023-10-20',
  },
  {
    eNm: 'check valve',
    explain: '배관에 설치되어 유체가 오직 한쪽 방향으로만 흐르도록 하는데 사용',
    hNm: '체크밸브',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '超過 降水量',
    eNm: 'excessive precipitation, precipitation excess',
    hNm: '초과 강수량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '超過 確率',
    eNm: 'exceedance probability',
    explain: '확률변수가 특정한 값 이상을 갖는 사상이 발생할 확률',
    hNm: '초과 확률',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '超過間隙水',
    eNm: 'excess pore water',
    hNm: '초과간극수',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '超過貯水量 ',
    eNm: 'surcharge storage capacity',
    hNm: '초과저수량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '超屈折',
    eNm: 'Superrefraction',
    hNm: '초굴절',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '初期降水',
    eNm: 'initial precipitation',
    hNm: '초기강수',
    rgsdt: '2016-04-15',
  },
  {
    hNm: '초기강우',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '初期降雨量',
    eNm: 'initial rainfall',
    hNm: '초기강우량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '初期損失',
    eNm: 'initial loss',
    hNm: '초기손실',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '初期抑留',
    eNm: 'initial detention',
    hNm: '초기억류',
    rgsdt: '2016-11-24',
  },
  {
    cNm: '初期抑留',
    eNm: 'initial detention',
    hNm: '초기억류',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '初期雨量',
    eNm: 'initial rain',
    hNm: '초기우량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '初期雨水',
    eNm: 'first flush',
    hNm: '초기우수',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '初期雨水',
    eNm: 'first flush',
    hNm: '초기우수',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '初期雨水',
    eNm: 'first flush',
    hNm: '초기우수',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '初期萎凋點',
    eNm: 'initial wilting point',
    hNm: '초기위조점',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '初期萎凋點',
    eNm: 'initial wilting point',
    hNm: '초기위조점',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '初期洪水',
    eNm: 'initial flood',
    hNm: '초기홍수',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '初期洪水',
    eNm: 'initial flood',
    hNm: '초기홍수',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '初生水',
    eNm: 'juvenile water',
    explain:
      '마그마 내부 또는 마그마로부터 기원한 휘발성 유체에 포함되어 있던 물이 지표로 나온 것',
    hNm: '초생수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '草生水路',
    eNm: 'grassed(sod) waterway',
    hNm: '초생수로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '超純水',
    eNm: 'ultrapure water',
    explain:
      '순수한 물의 성분만을 함유하는 수질을 나타내는 순수 물을 의미하며 극도로 정제한 물임',
    hNm: '초순수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '草食動物 ',
    eNm: 'Herbivores',
    explain: '식물을 먹고 사는 동물',
    hNm: '초식동물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '超深層曝氣法',
    eNm: 'deep shaft aeration process',
    explain:
      '반응조가 수심 50～150m 정도의 초심층 조와 고액분리설비로 구성된 활성슬러지법의 한 종류',
    hNm: '초심층폭기법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '草原氣候',
    eNm: 'grassland climate',
    explain:
      '건조한계와 사막한계 사이의 기후를 가리키는 것이며, 사막기후 지역을 둘러싸면서 분포',
    hNm: '초원기후',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '超音波',
    eNm: 'ultrasonic waves',
    explain: '인간이 들을 수 없는 음파',
    hNm: '초음파',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '超音波 流量計',
    eNm: 'ultrasonic flowmeter',
    explain:
      '유동유체 속에서 초음파의 전달특성을 이용하여 유량을 측정하는 장비',
    hNm: '초음파 유량계',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '超音波 流量計',
    eNm: 'ultrasonic flowmeter',
    explain:
      '유동유체 속에서 초음파의 전달특성을 이용하여 유량을 측정하는 장비',
    hNm: '초음파 유량계',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '觸媒',
    eNm: 'catalyst',
    hNm: '촉매',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總硬度',
    eNm: 'total hardness',
    explain: '물의 세기를 나타낸 말',
    hNm: '총경도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總硬度',
    eNm: 'total hardness',
    explain: '물의 세기를 나타낸 말',
    hNm: '총경도',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '總固形物',
    eNm: 'total solids, TS',
    explain:
      '수중에 있는 여과(용해)성 고형물과 현탁성 고형물(부유물질)을 합한 총량',
    hNm: '총고형물',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'total solids flux',
    explain: '단위면적당 농축되는 슬러지량 (유동량)',
    hNm: '총고형물플록스',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總括 物質移全係數',
    eNm: 'overall volumetric mass transfer coefficient',
    explain:
      '기체의 액 중에의 용해에 대해서는 분압의 법칙 및 Henry의 법칙이 성립하나, 이것은 평형상태에서 성립하는 것이며, 거기에 이를 때까지의 과도적 단계에서는 액 중에의 기체의 용해율-수송률은 시간적으로 변화함',
    hNm: '총괄 물질이전계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總量規制',
    eNm: 'Regulation of total emission',
    explain: '오염물질 배출량에 대해 배출량과 농도를 곱한 총량을 규제하는 방식',
    hNm: '총량규제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總量測定罔',
    hNm: '총량측정망',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '總量測定罔',
    hNm: '총량측정망',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '總量測定罔',
    hNm: '총량측정망',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '總浮游物質',
    eNm: 'Total Suspended Solids, TSS',
    explain:
      '여과지로 걸러지지 아니하는 부유물질을 건조로에서 105℃에서 2시간 건조시킨 후에 무게를 측정하여 ppm이나 mg/L로 나타냄',
    hNm: '총부유물질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總酸素要求量',
    eNm: 'Total oxygen demand',
    explain:
      '총산소소비량이라고도 하며, 시료 중의 유기물 및 질소, 황 등 산소를 소비하는 물질에 의해 소비된 산소의 총량',
    hNm: '총산소요구량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總細菌',
    eNm: 'total bacteria',
    explain: '인공배양을 하지 않은 상태에서 시료에 존재하는 세균의 전체 개체수',
    hNm: '총세균',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '總水頭',
    eNm: 'total head',
    explain: '베르누이 정리에서 속도수두와 압력수두와 위치수두의 총합',
    hNm: '총수두',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'total alkalinitㅊy',
    explain:
      '수중의 알칼리 성분을 중화하기 위해 필요한 산성분의 소비량을 구하고, 필요한 산성분을 탄산칼슘(CaCO3)으로 환산하여 ppm으로 나타낸 것',
    hNm: '총알칼리도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總溶存固形物',
    eNm: 'total dissolved soli, TDS',
    explain:
      '물속에 용해된 미네랄, 염분, 금속, 양이온, 음이온을 말하며, 이것은 순수한 물 이외 물속에 포함되어 있는 용해성 물질을 말하는데, 일반적으로 TDS 농도는 물속의 양이온과 음이온의 총 합계를 말함',
    hNm: '총용존고형물 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總有機炭素',
    eNm: 'total organic carbon, TOC',
    explain:
      '물속에 함유되어 있는 유기물 물질의 농도로서 물속에 포함된 전체 탄소량을 의미함. 수질의 오염정도를 나타내는 지표',
    hNm: '총유기탄소',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'total organic halogen compound',
    explain: '할로겐 원소를 함유한 화학물질 전체',
    hNm: '총유기할로겐화합물',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'total sediment discharge',
    explain: '하천에서 유수에 의해 이송되는 단위시간당 부유사와 소류사의 총량',
    hNm: '총유사량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總燐',
    eNm: 'total phosphorus, T-P',
    explain: '물속에 포함된 인화합물의 총 농도',
    hNm: '총인',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總殘留物',
    eNm: 'Total Fixed Solids, TFS',
    explain:
      '증발 후 용기 속에 남은 물질을 일정한 온도의 건조로(기)에서 건조시킨 것을 가리키는 말',
    hNm: '총잔류물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總貯水容量',
    eNm: 'total storage capacity',
    explain: '물을 저장할 수 있는 활용 가능 공간과 사수량의 합',
    hNm: '총저수용량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總窒素',
    eNm: 'total nitrogen, T-N',
    explain: '수중에 포함되어있는 질소 화합물의 총량',
    hNm: '총질소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總炭酸',
    eNm: 'total carbonic acid',
    explain:
      '물속에 존재하는 탄산, 탄산수소인온, 탄산염 이온의 함량을 이산화탄소의 양으로 변환하여 표시한 것',
    hNm: '총탄산',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '總炭素',
    eNm: 'total carbon, TC',
    hNm: '총탄소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總土壤遺失量',
    eNm: 'total soil loss',
    explain:
      '강우 → 우적의 타격 → 토괴의 분리 → 잉여수의 유출 → 세탈 → 침식 → 표토의 손실과 같은 일련의 과정을 통해 손실되는 토양유실의 총량',
    hNm: '총토양유실량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '總土壤遺失量',
    eNm: 'total soil loss',
    explain:
      '강우 → 우적의 타격 → 토괴의 분리 → 잉여수의 유출 → 세탈 → 침식 → 표토의 손실과 같은 일련의 과정을 통해 손실되는 토양유실의 총량',
    hNm: '총토양유실량',
    rgsdt: '2023-10-20',
  },
  {
    eNm: 'total trihalomethane(THM)',
    explain:
      '동식물의 사체나 배설물 등으로 상수원수에 함유되어 있는 유기물(부식질)이 살균소독으로 사용되는 염소와 반응하여 생성되는 물질로 클로로포름, 브로모디클로로메탄, 디트로모클로로메탄, 브로모포름 4가지 화합물을 지칭',
    hNm: '총트리할로메탄',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最高水位',
    eNm: 'highest water level',
    hNm: '최고수위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最高潮位',
    eNm: 'high water level, HWL',
    explain: '조석의 승강 운동 중 고조시의 조위',
    hNm: '최고조위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最大 汚染許容基準',
    eNm: 'maximum acceptable contaminant level, MACL',
    explain:
      '개별적인 오염물질배출시설에 해당되는 기준으로서 오염물질 배출의 최대허용치 혹은 최대허용농도를 정한 기준값',
    hNm: '최대 오염허용기준',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最大可能洪水量',
    eNm: 'probable maximum flood',
    explain:
      '최악의 기상조건에서 발생하는 강수량, 최대가능강수량에 의해 유역에서 나타날 수 있는 최대홍수량',
    hNm: '최대가능 홍수량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最大可能降水量',
    eNm: 'probable maximum precipitatio',
    explain: '한 유역에서기상조건에 따라 최대로 발생가능한 강수량',
    hNm: '최대가능강수량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最大渴水量',
    eNm: 'maximum drought',
    hNm: '최대갈수량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最大基質除去速度',
    eNm: 'maximum substrate removal rate',
    explain: '미생물에 의해 기질이 단위시간당 제거되는 최대속도',
    hNm: '최대기질제거속도',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '最大使用水量',
    eNm: 'maximum discharge',
    hNm: '최대사용수량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最大算定洪水量',
    eNm: 'maximum computed flood',
    explain: '.',
    hNm: '최대산정홍수량',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '最大算定洪水量',
    eNm: 'maximum computed flood',
    explain: '.',
    hNm: '최대산정홍수량',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '最大計劃雨水流出量',
    eNm: 'maximum storm water runoff',
    explain:
      '강우량 중 하수관으로 유입되는 우수량을 산정하여 관거 단면을 결정하게 되는데, 이때의 최대우수유출량을 말함',
    hNm: '최대우수유출량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最大有效降雨量',
    eNm: 'maximum effective rainfall',
    hNm: '최대유효강우량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最大粒經',
    eNm: 'maximum particle diameter',
    hNm: '최대입경',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最大靜水頭',
    eNm: 'maximum hydrostatic head',
    explain: '수압관에 작용하는 최대정수압에 상당하는 압력수두',
    hNm: '최대정수두',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最大蒸氣壓',
    eNm: 'maximum vapor pressure',
    explain: '수증기가 포화상태일 때의 수중기의 부분압력',
    hNm: '최대증기압',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最大窒酸化速度',
    eNm: 'maximum nitrification rate',
    explain:
      '질산화 반응에서 DO 및 암모니아성 질소농도가 충분히 높고, 반응속도에 영향이 생기지 않는 최대의 질산화 속도',
    hNm: '최대질산화속도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最大波',
    eNm: 'maximum wave',
    explain: '관측된 파고의 최대값',
    hNm: '최대파',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最大許容水中濃度',
    eNm: 'maximum permissible water concentration',
    explain:
      '사람이 마시는 물에 포함된 방사성물질의 농도 중 과학기술처장관이 정하는 최대한도의 허용농도',
    hNm: '최대허용수중농도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最大洪水量',
    eNm: 'maximum flood',
    hNm: '최대홍수량',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '最大洪水量',
    eNm: 'maximum flood',
    hNm: '최대홍수량',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '最小 管徑',
    eNm: 'minimum pipe diameter',
    explain:
      '배수설비의 장착 및 유지관리상 경험적으로 정해진 하수관거의 최소 내경',
    hNm: '최소관경',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最小 動水勾配線)',
    eNm: 'minimum hydraulic grade curve',
    explain:
      '유체가 흐르기 위해서는 동수구배선의 경사가 하향이 되어야 하는데, 이때 유체가 흐르기 위한 최소의 동수구배선의 경사',
    hNm: '최소동수구배선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最小自乘法',
    eNm: 'least squares method, method of least squares',
    hNm: '최소자승법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '崔尤度法',
    eNm: 'method of maximum likelihood',
    hNm: '최우도법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最低水位 ',
    eNm: 'lowest low-water level, L.L.W.L',
    hNm: '최저수위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最低貯水位',
    eNm: 'minimum pool level',
    explain: '댐이나 저수지의 수위가 가장 낮은 상태',
    hNm: '최저저수위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最低地下水位',
    eNm: 'minimum groundwater level',
    explain: '어떤 기간을 통해 관측된 저수위 중 가장 낮은 수위',
    hNm: '최저지하수위',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'optimum pH ',
    explain: '어떤 화학적 반응이 최대의 효과가 나타날 수 있는 pH',
    hNm: '최적 pH',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'optimum pH ',
    explain: '어떤 화학적 반응이 최대의 효과가 나타날 수 있는 pH',
    hNm: '최적 pH',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '最適水理斷面',
    eNm: 'best hydraulic section',
    explain:
      '주어진 통수 단면적에 대하여 통수되는 등류유량을 최대화할 수 있는 개수로의 단면형',
    hNm: '최적수리단면',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最適凝集点',
    eNm: 'optimum point of coaulation',
    explain:
      '물을 응집침전법으로 처리할 때, 최단시간에 최대량의 플럭(floc)이 얻어지는 최적 pH',
    hNm: '최적응집점',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最適地下水揚水',
    eNm: 'optimal groundwater pumping',
    hNm: '최적지하수양수',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '最終酸素要求量',
    eNm: 'ultimate oxidation demand, UOD',
    explain: '수중 유기물을 모두 분해하여 최종적으로 일정 수준에 이르는 산소량',
    hNm: '최종 산소요구량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最終酸素要求量',
    eNm: 'ultimate oxidation demand, UOD',
    explain: '수중 유기물을 모두 분해하여 최종적으로 일정 수준에 이르는 산소량',
    hNm: '최종 산소요구량',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '最終生化學的酸素要求量',
    eNm: 'ultimate biochemical oxygen demand',
    explain:
      '물속의 유기물과 질소화합물들이 산화되어 NO2 및 NO3로 변환되는데 소비된 최종 산소량',
    hNm: '최종 생물화학적 산소요구량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最終處分 ',
    eNm: 'ultimate disposal',
    hNm: '최종처분',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '終末沈降速度',
    eNm: 'terminal setting velocity',
    explain: '유체에서 입자가 가라앉는 속도',
    hNm: '최종침강속도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最終沈殿池 ',
    eNm: 'final settling tank, secondary',
    explain:
      '하수처리장에서 각종 처리를 행한 후 최종적으로 남아있는 고형분을 침전시켜서 처리수를 얻기 위해 사용하는 침전지',
    hNm: '최종침전지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '最初沈殿池',
    eNm: 'primary settling tank, preliminary clarifier',
    explain:
      '하수처리장에서 하수가 최초로 통과하는 침전지로 예비처리의 기능이 있음',
    hNm: '최초침전지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '追加鹽素處理',
    eNm: 'rechlorination; replenishment chlorination (at res',
    explain:
      '정수장에서 철, 망간, 암모니아 제거, 살균 등을 목적으로 하는 초기 공정에서 염소의 첨가 작업을 전염소처리라 하며, 후처리염소처리는 급수 직전에 수도꼭지의 잔류 염소를 보존 유지할 목적으로 첨가되는 것을 목적으로 한다.',
    hNm: '추가염소처리',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '秋分',
    eNm: 'autumnal equinox',
    explain: '24절기 중 하나로 밤이 점점 길어지다 낮과 밤의 길이가 같아지는 날',
    hNm: '추분',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '追跡期間',
    eNm: 'routing period',
    hNm: '추적기간',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '追跡物質',
    eNm: 'tracer material',
    explain: '어떤 물질의 이동경로를 파악하고 싶을 때 사용하는 물질',
    hNm: '추적물질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '追跡子',
    eNm: 'tracer',
    explain:
      '지하수 내에 어떠한 물질 또는 대수층의 특성 파악을 위해 첨가하는 목표 물질',
    hNm: '추적자',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '追跡子試驗 ',
    eNm: 'tracer test ',
    explain:
      '대수층 내에 인위적으로 추적자를 주입하고 시간 및 위치에 따른 추적자의 농도 변화를 측정하여 지하수의 흐름 경로, 속도, 공극률, 분산계수와 용질의 속도 및 분배계수 등을 구하는 현장시험',
    hNm: '추적자시험 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '追跡子試驗 ',
    eNm: 'tracer test ',
    explain:
      '대수층 내에 인위적으로 추적자를 주입하고 시간 및 위치에 따른 추적자의 농도 변화를 측정하여 지하수의 흐름 경로, 속도, 공극률, 분산계수와 용질의 속도 및 분배계수 등을 구하는 현장시험',
    hNm: '추적자시험 ',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '追跡子試驗 ',
    eNm: 'tracer test ',
    explain:
      '대수층 내에 인위적으로 추적자를 주입하고 시간 및 위치에 따른 추적자의 농도 변화를 측정하여 지하수의 흐름 경로, 속도, 공극률, 분산계수와 용질의 속도 및 분배계수 등을 구하는 현장시험',
    hNm: '추적자시험 ',
    rgsdt: '2023-10-10',
  },
  {
    eNm: 'axial flow turbine',
    hNm: '축류터빈',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'axial flow pump',
    explain:
      '펌프날개의 회전축과 동일한 방향으로 유체를 가속하거나 가압하기 위한 펌프',
    hNm: '축류펌프',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'axial flow pump',
    explain:
      '펌프날개의 회전축과 동일한 방향으로 유체를 가속하거나 가압하기 위한 펌프',
    hNm: '축류펌프',
    rgsdt: '2023-10-20',
  },
  {
    eNm: 'axial flow pump',
    explain:
      '펌프날개의 회전축과 동일한 방향으로 유체를 가속하거나 가압하기 위한 펌프',
    hNm: '축류펌프',
    rgsdt: '2023-10-20',
  },
  {
    eNm: 'axial flow pump',
    explain:
      '펌프날개의 회전축과 동일한 방향으로 유체를 가속하거나 가압하기 위한 펌프',
    hNm: '축류펌프',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '畜産界汚染源',
    eNm: 'livestock pollutant source',
    hNm: '축산계오염원',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '畜産廢水',
    eNm: 'livestock waste water',
    explain: '가축사육으로 인해 발생하는 더러운 물',
    hNm: '축산폐수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '築堤',
    eNm: 'banking embankment',
    hNm: '축제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '縮尺係數',
    eNm: 'scaling factor',
    hNm: '축척계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '春分',
    eNm: 'vernal equinox',
    explain: '24절기 중 하나로 밤이 점점 짧아지다 낮과 밤의 길이가 같아지는 날',
    hNm: '춘분',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'outlet damper, discharge damper',
    hNm: '출구댐퍼',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '出口損失',
    eNm: 'outlet loss',
    hNm: '출구손실',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '衝擊係數',
    eNm: 'impact coefficient',
    explain: '충격 하중을 나타내는 계수',
    hNm: '충격계수',
    rgsdt: '2016-04-15',
  },
  {
    hNm: '충격부하',
    rgsdt: '2016-11-22',
  },
  {
    hNm: '충격부하',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '衝擊水壓',
    eNm: 'impact pressure',
    hNm: '충격수압',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '衝擊水壓',
    eNm: 'impact pressure',
    hNm: '충격수압',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '衝擊波',
    eNm: 'shock wave',
    explain: '음속보다 빨리 진행하는 파동',
    hNm: '충격파',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '衝擊波',
    eNm: 'shock wave',
    explain: '음속보다 빨리 진행하는 파동',
    hNm: '충격파',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '衝動水車',
    eNm: 'impulse turbine',
    explain:
      '물의 위치에너지를 노즐에 의해 전부 속도에너지로 바꾸어 날개에 대한 충동력에 의해 임펠러를 회전시키는 수차',
    hNm: '충동수차',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沖積帶水層',
    eNm: 'alluvial aquifer',
    explain: '지표면 근처의 충적층에 물이 포화되어 대수층 역할을 하는것',
    hNm: '충적 대수층',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '沖積大平野',
    eNm: 'panplain',
    hNm: '충적대평야',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沖積作用',
    eNm: 'aggradation',
    explain: '하천에서 유속이 감소되는 구간에서 퇴적물들이 쌓이는 과정',
    hNm: '충적작용',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沖積地',
    eNm: 'alluvion',
    hNm: '충적지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沖積層',
    eNm: 'alluvium',
    explain: '유수의 작용으로 형성된 쇄설성 퇴적층',
    hNm: '충적층',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沖積土',
    eNm: 'alluvium',
    explain: '유수에 의해 운반되어 퇴적된 흙',
    hNm: '충적토',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沖積土',
    eNm: 'alluvium',
    explain: '유수에 의해 운반되어 퇴적된 흙',
    hNm: '충적토',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '沖積河床',
    eNm: 'alluvial beds, alluvial channel bed',
    explain: '충적하천의 하천바닥',
    hNm: '충적하상',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沖積河川',
    eNm: 'alluvial river',
    explain: '하천의 유사에 의해 하도와 제방이 형성되는 하천',
    hNm: '충적하천',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '充塡材',
    eNm: 'filler material',
    explain: '오염물질을 걸러내는 여과방식에서 여과지를 채우는 물질',
    hNm: '충전(진)재',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '臭氣',
    eNm: 'odor, offensive odor, malodor',
    explain: '인간의 후각으로 느낄 수 있는 것',
    hNm: '취기(냄새)',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '臭氣物質',
    eNm: 'odorant',
    explain: '냄새를 유말하는 물질',
    hNm: '취기물질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '臭氣防止法',
    eNm: 'odor control process',
    explain: '악취를 발생기키는 가스를 제거하는 방법',
    hNm: '취기방지법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '臭氣試驗',
    eNm: 'odor test',
    explain: '후각에 의하여 행해지는 판정의 시험 또는 정성분석',
    hNm: '취기시험',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '臭起源',
    eNm: 'odor source',
    explain: '냄새를 발생하는 원인물질이나 지점',
    hNm: '취기원',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '臭氣限界',
    eNm: 'odor threshold',
    explain:
      '취기물질이 무취의 공기와 구별할 수 있는 최소농도(detection threshold) 또는 취기를 인식할 수 있는 최소농도(recognition threshold)',
    hNm: '취기한계',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Zurich number',
    hNm: '취리히수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '臭味',
    eNm: 'odor and taste',
    explain: '냄새와 맛을 의미',
    hNm: '취미',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水',
    eNm: 'water-intake',
    explain:
      '상수도와 공업용수 등 각종 용수로 이용하기 위해서 수원에서 필요한 수량을 받아들이는 것을 의미',
    hNm: '취수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水',
    eNm: 'water-intake',
    explain:
      '상수도와 공업용수 등 각종 용수로 이용하기 위해서 수원에서 필요한 수량을 받아들이는 것을 의미',
    hNm: '취수',
    rgsdt: '2024-06-03',
  },
  {
    cNm: '取水孔',
    eNm: 'intake works, head works',
    explain: '취수하기 위한 수로 공작물',
    hNm: '취수공',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水管',
    eNm: 'intake pipe',
    explain:
      '하천, 호수 또는 저수지로부터 물을 취수하기 위하여 수중에 설치하는 관',
    hNm: '취수관 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水管渠',
    eNm: 'intake conduit',
    explain:
      '복단면 하천의 저수호안에 취수구를 설치하고, 직접 관내에 표류수를 취수하여 자연유하로 제내지에 도수하는 시설',
    hNm: '취수관거 ',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'intake conduit strainer',
    explain:
      '우물의 체수층 부분에 두는 채수기구로서  토사의 유입을 방지하고 지하수를 우물 내에 취수하는 부분',
    hNm: '취수관거용 스트레이너',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水口',
    eNm: 'intake hole',
    explain: '저수지, 하천 등에서 수로에 물을 취수하기 위하여 설치한 시설',
    hNm: '취수구',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水構造物',
    eNm: 'intake structure',
    hNm: '취수구조물',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'intake dam, diversion dam',
    hNm: '취수댐',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'intake bank',
    hNm: '취수둑',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水量',
    eNm: 'quantity of water intake',
    hNm: '취수량',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '取水路',
    eNm: 'intake channel, inlet channel',
    hNm: '취수로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水門',
    eNm: 'intake gate',
    explain:
      '취수구에 설치하는 수문으로 취수구를 막거나 취수량을 조절하기 위하여 사용하는 수문',
    hNm: '취수문',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水門',
    eNm: 'intake gate',
    explain:
      '취수구에 설치하는 수문으로 취수구를 막거나 취수량을 조절하기 위하여 사용하는 수문',
    hNm: '취수문',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '取水洑',
    eNm: 'intake dam',
    explain: '끌어 들인 물을 막아 놓기 위하여 만든 둑',
    hNm: '취수보',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水設備',
    eNm: 'intake works',
    hNm: '취수설비',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水水門',
    eNm: 'intake sluice',
    hNm: '취수수문',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水深',
    eNm: 'intake depth',
    explain: '취수하는데 요구되는 깊이로 투명깊이 (secchi depth) 이하가 무난함',
    hNm: '취수수심',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水施設',
    eNm: 'intake facilities',
    hNm: '취수시설',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'intake weir',
    hNm: '취수웨어',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水率',
    eNm: 'intake rate',
    hNm: '취수율',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水井',
    eNm: 'suction well',
    explain: '물을 취수하기 위해 펌프의 흡입관을 설치한 관정',
    hNm: '취수정',
    rgsdt: '2016-04-15',
  },
  {
    explain: '수량감소 우려와 공공급수시설의 수질보호를 위해 지정되는 지역',
    hNm: '취수정 보호구역',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '取水塔',
    eNm: 'intake tower',
    explain:
      '하천, 호수 또는 저수지 등에서 물을 취수하기 위하여 설치하는 탑 모양의 구조물',
    hNm: '취수탑',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取水塔',
    eNm: 'intake tower',
    explain:
      '하천, 호수 또는 저수지 등에서 물을 취수하기 위하여 설치하는 탑 모양의 구조물',
    hNm: '취수탑',
    rgsdt: '2023-10-20',
  },
  {
    eNm: 'intake frame',
    explain:
      '수중에 콘크리트 블록을 설치하고 안과 밖에 콘크리트와 돌 등으로 방어틀이 갖춰진 취수공간',
    hNm: '취수틀',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '取入(水)堡',
    eNm: 'intake weir',
    explain: '취수량을 확보하기 위해 설치된 보',
    hNm: '취입(수)보',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '取入(水)堡',
    eNm: 'intake weir',
    explain: '취수량을 확보하기 위해 설치된 보',
    hNm: '취입(수)보',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '取入洑',
    eNm: 'diversion weir',
    hNm: '취입보',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '取入洑',
    eNm: 'diversion weir',
    hNm: '취입보',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '側渠',
    eNm: 'gutter pipe',
    explain: '빗물을 채집하여 배수하기 위한 건물 외벽의 배수구',
    hNm: '측거',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '側管',
    eNm: 'bypass pipe',
    explain:
      '하나의 관수로가 도중에서 분기되었다가 하류에서 다시 합류하는 관수로 ',
    hNm: '측관',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '側溝',
    eNm: 'side ditch, side gutter',
    explain:
      '토목공사에 있어서 빗물, 용수, 지하수 등을 배제하기 위하여 지표면에 설치하는 배수구',
    hNm: '측구',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '側溝式餘水路',
    eNm: 'side-channel spillway',
    explain: '물넘이 위어의 중심선과 측구의 중심선을 나란히 한 여수로의 형식',
    hNm: '측구식 여수로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '側溝式餘水路',
    eNm: 'side-channel spillway',
    explain: '물넘이 위어의 중심선과 측구의 중심선을 나란히 한 여수로의 형식',
    hNm: '측구식 여수로',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '側壇',
    eNm: 'side step',
    hNm: '측단',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '側壇',
    eNm: 'side step',
    hNm: '측단',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '側壇',
    eNm: 'side step',
    hNm: '측단',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '側道',
    eNm: 'service road',
    hNm: '측도',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '側道',
    eNm: 'service road',
    hNm: '측도',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '側面放流式',
    eNm: 'side-discharge weir',
    explain:
      '하수처리장에서 홍수시의 바이패스나 수량조절을 위해 첨두유량을 경감시킬때 사용',
    hNm: '측면방류식웨어',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '側方貯溜',
    eNm: 'lateral storage',
    hNm: '측방저류',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '側方貯溜',
    eNm: 'lateral storage',
    hNm: '측방저류',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '側方浸蝕',
    eNm: 'lateral erosion',
    explain: '하천에서 양안의 측면을 깎는 작용',
    hNm: '측방침식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '測設運河',
    eNm: 'side canal',
    hNm: '측설운하',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '側水路',
    eNm: 'lateral canal',
    explain: '주수로를 따라 평행하게 건설한 수로',
    hNm: '측수로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '側壓 ',
    eNm: 'lateral pressure',
    explain: '수평방향으로 생기는 압력',
    hNm: '측압',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '側壓 ',
    eNm: 'lateral pressure',
    explain: '수평방향으로 생기는 압력',
    hNm: '측압',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '層高積雲',
    eNm: 'altocumulus stratiformis',
    explain: '중고도에 형성된 층적운 형태의 구름',
    hNm: '층고적운',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'benching',
    hNm: '층따기',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'benching',
    hNm: '층따기',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '層流',
    eNm: 'laminar flow',
    explain: '유선이 서로 엉키지 않고 평행하게 형성된 유체의 흐름',
    hNm: '층류',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '層流 ',
    eNm: 'laminar flow ',
    explain:
      '유체입자가 서로 층을 이루면서 직선적으로 혹은 평행선을 따라 움직이는 것',
    hNm: '층류 ',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'laminar separation',
    hNm: '층류박리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '層流底層',
    eNm: 'laminar sub-layer',
    explain: '흐름에서 층류와 난류의 경계',
    hNm: '층류저층',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '層流底層',
    eNm: 'laminar sub-layer',
    explain: '흐름에서 층류와 난류의 경계',
    hNm: '층류저층',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '層別沈下計',
    eNm: 'Multi Layer Settlement Meter',
    hNm: '층별침하계',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '層別沈下計',
    eNm: 'Multi Layer Settlement Meter',
    hNm: '층별침하계',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '層雲',
    eNm: 'stratus',
    explain:
      '비교적 구름밑면이 일정하고 상공 2,000m 미만의 하층에서 발생하는 회색의 구름',
    hNm: '층운',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '層雲',
    eNm: 'stratus',
    explain:
      '비교적 구름밑면이 일정하고 상공 2,000m 미만의 하층에서 발생하는 회색의 구름',
    hNm: '층운',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '層積雲',
    eNm: 'stratocumulus',
    explain:
      '하층에서 발생하는 엷은 판의 둥글둥글한 덩어리 또는 로라 모양의 운편들이 모여서 된 구름',
    hNm: '층적운',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '層積雲',
    eNm: 'stratocumulus',
    explain:
      '하층에서 발생하는 엷은 판의 둥글둥글한 덩어리 또는 로라 모양의 운편들이 모여서 된 구름',
    hNm: '층적운',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '治水',
    eNm: 'flood control',
    explain: '물을 다스려 홍수를 방어하는 것',
    hNm: '치수',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'substitution reaction, replacement reaction',
    explain:
      '화합물속의 원자 또는 이온 등이, 다른 원자 또는 이온 등과 서로 바뀌는 반응',
    hNm: '치환반응',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '親水',
    eNm: 'water-friendly',
    explain:
      '수환경, 즉 물과 친화력이 있는 것으로 물과 자주 접촉하거나 물에 익숙해지는 것 등을 의미',
    hNm: '친수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '親水空間',
    eNm: 'amenity oriented space, water amenity space',
    hNm: '친수공간',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '親水性',
    eNm: 'hydrophilicity, hydrophilic properties',
    explain: '물에 대한 친화력이 강한 성질',
    hNm: '친수성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '親水性',
    eNm: 'hydrophilicity, hydrophilic properties',
    explain: '물에 대한 친화력이 강한 성질',
    hNm: '친수성',
    rgsdt: '2023-10-20',
  },
  {
    eNm: 'hydrophilic collids',
    explain:
      '물과 친화성이 있어 물 분자를 주위로 끌어와 수화층을 만드는 성향이 있는 콜로이드',
    hNm: '친수성 콜로이드 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '親水性膜',
    eNm: 'hydrophilic membrane',
    hNm: '친수성막',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '親水用水',
    eNm: 'Chin soo dragon water',
    hNm: '친수용수',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '親水用水',
    eNm: 'Chin soo dragon water',
    hNm: '친수용수',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '親水用水',
    eNm: 'Chin soo dragon water',
    hNm: '친수용수',
    rgsdt: '2023-10-10',
  },
  {
    eNm: 'hydrophilic sol',
    explain: '물을 분산매로 하는 졸 가운데 물과 친화성이 큰 것을 의미',
    hNm: '친수졸',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'hydrophilic colloid',
    hNm: '친수콜로이드',
    rgsdt: '2016-11-22',
  },
  {
    eNm: 'hydrophilic colloid',
    hNm: '친수콜로이드',
    rgsdt: '2023-10-10',
  },
  {
    eNm: 'hydrophilic colloid',
    hNm: '친수콜로이드',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '親熱性',
    eNm: 'thermophilia',
    explain: '높은 온도를 좋아하는 성질',
    hNm: '친열성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '親溫性',
    eNm: 'mesophilia',
    explain: '대략 20~40℃의 온도를 좋아하는 성질',
    hNm: '친온성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '親油性 基質',
    eNm: 'lipophilic substrates',
    hNm: '친유성 기질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈降',
    eNm: 'settling',
    explain:
      '물중에 떠있는 입자가 중력, 원심력, 정전기력 등에 의해 바닥으로 가라앉는 것을 침강이라 함',
    hNm: '침강',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈降浮遊選別',
    eNm: 'precipitation flotation',
    explain: '부상 분리법의 일종',
    hNm: '침강 부유선별',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈降曲線',
    eNm: 'settling curve',
    explain: '유체속의 부유물의 침강속도를 곡선으로 나타낸 것',
    hNm: '침강곡선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈降濃縮裝置',
    eNm: 'thickener',
    explain: '슬러지의 농도를 침강법으로 농축시키는 장치',
    hNm: '침강농축장치',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈降法',
    eNm: 'precipitation method, sedimentation method',
    explain: '유체에서 입자의 침강속도를 이용한 입도분석방법',
    hNm: '침강법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈降分離',
    eNm: 'settling separation',
    explain:
      '액체 속에 포함되어 있는 현탁 물질을 중력을 이용하여 침강시켜 액체와 분리하는 방법',
    hNm: '침강분리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈降分析',
    eNm: 'sedimentation analysis',
    explain:
      '스토크스(Stoke’s)의 침강법칙을 이용해서 입자의 입경 분포를 측정하는 방법',
    hNm: '침강분석',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈降性 固形物',
    eNm: 'settleable solid',
    explain:
      '가만히 놓아둔 상태에서 중력에 의하여 침강하는 부유물질 중의 고형물',
    hNm: '침강성 고형물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈降性物質',
    eNm: 'settleable material, settleable solid',
    explain:
      '수질 오염의 정도를 나타내는 지표의 하나로 검수를 30분간 정치시키고, 그 사이에 침강해야할 것을 침강시킨 뒤 상등액 중의 현탁질을 정량하여 침강 이전의 현탁질의 양에서 뺀 것을 말함',
    hNm: '침강성 물질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈降逆轉',
    eNm: 'Subsidence  inversion',
    explain:
      '고기압 중심에서 상층의 공기가 서서히 침강하며 단열 압축에 의해 온도가 상승하여 하층의 공기보다 온도가 높아질 때 생기는 기온 역전현상',
    hNm: '침강성역전',
    rgsdt: '2016-11-21',
  },
  {
    cNm: '沈降速度',
    eNm: 'fall velocity',
    explain:
      '입자 등의 고형물체가 유체 속에 놓이게 되면 중력의 영향으로 하강(낙하)하게 되는데, 이때 물체가 하강하는 속도',
    hNm: '침강속도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈降速度',
    eNm: 'fall velocity',
    explain:
      '입자 등의 고형물체가 유체 속에 놓이게 되면 중력의 영향으로 하강(낙하)하게 되는데, 이때 물체가 하강하는 속도',
    hNm: '침강속도',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '沈降速度 分析曲線',
    eNm: 'sedimentation rate analysis curve',
    explain: '각 입자들의 침강속도와 그에 대한 함유율을 나타낸 그래프',
    hNm: '침강속도 분석곡선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈降池',
    eNm: 'sedimentation basin',
    hNm: '침강지',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '沈降池',
    eNm: 'sedimentation basin',
    hNm: '침강지',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '沈降海岸',
    eNm: 'coast of submergence',
    explain: '해수면의 상승 혹은 해안의 침강으로 새로 형성되는 해안',
    hNm: '침강해안',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸漏',
    eNm: 'percolation',
    explain: '강우가 지표면에 떨어진 후 지하수층까지 물이 이동하는 것',
    hNm: '침루',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸漏',
    eNm: 'percolation',
    explain: '강우가 지표면에 떨어진 후 지하수층까지 물이 이동하는 것',
    hNm: '침루',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '沈砂槽',
    eNm: 'grit chamber',
    explain:
      '하수 처리장에서 오수 중의 모래와 흙 따위를 가라앉혀 제거하기 위한 조 ',
    hNm: '침사조',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈砂池',
    eNm: 'sand sedimentation pond',
    explain: '토사를 함유한 원수로부터 침전법에 의하여 토사를 제거하는 못',
    hNm: '침사지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈水',
    eNm: 'inundation',
    explain:
      '다량의 강우나 홍수 등으로 인하여 물속에 잠긴 상태, 해수면 상승이나 지반침강으로 지면이 물속에 잠기는 상태',
    hNm: '침수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈水植物',
    eNm: 'submerged plant',
    explain: '식물체 전체가 수중 속에서 생육하는 수생식물의 총칭',
    hNm: '침수식물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸水地',
    eNm: 'flooded area',
    hNm: '침수지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '侵蝕 ',
    eNm: 'erosion',
    explain: '유동체에 의하여 지표가 깎여 나가는 현상',
    hNm: '침식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '侵蝕 ',
    eNm: 'erosion',
    explain: '유동체에 의하여 지표가 깎여 나가는 현상',
    hNm: '침식',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '侵蝕 ',
    eNm: 'erosion',
    explain: '유동체에 의하여 지표가 깎여 나가는 현상',
    hNm: '침식',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '浸蝕防止策',
    eNm: 'erosion control',
    explain: '침식현상을 막기위한 방법',
    hNm: '침식방지책',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '遊離炭酸',
    eNm: 'aggressive free carbon dioxide',
    explain:
      '수중에 용존하는 유리탄산 중 콘크리트 등에 대해서 침식작용을 보이는 것',
    hNm: '침식성 유리탄산',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸蝕性土壤',
    eNm: 'erodible soil',
    hNm: '침식성토양',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸蝕源',
    eNm: 'erosion source',
    hNm: '침식원',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸蝕表面',
    eNm: 'eroding surface',
    hNm: '침식표면',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '針葉樹林',
    eNm: 'coniferous forests',
    explain: '침엽수가 우점해 있는 식물군계',
    hNm: '침엽수림',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸潤',
    eNm: 'seepage',
    hNm: '침윤',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸潤面',
    eNm: 'phreatic surface, seepage face',
    hNm: '침윤면',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸潤線',
    eNm: 'phreatic line, seepage line',
    hNm: '침윤선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸潤線',
    eNm: 'phreatic line, seepage line',
    hNm: '침윤선',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '浸潤速度',
    eNm: 'seepage velocity',
    hNm: '침윤속도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸潤速度',
    eNm: 'seepage velocity',
    hNm: '침윤속도',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '浸潤水壓',
    eNm: 'seepage pressure',
    hNm: '침윤수압',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸入',
    eNm: 'intake',
    explain: '지표면을 통해 흙 속으로 물이 침투되는 것',
    hNm: '침입',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '侵入率',
    eNm: 'infiltration rate',
    hNm: '침입률',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '侵入率',
    eNm: 'infiltration rate',
    hNm: '침입률',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '侵入水頭',
    eNm: 'infiltration head',
    hNm: '침입수두',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '侵入水頭',
    eNm: 'infiltration head',
    hNm: '침입수두',
    rgsdt: '2023-07-03',
  },
  {
    cNm: '侵入指標',
    eNm: 'infiltration index',
    hNm: '침입지표',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '侵入指標',
    eNm: 'infiltration index',
    hNm: '침입지표',
    rgsdt: '2023-07-03',
  },
  {
    eNm: 'flocculant settling',
    hNm: '침전관실험',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '沈澱濃縮',
    eNm: 'thickening',
    explain: '중력을 이용하여 슬러지를 침전시켜 농축하는 것',
    hNm: '침전농축',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈澱膜',
    eNm: 'precipitation membrane',
    explain: '두 용액의 접촉면에 생성된 침전에 의하여 만들어진 막',
    hNm: '침전막',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈澱物',
    eNm: 'sediment, precipitation',
    explain: '액체 속에 포함되어 있는 오염물질이 바닥에 가라앉은 물질',
    hNm: '침전물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈澱法',
    eNm: 'precipitation method',
    explain:
      '물속에 부유하는 부유물 중 비중이 커서 가만히 놓아두어도 중력에 의하여 침강하는 고형물',
    hNm: '침전법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈澱性固形物',
    eNm: 'settleable solids',
    explain:
      '물속에 부유하는 부유물 중 비중이 커서 가만히 놓아두어도 중력에 의하여 침강하는 고형물',
    hNm: '침전성 고형물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈澱速度',
    eNm: 'settling velocity',
    explain:
      '모래 혹은 슬러지 같은 고체를 물속에서 가라앉힐 때 고체의 단위시간당 가라앉는 속도를 말한다. 모래인 경우는 그 속도가 시간에 따라 변화되지 않으나 부유물질 및 슬러지인 경우에는 시간에 따라 침전속도가 다름',
    hNm: '침전속도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈澱速度',
    eNm: 'settling velocity',
    explain:
      '모래 혹은 슬러지 같은 고체를 물속에서 가라앉힐 때 고체의 단위시간당 가라앉는 속도를 말한다. 모래인 경우는 그 속도가 시간에 따라 변화되지 않으나 부유물질 및 슬러지인 경우에는 시간에 따라 침전속도가 다름',
    hNm: '침전속도',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '沈澱速度',
    eNm: 'settling velocity',
    explain:
      '모래 혹은 슬러지 같은 고체를 물속에서 가라앉힐 때 고체의 단위시간당 가라앉는 속도를 말한다. 모래인 경우는 그 속도가 시간에 따라 변화되지 않으나 부유물질 및 슬러지인 경우에는 시간에 따라 침전속도가 다름',
    hNm: '침전속도',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '沈澱汚泥',
    eNm: 'sedimentation sludge',
    hNm: '침전슬러지',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '沈澱汚泥',
    eNm: 'sedimentation sludge',
    hNm: '침전슬러지',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '沈澱時間',
    eNm: 'settling time',
    explain: '침전하는데 필요한 시간을 의미',
    hNm: '침전시간',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈澱容量',
    eNm: 'sludge volume',
    explain: '활성슬러지 공정에서 슬러지의 부피를 의미',
    hNm: '침전용량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈澱率',
    eNm: 'settling efficiency',
    hNm: '침전율',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '沈澱滴定',
    eNm: 'precipitation titration',
    explain: '침전의 소멸과 발생을 이용하는 적정',
    hNm: '침전적정',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈澱槽',
    eNm: 'precipitation tank',
    explain:
      '수중의 현탁 물질을 밀도차를 이용하여 침강시켜 고체와 액체를 분리하기 위한 조',
    hNm: '침전조',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '沈澱池',
    eNm: 'sedimentation basin',
    explain:
      '물보다 무거운 입자는 물속에서 침강하게 되는데, 이러한 원리를 이용해서 원수 속의 입자(현탁물)를 침전시키는 넓은 못 ',
    hNm: '침전지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸漬？床法',
    eNm: 'submerged biofilter process',
    hNm: '침지여상법',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '浸漬？床法',
    eNm: 'submerged biofilter process',
    hNm: '침지여상법',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '沈漬率',
    eNm: 'seeping rate',
    hNm: '침지율',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '沈漬率',
    eNm: 'seeping rate',
    hNm: '침지율',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '浸出',
    eNm: 'leaching',
    explain:
      '침투수에 의하여 토양이나 기타 물질로부터 용해성 물질이 제거되는 현상',
    hNm: '침출',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'leachate collection system',
    explain:
      '매립지에서 형성된 침출수를 배출하지 않고 모아서 따로 처리하도록 하는 시스템',
    hNm: '침출수 포집시스템',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'leachate collection system',
    explain:
      '매립지에서 형성된 침출수를 배출하지 않고 모아서 따로 처리하도록 하는 시스템',
    hNm: '침출수 포집시스템',
    rgsdt: '2023-09-18',
  },
  {
    cNm: '浸出水',
    eNm: 'leachate',
    explain:
      '매립지 등 최종처분장에서 처분된 슬러지나 그 밖의 폐기물로부터 침출되어 나오는 오수 또는 침출오수',
    hNm: '침출수(액)',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸透',
    eNm: 'infiltration',
    explain: '물이 토양면을 통해 토양 속으로 스며드는 현상',
    hNm: '침투',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸透計',
    eNm: 'infiltrometer',
    explain: '토양의 침투능을 측정하는 장지',
    hNm: '침투계',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸透溪水',
    eNm: 'infiltration coefficient ',
    hNm: '침투계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸透能',
    eNm: 'infiltration capacity',
    explain: '토양수분 조건 중 침투가 최대로 발생하는 비율',
    hNm: '침투능',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸透能',
    eNm: 'infiltration capacity',
    explain: '토양수분 조건 중 침투가 최대로 발생하는 비율',
    hNm: '침투능',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '浸透能曲線',
    eNm: 'infiltration capacity curve',
    hNm: '침투능곡선',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'infiltration trench',
    explain:
      '우수침투를 목적으로 해서 침투관(유공관, 포라스콘크리트관 등)과 그 주위의 충전재로 구성되는 구조물 및 이것과 동등한 것을 말함. 빗물유출 억제의 일환으로 빗물을 모으는 측구 아래판을 쇄석과 자갈 등 투수성의 재료를 사용하여 빗물의 지하침투를 목적으로 함.',
    hNm: '침투도랑',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '浸透力',
    eNm: 'seepage force',
    explain: '토양표면에서 물이 침투되도록 하는 힘',
    hNm: '침투력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸透力',
    eNm: 'seepage force',
    explain: '토양표면에서 물이 침투되도록 하는 힘',
    hNm: '침투력',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '浸透力',
    eNm: 'seepage force',
    explain: '토양표면에서 물이 침투되도록 하는 힘',
    hNm: '침투력',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '浸透力',
    eNm: 'seepage force',
    explain: '토양표면에서 물이 침투되도록 하는 힘',
    hNm: '침투력',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '浸透速度',
    eNm: 'infiltration rate',
    explain: '단위 시간당 단위 지표 면적을 침투해 들어가는 물의 양',
    hNm: '침투속도',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '浸透速度',
    eNm: 'infiltration rate',
    explain: '단위 시간당 단위 지표 면적을 침투해 들어가는 물의 양',
    hNm: '침투속도',
    rgsdt: '2023-09-18',
  },
  {
    cNm: '浸透濾過',
    eNm: 'infiltration process',
    explain:
      '자연 모래지대와 사막을 이용하여 그 곳에 커다란 저류지를 만들어 인공적으로 지하침투를 시키고 호수 가까이에 파 놓은 우물에서 양수하는 여과처리법',
    hNm: '침투여과',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '浸透流量',
    eNm: 'seepage quantity of water',
    hNm: '침투유량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸透率',
    eNm: 'infiltration rate',
    hNm: '침투율',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸透貯留造',
    eNm: 'infiltration basin',
    hNm: '침투저류조',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '浸透貯留造',
    eNm: 'infiltration basin',
    hNm: '침투저류조',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '浸透指數',
    eNm: 'infiltration index',
    explain: '침투수량과 시간을 대수분포시켜 나올 때의 지수',
    hNm: '침투지수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸透地下水',
    eNm: 'infiltration groundwater',
    hNm: '침투지하수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '浸透側溝',
    eNm: 'infiltration trench',
    hNm: '침투측구',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '浸透側溝',
    eNm: 'infiltration trench',
    hNm: '침투측구',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '浸透花盆',
    eNm: 'infiltration planter',
    hNm: '침투화분',
    rgsdt: '2016-11-22',
  },
  {
    cNm: '浸透花盆',
    eNm: 'infiltration planter',
    hNm: '침투화분',
    rgsdt: '2023-10-10',
  },
];

export default data_ko_ca;
