let data_ko_ma = [
  {
    eNm: 'magnesium',
    explain:
      '가벼운 은백색의 금속으로 분말은 공기 중에서 가열하면서 눈부신 빛을 내고 맹렬히 연소하는 금속',
    hNm: '마그네슘',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'magnesium-potassium ratio',
    hNm: '마그네슘-칼륨비',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'manometer',
    explain: '압력과 수두사이의 정압관계를 이용한 차압계',
    hNm: '마노미터',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'manometer',
    explain: '압력과 수두사이의 정압관계를 이용한 차압계',
    hNm: '마노미터',
    rgsdt: '2023-10-17',
  },
  {
    eNm: 'crest length',
    hNm: '마루길이',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'crest length',
    hNm: '마루길이',
    rgsdt: '2023-09-14',
  },
  {
    eNm: 'crest width',
    hNm: '마루나비',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '摩滅率',
    eNm: 'abrasion ratio',
    explain: '여과 모래의 파쇄에 대한 저항성을 나타내는 지표',
    hNm: '마멸율',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'community sewage',
    explain: '자연마을 단위로 설치하는 하수도',
    hNm: '마을하수도',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'micro strainer',
    explain:
      '물 처리에 사용되는 여과기의 일종으로 23,35,65mm의 구멍을 갖는 직조된 스테인리스 스틸망이 조 속의 회전드럼 주위에 고정되어 있는 장치',
    hNm: '마이크로스트레이너',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'micro strainer',
    explain:
      '물 처리에 사용되는 여과기의 일종으로 23,35,65mm의 구멍을 갖는 직조된 스테인리스 스틸망이 조 속의 회전드럼 주위에 고정되어 있는 장치',
    hNm: '마이크로스트레이너',
    rgsdt: '2023-10-17',
  },
  {
    eNm: 'micro strainer',
    explain:
      '물 처리에 사용되는 여과기의 일종으로 23,35,65mm의 구멍을 갖는 직조된 스테인리스 스틸망이 조 속의 회전드럼 주위에 고정되어 있는 장치',
    hNm: '마이크로스트레이너',
    rgsdt: '2023-10-12',
  },
  {
    eNm: 'micro strainer',
    explain:
      '물 처리에 사용되는 여과기의 일종으로 23,35,65mm의 구멍을 갖는 직조된 스테인리스 스틸망이 조 속의 회전드럼 주위에 고정되어 있는 장치',
    hNm: '마이크로스트레이너',
    rgsdt: '2023-10-12',
  },
  {
    eNm: 'Microcystin',
    hNm: '마이크로시스틴',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'Microcystin',
    hNm: '마이크로시스틴',
    rgsdt: '2023-09-12',
  },
  {
    eNm: 'Microcystin',
    hNm: '마이크로시스틴',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '馬蹄形 斷面',
    eNm: 'horseshoe-shaped section',
    hNm: '마제형 단면',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '馬蹄形 斷面',
    eNm: 'horseshoe-shaped section',
    hNm: '마제형 단면',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '馬蹄形 導水路',
    eNm: 'horseshoe water channel',
    explain: '수로 단면이 말발굽 모양인 개방수로',
    hNm: '마제형도수로',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '馬蹄形渦流',
    eNm: 'horseshoe vortex',
    hNm: '마제형와류',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'priming water',
    explain:
      '펌프의 시작 전 내부의 공기를 배출하고, 물을 채워 양수되지 않는 것을 방지하는 것 또는 그 물을 의미',
    hNm: '마중물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '摩擦',
    eNm: 'friction',
    explain:
      '어떤 것이 다른 어떤 것과 접촉한 상태에서 운동을 할 때 운동방향과 반대방향으로 작용되는 운동',
    hNm: '마찰',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '摩擦角',
    eNm: 'angle of friction',
    hNm: '마찰각',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '摩擦傾斜',
    eNm: 'friction slope',
    hNm: '마찰경사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '摩擦係數',
    eNm: 'coefficient of friction',
    explain:
      '마찰력의 크기는 수직항력에 비례하는데 이때의 비례상수를 말하며, 마찰력이 클수록 커짐',
    hNm: '마찰계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '摩擦攪拌接合',
    eNm: 'friction stir welding',
    explain: '용접하는 물질 사이의 마찰열을 사용한 접합법',
    hNm: '마찰교반접합',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '摩擦速度',
    eNm: 'friction velocity',
    explain:
      '흐름의 상태(층류 또는 난류)나 경계면의 상태(매끈한 정도 또는 거친 정도)에 무관하게 정의되는 속도의 차원을 가지는 개념적 유속',
    hNm: '마찰속도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '摩擦損失',
    eNm: 'friction loss',
    explain:
      '유체가 관 등의 수로에 물이 흐를 때 점성 때문에 접촉 수로의 벽면과의 마찰, 또는 유체 자신의 분자간의 마찰에 의해 생기는 에너지 손실',
    hNm: '마찰손실',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '摩擦損失',
    eNm: 'friction loss',
    explain:
      '유체가 관 등의 수로에 물이 흐를 때 점성 때문에 접촉 수로의 벽면과의 마찰, 또는 유체 자신의 분자간의 마찰에 의해 생기는 에너지 손실',
    hNm: '마찰손실',
    rgsdt: '2023-10-12',
  },
  {
    cNm: '摩擦損失係數',
    eNm: 'coefficient  of friction loss',
    explain:
      '수로에 물이 흐를 때 물과 벽면의 마찰에 의해서 생기는 마찰손실수두를 구하기 위하여 곱해주는 계수',
    hNm: '마찰손실계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '摩擦損失水頭',
    eNm: 'friction loss of head',
    explain:
      '물이 수로를 흐를 때 물 분자 사이의 내부 마찰이나, 물 분자와 수로벽면의 마찰저항으로 발생하는 에너지의 손실을 수두로 나타낸 것',
    hNm: '마찰손실수두',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '摩擦損失水頭',
    eNm: 'friction loss of head',
    explain:
      '물이 수로를 흐를 때 물 분자 사이의 내부 마찰이나, 물 분자와 수로벽면의 마찰저항으로 발생하는 에너지의 손실을 수두로 나타낸 것',
    hNm: '마찰손실수두',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '摩擦水頭',
    eNm: 'friction head',
    explain:
      '관(管) 속을 흐르는 물이 그 점성(粘性) 때문에 생기는 마찰로 잃게 되는 수두(水頭)를 나타낸다',
    hNm: '마찰수두',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '摩擦水頭',
    eNm: 'friction head',
    hNm: '마찰수두',
    rgsdt: '2023-06-27',
  },
  {
    cNm: '摩擦抵抗',
    eNm: 'frictional resistance',
    hNm: '마찰저항',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '摩擦抵抗係數',
    eNm: 'friction factor',
    hNm: '마찰저항계수',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'mach angle',
    hNm: '마하각',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '膜 相似',
    eNm: 'membrane analogy',
    hNm: '막 상사',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '膜 相似',
    eNm: 'membrane analogy',
    hNm: '막 상사',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '膜蘆花',
    eNm: 'membrane degradation',
    explain: '오랜 사용으로 막의 변형이 일어나 성능이 감소되는 것',
    hNm: '막노화',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'key',
    hNm: '막대공',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'key',
    hNm: '막대공',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '膜面流速',
    eNm: 'membrane surface flow velocity',
    hNm: '막면유속',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '膜面流速',
    eNm: 'membrane surface flow velocity',
    hNm: '막면유속',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '膜面流速',
    eNm: 'membrane surface flow velocity',
    hNm: '막면유속',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '膜面積',
    eNm: 'membrane surface area',
    hNm: '막면적',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '膜面積',
    eNm: 'membrane surface area',
    hNm: '막면적',
    rgsdt: '2023-09-12',
  },
  {
    eNm: 'membrane module',
    explain: 'ff',
    hNm: '막모듈',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'membrane module',
    hNm: '막모듈',
    rgsdt: '2023-10-19',
  },
  {
    eNm: 'membrane module',
    hNm: '막모듈',
    rgsdt: '2023-09-12',
  },
  {
    eNm: 'module clogging',
    hNm: '막모듈폐색',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'module clogging',
    hNm: '막모듈폐색',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '膜分離槽',
    eNm: 'membrane reactor',
    hNm: '막분리조',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '膜分離槽',
    eNm: 'membrane reactor',
    hNm: '막분리조',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '膜洗淨',
    eNm: 'membrane washing; cleaning',
    hNm: '막세정',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '膜洗淨',
    eNm: 'membrane washing; cleaning',
    hNm: '막세정',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '膜壽命',
    eNm: 'membrane life',
    hNm: '막수명',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '膜壽命',
    eNm: 'membrane life',
    hNm: '막수명',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '膜濾過',
    eNm: 'membrane filtration',
    explain:
      '막 분리 기술은 액상, 기체상의 일정한 크기의 입자를 막 양단의 압력차, 농도 차, 전위 차 등의 추진력으로 농축, 분리, 정제하는 기술',
    hNm: '막여과',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '膜濾過法',
    eNm: 'membrane separation process',
    hNm: '막여과법',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '膜濾過法',
    eNm: 'membrane separation process',
    hNm: '막여과법',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '膜濾過流速',
    eNm: 'membrane filtration flux',
    hNm: '막여과유속',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '膜濾過流速',
    eNm: 'membrane filtration flux',
    hNm: '막여과유속',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '膜濾過活性汚泥法',
    eNm: 'membrane separation bioreactor',
    hNm: '막여과활성슬러지법',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '膜濾過活性汚泥法',
    eNm: 'membrane separation bioreactor',
    hNm: '막여과활성슬러지법',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '膜濾過活性汚泥法',
    eNm: 'membrane separation bioreactor',
    hNm: '막여과활성슬러지법',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '膜汚染',
    eNm: 'fouling',
    hNm: '막오염',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '膜汚染',
    eNm: 'fouling',
    hNm: '막오염',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '膜差壓',
    eNm: 'transmembrane pressure difference',
    explain: '막의 양쪽에서 발생하는 압력차이',
    hNm: '막차압',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '灣曲率',
    eNm: 'sinuosity',
    hNm: '만곡률',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '灣曲比',
    eNm: 'geometrical ratio',
    explain: '하천에서 직선길이와 곡선길이의 비',
    hNm: '만곡비',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '彎曲損失',
    eNm: 'bend loss',
    hNm: '만곡손실',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '灣曲水路',
    eNm: 'sinuous channel',
    hNm: '만곡수로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '灣曲水路',
    eNm: 'sinuous channel',
    hNm: '만곡수로',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '滿水位',
    eNm: 'High Water Level',
    hNm: '만수위',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '滿水位',
    eNm: 'High Water Level',
    hNm: '만수위',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '滿堤水位',
    eNm: 'bankful stage',
    hNm: '만제수위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '滿堤流量',
    eNm: 'bankful discharge',
    explain: '하천 제방에서 최초로 물이 넘치는 순간의 유량',
    hNm: '만제유량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '末端區間',
    eNm: 'tail reach',
    hNm: '말단구간',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '末端區間',
    eNm: 'tail reach',
    hNm: '말단구간',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '末端收縮',
    eNm: 'end contraction',
    hNm: '말단수축',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '末端收縮',
    eNm: 'end contraction',
    hNm: '말단수축',
    rgsdt: '2023-09-14',
  },
  {
    explain: '물속에 존재하는 화학물질로 인해 발생하는 맛과 냄새',
    hNm: '맛·냄새',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '異臭味除去法',
    eNm: 'taste and odor removal method',
    hNm: '맛·냄새제거법',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '異臭味除去法',
    eNm: 'taste and odor removal method',
    hNm: '맛·냄새제거법',
    rgsdt: '2023-09-12',
  },
  {
    eNm: 'manganese bacteria',
    hNm: '망간박테리아',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'manganese sand',
    hNm: '망간사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '除去',
    eNm: 'manganese removal',
    explain: '망간제거는 물에 포함된 망간을 제거하는 것을 말함',
    hNm: '망간제거',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '除去',
    eNm: 'manganese removal',
    explain: '망간제거는 물에 포함된 망간을 제거하는 것을 말함',
    hNm: '망간제거',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '網狀河川',
    eNm: 'braided river',
    explain:
      '하천 경사가 완만하며 수심이 얕은 여러 줄기의 그물 모양으로 이루어진 하도망을 가진 하천',
    hNm: '망상하천',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '網狀河川',
    eNm: 'braided river',
    explain:
      '하천 경사가 완만하며 수심이 얕은 여러 줄기의 그물 모양으로 이루어진 하도망을 가진 하천',
    hNm: '망상하천',
    rgsdt: '2023-10-17',
  },
  {
    eNm: 'crib groyne bank protection',
    hNm: '망태계호안',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'crib groyne bank protection',
    explain:
      '철선으로 짜여진 망태에 돌을 채우거나, 돌무더기를 철망으로 고정하는 방법 등으로 만들어진 호안으로 내구성과 순응성이 크기 때문에 유속이 빠른 하천 지역과 수공구조물의 상하류 지역 등 흐름의 영향을 많이 받는 곳에서 제방과 하상의 보호공으로 적합한 호안이다. 망태계 호안공법은 돌망태 방법, 게비온 방법 및 식생콘크리트 바구니 방법 등이 있다.',
    hNm: '망태계호안',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '公式',
    eNm: "manning's formula",
    explain: '개수로에서 유체단면의 평균 유속을 구하는 공식',
    hNm: '매닝공식',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Manning’s roughness coefficient',
    explain: '수로의 벽면의 거칠기 성질에 의해 결정되는 계수',
    hNm: '매닝조도계수',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Manning’s roughness coefficient',
    explain: '수로의 벽면의 거칠기 성질에 의해 결정되는 계수',
    hNm: '매닝조도계수',
    rgsdt: '2023-10-16',
  },
  {
    cNm: '埋立',
    eNm: 'filling, reclamation',
    explain: '가까운 바다에 토사를 퇴적시켜 인공적으로 새로운 육지를 만드는 것',
    hNm: '매립',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '埋立',
    eNm: 'filling, reclamation',
    explain: '가까운 바다에 토사를 퇴적시켜 인공적으로 새로운 육지를 만드는 것',
    hNm: '매립',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '埋立契汚染源',
    eNm: 'pollution source of reclamation type',
    hNm: '매립계오염원',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '埋立契汚染源',
    eNm: 'pollution source of reclamation type',
    hNm: '매립계오염원',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '埋立處分',
    eNm: 'Landfill disposal',
    explain: '쓰레기 또는 폐기물을 매립하여 처리하는 방법',
    hNm: '매립처분',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '埋沒水路',
    eNm: 'buried channel',
    hNm: '매몰수로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '埋沒河川',
    eNm: 'buried channel',
    hNm: '매몰하천',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '埋設管',
    eNm: 'underground pipe',
    explain: '땅 속에 묻혀 있는 관',
    hNm: '매설관',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '埋設物深知器',
    eNm: 'pipe locator, underground facility locator',
    explain: '전자기파를 사용하여 지하에 매설된 시설을 탐지하는 기기',
    hNm: '매설물 탐지기',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '埋設物防護',
    eNm: 'protection for underground facility',
    explain:
      '공사를 시공할 때에 영향을 받을 위험이 있는 매설물을 방호하기 위하여 실시하는 모든 처리',
    hNm: '매설물방호',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '埋設表示',
    eNm: 'indication of laying',
    explain: '지하에 매설되어 있는 시설에 대한 정보를 지표면에서 표시하는 것',
    hNm: '매설표시',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '煤煙',
    eNm: 'smoke',
    explain:
      '일반적으로 연소과정에서 형성되는 가스 중에 포함되어있는 입자로 고체, 기체, 휘발성 증기 등으로 구성',
    hNm: '매연',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '煤煙濃度',
    eNm: 'smoke density',
    hNm: '매연농도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '煤塵',
    eNm: 'dust',
    explain:
      '연소과정에서 형성되는 매연의 일부로, 연기 속에 포함되어 있는 그을음이나 재 등의 성분',
    hNm: '매진',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脈動流',
    eNm: 'pulsating flow',
    hNm: '맥동류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '脈動裝置',
    eNm: 'Pulsator',
    hNm: '맥동장치',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pump pressure pulsation',
    explain: '맥박이 뛰듯이 송출량이 증가와 감소가 주기적으로 일어나는 펌프',
    hNm: '맥동펌프',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '脈動型高速凝集沈澱池',
    eNm: 'hydraulic pulsed suspended solid contact clarifier',
    explain: '물의 맥동을 사용하여 플록을 형성시켜 침전시키는 반응조',
    hNm: '맥동형고속응집침전지',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'Mann-Kendall test',
    hNm: '맨-켄달 검정법',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'Mann-Kendall test',
    hNm: '맨-켄달 검정법',
    rgsdt: '2023-09-12',
  },
  {
    eNm: 'manhole interval',
    explain: '2개 맨홀의 중심 간 거리',
    hNm: '맨홀 간격',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '盲谷',
    eNm: 'blind valley',
    hNm: '맹곡',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '盲排水溝',
    eNm: 'stone-filled drain ditch',
    explain:
      '지표면 가까이의 침투수를 모아서 배수하기 위해 땅 속에 설치하는 배수구',
    hNm: '맹배수구',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '盲暗渠',
    eNm: 'stone filled drain dummy ditch',
    explain: '배수를 통한 지하수위의 조절을 위해 땅 속에 매설한 수로',
    hNm: '맹암거',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '盲下水',
    eNm: 'blind drain',
    explain: '지하 배수구의 일종',
    hNm: '맹하수',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'mud ball',
    explain:
      '급속여과지에서 세척이 불충분하여 여층의 내부에 주로 미세한 모래를 핵으로 하여 생기는 20~25mm 정도의 덩어리',
    hNm: '머드볼',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Muskingum method',
    explain: '하도 홍수추적의 한 가지 방법',
    hNm: '머스킹검방법',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'muffle furnace',
    explain:
      '가열되어지는 물체에 직접 불꽃이 닿지 않게 가열실과 연소실 사이 격벽을 설치한 가마',
    hNm: '머플로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '飮用水水質基準',
    eNm: 'water quality standards for drinking water, quality standards for potable water',
    explain:
      '사람이 음용하기에 알맞은 물에 대해 먹는 물 수질기준 및 검사 등에 관한 기준을 규칙으로 정한 규정',
    hNm: '먹는물수질기준',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '食物連鎖',
    eNm: 'food chain',
    explain: '생물군집 내에서 포식, 피식의 관계에 의한 연쇄적 연결',
    hNm: '먹이사슬',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'multiple arch dam',
    explain: '여러 개의 아치 형태의 댐체로 이루어진 댐',
    hNm: '멀티플아치댐',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'multiple arch dam',
    explain: '여러 개의 아치 형태의 댐체로 이루어진 댐',
    hNm: '멀티플아치댐',
    rgsdt: '2023-10-17',
  },
  {
    eNm: "merian's formula",
    explain: '호소 및 해안에서 진동의 주기를 구하는 공식',
    hNm: '메리안의 공식',
    rgsdt: '2016-04-15',
  },
  {
    eNm: "merian's formula",
    explain: '호소 및 해안에서 진동의 주기를 구하는 공식',
    hNm: '메리안의 공식',
    rgsdt: '2023-10-16',
  },
  {
    eNm: "merian's formula",
    explain: '호소 및 해안에서 진동의 주기를 구하는 공식',
    hNm: '메리안의 공식',
    rgsdt: '2023-10-16',
  },
  {
    eNm: 'mesocosm',
    hNm: '메소코즘',
    rgsdt: '2016-11-24',
  },
  {
    eNm: 'mesocosm',
    hNm: '메소코즘',
    rgsdt: '2023-09-14',
  },
  {
    eNm: 'mechanical joint',
    explain: '주철관의 접속에 쓰이는 이음',
    hNm: '메카니칼 이음',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'sodium metaphosphate',
    explain: '경수의 연화 등을 위해 사용되는 인산나트륨 중합체',
    hNm: '메타인산나트륨',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'methane fermentation, methanation',
    explain:
      '유기산 등이 편성혐기성세균인 메탄생성세균의 작용에 의하여 메탄과 이산화탄소로 변하는 과정',
    hNm: '메탄발효',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'methane fermentation process',
    hNm: '메탄발효법',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'methane fermentation process',
    hNm: '메탄발효법',
    rgsdt: '2023-09-12',
  },
  {
    eNm: 'methanogens',
    explain:
      '늪이나 진흙 등 혐기성 환경에서 대사 작용의 생산물로 메탄가스를 발생시키는 세균',
    hNm: '메탄변환박테리아',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'methanogenesis',
    explain:
      '메탄생성세균 (methanogen)에 의해서 혐기성 환경에서 메탄이 형성되는 작용',
    hNm: '메탄생성반응',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'methanogenesis',
    explain:
      '메탄생성세균 (methanogen)에 의해서 혐기성 환경에서 메탄이 형성되는 작용',
    hNm: '메탄생성반응',
    rgsdt: '2023-10-17',
  },
  {
    eNm: 'methane bacteria, methanogens',
    explain:
      '늪이나 진흙 등 혐기성 환경에서 대사 작용의 생산물로 메탄가스를 발생시키는 세균',
    hNm: '메탄생성세균',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'methane bacteria, methanogens',
    explain:
      '늪이나 진흙 등 혐기성 환경에서 대사 작용의 생산물로 메탄가스를 발생시키는 세균',
    hNm: '메탄생성세균',
    rgsdt: '2023-10-17',
  },
  {
    eNm: 'methemoglobinemia',
    explain:
      '적혈구 내의 헤모글로빈이 3가철 헤모글로빈인 메트헤모글로빈으로 주로 구성되어 있는 경우로 청색증을 유발',
    hNm: '메트헤모글로빈혈증',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'methylene blue active substance',
    explain:
      '메틸블루에 의해서 클로로포름에 녹는 청색의 착화합물을 형성하는 수중의 물질',
    hNm: '메틸렌블루 활성물질',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'methyl mercury',
    explain: '알킬수은의 하나로서 수은과 메틸기(CH3)가 결합된 것',
    hNm: '메틸수은',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'methyl alcohol',
    hNm: '메틸알코올',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'methyl orange alkalinity',
    explain:
      '물시료의 pH를 4.5까지 감소시키는데 사용되는 산의 양으로 측정한 알칼리도',
    hNm: '메틸오렌지알칼리도',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'membrane bioreactor',
    explain: '통상적인 활성슬러지 공법과 막여과 공법이 결합된 수처리조',
    hNm: '멤브레인 바이오리엑터',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'membrane bioreactor',
    explain: '통상적인 활성슬러지 공법과 막여과 공법이 결합된 수처리조',
    hNm: '멤브레인 바이오리엑터',
    rgsdt: '2023-09-27',
  },
  {
    eNm: 'membrane filter',
    hNm: '멤브레인 필터',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'membrane filter',
    hNm: '멤브레인 필터',
    rgsdt: '2023-09-12',
  },
  {
    eNm: 'membrane filter method,',
    explain:
      '막을 통하여 고순도의 물은 통과하고 용존, 부유고형물은 배제시키는 공정',
    hNm: '멤브레인법',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'power spectrum',
    hNm: '멱스펙트럼',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '面像 洪水',
    eNm: 'sheet flood',
    hNm: '면상 홍수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '面狀侵蝕',
    eNm: 'sheet erosion',
    explain:
      '비탈진 땅에서 강우 또는 관개에 의해 발생된 유거수가 전면에 걸쳐 표토를 이동시키는 평면적인 토양침식',
    hNm: '면상침식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '免疫',
    eNm: 'immunity',
    explain:
      '생물이 감염이나 병으로부터 대항하여 병원균을 죽이거나 무력화하는 작용 ',
    hNm: '면역',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '面源汚染',
    eNm: 'non-point source pollution',
    explain:
      '점(특정)오염원이외의 것으로, 넓은 면적에 불규칙하게 분포하고, 제어하기가 곤란한 오염원',
    hNm: '면원오염',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '面積(降)雨量',
    eNm: 'areal rainfall',
    explain:
      '임의의 유역에 대한 점강우량의 면적 평균값으로 정의되며 mm단위를 사용하여 나타냄',
    hNm: '면적(강)우량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '面積-降雨量曲線',
    eNm: 'area depth curve',
    hNm: '면적-강우량곡선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '面的-高度解析',
    eNm: 'hypsometric analysis',
    explain:
      '일정 고도 이상의 면적과 고도를 구하여 도시하여 지형을 해석하는 방법',
    hNm: '면적-고도해석',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '面積空隙率',
    eNm: 'areal porosity',
    explain:
      '다공성 매체의 단면에서 공극이 차지하는 면적과 전체 시료의 면적의 비율',
    hNm: '면적공극률',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '面積負荷',
    eNm: 'area loading',
    explain: '여상 면적당 슬러지 케이크 투입량',
    hNm: '면적부하',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '面積增分法',
    hNm: '면적증분법',
    rgsdt: '2016-11-24',
  },
  {
    cNm: '面積增分法',
    eNm: 'Area Incremental Method',
    hNm: '면적증분법',
    rgsdt: '2023-10-12',
  },
  {
    cNm: '滅菌',
    eNm: 'sterilization',
    explain:
      '포자를 포함한 모든 미생물을 살균 또는 제거하여 세균, 균류가 존재하지 않는 무균상태를 만드는 것으로 소독의 가장 안전한 형태',
    hNm: '멸균',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '滅種',
    eNm: 'extinction',
    explain:
      '어느 생물종이 적응하지 못하고 그 영역이나 지구상에서 완전히 사멸되는 것',
    hNm: '멸종',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '滅種危機種',
    eNm: 'endangered species',
    explain: '희귀종야생생물로 가까운 미래에 멸종될 위험이 높은 종',
    hNm: '멸종위기종',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '明礬 ',
    eNm: 'alum',
    explain:
      '수중의 부유물질 및 콜로이드 물질을 응집시켜 침전을 유발시키기 위해 사용하는 약품인 황산알루미늄',
    hNm: '명반',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '明礬 ',
    eNm: 'alum',
    explain:
      '수중의 부유물질 및 콜로이드 물질을 응집시켜 침전을 유발시키기 위해 사용하는 약품인 황산알루미늄',
    hNm: '명반',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '毛管',
    eNm: 'capillary tube',
    explain: '모관 현상을 나타낼 수 있을 정도의 충분히 가는 관',
    hNm: '모관',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'capillary potential',
    explain: '모세관 속에 있는 액체의 에너지',
    hNm: '모관 퍼텐셜',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管間隙',
    eNm: 'capillary pore',
    explain: '모세관 현상을 초래할 수 있는 공극',
    hNm: '모관간극',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管境界帶',
    eNm: 'boundary zone of capillarity',
    explain:
      '불포화대의 하부에 존재하는 부분으로 지하수면에서 모관현상에 의해 물이 상승하는 부분',
    hNm: '모관경계대',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管孔隙',
    eNm: 'capillary sapce',
    explain: '모관 현상으로 물을 간직할 수 있는 크기의 공극',
    hNm: '모관공극',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管力',
    eNm: 'capillary forces',
    explain: '물이 작은 관을 통해 상승하게 만드는 힘',
    hNm: '모관력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管流',
    eNm: 'capillary flow',
    hNm: '모관류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管上昇',
    eNm: 'capillary rise',
    explain: '모세관 현상으로 인해 토양수분이 상승하는 현상',
    hNm: '모관상승',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '毛管上昇高',
    eNm: 'capillary height',
    hNm: '모관상승고',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管水',
    eNm: 'capillary water',
    explain:
      '토양입자 간의 모관 인력에 의하여 토양 내의 작은 공극을 상승하는 수분',
    hNm: '모관수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管水帶',
    eNm: 'capillary fringe',
    explain: '비포화대의 일부이지만 공극이 물로 채워져있는 부분',
    hNm: '모관수대',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '毛管水頭',
    eNm: 'capillary head',
    explain: '가는 관을 따라 물이 상승하는 모관현상에 의해 물이 상승한 높이',
    hNm: '모관수두',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管水分',
    eNm: 'capillary water',
    explain: '모세관 현상에 의해 토양에 유지되는 수분',
    hNm: '모관수분',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '毛管水分',
    eNm: 'capillary water',
    hNm: '모관수분',
    rgsdt: '2023-06-27',
  },
  {
    cNm: '毛管水壓',
    eNm: 'capillary pressure',
    explain:
      '모세관 현상에 의해 토양으로 빨려 들어온 물이 주위의 토양입자를 잡아당기는 압력',
    hNm: '모관수압',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管水移動',
    eNm: 'capillary migration, capillary movement',
    explain:
      '표면장력으로 인해 비포화대에서 물이 토양 공극을 따라 이동하는 현상',
    hNm: '모관수이동',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管壓',
    eNm: 'capillary pressure ',
    explain: '모관수가 주변의 흙 입자를 끌어당기는 작용을 할 때의 압력',
    hNm: '모관압',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管移動',
    eNm: 'capillary movement',
    explain: '토양 속에서 모관력에 의해 토양수분이 이동하는 것',
    hNm: '모관이동',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管作用',
    eNm: 'capillary action',
    explain:
      '액체의 표면장력에 의해서 공극이나 작은 관(管) 내부에서 액체가 이동하는 현상',
    hNm: '모관작용',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管土壤含水',
    eNm: 'capillary soil moisture',
    explain:
      '토양입자 사이의 공극에 존재하는 물 중에서 모세관력에 의해서 유지되는 물',
    hNm: '모관토양함수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管透水試驗器',
    eNm: 'capillary permeameter',
    hNm: '모관투수시험기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛管現像',
    eNm: 'capillarity',
    explain: '액체가 가는 관을 따라 상승하는 현상',
    hNm: '모관현상',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Monod equation',
    hNm: '모노드식',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'Monod equation',
    hNm: '모노드식',
    rgsdt: '2023-10-19',
  },
  {
    eNm: 'Monod equation',
    hNm: '모노드식',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '曝氣法',
    eNm: 'modified aeration process',
    explain:
      '활성슬러지법의 고율 활성슬러지법의 하나로서, 1차 침전지를 생략하여 하수를 직접 포기조로 유입시키고, 슬러지반송비를 5-10%로 낮게 하여 1. 5-2. 0 시간 정도의 포기하는 방법',
    hNm: '모디파이드 포기법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '砂',
    eNm: 'sand',
    explain:
      '잘게 부서진 암석과 광물 파편으로 구성되어있는 지름이 2~0.02mm인 입자상 물질',
    hNm: '모래',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '砂',
    eNm: 'sand',
    explain:
      '잘게 부서진 암석과 광물 파편으로 구성되어있는 지름이 2~0.02mm인 입자상 물질',
    hNm: '모래',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '防砂工法',
    eNm: 'sand screen',
    explain: '토사 침전 유도 구조물',
    hNm: '모래막이',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '砂濾過',
    eNm: 'sand filter',
    explain:
      '모래 여상을 이용해 원수 속의 불순물을 제거해서 세정을 실행하는 방법',
    hNm: '모래여과',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '砂濾過池',
    eNm: 'sand filter',
    explain: '모래를 여과재로 사용하는 여과로 오염물질(불순물)을 제거하는 시설',
    hNm: '모래여과지',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '砂濾過池',
    eNm: 'sand filter',
    explain: '모래를 여과재로 사용하는 여과로 오염물질(불순물)을 제거하는 시설',
    hNm: '모래여과지',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '砂濾過池',
    eNm: 'sand filter',
    explain: '모래를 여과재로 사용하는 여과로 오염물질(불순물)을 제거하는 시설',
    hNm: '모래여과지',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '砂濾床',
    eNm: 'sand filter bed',
    explain: '모래를 여과재로 사용하는 여과장치',
    hNm: '모래여상',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '砂濾床',
    eNm: 'sand filter bed',
    explain: '모래를 여과재로 사용하는 여과장치',
    hNm: '모래여상',
    rgsdt: '2023-10-17',
  },
  {
    eNm: 'mortar lining pipe',
    explain: '모르타르 라이닝 도장을 강관이나 주철관에 실시한 관',
    hNm: '모르타르 라이닝관',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'method of moment',
    explain:
      '확률분포함수, 시계열 함수 등을 관측 값으로부터 추정할 때 사용되는 방법',
    hNm: '모멘트법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛髮濕度計',
    eNm: 'hair hygrometer',
    hNm: '모발습도계',
    rgsdt: '2016-11-24',
  },
  {
    cNm: '毛髮濕度計',
    eNm: 'hair hygrometer',
    hNm: '모발습도계',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '毛細管',
    eNm: 'capillary tube',
    explain: '모세관 현상을 나타낼 수 있을 정도의 충분히 가는 관',
    hNm: '모세관',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'capillary membrane',
    explain: '미세한 관을 묶어놓은 형태의 여과막',
    hNm: '모세관 멤브레인',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '毛細管空隙',
    eNm: 'capillary interstice',
    explain: '토양에 나타나는 작은 공극',
    hNm: '모세관공극',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '毛細管空隙',
    eNm: 'capillary interstice',
    explain: '토양에 나타나는 작은 공극',
    hNm: '모세관공극',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '毛細管帶',
    eNm: 'capillary zone ',
    explain:
      '모세관 현상으로 지하수면으로부터 물이 상승하여 비포화대임에도 불구하고 공극이 물로 채워져있는 부분',
    hNm: '모세관대 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛細管水',
    eNm: 'capillary Water ',
    explain: '모세관대의 공극에 보유된 물',
    hNm: '모세관수 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛細管壓',
    eNm: 'capillary pressure',
    explain: '모관수가 주변의 흙 입자를 끌어당기는 작용을 할 때의 압력',
    hNm: '모세관압',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛細管作用',
    eNm: 'capillary action',
    explain:
      '액체의 표면장력에 의해서 공극이나 작은 관(管) 내부에서 액체가 이동하는 현상',
    hNm: '모세관작용',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛細管飽和圈',
    eNm: 'zone of capillary saturation',
    explain: '모세관 현상에 의해 끌려올려진 물에 의해 포화된 지층의 일부지역',
    hNm: '모세관포화권',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '毛細管現象',
    eNm: 'capillarity',
    explain: '액체가 가는 관을 따라 상승하는 현상',
    hNm: '모세관현상',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毛細管現象',
    eNm: 'capillarity',
    explain: '액체가 가는 관을 따라 상승하는 현상',
    hNm: '모세관현상',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '毛細管現象',
    eNm: 'capillarity',
    explain: '액체가 가는 관을 따라 상승하는 현상',
    hNm: '모세관현상',
    rgsdt: '2023-10-12',
  },
  {
    cNm: '母水路',
    eNm: 'parent canal',
    hNm: '모수로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '母集團分布',
    eNm: 'population distribution',
    explain: '분석대상이 되는 전체자료가 가지는 것으로 예상되는 분포',
    hNm: '모집단분포',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '模型',
    eNm: 'model',
    explain:
      '수리구조물 해석을 위해 실제구조물의 특성을 대변하도록 만든 축소 구조물.',
    hNm: '모형',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '模型基準',
    eNm: 'modeling criteria',
    explain: '수리학적 해석을 위한 모형 작업의 실시 기준',
    hNm: '모형기준',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '模型試驗',
    eNm: 'model test',
    explain: '일정 비율로 축조된 모형을 사용해 행하는 시험',
    hNm: '모형시험',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '模型化',
    eNm: 'modeling',
    explain:
      '실제 시스템을 소형화된 모형 또는 수학적 모델을 사용하여 실제 일어나는 작용을 평가하는 것',
    hNm: '모형화',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '不連續面',
    eNm: 'moho discontinuity',
    explain: '지각의 하부를 나타내는 면',
    hNm: '모호불연속면',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'monsoon',
    explain:
      '대륙과 인접한 해양의 부등 가열과 냉각에 의해 유발되는 계절적인 바람과 날씨 시스템',
    hNm: '몬순',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'mole',
    explain:
      '원자나 분자나 이온과 같은 물질의 기본단위 입자를 묶어서 그 개수를 세는 단위',
    hNm: '몰',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'molar concentration',
    explain: '용액 1L에 포함된 용질의 몰수(체적 몰농도)',
    hNm: '몰농도',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'molality',
    explain: '용매 1kg에 녹아있는 용질의 몰수로 나타낸 농도',
    hNm: '몰랄농도',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'mole fraction',
    explain:
      '두 가지 이상의 성분이 섞여 있을 때 한 성분의 농도를 나타내는 방법의 하나로 전체 성분에 대한 어떤 성분의 몰수 비',
    hNm: '몰분율',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'lagoon, mere, pond',
    explain: '분지형태의 넓은 땅에 항상 물이 고여 있는 곳을 총칭',
    hNm: '못',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'nursery bed water',
    hNm: '못자리 용수량',
    rgsdt: '2016-11-24',
  },
  {
    eNm: 'nursery bed water',
    hNm: '못자리 용수량',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '蒙利面積',
    eNm: 'irrigation area',
    explain:
      '근대 개항기 경기도 광명 지역에 있는 관개 시설에서 물을 공급받는 땅의 면적',
    hNm: '몽리면적',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '蒙利面積',
    eNm: 'irrigation area',
    explain:
      '근대 개항기 경기도 광명 지역에 있는 관개 시설에서 물을 공급받는 땅의 면적',
    hNm: '몽리면적',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '無耕耘',
    eNm: 'zero tillage',
    explain: '작물의 재배에 적합하도록 토양 교반을 하지 않는 것',
    hNm: '무경운',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無機廢水',
    eNm: 'inorganic wastewater',
    explain: '공업폐수 중 무기물질을 주로 포함한 폐수',
    hNm: '무기 폐수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無機高分子凝集劑',
    eNm: 'inorganic polymer coagulant',
    explain: '알루미늄염, 철염 등의 무기응집제들을 가수분해해서 중합시킨 것',
    hNm: '무기고분자응집제',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '無機高分子凝集劑',
    eNm: 'inorganic polymer coagulant',
    explain: '알루미늄염, 철염 등의 무기응집제들을 가수분해해서 중합시킨 것',
    hNm: '무기고분자응집제',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '無機膜',
    eNm: 'inorganic membrane',
    explain:
      '무기물을 소재로 하는 막의 총칭. 세라믹막, 탄소막, 유리막 등이 있음',
    hNm: '무기막',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '無機膜',
    eNm: 'inorganic membrane',
    explain:
      '무기물을 소재로 하는 막의 총칭. 세라믹막, 탄소막, 유리막 등이 있음',
    hNm: '무기막',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '無機物溶解',
    eNm: 'mineral dissolution',
    explain:
      '토양이나 지하수 환경에서 암석을 구성하는 무기 광물질이 물에 의해 용해되는 현상',
    hNm: '무기물용해',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無機物溶解',
    eNm: 'mineral dissolution',
    explain:
      '토양이나 지하수 환경에서 암석을 구성하는 무기 광물질이 물에 의해 용해되는 현상',
    hNm: '무기물용해',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '無機物化',
    eNm: 'mineralization',
    explain:
      '자연계에 존재하는 유기물질이 미생물에 의해 분해되어 무기물로 변하는 과정',
    hNm: '무기물화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無機酸營養湖 ',
    eNm: 'inorganic acidotrophic lake',
    explain: '무기염류를 다량 함유한 지하수가 유입되어 생성되는 호수',
    hNm: '무기산 영양호',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無機性燐',
    eNm: 'inorganic phosphorus',
    explain: '탄소와 결합하여 있지 않은 인',
    hNm: '무기성 인',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無機性汚泥',
    eNm: 'inorganic sludge',
    explain:
      '무기성분을 많이 함유한 슬러지의 총칭, 규조토 앙금, 탄산칼슘 앙금, 폐백토 등이 있음',
    hNm: '무기성슬러지',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '無機性汚泥',
    eNm: 'inorganic sludge',
    explain:
      '무기성분을 많이 함유한 슬러지의 총칭, 규조토 앙금, 탄산칼슘 앙금, 폐백토 등이 있음',
    hNm: '무기성슬러지',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '無機性堆積物',
    eNm: '無機性堆積物',
    explain:
      '주로 호소(湖沼)의 바닥에 퇴적된 물질로서 호숫가에 퇴적되어 있으며, 석회 퇴적물, 철 퇴적물, 망간 퇴적물, 규산 퇴적물, 점토 퇴적물 등이 있음',
    hNm: '무기성퇴적물',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '無機水銀',
    eNm: 'inorganic mercury',
    hNm: '무기수은',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '無機水銀',
    eNm: 'inorganic mercury',
    hNm: '무기수은',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '無機營養生物',
    eNm: 'lithotroph',
    explain: '무기화합물을 산화시켜 발생하는 에너지를 이용하여 살아가는 생물',
    hNm: '무기영양생물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無機榮養細菌',
    eNm: 'chemolithotroph, chemolithotrophic bacteria',
    explain:
      'H2S, S, NH4+,  H2, NO2-, Fe2+ 등의 무기물을 산화시키는 과정에서 발생하는 에너지를 이용하여 탄소를 고정할 수 있는 독립영양세균',
    hNm: '무기영양세균',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'mineral nutrient, inorganic nutrient',
    explain: '무기물로서 존재하는 영양염류',
    hNm: '무기영양염',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無機溶解性物質',
    eNm: 'inorganic dissolved substance ',
    explain: '수용액에 녹아있는 물질 중에 무기질',
    hNm: '무기용해성 물질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無機凝集劑',
    eNm: 'inorganic coagulant',
    explain:
      '응집제 가운데 알루미늄염, 철염, 소석회 등과 같이 무기성분만으로 제조된 것',
    hNm: '무기응집제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無機質土壤',
    eNm: 'mineral soil',
    explain: '암석의 풍화과정에서 형성된 2차광물로 구성되어 있는 토양',
    hNm: '무기질토양',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無機態養分',
    eNm: 'inorganic nutrient',
    explain:
      '무기물의 형태로 존재하는 양분을 총칭하는 것으로 유기물 형태의 양분과 대비되는 용어',
    hNm: '무기태 양분',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無機化(作用)',
    eNm: 'mineralization',
    explain:
      '생물 또는 생물 사체 중의 유기화합물이 식물이 이용 가능한 형태의 무기화합물로 분해되는 것. 유기물의 무기화는 연소나 생물대사에 의하여 이루어짐',
    hNm: '무기화(작용)',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '無機化合物',
    eNm: 'inorganic compound',
    explain:
      '유기화합물을 제외한 모든 화합물이며, 탄소를 함유하지 않은 화합물과 탄소를 함유하는 간단한 화합물인 산화물·사이안화물·탄산염 등을 말함',
    hNm: '무기화합물',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '圖表',
    eNm: 'moody diagram',
    explain:
      '새로운 깨끗한 시판의 관에 대하여 관마찰 계수와 레이놀즈수의 관계를 관벽의 상대 조도의 차이에 의해 정리한 그림',
    hNm: '무디도표',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '圖表',
    eNm: 'moody diagram',
    explain:
      '새로운 깨끗한 시판의 관에 대하여 관마찰 계수와 레이놀즈수의 관계를 관벽의 상대 조도의 차이에 의해 정리한 그림',
    hNm: '무디도표',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '無負荷運轉',
    eNm: 'no-load running',
    explain: '기계설비에 부하를 주지 않는 형태로 운전하는 것',
    hNm: '무부하운전',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '無酸素性',
    eNm: 'anoxic',
    explain:
      '물속에 O2와 같은 용존산소는 없지만 NO2, NO3와 같은 결합산소는 존재하는 상태. ',
    hNm: '무산소성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無酸素槽',
    eNm: 'anoxic tank',
    explain:
      '생물학적 질소 제거법에서 탈질을 하기 위하여 무산소성 상태로 만든 조',
    hNm: '무산소조',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '無酸素槽',
    eNm: 'anoxic tank',
    explain:
      '생물학적 질소 제거법에서 탈질을 하기 위하여 무산소성 상태로 만든 조',
    hNm: '무산소조',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '無酸素呼吸',
    eNm: 'anaerobic respiration',
    explain: '산소를 이용하지 않는 호흡',
    hNm: '무산소호흡',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無酸素呼吸',
    eNm: 'anaerobic respiration',
    explain: '산소를 이용하지 않는 호흡',
    hNm: '무산소호흡',
    rgsdt: '2023-10-12',
  },
  {
    cNm: '無生物的環境',
    eNm: 'abiotic environment',
    explain: '생태계의 구성요소 중 생물체에 영향을 주는 물리적, 환경적 요소',
    hNm: '무생물적 환경',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無生浮遊物',
    eNm: 'abioseston, tripton',
    explain: '생명이 없는 미립물(微粒物)을 의미',
    hNm: '무생부유물',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'plethysmothallus',
    hNm: '무성엽상체',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'non-revenue water',
    explain:
      '정수장에서 소비지로 공급한 물 중에서 누수가 되었거나 수도요금을 징수할 수 없게 된 물의 양',
    hNm: '무수수량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無效率',
    eNm: 'non-revenue water ratio',
    explain:
      '총급수량(정수장에서 생산해 공급한 수돗물) 중에서 요금수입으로 받아들여지지 않은 수량의 비율',
    hNm: '무수율',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無循環湖',
    eNm: 'amictic lake',
    explain:
      '일년 동안 변하는 온도 범위에서 얼음으로 덮여 일년 내내 얼음으로 덮여 있는 호수',
    hNm: '무순환호',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無藥注脫水法',
    eNm: 'chemicals-free dewatering, non-chemicals dewatering method',
    explain:
      '슬러지를 탈수할 때 약제를 첨가하지 않고, 슬러지를 그대로 탈수하는 방법',
    hNm: '무약주탈수법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無煙炭',
    eNm: 'anthracite',
    explain: '역청탄보다 석탄화도가 더욱 진행된 석탄',
    hNm: '무연탄',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無用水',
    eNm: 'useless water',
    explain: '작물의 성장에 사용할 수 없는 토양수',
    hNm: '무용수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無燐合成洗劑',
    eNm: 'non-phosphorus synthetic detergent',
    explain: '인산염을 제거한 합성세제',
    hNm: '무인합성세제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無停電電源裝置',
    eNm: 'uninterruptible power supply',
    explain:
      '정전 등의 비상상황에도 일정한 전력을 기기에 공급하기 위해 사용되는 장치',
    hNm: '무정전전원장치',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '無停電電源裝置',
    eNm: 'uninterruptible power supply',
    explain:
      '정전 등의 비상상황에도 일정한 전력을 기기에 공급하기 위해 사용되는 장치',
    hNm: '무정전전원장치',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '無潮區域',
    eNm: 'nontidal compartment',
    explain: '조석의 영향을 받지 않는 구역',
    hNm: '무조구역',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無潮河川',
    eNm: 'non-tidal river',
    explain: '조석의 영향을 받지 않는 하천',
    hNm: '무조하천',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無次元單位圖',
    eNm: 'dimensionless unit hydrograph',
    explain:
      '단위유량도의 유량(종축)과 시간(횡축)에 무차원량으로 표시한 단위도',
    hNm: '무차원단위도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無次元水文曲線',
    eNm: 'dimensionless hydrograph',
    explain:
      '단위유량도의 유량(종축)과 시간(횡축)에 무차원량으로 표시한 수문곡선',
    hNm: '무차원수문곡선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無閉塞形回轉子',
    eNm: 'non-clogging impeller',
    explain:
      '펌프의 회전자와 케이싱의 통과부분을 크게하여 상당한 크기의 협잡물도 폐색을 일으키지 않도록 만든 회전자',
    hNm: '무폐색형회전자',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無限 貯水池',
    eNm: 'infinite reservoir',
    hNm: '무한 저수지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無限帶水層',
    eNm: 'infinity aquifer',
    hNm: '무한대수층',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無效水量',
    eNm: 'ineffective water volume, ',
    explain: '증발 및 증산으로 인하여 직접유출에 기여하지 못하는 강수량의 일부',
    hNm: '무효수량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無效率',
    eNm: 'ineffective water ratio',
    explain:
      '총급수량(정수장에서 생산해 공급한 수돗물) 중에서 무효하게 사용한 물의 비율',
    hNm: '무효율',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無效貯水量',
    eNm: 'deal storage (capacity), noneffective storage,',
    explain: '용수공급에 필요한 최저수위에 달하지 않는 수량',
    hNm: '무효저수량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '無效電流',
    eNm: 'reactive current',
    explain:
      '교류 회로를 흐르고 있는 전류 가운데 유효 전력이 되지 않는 부분으로 전압과 직각 위상의 전류 성분',
    hNm: '무효전류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '門扉',
    eNm: 'gate',
    hNm: '문비',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'gate recess',
    explain: '수문의 개폐 시 사용되는 빈 공간',
    hNm: '문집',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'depth of sill',
    hNm: '문턱깊이',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水',
    eNm: 'water',
    explain: '상온에서 액체인 무색, 무미, 무취의 수소와 산소의 화합물',
    hNm: '물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水收支分析',
    eNm: 'water budget analysis',
    explain:
      '물의 유입량, 유출량, 변화량 등을 파악하여 그 합계가 정확히 맞도록 분석하는 것의 의미',
    hNm: '물 수지분석',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水收支分析',
    eNm: 'water budget analysis',
    explain:
      '물의 유입량, 유출량, 변화량 등을 파악하여 그 합계가 정확히 맞도록 분석하는 것의 의미',
    hNm: '물 수지분석',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '水再利用',
    eNm: 'water reuse',
    hNm: '물 재이용',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '水再利用',
    eNm: 'water reuse',
    hNm: '물 재이용',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '水再利用施設',
    eNm: 'water reuse facility',
    hNm: '물 재이용시설',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '水再利用施設',
    eNm: 'water reuse facility',
    hNm: '물 재이용시설',
    rgsdt: '2023-09-27',
  },
  {
    eNm: 'water application efficiency',
    hNm: '물 활용 효율',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'water application efficiency',
    hNm: '물 활용 효율',
    rgsdt: '2023-09-18',
  },
  {
    eNm: 'water application efficiency',
    hNm: '물 활용 효율',
    rgsdt: '2023-09-18',
  },
  {
    eNm: 'water landscape',
    hNm: '물경관',
    rgsdt: '2016-11-24',
  },
  {
    eNm: 'water landscape',
    hNm: '물경관',
    rgsdt: '2023-09-14',
  },
  {
    eNm: 'water hardness',
    explain:
      '물에 함유되어 있는 칼슘이온 (Ca2+)과 마그네슘이온 (Mg2+)의 농도의 합에 해당하는 값을 탄산칼슘 농도로 나타내는 수질 지표이다(mg/L CaCO3)',
    hNm: '물경도',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'hydroeconomic analysis',
    explain:
      '수자원분야의 사업을 비용과 편익을 따져 수익률을 계산하여 사업의 경제적 타당성을 분석하는 방법',
    hNm: '물경제분석',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'fish lock',
    hNm: '물고기 갑문',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'fish ladder',
    explain: '낙차를 두어 계단형식으로 만들어진 어도',
    hNm: '물고기 사다리',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'fish ladder',
    explain: '낙차를 두어 계단형식으로 만들어진 어도',
    hNm: '물고기 사다리',
    rgsdt: '2023-10-17',
  },
  {
    eNm: 'water mould',
    explain:
      '물곰팡이는 난균강의 물곰팡이목 또는 사프롤레그니아목(Saprolegniales)에 속하는 곰팡이의 총칭',
    hNm: '물곰팡이',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'water management',
    hNm: '물관리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水管理組織',
    eNm: 'water management organization',
    explain: '수자원의 확보 분배, 홍수조절 등을 관리하는데 주체가 되는 조직',
    hNm: '물관리조직',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'channel network',
    explain: '수계도의 유로폭을 무시하고 선으로 연결한 망',
    hNm: '물길망',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水華現象',
    eNm: 'water bloom',
    explain:
      '부영양화 된 호수에 조류가 대량 증식하여 물 표면의 색깔이 녹색이나 갈색으로 변한 것',
    hNm: '물꽃현상',
    rgsdt: '2016-04-15',
  },
  {
    explain: '설계유량 이상의 물이 유입될 때 빠른속도로 배수시키기 위한 시설',
    hNm: '물넘이',
    rgsdt: '2016-11-23',
  },
  {
    explain: '설계유량 이상의 물이 유입될 때 빠른속도로 배수시키기 위한 시설',
    hNm: '물넘이',
    rgsdt: '2023-10-10',
  },
  {
    explain: '설계유량 이상의 물이 유입될 때 빠른속도로 배수시키기 위한 시설',
    hNm: '물넘이',
    rgsdt: '2023-10-10',
  },
  {
    eNm: 'overflow dam',
    explain:
      '일정한 수위 이상일때 마루를 넘어 월류가 가능한 구조로 설치하는 댐',
    hNm: '물넘이댐',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'deversior',
    explain:
      '물넘이는 홍수 시 넘치는 물을 안전하게 유하시켜 저수시설이나 수로를 안전하게 할 수 있는 배수시설',
    hNm: '물넘이둑',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水景施設',
    eNm: 'waterscape facilities for recreation',
    hNm: '물놀이형 수경시설',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '水景施設',
    eNm: 'waterscape facilities for recreation',
    hNm: '물놀이형 수경시설',
    rgsdt: '2023-09-27',
  },
  {
    eNm: 'hydraulic fill dam',
    hNm: '물다짐댐',
    rgsdt: '2016-11-24',
  },
  {
    eNm: 'hydraulic fill dam',
    hNm: '물다짐댐',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '物理氣象學',
    eNm: 'physical meteorology',
    explain: '물리학적으로 기상현상을 설명하려는 기상학의 한 분야',
    hNm: '물리기상학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '物理的 處理',
    eNm: 'physical treatment',
    explain: '원수나 폐수 내의 불순물을 물리적인 작용에 의하여 처리하는 것',
    hNm: '물리적 처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '物理的 透水性',
    eNm: 'physical permeability',
    hNm: '물리적 투수성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '物理的風化',
    eNm: 'physical weathering',
    explain:
      '물과 바람에 의한 침식작용, 온도 변화, 반복되는 동경과 융해 등으로 작용하는 압력에 의해 암석이 잘게 부서지는 현상',
    hNm: '물리적 풍화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '物理的吸着',
    eNm: 'physical adsorption, physisorption',
    explain:
      '흡착결합 중에서 흡착분자와 표면과의 상호작용이 약한 분자간 힘에 의한 것을 말하며, 반데르발스(Vander Waal’s) 흡착이라고도 칭함',
    hNm: '물리적 흡착',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '物理海洋學',
    eNm: 'physical oceanography',
    explain: '해수의 물리적 특성 등을 연구하는 학문',
    hNm: '물리해양학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '物理化學的處理',
    eNm: 'physicochemical treatment',
    explain:
      '물리화학적 처리는 물리적 및 화학적인 조작을 첨가하는 것에 의해 물질, 물질의 성질 또는 에너지상태 등의 변화를 주거나 물로부터 분리 또는 제거하는 조작과정을 칭함',
    hNm: '물리화학적처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '物理化學的處理',
    eNm: 'physicochemical treatment',
    explain:
      '물리화학적 처리는 물리적 및 화학적인 조작을 첨가하는 것에 의해 물질, 물질의 성질 또는 에너지상태 등의 변화를 주거나 물로부터 분리 또는 제거하는 조작과정을 칭함',
    hNm: '물리화학적처리',
    rgsdt: '2023-10-17',
  },
  {
    eNm: 'water seal, water sealing',
    explain:
      '댐 공사 등 시설을 설치할 때 공사구역의 흐름을 막기위해 가설하는 구조물',
    hNm: '물막이',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'coffering',
    explain: '주변 물의 흐름을 막기 위해 만들어지는 구조물',
    hNm: '물막이공',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'closing dyke',
    explain:
      '수중에 수리구조물 설치 시 공사구역의 주변을 일시적으로 막아 외수의 침입을 방지하는 가설 구조물',
    hNm: '물막이둑',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'apron',
    hNm: '물받이',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'drip irrigation, trickle irriqation',
    hNm: '물방울 관개',
    rgsdt: '2016-11-24',
  },
  {
    eNm: 'drip irrigation, trickle irriqation',
    hNm: '물방울 관개',
    rgsdt: '2023-09-14',
  },
  {
    eNm: 'Spray',
    hNm: '물보라',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'water conservation',
    explain: '수자원의 확보와 수질을 보전하는 일',
    hNm: '물보존',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'water deficit country; water shortage country',
    explain:
      '가용수자원량이 부족한 상태, 연간 1인당 가용 가능한 수자원량이 1,700톤 미만인 나라를 물 부족국가라 함',
    hNm: '물부족국가',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'water deficit country; water shortage country',
    explain:
      '가용수자원량이 부족한 상태, 연간 1인당 가용 가능한 수자원량이 1,700톤 미만인 나라를 물 부족국가라 함',
    hNm: '물부족국가',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '水分析',
    eNm: 'water analysis',
    explain:
      '물의 물리적, 화학적, 생물학적 상태를 파악하기 위하여 행하는 모든 분석',
    hNm: '물분석',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'stoplog',
    explain:
      '수문의 양쪽 측벽에 각재를 삽입하여 유량조절을 할 수 있게 만드는 구조물',
    hNm: '물빈지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '洗滌',
    eNm: 'badkwashing by water',
    explain: '불순물을 물로 씻어 없애는 방법',
    hNm: '물세척',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'water consumption , water rate',
    hNm: '물소비(량)',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'consumptive use efficiency',
    hNm: '물소비효율',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '需要',
    eNm: 'water demand',
    explain: '물의 수요시기와 수요량을 기준으로 한 물 소요수량',
    hNm: '물수요',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'water requirement',
    hNm: '물수요량',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'water budget',
    explain:
      '수문순환 과정에서 수량의 유입, 유출, 증발, 침투, 용수공급 등을 전체적으로 비교하여 수량의 과부족을 평가하는 방법',
    hNm: '물수지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水平器',
    eNm: 'water level',
    hNm: '물수평기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水循環',
    eNm: 'hydrologic cycle, water cycle',
    explain:
      '지표와 수면에서의 증발과 강수, 지표면의 침투와 유출 등의 연속적인 과정',
    hNm: '물순환',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水循環',
    eNm: 'hydrologic cycle, water cycle',
    explain:
      '지표와 수면에서의 증발과 강수, 지표면의 침투와 유출 등의 연속적인 과정',
    hNm: '물순환',
    rgsdt: '2023-10-17',
  },
  {
    eNm: 'water fog',
    explain: '비가 내리듯이 짙게 끼는 안개',
    hNm: '물안개',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水構造',
    eNm: 'water structure',
    explain:
      '물은 육각형 고리구조, 오각형 고리구조, 오각형 사슬구조의 화학적 구조로 형성되어 있음',
    hNm: '물의 구조',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水性質',
    eNm: 'water property',
    explain: '증류수는 무색, 투명, 무미·무취의 액체',
    hNm: '물의 성질',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'hydrologic cycle',
    explain: '물이 형태를 바꾸며 지구 표면의 암권, 기권, 수권을 순화하는 것',
    hNm: '물의 순환',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'water compressibility',
    explain: '압력을 단위 증가 또는 단위 감소 시켰을 때 물의 부피변화',
    hNm: '물의 압축률',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '運動學',
    eNm: 'water kinematics',
    explain: '수리학에서 물이 이동할 때의 거동을 다루는 분야',
    hNm: '물의 운동학',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'ion product of water',
    hNm: '물의 이온곱',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'ion product of water',
    hNm: '물의 이온곱',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '水粘性',
    eNm: 'viscosity',
    explain:
      '물의 점성은 유체(기체 또는 액체)가 흐를 때 발생하는 내부적인 마찰이나 저항을 의미',
    hNm: '물의 점성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水精製',
    eNm: 'water refining',
    explain: '물속의 함유된 불순물을 모두 제거하는 것',
    hNm: '물의 정제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水造成',
    eNm: 'water composition',
    explain:
      '물은 두 개의 수소원자와 한 개의 산소로 이루어진 물질이며, 화학식은 H2O',
    hNm: '물의 조성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水充塡率',
    eNm: 'recharge rate',
    explain: '지하수가 단위 시간당 단위 면적으로 함양되는 물의 양',
    hNm: '물의 충전율',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水充塡率',
    eNm: 'recharge rate',
    explain: '지하수가 단위 시간당 단위 면적으로 함양되는 물의 양',
    hNm: '물의 충전율',
    rgsdt: '2023-10-17',
  },
  {
    eNm: 'sphagnum moss',
    explain: '물이끼과에 속하는 연한 녹색의 선류 중의 하나',
    hNm: '물이끼',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'water use charge',
    explain:
      '상수원 지역의 주민지원사업과 수질개선사업의 촉진을 위해 상수원 수질개선 및 주민지원 등에 관한 법률에 따라 부과하는 부담금',
    hNm: '물이용부담금',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'water reclamation',
    explain:
      '오염된 물을 정화하여 재사용하거나 자연계에 존재하는 수체로 돌려보내는 것',
    hNm: '물재생',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'water control',
    hNm: '물조절',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'water mites',
    explain: '절지동문문의 곤충강에 속하며 딱정벌레목의 물에 사는 진드기',
    hNm: '물진드기류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '物質代謝',
    eNm: 'metabolism',
    explain: '생물의 세포에서 생명을 유지하기 위해 일어나는 화학 반응',
    hNm: '물질대사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '物質收支',
    eNm: 'mass balance, material balance',
    explain:
      '어떤 계(system)의 경계면에서 일어나는 물질의 유입과 유출량을 비교하여 내부에 남아있는 물질의 양을 계산하는 것ㄴ',
    hNm: '물질수지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '物質循環',
    eNm: 'matter cycle, matter cycling',
    explain: '특정 물질이 대기, 물 및 토양권을 이동, 순환하는 것',
    hNm: '물질순환',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '物質循環',
    eNm: 'matter cycle, matter cycling',
    explain: '특정 물질이 대기, 물 및 토양권을 이동, 순환하는 것',
    hNm: '물질순환',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '物質移動速度',
    eNm: 'mass transfer rate',
    explain:
      '물질이 계(system)의 한 구성요소로부터 다른 구성요소로 이동하는 속도',
    hNm: '물질이동속도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '物質移動',
    eNm: 'mass transfer',
    explain: '어느 한 물질에서 다른 물질로 그 일부가 이동하는 것',
    hNm: '물질전달',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水處理',
    eNm: 'water treatment',
    explain: '원수를 사용하는 목적에 적합하도록 하는 처리',
    hNm: '물처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水處理',
    eNm: 'water treatment',
    explain: '원수를 사용하는 목적에 적합하도록 하는 처리',
    hNm: '물처리',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '물割當政策',
    eNm: 'water allocation policy',
    hNm: '물할당정책',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水質環境',
    eNm: 'water environment',
    explain: '물의 물질순환 과정으로 이루어지는 환경',
    hNm: '물환경',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Water Environment Governance',
    hNm: '물환경 거버넌스',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'Meuse River valley',
    explain:
      '벨기에의 수도 리즈시 옆 뮤즈강 하구의 공업지대에서 일어난 대기오염에 의한 중독사건',
    hNm: '뮤즈계곡 사건',
    rgsdt: '2016-11-19',
  },
  {
    eNm: 'Meuse River valley',
    explain:
      '벨기에의 수도 리즈시 옆 뮤즈강 하구의 공업지대에서 일어난 대기오염에 의한 중독사건',
    hNm: '뮤즈계곡 사건',
    rgsdt: '2023-10-16',
  },
  {
    eNm: 'Meuse River valley',
    explain:
      '벨기에의 수도 리즈시 옆 뮤즈강 하구의 공업지대에서 일어난 대기오염에 의한 중독사건',
    hNm: '뮤즈계곡 사건',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '美國硬度',
    eNm: 'american hardness',
    explain: '탄산칼슘 농도를 사용하여 경도를 표시하는 것',
    hNm: '미국경도',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '微氣象學',
    eNm: 'micrometeorology',
    explain: '미기상은 지상 1.5m 정도의 기층에서 일어나는 작은 규모의 기상',
    hNm: '미기상학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微氣候',
    eNm: 'microclimate',
    explain: '소기후보다 작은 범위의 기후',
    hNm: '미기후',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微氣候學',
    eNm: 'microclimatology',
    explain:
      '대기의 지표층 근처 내의 기상 변수들의 장기간의 통계를 다루는 기후학이 분야',
    hNm: '미기후학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '***面',
    eNm: 'slickensides',
    explain: '단층 이동에 의해 연마된 단단한 암석의 윤기나는 면',
    hNm: '미끄럼면',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'minamata disease',
    explain: '어패류에 축적된 유기수은을 경구 섭취함으로써 발생하는 신경질환',
    hNm: '미나마따병',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Minamata disease',
    explain:
      '일본 구마모토현 미나마타시에서 발생한 수은에 의한 공해병, 또는 이와 유사한 유형의 공해병을 통칭하는 경우에도 사용한다.',
    hNm: '미나마타병',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '微量營養素',
    eNm: 'micronutrient',
    hNm: '미량 영양소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微量元素',
    eNm: 'minor element, micronutrient',
    explain: '특정 물질계에서 주요 구성원소가 아닌 원소의 총칭',
    hNm: '미량원소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '未普及地域',
    eNm: 'non-water supply district; unserved area',
    hNm: '미보급지역',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '微粉炭',
    eNm: 'coal dust, pulverized coal',
    explain: '입경 3mm 이하의 석탄',
    hNm: '미분탄',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'fibric material',
    hNm: '미분해 유기잔재',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '微砂質沙',
    eNm: 'silty sand',
    hNm: '미사질 모래',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微砂質壤土',
    eNm: 'silty loam, silty clay loam',
    hNm: '미사질(식)양토',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微砂質埴土',
    eNm: 'silty clay',
    explain: '점토함량이 25~45%, 미사가 45% 이상인 토양',
    hNm: '미사질식토',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微生物 ',
    eNm: 'microorganism',
    explain: '매우 작아서 눈으로 볼 수 없는 생물',
    hNm: '미생물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微生物結合擔體',
    eNm: 'microbe-bound carrier',
    explain: '미생물을 담체표면 또는 세공 중에 자연발생적으로 부착시킨 담체',
    hNm: '미생물 결합담체',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微生物付着擔體',
    eNm: 'microbe-attached carrier',
    explain: '미생물을 담체표면 또는 세공 중에 자연발생적으로 부착시킨 담체',
    hNm: '미생물 부착담체',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微生物分解性',
    eNm: 'biodegradability',
    explain: '폐수 중의 유기물이 미생물에 의하여 분해를 받는 정도',
    hNm: '미생물 분해성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微生物分解性',
    eNm: 'biodegradability',
    explain: '폐수 중의 유기물이 미생물에 의하여 분해를 받는 정도',
    hNm: '미생물 분해성',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '微生物生體量',
    eNm: 'microbial biomass',
    explain: '일정 지역 안에 살고 있는 미생물의 총 질량',
    hNm: '미생물 생체량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微生物增殖係數',
    eNm: 'yield coefficient',
    explain: '기질소비속도에 대한 박테리아의 증식속도비',
    hNm: '미생물 증식계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微生物成長曲線',
    eNm: 'microbial growth curve',
    explain: '미생물의 시간에 따른 생장을 그래프로 표시한 것',
    hNm: '미생물성장곡선',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '微生物集團',
    eNm: 'microbial population',
    explain: '일정 토양 부피 또는 질량 안에 살아있는 미생물의 수',
    hNm: '미생물집단',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微細空隙',
    eNm: 'micropore',
    explain: '토양공극 중 모세관 공극을 포함하는 작은 공극',
    hNm: '미세공극',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微細氣泡',
    eNm: 'fine bubble',
    explain:
      '산기식 반응조에서 세라믹제 또는 합성수지제 산기판, 산기통 등으로 구성된 산기장치에서 발생되는 기포',
    hNm: '미세기포',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微細먼지',
    eNm: 'fine dust',
    explain: '눈에 보이지 않을 정도로 작은 먼지',
    hNm: '미세먼지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微細浮遊物質',
    eNm: 'fine suspended material',
    hNm: '미세부유물질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微細浮遊砂',
    eNm: 'fine suspended material',
    hNm: '미세부유사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微細浮遊砂濃度',
    eNm: 'fine suspended material concentration',
    hNm: '미세부유사농도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微細粉塵',
    eNm: 'microscopic dust',
    explain: '마이크로 사이즈의 매우 작은 분진',
    hNm: '미세분진',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'fine screen',
    explain: '유효간격 5mm 이하의 망사체 스크린을 의미',
    hNm: '미세스크린',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'fine screen',
    explain: '유효간격 5mm 이하의 망사체 스크린을 의미',
    hNm: '미세스크린',
    rgsdt: '2023-04-17',
  },
  {
    cNm: '微細濾過',
    eNm: 'microfiltration/microscreen',
    explain:
      '폐수처리 시 폐수처리장의 유입부에 스크린을 설치하여 조류나 미생물 등을 제거하는 방법 중에서 미세입자까지 여과하는 방법',
    hNm: '미세여과',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微細粒子',
    eNm: 'fine particle',
    explain: '입경 10㎛ 이하의 미세한 입자상 물질',
    hNm: '미세입자',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微細粒子濃度',
    eNm: 'particulate matter 10, PM10',
    explain: '입경 10㎛이하의 미세한 입자상 물질의 농도',
    hNm: '미세입자농도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微小空隙',
    eNm: 'micropore',
    explain: '토양공극 중 모세관 공극을 포함하는 작은 공극',
    hNm: '미소공극',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微小動物',
    eNm: 'animalcule',
    explain: '육안으로는 식별이 어려운 현미경으로 볼 수 있는 동물',
    hNm: '미소동물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微小生物相',
    eNm: 'microbiota',
    explain: '직경 0.1㎜이하의 가장 작은 생물',
    hNm: '미소생물상',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微小損失',
    eNm: 'minor loss ',
    explain: '흐름의 단면에 갑작스러운 변화가 생김으로 인해서 발생하는 손실',
    hNm: '미소손실',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微小損失係數',
    eNm: 'minor loss coefficent',
    explain:
      '소손실은 속도수두에 대략 비례하는 것으로 알려져 있는데, 이때의 비례상수를 말함',
    hNm: '미소손실계수',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'microplankton, nanoplankton',
    hNm: '미소플랑크톤',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '微小後生動物',
    eNm: 'micrometazoa',
    explain:
      '1개체의 생물에 1개의 세포로만 이루어지는 원생동물을 제외한 모든 생물',
    hNm: '미소후생동물',
    rgsdt: '2016-04-15',
  },
  {
    explain: '프랑스 알프스에서 지중해로 부는 국지풍의 일종인 활강바람',
    hNm: '미스트랄',
    rgsdt: '2016-11-21',
  },
  {
    explain: '프랑스 알프스에서 지중해로 부는 국지풍의 일종인 활강바람',
    hNm: '미스트랄',
    rgsdt: '2023-10-10',
  },
  {
    eNm: 'micro manometer',
    hNm: '미차액주계',
    rgsdt: '2016-11-24',
  },
  {
    eNm: 'micro manometer',
    hNm: '미차액주계',
    rgsdt: '2023-10-13',
  },
  {
    eNm: 'Michaelis？Menten kinetics',
    hNm: '미카엘-멘텐공식',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'Michaelis？Menten kinetics',
    hNm: '미카엘-멘텐공식',
    rgsdt: '2023-09-27',
  },
  {
    cNm: '微好氣性菌',
    eNm: 'microaerophilic',
    explain:
      '공기 중에서는 산소의 분압이 낮은 상태에서, 수중에서는 용존산소의 농도가 낮은 환경에서 잘 성장하는 세균',
    hNm: '미호기성균',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '敏感度',
    eNm: 'sensitivity',
    explain:
      '자극과 관련하여 유기체가 내외부로부터 오는 자극의 강도 및 변화에 대하여 보이는 반응성',
    hNm: '민감도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '密度 非依存的',
    eNm: 'density independent',
    explain: '개체 또는 개체군의 성장이 자신들의 밀도에 영향을 받지 않는 특성',
    hNm: '밀도 비의존적',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '密度傾斜',
    eNm: 'density gradient',
    explain: '밀도의 연직분포가 급격히 변하는 층',
    hNm: '밀도경사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '密度計',
    eNm: 'densimeter, density gauge',
    explain: '밀도를 측정하는 장치',
    hNm: '밀도계',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '密度勾配遠心分離法',
    eNm: 'density gradient centrifugation',
    explain:
      '시료에 포함되어 있는 밀도가 다른 용액들을 원심력을 사용하여 분리하는 방법',
    hNm: '밀도구배원심분리법',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '密度勾配遠心分離法',
    eNm: 'density gradient centrifugation',
    explain:
      '시료에 포함되어 있는 밀도가 다른 용액들을 원심력을 사용하여 분리하는 방법',
    hNm: '밀도구배원심분리법',
    rgsdt: '2023-09-19',
  },
  {
    cNm: '密度勾配遠心分離法',
    eNm: 'density gradient centrifugation',
    explain:
      '시료에 포함되어 있는 밀도가 다른 용액들을 원심력을 사용하여 분리하는 방법',
    hNm: '밀도구배원심분리법',
    rgsdt: '2023-09-19',
  },
  {
    cNm: '密度勾配遠心分離法',
    eNm: 'density gradient centrifugation',
    explain:
      '시료에 포함되어 있는 밀도가 다른 용액들을 원심력을 사용하여 분리하는 방법',
    hNm: '밀도구배원심분리법',
    rgsdt: '2023-09-19',
  },
  {
    cNm: '密度勾配遠心分離法',
    eNm: 'density gradient centrifugation',
    explain:
      '시료에 포함되어 있는 밀도가 다른 용액들을 원심력을 사용하여 분리하는 방법',
    hNm: '밀도구배원심분리법',
    rgsdt: '2023-09-19',
  },
  {
    cNm: '密度流',
    eNm: 'density current',
    explain: '유수의 흐름에서 밀도차이로 인하여 발생하는 흐름',
    hNm: '밀도류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '密度流',
    eNm: 'density current',
    explain: '유수의 흐름에서 밀도차이로 인하여 발생하는 흐름',
    hNm: '밀도류',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '密度成層',
    eNm: 'stratification',
    hNm: '밀도성층',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'flood tide ',
    explain: '조석에 의해 간조에서 만조로 수위가 높아지는 해수의 이동',
    hNm: '밀물',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'closed well',
    explain: '지표로부터의 오염을 방지하기 위해 밀폐된 형태의 우물',
    hNm: '밀폐우물',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'closed well',
    explain: '지표로부터의 오염을 방지하기 위해 밀폐된 형태의 우물',
    hNm: '밀폐우물',
    rgsdt: '2023-09-27',
  },
  {
    eNm: 'closed well',
    explain: '지표로부터의 오염을 방지하기 위해 밀폐된 형태의 우물',
    hNm: '밀폐우물',
    rgsdt: '2023-09-27',
  },
  {
    eNm: 'foot protection',
    explain: '지하수 속에 있는 건조물의 기초부분을 보호하기 위해 다지는 것',
    hNm: '밑다짐',
    rgsdt: '2016-04-15',
  },
];

export default data_ko_ma;
