let data_ko_pa = [
  {
    cNm: '波 回折',
    eNm: 'wave diffraction',
    explain: '파의 진행에 나타나는 현상',
    hNm: '파 회절',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波高 ',
    eNm: 'wave height',
    explain: '파정과 파곡의 수직 높이차1',
    hNm: '파고 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波高計',
    eNm: 'wave gauge',
    explain: '수면에 발생한 파도의 파고나 주기를 측정하는 장치',
    hNm: '파고계',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波谷',
    eNm: 'wave trough',
    hNm: '파곡',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '破過',
    eNm: 'breakthrough',
    explain:
      '폐수를 활성탄 흡착탑 또는 이온교환탑 같은 곳에서 처리할 때 처리수 중에 처리 대상물질이 누출되어지는 현상',
    hNm: '파과',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '破壞點',
    eNm: 'break point',
    explain:
      '서로 다른 물질이 만나 반응하여 특정물질을 생성할 때 급격한 농도변화가 시작되는 점, 즉, 농도분포선이 변화되는 점을 말하며, 변곡점이라고도 함',
    hNm: '파괴점',
    rgsdt: '2016-04-15',
  },
  {
    cNm: ' 破壞點 鹽素注入',
    eNm: 'break point chlorination',
    explain:
      '염소 소독과정 중 수중에 존재하는 환원성 물질이 주입염소를 소모하며 암모니아성 질소와의 반응으로 인해 클로라민이 형성되고 산화과정을 거쳐 결합잔류염소를 최소화 시키고, 염소주입량에 비례하여 유리잔류염소량이 증가되기 시작하는 점까지 염소를 주입하는 방식을 말함',
    hNm: '파괴점 염소주입',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '破壞點 鹽素注入',
    eNm: 'break point chlorination',
    explain:
      '염소 소독과정 중 수중에 존재하는 환원성 물질이 주입염소를 소모하며 암모니아성 질소와의 반응으로 인해 클로라민이 형성되고 산화과정을 거쳐 결합잔류염소를 최소화 시키고, 염소주입량에 비례하여 유리잔류염소량이 증가되기 시작하는 점까지 염소를 주입하는 방식을 말함',
    hNm: '파괴점 염소주입',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '波動',
    eNm: 'wave motio',
    explain: '진동이 멀리 퍼져나가는 현상',
    hNm: '파동',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波動速度',
    eNm: 'wave velocity',
    hNm: '파동속도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波動力學 ',
    eNm: 'wave mechanics',
    explain: '미시적 현상의 해석이 가능한 양자역학 이론',
    hNm: '파동역학',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'p-nitrophenol method',
    explain:
      '아베렐 노리스법과 함께 지정된 파리티온, 메틸 파라티온 및 EPN 등을 정량 분석할 때 사용하는 방법',
    hNm: '파라니트로페놀법',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'p-nitrophenol method',
    explain:
      '아베렐 노리스법과 함께 지정된 파리티온, 메틸 파라티온 및 EPN 등을 정량 분석할 때 사용하는 방법',
    hNm: '파라니트로페놀법',
    rgsdt: '2023-10-20',
  },
  {
    eNm: 'p-nitrophenol method',
    explain:
      '아베렐 노리스법과 함께 지정된 파리티온, 메틸 파라티온 및 EPN 등을 정량 분석할 때 사용하는 방법',
    hNm: '파라니트로페놀법',
    rgsdt: '2023-10-20',
  },
  {
    eNm: 'paratyphoid',
    explain:
      '파라티푸스균(Salmonella paratyphi)의 감염에 의한 급성 전신성 발열',
    hNm: '파라티푸스',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波浪豫報',
    eNm: 'wave forecasting',
    hNm: '파랑예보',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波浪作用',
    eNm: 'wave action',
    hNm: '파랑작용',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波浪推定',
    eNm: 'wave hindcasting',
    hNm: '파랑추정',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波力',
    eNm: 'wave force',
    hNm: '파력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波面',
    eNm: 'wave front',
    hNm: '파면',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波面',
    eNm: 'wave front',
    hNm: '파면',
    rgsdt: '2023-10-20',
  },
  {
    cNm: '波峯',
    eNm: 'wave crest',
    hNm: '파봉',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波峯線法',
    eNm: 'wave crest method',
    hNm: '파봉선법',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'undular hydraulic jump',
    hNm: '파상도수',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'corrugated stainless steel pipe',
    explain: '물결모양의 스테인리스강관을 말하는 것',
    hNm: '파상스테인리스강관',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Parshall flume',
    hNm: '파샬수로',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Parshall flume',
    hNm: '파샬수로',
    rgsdt: '2023-10-19',
  },
  {
    eNm: 'Parshall flume',
    hNm: '파샬플룸 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波速',
    eNm: 'wave velocity',
    hNm: '파속',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '破碎作用',
    eNm: 'cataclasis',
    hNm: '파쇄작용',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '破碎作用',
    eNm: 'cataclasis',
    hNm: '파쇄작용',
    rgsdt: '2023-09-18',
  },
  {
    eNm: 'pascal',
    explain: '압력을 나타내는 SI 단위',
    hNm: '파스칼',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Pascal’s principle',
    explain:
      '밀폐된 용기 속에 담겨 있는 액체의 한쪽 부분에 주어진 압력은 그 세기에는 변함없이 같은 크기로 액체의 각 부분에 골고루 전달된다는 법칙',
    hNm: '파스칼의 원리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波壓 ',
    eNm: 'wave pressure',
    explain: '해안 제방이나 방파제 등의 제체에 작용하는 파랑에 의한 압력',
    hNm: '파압',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'wave energy',
    hNm: '파에너지',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'fouling',
    explain: '막여과에서 유입수 속의 오염물질에 의해 막이 막히는 현상',
    hNm: '파울링',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波屈折',
    eNm: 'wave refraction',
    explain: '서로 다른 매질을 통과할 때 꺾이는 현상',
    hNm: '파의 굴절',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波屈折',
    eNm: 'wave refraction',
    explain: '서로 다른 매질을 통과할 때 꺾이는 현상',
    hNm: '파의 굴절',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '波의 週期',
    eNm: 'wave period',
    hNm: '파의 주기',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Phi index',
    explain: '침투능을 산정할 때 가장 간단하고 편리한 방법 ',
    hNm: '파이지수',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Phi index',
    explain: '침투능을 산정할 때 가장 간단하고 편리한 방법 ',
    hNm: '파이지수',
    rgsdt: '2023-10-19',
  },
  {
    eNm: 'pipe-cleaning method',
    explain:
      '관 내부의 부식등으로 인한 적수발생 문제 등을 해결하기 위해 관을 청소하는 방법',
    hNm: '파이프클리닝공법',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'pilot plant',
    hNm: '파일럿플랜트',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '型採水器',
    eNm: 'pilot type water sampler',
    explain:
      '채수병을 비록하여, 댐, 하천, 호수, 해양에서 측정하거나 수질 생태를 알아보기 위하여 물을 채집하는 장비',
    hNm: '파일롯트형 채수기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '派底面',
    eNm: 'wave base',
    explain: '파도의 운동에 의해 영향을 받은 최대 깊이',
    hNm: '파저면',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '波質量輸送',
    eNm: 'wave mass transport',
    hNm: '파질량 수송',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '派川',
    eNm: 'Branch',
    hNm: '파천',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '派川',
    eNm: 'Branch',
    hNm: '파천',
    rgsdt: '2023-06-29',
  },
  {
    eNm: 'percolation method',
    explain:
      '탈취나 탈색을 하기 위하여 용액을 흡착제의 충전층을 통과시키는 조작',
    hNm: '파코레이션법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波向',
    eNm: 'wave direction',
    explain: '파가 진행하는 방향',
    hNm: '파향',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波向線',
    eNm: 'wave ray',
    hNm: '파향선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '波形',
    eNm: 'wave profile',
    hNm: '파형',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pahoehoe',
    explain:
      '현무암질 용암의 한 종류로 점성이 낮아서 유동성이 높은 용암에서 나타나는 표면이 넓게 나타나는 주름 구조가 나타남.',
    hNm: '파호이호이',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'pahoehoe',
    explain:
      '현무암질 용암의 한 종류로 점성이 낮아서 유동성이 높은 용암에서 나타나는 표면이 넓게 나타나는 주름 구조가 나타남.',
    hNm: '파호이호이',
    rgsdt: '2023-09-18',
  },
  {
    eNm: 'pahoehoe laver',
    explain:
      '반원형의 호를 만들거나 가는 동심원상의 주름을 많이 만드는 고체용암',
    hNm: '파호호용암',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'pahoehoe laver',
    explain:
      '반원형의 호를 만들거나 가는 동심원상의 주름을 많이 만드는 고체용암',
    hNm: '파호호용암',
    rgsdt: '2023-09-18',
  },
  {
    cNm: '波回折',
    eNm: 'wave dirffraction',
    explain: '파의 진행에 나타나는 현상',
    hNm: '파회절',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '板構造應力',
    eNm: 'tectonic stress',
    explain: '대규모의 조산운동을 일으키는 힘',
    hNm: '판구조응력',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'farm pond',
    hNm: '팜폰드',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'farm pond',
    hNm: '팜폰드',
    rgsdt: '2023-06-27',
  },
  {
    eNm: 'packer',
    hNm: '패커',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'packer',
    hNm: '패커',
    rgsdt: '2023-06-27',
  },
  {
    eNm: 'pattern diagram ',
    explain: '지하수 수질의 화학분석 결과를 나타내는 도표의 일종',
    hNm: '패턴다이어그램 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '膨化',
    eNm: 'bulking',
    explain:
      '활성슬러지 공법에서 슬러지의 밀도가 감소하고 응집성이 불량해져 최종침전지에서의 침전분리 효율이 현저히 감소하는 현상',
    hNm: '팽화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '膨化汚泥',
    eNm: 'bulking sludge',
    explain:
      '포기조 내에서 팽화가 일어나, 2차 침전지에서 침전이 제대로 이루어 지지 않는 슬러지',
    hNm: '팽화 슬러지',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pulp mill wastewater',
    hNm: '펄프폐수',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pump  ',
    explain:
      '외부에서 동력을 얻어 액체를 낮은 곳에서 높은 곳으로 이동시키거나, 또는 액압을 저압에서 고압으로 가압하는 기계',
    hNm: '펌프',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pumping flow system',
    explain: '펌프로 가압하여 배수하는 것',
    hNm: '펌프가압식배수방식',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'pump diameter',
    hNm: '펌프구경',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '配水',
    eNm: 'pumping drainage',
    explain: '펌프를 사용하여 과잉배수를 배제하는 것',
    hNm: '펌프배수',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pump valve',
    explain: '개폐를 통해 유량을 제어하는 펌프의 부속',
    hNm: '펌프밸브',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '水頭容量曲線 ',
    eNm: 'pump system head curve',
    hNm: '펌프수두용량곡선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '室',
    eNm: 'pump room',
    explain:
      '펌프 본체, 밸브류, 배관, 유량계, 원동기 등 많은 기기가 설치된 방으로 일반적으로 배관실과 원동기실로 구성',
    hNm: '펌프실',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'actual head of pump, pump actual head',
    hNm: '펌프실양정',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pumping head',
    hNm: '펌프양정',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pump filter',
    hNm: '펌프여과장치',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'pump station',
    explain:
      '처리장으로 원수 또는 하수를 양수하기 위한 펌프와 기타 설비를 포함하는 구조물',
    hNm: '펌프장',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'total head of pump, pump total head',
    hNm: '펌프전양정',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pump shaft power',
    hNm: '펌프축동력',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pump characteristics',
    hNm: '펌프특성',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pump characteristic curve',
    explain: '토출량, 펌프효율, 전양정, 축동력 등의 관계를 나타낸 곡선',
    hNm: '펌프특성곡선',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pump efficeincy',
    explain: '펌프의 이론마력(수동력)의 축 동력에 대한 백분비',
    hNm: '펌프효율',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pumping action',
    hNm: '펌핑액션',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'phenol',
    explain:
      '벤젠고리나 나프탈렌고리 등과 같은 방향족성의 고리에 히드록시기(-OH)기가 치환된 방향족 탄소의 총칭',
    hNm: '페놀',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'phenols',
    explain: '벤젠 고리에 히드록시기(-OH)가 치환된 방향족 탄소 화합물의 종류',
    hNm: '페놀류',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'phenol waste',
    explain: '페놀류가 함유된 폐기물',
    hNm: '페놀폐기물',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'phenolphthalein alkalinity',
    hNm: '페놀프탈레인알칼리도',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'phenolic compound',
    explain: '방향환을 가진 화합물의 총칭',
    hNm: '페놀화합물',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pedon',
    hNm: '페돈',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'fenton treatment',
    explain:
      '오수나 폐수에 과산화수소와 2가의 철염의 펜톤시약의 혼합용액을 사용하여 발생하는 OH기의 산화력으로 유기물을 처리하는 방법',
    hNm: '펜톤처리',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'fenton treatment',
    explain:
      '오수나 폐수에 과산화수소와 2가의 철염의 펜톤시약의 혼합용액을 사용하여 발생하는 OH기의 산화력으로 유기물을 처리하는 방법',
    hNm: '펜톤처리',
    rgsdt: '2023-10-19',
  },
  {
    eNm: 'pelton turbine',
    explain: '고낙차 발전에 사용하는 충동수차의 일종',
    hNm: '펠톤수차',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pelton turbine',
    explain: '고낙차 발전에 사용하는 충동수차의 일종',
    hNm: '펠톤수차',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '偏光',
    eNm: 'polarization',
    explain: '진행방향 중 수직한 평면에서 전기장의 방향이 일정한 빛',
    hNm: '편광',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '偏流',
    eNm: 'drift current, eccentric flow, short circuit flow',
    explain:
      '유입관로에서 침전지와 같은 넓은 면적을 갖는 장소로 물이 흘러들어갈 때, 수로단면이나 벽면형상, 유입방향의 관성력 등에 의해 만들어진 유선의 불균일한 흐름',
    hNm: '편류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '片利共生',
    eNm: 'commensalism',
    explain:
      '생물의 공생 중 한쪽 생물은 이익을 받지만 다른 쪽의 생물은 이익이나 불이익 등 아무런 영향도 받지 않는 관계의 공생',
    hNm: '편리공생',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '鞭毛類',
    eNm: 'flagellates',
    explain: '편모를 가지는 운동하는 단세포생물류',
    hNm: '편모류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '鞭毛蟲類',
    eNm: 'flagellates, Mastigophora',
    explain:
      '원생동물문 편모충상강의 총칭으로 일생 동안에 반드시 편모를 갖는 단세포동물',
    hNm: '편모충류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '偏西風',
    eNm: 'weaterlies',
    explain: '남북 양반구의 중위도지역에서 서에서 동으로 부는 띠모양의 바람',
    hNm: '편서풍',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '偏性嫌氣性 微生物',
    eNm: 'obligate anaerobe, strict anaerobe',
    explain: '유리산소를 포함하는 산소가 전혀 없는 곳에서 살아가는 미생물',
    hNm: '편성혐기성 미생물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '偏性好氣性 微生物',
    eNm: 'obligate aerobe, strict aerobe',
    explain: '유리 산소가 존재하는 데에서만 생육할 수 있는 미생물',
    hNm: '편성호기성 미생물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '偏心',
    eNm: 'eccentricity',
    explain: '힘이 작용하는 축이 중심(도심)축에서 벗어나 있는 것',
    hNm: '편심',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '偏心井',
    eNm: 'eccentric well',
    explain: '우물의 주변지역 중 일부가 불연속면으로 되어있는 경우',
    hNm: '편심우물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '便益費用分析',
    eNm: 'benefit cost analysis',
    hNm: '편익비용분석',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '便益費用分析',
    eNm: 'benefit cost analysis',
    hNm: '편익비용분석',
    rgsdt: '2023-06-27',
  },
  {
    cNm: '片節',
    eNm: 'Proglottid',
    explain:
      '지네 같이 수 많은 마디로 이루어진 생물의 경부에 이어지는 각 마디의 부분',
    hNm: '편절',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '片害共生',
    eNm: 'amensalism',
    explain:
      '공생을 하는 2종 중 한쪽은 억제되거나 죽지만 다른 한쪽은 해를 입지 않는 관계',
    hNm: '편해공생',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '扁形動物',
    eNm: 'flatworms, Planthelminthes',
    explain:
      '와충(渦蟲)류, 단생(單生)류, 흡충(吸蟲)류, 조충(條蟲)류의 4종류를 포함하는 후생동물문(門)이고, 장외는 체강이 없는 무체강동물',
    hNm: '편형동물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均給水量 ',
    eNm: 'mean water consumption',
    hNm: '평균 급수량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均垂直水理傳導度',
    explain:
      '동일한 토양이나 암석 내에서 수직방향으로 작용하는 수리전도도의 평균',
    hNm: '평균 수직 수리전도도',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '平均水平水理傳導度',
    explain:
      '동일한 토양이나 암석 내에서 수평방향으로 작용하는 수리전도도의 평균',
    hNm: '평균 수평 수리전도도',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '平均水平水理傳導度',
    explain:
      '동일한 토양이나 암석 내에서 수평방향으로 작용하는 수리전도도의 평균',
    hNm: '평균 수평 수리전도도',
    rgsdt: '2023-09-18',
  },
  {
    cNm: '平均粒徑',
    eNm: '50% diameter of soil particle',
    explain: '입도분포곡선에서 중량 백분율의 50%에 해당하는 입경',
    hNm: '평균 입경',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '平均干潮位',
    eNm: 'low water of ordinary mean tide, L.W.O.M.T',
    explain: '대조시 간조위와 소조시 간조위의 평균',
    hNm: '평균간조위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均高水位',
    eNm: 'mean high water level',
    hNm: '평균고수위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均供給量',
    eNm: 'average supply',
    hNm: '평균공급량',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '平均氣溫 ',
    eNm: 'average air temperature',
    explain: '일정 기간동안 어떤 지역의 기온의 산술적 평균값',
    hNm: '평균기온',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均斷面法 ',
    eNm: 'mean section method',
    explain: '하천의 횡당면을 등간격으로 나누어 유량을 구하는 방법',
    hNm: '평균단면법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均單位掃流力',
    eNm: 'mean unit tractive force',
    explain: '개수로에서 수로바닥과 양측 벽에 작용하는 마찰응력의 평균치',
    hNm: '평균단위 소류력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均大氣壓',
    eNm: 'normal pressure',
    explain: '지구 대기압의 평균치',
    hNm: '평균대기압',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均對流圈界面',
    eNm: 'mean tropopause',
    explain: '대류권계면의 평균 고도',
    hNm: '평균대류권계면',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均煤塵濃度',
    eNm: 'mean dust concentration',
    hNm: '평균매진농도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均水理深',
    eNm: 'hydraulic mean depth',
    explain:
      '수면폭에 대한 평균 수심으로, 개수로의 유수단면적(통수단면)을 수면폭으로 나눈 값',
    hNm: '평균수리심',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均水深',
    eNm: 'mean depth',
    explain: '통수단면적을 수면폭으로 나눈 값',
    hNm: '평균수심',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均水位',
    eNm: 'mean water level',
    hNm: '평균수위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均汚泥滯留時間',
    eNm: 'mean cell residence time(MCRT)',
    explain:
      '활성슬러지의 제어인자를 제안한 것으로 폭기조와 최종침전지에 머무는 시간을 산술 평균한 값',
    hNm: '평균슬러지체류시간',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均流量',
    eNm: 'mean flow',
    explain: '어느 시간간격의 유량관측치의 평균',
    hNm: '평균유량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均流速',
    eNm: 'mean velocity',
    explain:
      '수로의 단면의 각 지점에서의 유속의 평균으로 총유량을 통수단면적으로 나눈 값',
    hNm: '평균유속',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均流速公式',
    eNm: 'mean velocity formula',
    explain: '관수로와 개수로에서 흐르는 물의 평균유속을 구하는 공식',
    hNm: '평균유속공식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均低水位',
    eNm: 'mean low water level',
    hNm: '평균저수위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均低潮位',
    eNm: 'mean low water level',
    hNm: '평균저조위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均潮差',
    eNm: 'mean tide range',
    hNm: '평균조차',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均透過損失',
    eNm: 'mean transmission loss',
    hNm: '평균투과손실',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均波高',
    eNm: 'average wave height',
    hNm: '평균파고',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均抗力係數',
    eNm: 'mean drag coefficient',
    explain:
      '유체와 고체와의 경계층에서의 총 항력은 흐름의 동수압과 단면적의 곱에 비례하는데, 이때의 비례상수',
    hNm: '평균항력계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均海面',
    eNm: 'mean sea level, MSL',
    explain:
      '해수면 변화의 전체 주기동안 일정 간격으로 측정한 해면의 높이를 평균한 것.',
    hNm: '평균해면',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平均海面',
    eNm: 'mean sea level, MSL',
    explain:
      '해수면 변화의 전체 주기동안 일정 간격으로 측정한 해면의 높이를 평균한 것.',
    hNm: '평균해면',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '平年降水量',
    eNm: 'normal annual precipitation',
    hNm: '평년강수량 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平水量',
    eNm: 'ordinary flow',
    hNm: '평수량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平水位',
    eNm: 'ordinary water level',
    explain:
      '어떤 기간에 관측된 수위 중, 그 수위보다 높은 수위와 낮은 수위의 횟수가 같게 되는 수위',
    hNm: '평수위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平地區域',
    eNm: 'Plain District',
    hNm: '평지구역',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '平地區域',
    eNm: 'Plain District',
    hNm: '평지구역',
    rgsdt: '2023-06-27',
  },
  {
    cNm: '平行式埠頭',
    eNm: 'marginal wharf',
    hNm: '평행식부두',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平衡傾斜',
    eNm: 'equilibrium slop',
    explain: '세굴과 퇴적으로 인한 하상경사의 변화가 없는 하천경사',
    hNm: '평형경사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平衡洗掘',
    eNm: 'equilibrium scour',
    hNm: '평형세굴',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平衡河床',
    eNm: 'equilibrium riverbed',
    hNm: '평형하상',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '平衡河川',
    eNm: 'stream in equilibrium',
    hNm: '평형하천',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '平衡河川',
    eNm: 'stream in equilibrium',
    hNm: '평형하천',
    rgsdt: '2023-06-27',
  },
  {
    cNm: '廢孔',
    eNm: 'abandoned well ',
    hNm: '폐공',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '廢棄物',
    eNm: 'waste',
    explain:
      '폐기물관리법에 의하면 쓰레기, 연소재, 오니, 폐유, 폐산, 폐알칼리 및 동물의 사체 등으로서 사람의 생활이나 사업 활동에 필요하지 않게 된 물질 ',
    hNm: '폐기물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '廢棄物資源化技術',
    eNm: 'nesauace necauey technology from waste',
    hNm: '폐기물자원화기술',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '廢棄物再循環',
    eNm: 'solid waste recycling',
    explain: '폐기물을 유용한 자원으로 취급하여 재사용하는 것',
    hNm: '폐기물재순환',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '廢棄物處分',
    eNm: 'waste disposal',
    explain:
      '폐기물의 소각(燒却)·파쇄(破碎) 등 중간처분과 매립 등 최종처분으로 규정',
    hNm: '폐기물처분',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '閉塞前線',
    eNm: 'occluded front',
    explain:
      '중위도 저기압이 발달함에 따라  한랭전선과 온난전선이 서로 접근한 후 한랭전선이 온난전선 밑으로 겹쳐질 때 형성되는 전선',
    hNm: '폐색전선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '閉鎖性水域',
    eNm: 'closed water area',
    explain: '물의 순환이 원활하지 못하여 오염 및 정체가 쉬운 수역',
    hNm: '폐쇄성수역',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'closed impeller pump',
    hNm: '폐쇄임펠러펌프',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '廢水',
    eNm: 'wastewater',
    explain:
      '고체나 액체성의 폐기물이 혼입되어 그대로 사용 못하고 별도의 처리를 해야 하는 물을 의미',
    hNm: '폐수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '廢水無放流排出施設',
    hNm: '폐수무방류배출시설',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '廢水無放流排出施設',
    hNm: '폐수무방류배출시설',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '廢水排出施設',
    eNm: 'wastewater discharging facility',
    explain:
      '수질오염물질을 배출하는 시설물·기계·기구 및 기타 물체로서 환경부령으로 정한 것',
    hNm: '폐수배출시설',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '廢水試驗',
    eNm: 'wastewater examination',
    explain: '폐수 성상 등을 시험하는 것',
    hNm: '폐수시험',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '廢水再生',
    eNm: 'wastewater reclamation',
    explain: '재사용이 가능할 정도로 폐수정화를 수행하는것',
    hNm: '폐수재생',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '廢水處理',
    eNm: 'wastewater treatment',
    explain:
      '폐수 중의 유해물질을 제거하기 위한 방법. 처리의 정도에 따라서 1차 처리, 2차 처리, 3차 처리로 구분됨',
    hNm: '폐수처리',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'wasted alkali',
    explain:
      ' pH가 12.5 이상인 강알칼리로써 부식성이 강하고 주변 환경을 오염시킬 수 있으며 지정폐기물로 지정되어 있음',
    hNm: '폐알칼리',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'waste heat boiler',
    hNm: '폐열보일러',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '廢油',
    eNm: 'waste oil',
    explain:
      '폐기물 중 기름성분이 5%이상 함유된 것을 폐유라 하며 폐기물 관리법에 따라 (1) 윤활유계 (2) 윤활유 이외의 광물류(연료유, 세정유) (3) 동식물계류 및 타르·피치(pitch)류 등 세 가지로 분류함',
    hNm: '폐유',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '廢油處理',
    eNm: 'bilge treatment',
    explain:
      '이미 사용되어져 불순물이 유입되었거나 오염되어 더 이상 사용할 수 없는 기름을 처리하는 것을 의미',
    hNm: '폐유(선박폐유) 처리 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '廢油 處理施設',
    eNm: 'bilge treatment facility',
    explain: '폐유의 처리를 목적으로 설치된 시설',
    hNm: '폐유(선박폐유) 처리시설',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '廢合回路方程式',
    eNm: 'Loop Equation',
    hNm: '폐합회로방정식',
    rgsdt: '2016-11-26',
  },
  {
    cNm: '廢合回路方程式',
    eNm: 'Loop Equation',
    hNm: '폐합회로방정식',
    rgsdt: '2023-06-26',
  },
  {
    eNm: 'regeneration of spent carbon',
    explain:
      '입상의 폐활성탄에 흡착된 유기물을 소각하면서 미착성을 회복시켜 폐활성탄을 반복 사용하는 것',
    hNm: '폐활성탄의 재생',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '暴(曝)氣',
    eNm: 'aeration',
    explain:
      '수처리 공정에서 물과 공기를 잘 접촉시켜 액체에 산소를 공급하는 조작',
    hNm: '포기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '飽氣帶',
    eNm: 'saturated zone',
    hNm: '포기대',
    rgsdt: '2023-06-27',
  },
  {
    cNm: '飽氣帶',
    eNm: 'saturated zone',
    hNm: '포기대',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '包絡線方法',
    eNm: 'envelope method',
    hNm: '포락선방법',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '包絡線方法',
    eNm: 'envelope method',
    hNm: '포락선방법',
    rgsdt: '2023-06-26',
  },
  {
    eNm: 'formalin',
    explain:
      '포름알데히드의 수용액이며, 보통 약 35% 용액을 이것에 안정제로서 0∼15%의 메탄올이 들어 있음',
    hNm: '포르말린',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '泡沫分離法',
    eNm: 'foam separation',
    hNm: '포말분리법',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '飽水帶',
    eNm: 'saturated with water',
    hNm: '포수대',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '飽水帶',
    eNm: 'saturated with water',
    hNm: '포수대',
    rgsdt: '2023-06-27',
  },
  {
    eNm: 'phostrip process',
    hNm: '포스트립공법',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'poise',
    hNm: '포이즈',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'point gague',
    hNm: '포인트 게이지',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'point gague',
    hNm: '포인트 게이지',
    rgsdt: '2023-06-26',
  },
  {
    cNm: '圃場排水',
    eNm: 'field drainage',
    hNm: '포장배수',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '圃場排水',
    eNm: 'field drainage',
    hNm: '포장배수',
    rgsdt: '2023-06-26',
  },
  {
    cNm: '包裝水力',
    eNm: 'hydro-power potential',
    explain: '하천이 가진 잠재적 수력발전능력',
    hNm: '포장수력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '飽和',
    eNm: 'saturation',
    hNm: '포화',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '飽和',
    eNm: 'saturation',
    hNm: '포화',
    rgsdt: '2023-06-26',
  },
  {
    cNm: '飽和曲線',
    eNm: 'saturation curve',
    explain: '포화 토양의 밀도와 함수비 사이의 관계를 나타내는 곡선',
    hNm: '포화곡선',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '飽和空氣',
    eNm: 'saturated air',
    explain: '특정 온도에서 수분을 최대로 포함하고 있을 때의 공기',
    hNm: '포화공기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '飽和斷熱減率',
    eNm: 'saturation-adiabatic lapse',
    explain:
      '공기를 평형상태의 대기 중 포화단열과정으로 상승시켰을 때 온도가 고도에 반비례하여 감소하는 비율',
    hNm: '포화단열감률',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '飽和帶 ',
    eNm: 'zone of saturation ',
    explain:
      '토양 또는 암석중의 공극들이 지층에서의 대기압보다 높은 압력을 가진 물에 의해서 채워져 있는 부분',
    hNm: '포화대 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '飽和度 ',
    eNm: 'degree of saturation',
    explain:
      '최고로 들어갈 수 있는 양과 비교하여 현재의 양을 백분율로 나타낸 것',
    hNm: '포화도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '飽和度 ',
    eNm: 'degree of saturation',
    explain: '토양 속의 공극 중 물이 차지하고 있는 비율',
    hNm: '포화도 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '飽和水',
    eNm: 'saturated water',
    hNm: '포화수',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '飽和水蒸氣壓',
    eNm: 'saturated water vapor pressure',
    explain: '특정 온도에서 공기가 최대의 수증기에 의한 압력',
    hNm: '포화수증기압',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '飽和濕度',
    eNm: 'saturation humidity',
    explain: '특정 온도에서 특정 부피의 공기가 가질 수 있는 최대 수증기량',
    hNm: '포화습도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '飽和壓力',
    eNm: 'saturation pressure',
    explain: '어떤 온도에서 가스가 포화상태가 되는 압력',
    hNm: '포화압력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '飽和液線',
    eNm: 'saturation liquid line',
    explain: '액체 내부의 증기가 기포로 변하기 직전의 상태의 액선',
    hNm: '포화액선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '飽和溫度',
    eNm: 'saturation temperature',
    explain: '물의 증발이 더 이상 진행되지 않는 온도',
    hNm: '포화온도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '飽和溶液',
    eNm: 'saturated solution',
    explain:
      '용질이 일정한 온도에서 일정량의 용매에 최대로 녹아 더 이상 녹을 수 없는 상태의 용액을 말함',
    hNm: '포화용액',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '飽和溶存酸素量',
    eNm: 'saturation dissolved oxygen',
    explain: '물속에 산소가 최대로 녹을 수 있는 산소량',
    hNm: '포화용존산소량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '飽和指數',
    eNm: 'saturation index',
    explain:
      '용액이 특정한 물질에 대하여 과포화나 불포화, 평형상태에 있는가를 정의하는 변수',
    hNm: '포화지수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '飽和浸出液',
    eNm: 'saturation extract',
    explain: '포화상태의 토양으로부터 침출한 물을 가리키는 용어이다.',
    hNm: '포화침출액',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '飽和土壤',
    eNm: 'saturation soil',
    hNm: '포화토양',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '飽和含水率',
    eNm: 'percentage of saturated water content',
    explain:
      '일정 조건의 상태량 변화에 의해 함수율이 일정 한도에 멈추고 상태량을 변화 시켜도 그 이상 증가하지 않을 때의 함수율',
    hNm: '포화함수율',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'capture zone',
    explain: '양수정 주위에서 우물에 지하수를 공급하는 지역을 말한다.',
    hNm: '포획구간',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '曝氣,',
    eNm: 'aeration',
    explain: '수돗물의 정수나 하수처리할 때 물속에 공기를 주입하는 것',
    hNm: '폭기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '曝氣 酸化池',
    eNm: 'aerated lagoon',
    explain: '호기성 분해를 공기를 주입시켜 분해를 촉진시키는 형태의 산화지',
    hNm: '폭기(포기)산화지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '曝氣水,',
    eNm: 'aerated water',
    explain:
      '수중의 공기를 흡입하거나 공중에 물을 살포하는 등 강제적으로 공기와 물을 접촉시켜 산소를 충분히 용해시킨 물',
    hNm: '폭기(포기)수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '曝氣時間',
    eNm: 'aeration time',
    explain: '하수 또는 폐수의 처리에서 폐수가 폭기조 내에 머무는 시간',
    hNm: '폭기(포기)시간',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '曝氣槽 ',
    eNm: 'aeration tank',
    explain:
      '활성슬러지법으로 하수 및 폐수를 처리할 때 미생물을 이용하여 유기물을 처리하기 위해 공기가 공급되는 반응조',
    hNm: '폭기(포기)조',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '曝氣機',
    eNm: 'aeration  instrument',
    hNm: '폭기기',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '曝氣時間',
    eNm: 'aeration time',
    explain: '활성슬러지와 폐수가 폭기조에 체류하는 시간',
    hNm: '폭기시간',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '曝氣裝置',
    eNm: 'aerator',
    explain: '폭기를 효율적으로 행하는 장치',
    hNm: '폭기장치',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '曝氣槽',
    eNm: 'aeration tank',
    explain:
      '수처리를 위한 생물학적 반응을 촉진하기 위해 산소를 공급하는 반응조',
    hNm: '폭기조',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '曝氣處理',
    eNm: 'aeration treatment',
    explain: '상수원에 공기를 불어 넣는 것',
    hNm: '폭기처리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '曝氣沈砂池',
    eNm: 'aeration grit chamber',
    explain: '산기장치를 설치하여 입자를 분리하는 침사지 ',
    hNm: '폭기침사지',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '曝氣塔',
    eNm: 'aeration tower',
    explain: '처리되는 물에 산소를 공급하기 위해 만들어진 탑상 구조물',
    hNm: '폭기탑',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'aeration tank',
    explain: '활성오니법에서 산소를 공급하여 오수를 정화하는 반응조이다.',
    hNm: '폭기탱크',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'torrent',
    hNm: '폭류계곡',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '暴雪',
    eNm: 'heavy snowfall',
    explain: '짧은 시간 동안 많이 내리는 눈',
    hNm: '폭설',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '暴風海溢',
    eNm: 'storm surge',
    explain:
      '태풍이나 심한 폭풍, 또는 강한 저기압의 영향으로 해안에서 해수면이 이상적으로 높아지는 현상',
    hNm: '폭풍해일',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pontoon',
    hNm: '폰툰',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'polyethylene pipe',
    explain: '에틸렌을 사슬모양으로 중합시켜 만든 폴리에틸렌으로 제조한 도관',
    hNm: '폴리에틸렌관',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'Polyvinyl Chloride',
    explain: '염화비닐 수지로도 불리우는 염화비닐의 중합체',
    hNm: '폴리염화비닐',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'poly chlorinatd biphenyl; PCB',
    explain: '염소가 치환되어 들어간 물질의 총칭',
    hNm: '폴리염화비페닐',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'poly chlorinatd biphenyl; PCB',
    explain: '염소가 치환되어 들어간 물질의 총칭',
    hNm: '폴리염화비페닐',
    rgsdt: '2023-10-10',
  },
  {
    eNm: 'polyaluminium chloride, PAC, PACl',
    explain:
      '염산과 알루미늄으로 만들어진 중합체로 합성고분자 응집제 종류 중의 하나',
    hNm: '폴리염화알루미늄',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'fohn',
    explain:
      '바람이 산을 타고 올라가면서 단열팽창하여 공기의 온도가 하강하여 응결되고 구름이 형성되어 비를 내리게 하는 현상',
    hNm: '푄',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'fohn',
    explain:
      '바람이 산을 타고 올라가면서 단열팽창하여 공기의 온도가 하강하여 응결되고 구름이 형성되어 비를 내리게 하는 현상',
    hNm: '푄',
    rgsdt: '2023-10-19',
  },
  {
    eNm: 'foehn cloud',
    explain: '푄현상에 의해서 단열냉각에 의해 만들어지는 구름',
    hNm: '푄 구름',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '標高',
    eNm: 'elevation',
    explain: '수준기준면으로부터 관측점까지 중력방향을 따라 관측한 연직거리',
    hNm: '표고',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '標高面積曲線',
    eNm: 'elevation-area curve',
    hNm: '표고면적곡선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '標高別 容量曲線',
    eNm: 'elevation-capacity curve',
    hNm: '표고별 용량곡선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面境界層',
    eNm: 'surface boundary layer',
    hNm: '표면경계층',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面排水',
    eNm: 'surface drainage',
    explain:
      '땅 속으로 물의 침투를 방지하기 위해 옹벽의 배면이나 전면의 강우수나 유입수를 지표에 둔 불투수층과 배수구로 배수하는 것',
    hNm: '표면배수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '水面負荷',
    eNm: 'overflow rate,surface loading',
    explain: '침전지 등에서 처리수의 단위 면적당, 단위 시간당 흐르는 수량',
    hNm: '표면부하',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面洗滌',
    eNm: 'surface washing',
    explain:
      '역류세척을 할 때 동시에 사면토에서 압력정수를 분사하여 여과층의 표면을 세척하는 것',
    hNm: '표면세척',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面濾過',
    eNm: 'surface filtration',
    explain: '여층의 상층부에서만 현탁물질을 제거하는 여과 방법',
    hNm: '표면여과 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面映像流速計',
    eNm: 'surface image velocimetry, SIV',
    explain:
      '비접촉식 유속 측정 장치로 홍수시에 수면의 영상을 촬영하여 하천 수면 유속측정에 유용하게 사용가능',
    hNm: '표면영상유속계',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面流速',
    eNm: 'surface velocity',
    hNm: '표면유속',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面流出',
    eNm: 'surface run-off',
    hNm: '표면유출',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面凝結',
    eNm: 'surface condensation',
    explain: '천장이나 마루 등 물체의 표면에 생기는 이슬',
    hNm: '표면응결',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面應力 ',
    eNm: 'surface stress',
    explain: '재료 외부표면에 발생하는 응력',
    hNm: '표면응력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面張力',
    eNm: 'surface tension',
    explain:
      '액체가 가능한 최소의 표면적을 유지하기 위하여 스스로 수축하는 힘의 성질',
    hNm: '표면장력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面張力計 ',
    eNm: 'tensiometer ',
    hNm: '표면장력계 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面張力波',
    eNm: 'capillary wave',
    explain:
      '표면장력의 영향이 중력의 영향보다 커 유체의 자유표면위에 생기는 파',
    hNm: '표면장력파',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面張力波',
    eNm: 'capillary wave',
    explain:
      '표면장력의 영향이 중력의 영향보다 커 유체의 자유표면위에 생기는 파',
    hNm: '표면장력파',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '表面 遮水壁',
    eNm: 'surface curtain wall',
    explain: '제체내로 물이 침투하는 것을 막기 위한 벽',
    hNm: '표면차수벽',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面抗力',
    eNm: 'surface drag, skin friction',
    hNm: '표면항력',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面活性劑',
    eNm: 'surface active agent, surfactant',
    explain:
      '저농도에서 뚜렷한 표면 활성을 나타내는 물질 중에, 특히 계면 현상의 조절에 사용되는 것',
    hNm: '표면활성제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表面效果',
    eNm: 'surface effect',
    hNm: '표면효과',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '漂砂 ',
    eNm: 'littoral drift',
    explain: '연안류에 의해 이동하는 모래입자',
    hNm: '표사',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'littoral process',
    hNm: '표사과정',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'littoral zone',
    hNm: '표사대',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'littoral material',
    hNm: '표사물질',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '漂砂移動',
    eNm: 'littoral movement',
    hNm: '표사이동',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '漂砂特性',
    eNm: 'littoral characteristics',
    hNm: '표사특성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '表水層',
    eNm: 'epilimnion',
    explain:
      '호소(湖沼)의 성층수의 하나로 표층에 가까우며 수온의 연직차가 적고 거의 등온의 수층',
    hNm: '표수층',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '標準貫入試驗 ',
    eNm: 'standard penetration',
    explain: '토양의 상대밀도와 지반의 지지력 추정 등을 파악하기 위한 시험법',
    hNm: '표준관입시험 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '標準大機',
    eNm: 'standard atmosphere',
    explain:
      '전 지구에서 관측한 기온이나 기압 등의 고도 분포를 실제 대기의 평균 상태와 비슷하도록 단순한 형태로 만든 기준대기 모델',
    hNm: '표준대기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '標準撒水廬床法',
    eNm: 'standard trickling filters',
    explain:
      '미생물군의 작용에 의하여 폐수 중의 유기물을 처리하는 생물학적 처리방법으로, 도시의 2차 처리에 주로 사용하는 폐수처리 방법',
    hNm: '표준살수여상법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '標準狀態 ',
    eNm: 'standard condition',
    hNm: '표준상태',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '標準設計降雨量',
    eNm: 'standard project storm, SPS',
    explain: '하천과 수리시설물의 설계 시 이용하는 계획강우량',
    hNm: '표준설계강우량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '標準設計洪水量',
    eNm: 'standard project flood, SPF',
    explain:
      '표준설계계획강우량을 강우-유출관계 해석법을 통해 산정한 설계홍수량',
    hNm: '표준설계홍수량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '標準試藥',
    eNm: 'standard reagent',
    explain: '용량 분석에 사용하는 시약',
    hNm: '표준시약',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '標準流域法',
    eNm: 'index area method',
    hNm: '표준유역법',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '標準流域法',
    eNm: 'index area method',
    hNm: '표준유역법',
    rgsdt: '2023-06-26',
  },
  {
    cNm: '標準節',
    eNm: 'standard sieve',
    hNm: '표준체',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '標準遞減曲線',
    eNm: 'normal recession curve',
    hNm: '표준체감곡선',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '標準遞減曲線',
    eNm: 'normal recession curve',
    hNm: '표준체감곡선',
    rgsdt: '2023-06-26',
  },
  {
    cNm: '標準逐次法',
    eNm: 'standard step method',
    explain: '부등류의 수면형을 산정할 때 사용하는 방법',
    hNm: '표준축차법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '標準侵入曲線',
    eNm: 'standard infiltration curve',
    hNm: '표준침입곡선',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '標準侵入曲線',
    eNm: 'standard infiltration curve',
    hNm: '표준침입곡선',
    rgsdt: '2023-06-26',
  },
  {
    cNm: '標準偏差',
    eNm: 'standard deviation',
    explain: '분산의 제곱근',
    hNm: '표준편차',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '標準活性汚泥法',
    eNm: 'conventional activated sludge',
    explain: '활성 슬러지법을 이용한 하수 처리의 기본방식',
    hNm: '표준활성슬러지법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '標準活性汚泥法',
    eNm: 'conventional activated sludge',
    explain: '활성 슬러지법을 이용한 하수 처리의 기본방식',
    hNm: '표준활성슬러지법',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '表土',
    eNm: 'surface soil , topsoil',
    explain: '토양층의 최상부 20cm 정도를 구성하는 층',
    hNm: '표토',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'Fourier analysis',
    explain:
      '주파수 분석 방법으로 시계열 자료에 어떤 주파수 성분들이 영향을 미치는지 분석하는 수학적 방법',
    hNm: '푸리에분석',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'Poisson’s equation',
    hNm: '푸아송방정식',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'cycle filtration for pool water',
    explain:
      '풀 용수는 4∼5일 사용으로 심하게 오염되므로, 순환여과나 염소멸균을 실시하여 용수를 교체해야 함 ',
    hNm: '풀 용수의 순환 여과',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '風胴試驗',
    eNm: 'wind tunnel test',
    hNm: '풍동시험',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'wind soil erosion',
    explain: '바람에 의해 토양이 침식되는 것',
    hNm: '풍력토양침식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '風上',
    eNm: 'windward',
    explain: '바람이 특정 지점으로 불어오는 방향',
    hNm: '풍상',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '風速',
    eNm: 'wind speed',
    explain: '공기가 단위 시간에 흐르는 속도',
    hNm: '풍속',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '風速計',
    eNm: 'anemometer',
    explain: '바람의 속도(풍속)을 측정하는 기기',
    hNm: '풍속계',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '風俗分布曲線',
    eNm: 'wind profile',
    explain: '지표면에서부터 고도에 따른 바람의 분포를 나타낸 모식도 ',
    hNm: '풍속분포곡선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '風送流',
    eNm: 'wind drift',
    explain: '일정한 바람과 해수면 사이의 마찰에 의해 생기는 해수의 흐름',
    hNm: '풍송류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '風波',
    eNm: 'wind wave',
    explain: '해상에서 바람에 의해 형성되는 파의 일종',
    hNm: '풍파',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '風波',
    eNm: 'wind wave',
    explain: '해상에서 바람에 의해 형성되는 파의 일종',
    hNm: '풍파',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '風下',
    eNm: 'leeward',
    explain: '바람이 불어 가는 방향',
    hNm: '풍하',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Price current meter',
    explain: '유속 측정 장치',
    hNm: '프라이스유속계',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Francis turbin',
    explain: '반동수차의 한 가지 종류',
    hNm: '프란시스수차',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Francis turbin',
    explain: '반동수차의 한 가지 종류',
    hNm: '프란시스수차',
    rgsdt: '2023-10-19',
  },
  {
    eNm: "Freundich's equation",
    explain: '흡착농도와 용존농도의 관계를 나타내는 경험식',
    hNm: '프레운드리히 식',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'propeller pump',
    explain:
      '회전축방향에서 유입된 물을 날개바퀴를 회전하여 회전축에 직각방향으로 물을 내보내는 펌프',
    hNm: '프로펠러 펌프',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'propeller pump',
    explain:
      '회전축방향에서 유입된 물을 날개바퀴를 회전하여 회전축에 직각방향으로 물을 내보내는 펌프',
    hNm: '프로펠러 펌프',
    rgsdt: '2023-10-19',
  },
  {
    eNm: 'propeller water turbine',
    explain: '회전축과 유수의 방향이 동일한 발전용 수차',
    hNm: '프로펠러수차',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'propeller water turbine',
    explain: '회전축과 유수의 방향이 동일한 발전용 수차',
    hNm: '프로펠러수차',
    rgsdt: '2023-10-19',
  },
  {
    eNm: 'proportional weir',
    explain:
      '웨어의 월류수심이 웨어 정부보다 다소 높은 임의의 기준면을 초과하도록 하여 월류유량이 월류수심에 선형적으로 비례하도록 고안된 유량 측정 장치',
    hNm: '프로포셔널 웨어',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'froude number',
    hNm: '프루드수',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'froude number',
    hNm: '프루드수',
    rgsdt: '2023-06-26',
  },
  {
    eNm: 'Plinth',
    hNm: '프린스',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'Plinth',
    hNm: '프린스',
    rgsdt: '2023-06-26',
  },
  {
    eNm: 'playa',
    explain: '건조한 내륙분지에 일시적 호우에 의해 형성된 소금 호수',
    hNm: '플라야',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'playa',
    explain: '건조한 내륙분지에 일시적 호우에 의해 형성된 소금 호수',
    hNm: '플라야',
    rgsdt: '2023-09-18',
  },
  {
    cNm: '淨水作用 ',
    eNm: 'water furification action of fly ash',
    explain:
      '석탄이나 중유 등을 연소했을 때에 생성되는 플라이 애쉬의 미세한 입자호수 중의 오염물을 침전시켜 정수작용을 하는데 큰 역할을 함',
    hNm: '플라이 애쉬의 정수 작용',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Planck’s law',
    explain: '온도 T의 흑체로부터 발생하는 모든 파장의 복사',
    hNm: '플랑크의 법칙',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Planck’s law',
    explain: '온도 T의 흑체로부터 발생하는 모든 파장의 복사',
    hNm: '플랑크의 법칙',
    rgsdt: '2023-10-19',
  },
  {
    eNm: 'Planck’s law',
    explain: '온도 T의 흑체로부터 발생하는 모든 파장의 복사',
    hNm: '플랑크의 법칙',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '浮遊生物',
    eNm: 'plankton',
    explain: '부유생물이라고도 하며 생태적으로 수중생물을 구분한 무리',
    hNm: '플랑크톤',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '調節',
    eNm: 'plankton control',
    explain:
      '저수지 등에서 수도원수를 취수할 때, 플랑크톤조류의 번식을 제어하는 과정',
    hNm: '플랑크톤 조절',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'flash weir',
    hNm: '플래시 보',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'flash weir',
    hNm: '플래시 보',
    rgsdt: '2023-06-29',
  },
  {
    eNm: 'flange joint',
    hNm: '플랜지접합',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'flap weir',
    hNm: '플랩 보',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'flap weir',
    hNm: '플랩 보',
    rgsdt: '2023-06-26',
  },
  {
    eNm: 'plug flow reactor; PFR',
    hNm: '플럭 흐름',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'plug flow reactor; PFR',
    hNm: '플럭 흐름',
    rgsdt: '2023-09-27',
  },
  {
    eNm: 'floor',
    hNm: '플로어',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'floor',
    hNm: '플로어',
    rgsdt: '2023-06-26',
  },
  {
    eNm: 'float valve',
    explain: '액면에 뜨게 한 플로트가 상하로 움직임에 따라 개폐되는 밸브',
    hNm: '플로트 밸브',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'floc',
    explain: '물에 응집제를 혼합시켰을 때 형성되는 응집물',
    hNm: '플록',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '形成',
    eNm: 'flocculation',
    explain:
      '급속교반지에서 생긴 소형 플록(floc)을 대형플록으로 성장시키는 과정',
    hNm: '플록형성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '避難情報地圖',
    eNm: 'evacuation information map',
    hNm: '피난정보지도',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '避難情報地圖',
    eNm: 'evacuation information map',
    hNm: '피난정보지도',
    rgsdt: '2023-06-26',
  },
  {
    cNm: '被覆工',
    eNm: 'lining',
    hNm: '피복공',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '被覆工',
    eNm: 'lining',
    hNm: '피복공',
    rgsdt: '2023-06-26',
  },
  {
    eNm: 'PCB disposal',
    explain:
      '대표적 환경호르몬물질(내분비 교란성 화학물질)의 하나로 다이옥신 생성 원인물질로 알려져 있는 폴리염화비페닐(PCB)을 처리하는 방법',
    hNm: '피시비처리법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '被壓',
    eNm: 'artesian',
    explain: '압력을 받고 있는 상태를 나타내는 용어',
    hNm: '피압',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '被壓帶水層 ',
    eNm: 'confined aquifer ',
    explain: '상하부의 낮은 투수계수를 가지는 지층 사이에 형성된 대수층',
    hNm: '피압대수층 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '被壓水',
    eNm: 'confined ground water',
    hNm: '피압수',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'artesian well',
    hNm: '피압정',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '被壓地下水',
    eNm: 'confined ground water',
    explain:
      '대수층의 상부와 하부가 점토층과 같이 물이 통하지 않는 불투수층으로 되어 있을 때, 대기압보다 큰 압력을 받고 있는 대수층의 지하수를 말한다.',
    hNm: '피압지하수',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '被壓地下水',
    eNm: 'confined ground water',
    explain:
      '대수층의 상부와 하부가 점토층과 같이 물이 통하지 않는 불투수층으로 되어 있을 때, 대기압보다 큰 압력을 받고 있는 대수층의 지하수를 말한다.',
    hNm: '피압지하수',
    rgsdt: '2023-09-18',
  },
  {
    explain: '피압 대수층에 우물을 설치했을 때 우물 내부의 수면을 연결한 면',
    hNm: '피압지하수면',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'piezometer ',
    hNm: '피에조메타 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '超微細浮遊生物',
    eNm: 'picoplankton',
    explain: '0.2∼2m의 범위 내에 있는 플랑크톤 무리',
    hNm: '피코플랑크톤',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pitot tube',
    explain: '유속 측정 장치의 일종',
    hNm: '피토관',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'pitot meter, pitot tube',
    explain: '유속 측정 장치',
    hNm: '피토유속계',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Fick’s law',
    explain: '액체 중에서 용질이 확산하는 것에 대한 법칙',
    hNm: '픽의 법칙',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '必要消毒能',
    eNm: 'disinfectant concentration X Contact time(C.T)',
    explain:
      '살균공정의 운영에 있어서 미생물의 감소속도보다 더 중요한 것은 수중미생물을 사멸시키는데 필요한 소독제의 농도와 접촉시간과의 관계인데 이러한 관계를 나타내는 것이 필요소독능의 개념',
    hNm: '필요소독능',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '筆地 用水量',
    eNm: 'water consumption of pen',
    hNm: '필지 용수량',
    rgsdt: '2016-11-26',
  },
  {
    cNm: '筆地 用水量',
    eNm: 'water consumption of pen',
    hNm: '필지 용수량',
    rgsdt: '2023-06-26',
  },
];

export default data_ko_pa;
