let data_ko_da = [
  {
    cNm: '多境界帶水層',
    eNm: 'multiple-boundary aquifer',
    explain:
      '대수층이 상하부의 지층뿐만 아니라 지표수체 등 여러 개의 수리학적 실체와 경계를 이루고 있는 경우',
    hNm: '다경계대수층',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多孔管',
    eNm: 'perforated pipe',
    explain: '집수 또는 배수를 위해 다수의 구멍을 뚫어 지하에 매설하는 관',
    hNm: '다공관',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多孔排水管',
    eNm: 'perforated drain pipe',
    hNm: '다공배수관',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多孔性散氣裝置',
    eNm: 'porous diffuser',
    explain:
      '산기장치의 하나로, 세라믹이나 수지, 금속 등의 판이나 관에 다수의 기공을 설치하여 비표면적이 높은 미세기포를 사용하여 산소공급 효율을 높인 장치',
    hNm: '다공성 산기장치',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'porous plastics',
    hNm: '다공성플라스틱',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'porous slab-type',
    hNm: '다공슬래브집수장치',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多孔質膜',
    eNm: 'porous membrane',
    explain: '다공질 구조를 가지는 막 뜻 이빨원숭이',
    hNm: '다공질막',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'multi-orifice valve',
    explain:
      '많은 구멍(오리피스)을 가진 가동판과 고정판을 겹쳐서 수압, 유량을 조정하는 슬립밸브',
    hNm: '다공질오리피스밸브',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多孔質支持層',
    eNm: 'porous support, porous layer',
    explain: '지층을 구성하는 입자 내부에 존재하는 공극',
    hNm: '다공질지지층',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多孔集水管',
    eNm: 'perforated collecting pipe',
    hNm: '다공집수관',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多孔板形下部集水裝置',
    eNm: 'porous plate-type underdrain system',
    explain:
      '직경이 수 mm인 입상물질을 강정상태로 형성한 판으로, 저판 상의 지벽에 다공판을 붙여서 집수장치로 사용하는 여과지의 하부집수장치',
    hNm: '다공판형하부집수장치',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多官能性交換體',
    eNm: 'multifunctional exchanger',
    explain: '두 종류 이상의 교환기(交換基)를 갖는 이온교환체',
    hNm: '다관능성교환체',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多段 曝氣法',
    eNm: 'step aeration',
    explain:
      '유입수 내의 질소를 제거하기 위하여 포기조를 여러 개 직렬로 연결한 방법',
    hNm: '다단 포기법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多段階貯留池',
    eNm: 'multiple pond system',
    hNm: '다단계 저류지',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '多段階貯留池',
    eNm: 'multiple pond system',
    hNm: '다단계 저류지',
    rgsdt: '2023-09-12',
  },
  {
    eNm: 'linealized multi-stage model',
    hNm: '다단선형모델',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'linealized multi-stage model',
    hNm: '다단선형모델',
    rgsdt: '2023-09-19',
  },
  {
    cNm: '多段洗淨',
    eNm: 'multistage elutriation',
    hNm: '다단세정',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多段燒却爐',
    eNm: 'multistage incinerator',
    hNm: '다단소각로',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '多段式消化',
    eNm: 'multi-stage digestion',
    explain: '2단 이상의 소화조탱크를 이용하여 슬러지를 소화하는 방식',
    hNm: '다단식 소화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多段式濾過法 ',
    eNm: 'multiple filtration',
    hNm: '다단식 여과법',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'multistage centrifugal pump',
    explain:
      '원심펌프의 내부에 안내 날개가 아니라, 펌프에 들어간 유체가 직렬로 2번 이상 날개차를 통과하는 구조로 개선하여 고양정에 적용이 가능하도록 만든 터보형 펌프',
    hNm: '다단원심분리펌프',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多段遠心',
    eNm: 'multistage centrifugal pump',
    hNm: '다단원심펌프',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'multistage turbo blower',
    hNm: '다단터보블로어',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多段',
    eNm: 'multistage pump',
    hNm: '다단펌프',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'multistage propeller pump',
    explain:
      '1개의 축에 임펠러를 여러 개 장치하여 순차적으로 압력을 증가시켜가는 프로펠러펌프',
    hNm: '다단프로펠러펌프',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Multi-Stage Flash Distillation',
    explain:
      '다중효용법, 증기압축법을 비롯한 해수 담수화의 하나로써 사용처가 많은 대표적 방법',
    hNm: '다단플래쉬법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多糖類',
    eNm: 'polysaccharide',
    hNm: '다당류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多目的灌漑',
    eNm: 'broad irrigation',
    hNm: '다목적관개',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'multipurpose dam',
    explain:
      '댐의 저류공간의 용수공급, 홍수조절, 발전 등 여러 가지 목적으로 건설·운영되는 댐',
    hNm: '다목적댐',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'multipurpose dam',
    explain:
      '댐의 저류공간의 용수공급, 홍수조절, 발전 등 여러 가지 목적으로 건설·운영되는 댐',
    hNm: '다목적댐',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '多目的貯水池',
    eNm: 'multiple purpose reservoir, multipurpose reservoir',
    explain: '두 가지 이상의 목적을 위해 운영되는 저수지',
    hNm: '다목적저수지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多成分吸着',
    eNm: 'multi-component adsorption',
    explain:
      '2가지 이상의 성분의 유체가 혼합되어 있을 때 일어나는 흡착으로, 단독 흡착 시 더 강하게 흡착되는 성분이 더욱 강하게 흡착됨',
    hNm: '다성분흡착',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多樣性指數',
    eNm: 'diversity index',
    explain: '특정 범위 안의 존재하는 생물 종의 다양한 정도를 의미',
    hNm: '다양성 지수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多雨期',
    eNm: 'baiu',
    explain:
      '6월 하순부터 7월 중순까지 중국 양쯔강 유역으로부터 한국을 거쳐 북해도를 제외한 일본에 나타나는 우계',
    hNm: '다우기',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'dowel',
    hNm: '다우얼',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'dowel',
    hNm: '다우얼',
    rgsdt: '2023-09-14',
  },
  {
    eNm: 'multiple water supply system',
    explain:
      '다양한 수자원을 조합하여 원수로 활용하고 필요한 수준에 따라 다양한 종류의 수질을 가진 물을 공급하는 시스템',
    hNm: '다원급수시스템',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'multi-element hollow cathod lamp',
    explain:
      '원자흡광 분석의 광원으로 사용되는 부품으로 목적원소를 함유하는 중공음극 한 개 또는 그 이상을 저압의 네온과 함께 채운 방전관을 지칭함',
    hNm: '다원소중공음극램프',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'dioxine',
    explain:
      '산소원자 1개나 2개의 원자에 벤젠고리 2개가 연결되어진 3중의 고리형태로 1~8개의 염소원자를 갖는 방향족 화합물을 의미',
    hNm: '다이옥신',
    rgsdt: '2023-06-27',
  },
  {
    cNm: '多重圓板型脫水機',
    eNm: 'multi-disk dehydrator',
    hNm: '다중원판형 탈수기',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '多重燐酸鹽',
    explain: '인산이 선상(linear)으로 결합되어 형성된 다중체',
    hNm: '다중인산염',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '多重沈殿池',
    eNm: 'multiple effect evaporation process',
    explain:
      '침전지내에 경사판이나 경사관을 삽입하여 층을 다층으로 구성한 침전지',
    hNm: '다중침전지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多重效用法',
    eNm: 'Multiple Effect Distillation',
    explain:
      '다단플래쉬법과 증기압축법 등을 비롯한 해수 담수화의 한 가지 방법이다.',
    hNm: '다중효용법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多重效用法',
    eNm: 'Multiple Effect Distillation',
    explain:
      '다단플래쉬법과 증기압축법 등을 비롯한 해수 담수화의 한 가지 방법이다.',
    hNm: '다중효용법',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '多枝管水路',
    eNm: 'branched pipeline',
    hNm: '다지관수로',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'compactness',
    explain: '토양의 다짐 정도를 정량적으로 표시',
    hNm: '다짐도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '壓縮作用',
    eNm: 'compaction',
    explain: '퇴적물이 압력을 받아 공극이 크기가 줄어들며 다져지는 것',
    hNm: '다짐작용',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '多層式沈殿池',
    eNm: 'multiple sedimentation tank',
    hNm: '다층식침전지',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '多層濾過',
    eNm: 'multi layer filtration',
    explain:
      '여과 효율을 높이기 위해 2~3종의 여과재를 사용하여 여러 단으로 구성된 여과층으로 여과하는 것',
    hNm: '다층여과',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多層濾過器',
    eNm: 'multilayer filtration',
    explain:
      '여과 속도를 증가시키기 위해 두 개 이상의 여과재를 층상으로 쌓아 여과시키는 장치',
    hNm: '다층여과기',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '多層取水塔',
    eNm: 'multilayered intake tower, tower crib',
    explain:
      '수위변동이나 깊은 수심에서 취수가 가능하도록 다층구조로 만든 취수탑',
    hNm: '다층취수탑',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Dasya',
    explain: '진정홍조강 비단풀목의 홍조식물과',
    hNm: '다홍풀속',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '多環芳香族炭化水素',
    eNm: 'polycyclic aromatic hydrocarbon(PAH)',
    explain: '벤젠 고리를 여러 개 갖고 있는 화합물질을 의미',
    hNm: '다환방향족탄화수소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '段階揚水試驗 ',
    eNm: 'step-drawdown test ',
    explain:
      '한계 양수량 및 비용천수량을 구하기 위하여 몇단계로 양수량을 늘려가거나 줄여가면서 하는 양수시험',
    hNm: '단계양수시험 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '段丘',
    eNm: 'terrace',
    explain: '하도와 범람원 위치보다 상위에 위치한 이전에 형성된 범람원',
    hNm: '단구',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '段丘',
    eNm: 'terrace',
    explain: '하도와 범람원 위치보다 상위에 위치한 이전에 형성된 범람원',
    hNm: '단구',
    rgsdt: '2023-09-18',
  },
  {
    cNm: '單口空氣',
    eNm: 'single inlet-air valve',
    hNm: '단구공기밸브',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '段丘堤防',
    eNm: 'terrace ridge',
    explain: '하천 양안으로 낮게 계단모양으로 배열되는 제방',
    hNm: '단구제방',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單極抵抗',
    eNm: 'single point resistance',
    explain: '시추공에서 수행되는 전기저항 검층법의 일종',
    hNm: '단극저항',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '短期氣象豫報',
    eNm: 'short-range weather forecast',
    explain: '현재부터 3일까지의 단기간동안 기상현상을 예상하여 발표하는 것',
    hNm: '단기기상예보',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '短期流出',
    eNm: 'short-term runoff',
    explain:
      '유역 내 강우에 의한 직접적인 영향으로 단기간에 나타나는 유출량 변화',
    hNm: '단기유출',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單斷面',
    eNm: 'single section',
    hNm: '단단면',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '單斷面',
    eNm: 'single section',
    hNm: '단단면',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '單糖類',
    eNm: 'monosaccharide',
    explain: '다당류를 완전히 가수분해하면 얻어지는 당화합물의 기본 단위',
    hNm: '단당류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單獨粒子沈降速度',
    eNm: 'settling velocity of single particle, settling velocity of discrete particles',
    explain: '단일입자가 독립적으로 중력에 의해 등속도로 침강하게 될 때의 속도',
    hNm: '단독입자침강속도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單獨粒子沈降速度',
    eNm: 'settling velocity of single particle, settling velocity of discrete particles',
    explain: '단일입자가 독립적으로 중력에 의해 등속도로 침강하게 될 때의 속도',
    hNm: '단독입자침강속도',
    rgsdt: '2023-10-17',
  },
  {
    explain: '화장실에서 발생하는 오수만을 따로 처리하는 방식',
    hNm: '단독처리 정화조',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'single acting pump',
    explain: '피스톤의 1회 왕복시 흡입과 송출이 1회 일어나는 펌프',
    hNm: '단동펌프',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '短絡流',
    eNm: 'short circuit flow, short circuiting flow',
    explain: '체류시간보다 빨리 유출부에 도달하는 현상',
    hNm: '단락류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '段落餘水路',
    eNm: 'drop spillway',
    hNm: '단락여수로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷面計數',
    eNm: 'section modulus',
    explain:
      '임의의 단면에서 중립축에 대한 단면 2차 모멘트를 중립축에서 가장자리까지 거리로 나눈 값',
    hNm: '단면계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷面計數',
    eNm: 'section modulus',
    explain:
      '임의의 단면에서 중립축에 대한 단면 2차 모멘트를 중립축에서 가장자리까지 거리로 나눈 값',
    hNm: '단면계수',
    rgsdt: '2024-04-19',
  },
  {
    cNm: '斷面計數',
    eNm: 'section modulus',
    explain:
      '임의의 단면에서 중립축에 대한 단면 2차 모멘트를 중립축에서 가장자리까지 거리로 나눈 값',
    hNm: '단면계수',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '斷面收縮',
    eNm: 'contraction',
    explain: '유수의 흐름에서 단면적이 축소되는 것',
    hNm: '단면수축',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷面收縮',
    eNm: 'contraction',
    explain: '유수의 흐름에서 단면적이 축소되는 것',
    hNm: '단면수축',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '軟水',
    eNm: 'soft water',
    explain:
      '칼슘이온이나 마그네슘이온을 적게 포함하고 있는 물로 강물이나 빗물, 수돗물, 증류수 등이 있음',
    hNm: '단물',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '軟水',
    eNm: 'soft water',
    explain:
      '칼슘이온이나 마그네슘이온을 적게 포함하고 있는 물로 강물이나 빗물, 수돗물, 증류수 등이 있음',
    hNm: '단물',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '蛋白質 加水分解',
    eNm: 'proteolysis',
    explain: '단백질의 펩티드 결합을 가수적으로 분해하는 것',
    hNm: '단백질 가수분해',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '蛋白質 加水分解',
    eNm: 'proteolysis',
    explain: '단백질의 펩티드 결합을 가수적으로 분해하는 것',
    hNm: '단백질 가수분해',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '蛋白質 分解酵素',
    eNm: 'proteolytic enzyme',
    explain:
      '단백질의 펩티드 결합을 끊어 분해시키고 단백질을 알부모오스, 펩톤 등의 폴리펩티드에 이르기까지 분석하는 효소',
    hNm: '단백질 분해효소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '蛋白質 分解酵素',
    eNm: 'proteolytic enzyme',
    explain:
      '단백질의 펩티드 결합을 끊어 분해시키고 단백질을 알부모오스, 펩톤 등의 폴리펩티드에 이르기까지 분석하는 효소',
    hNm: '단백질 분해효소',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '短峰波',
    eNm: 'short crested wave',
    explain: '파봉선이 짧게 끊어지는 것처럼 보이는 파',
    hNm: '단봉파',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單사波',
    eNm: 'monoclinal wave',
    hNm: '단사파',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '單사波',
    eNm: 'monoclinal wave',
    hNm: '단사파',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '單斜河川',
    eNm: 'monoclinal river',
    explain: '하상의 경사가 거의 일정한 구간의 하천',
    hNm: '단사하천',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單斜洪水波',
    eNm: 'monoclinal flood wave',
    explain: '단사하천에서 홍수가 일어날 때의 파',
    hNm: '단사홍수파',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單線管水路',
    eNm: 'single pipe line',
    hNm: '단선관수로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷續河川',
    eNm: 'interrupted river',
    explain: '강우량에 따라 물이 흐르는 구간이 변화하는 하천',
    hNm: '단속하천',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '斷水',
    eNm: 'suspension of water supply',
    hNm: '단수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單純沈澱',
    eNm: 'plain sedimentation',
    hNm: '단순침전',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單式 干拓',
    eNm: 'reclamation ny single dike system',
    hNm: '단식 간척',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '單式 干拓',
    eNm: 'reclamation ny single dike system',
    hNm: '단식 간척',
    rgsdt: '2023-09-14',
  },
  {
    eNm: 'check valve',
    explain:
      '유체를 일정한 방향으로만 흐르게 하고, 역류를 방지하는 목적으로 사용하는 밸브',
    hNm: '단식역류방지밸브',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷崖',
    eNm: 'scarp, escarpment',
    explain: '수직 또는 급경사의 암석사면',
    hNm: '단애',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷熱',
    eNm: 'adiabatic, fracture',
    explain: '외부와 열이 통하지 않고, 열이 차단된 것을 의미',
    hNm: '단열',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷熱 遞感率',
    eNm: 'adiabatic lapse rate ',
    explain: '단열냉각에 의한 온도의 하강률',
    hNm: '단열 체감율',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷熱減率',
    eNm: 'adiabatic lapse rate ',
    explain: '단열냉각에 의한 온도의 하강률',
    hNm: '단열감률',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷熱過程',
    eNm: 'adiabatic process',
    explain:
      '단열과정은 열역학적으로 외부와 열 전달이 차단된 채로 일어나는 과정',
    hNm: '단열과정',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷熱反應',
    eNm: 'adiabatic reaction ',
    explain:
      '기본 반응의 전과정이 단일의 포텐셜 에너지 곡면상에서 이루어지는 반응',
    hNm: '단열반응',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷熱反應',
    eNm: 'adiabatic reaction ',
    explain:
      '기본 반응의 전과정이 단일의 포텐셜 에너지 곡면상에서 이루어지는 반응',
    hNm: '단열반응',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '斷熱反應',
    eNm: 'adiabatic reaction ',
    explain:
      '기본 반응의 전과정이 단일의 포텐셜 에너지 곡면상에서 이루어지는 반응',
    hNm: '단열반응',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '斷熱線 ',
    eNm: 'adiabat, adiabatics',
    hNm: '단열선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷熱溫度變化',
    eNm: 'adiabatic temperature change',
    explain: '열의 출입이 없이 공기의 부피 변화과정에서 나타나는  온도 변화',
    hNm: '단열온도변화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷熱效率',
    eNm: 'isentropic efficiency, adiabatic efficiency',
    explain:
      '동일 엔트로피(단열) 헤드(head)와 실제 압축에 필요한 헤드(head)와의 비',
    hNm: '단열효율',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單位降雨繼續其間',
    eNm: 'unit-rainfall duration',
    hNm: '단위강우계속기간',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '單位工程,',
    eNm: 'unit process',
    hNm: '단위공정',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單位排水量',
    eNm: 'unit area drainage discharge',
    explain: '단위시간동안 단위면적으로부터 배수되는 물의 양',
    hNm: '단위배수량',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '單位流量圖',
    eNm: 'unit hydrograph',
    explain:
      '유효우량이 유역에 발생하였을 때 발생하는 단위유효우량에 대한 유출수문곡선',
    hNm: '단위유량도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單位流量圖',
    eNm: 'unit hydrograph',
    explain:
      '유효우량이 유역에 발생하였을 때 발생하는 단위유효우량에 대한 유출수문곡선',
    hNm: '단위유량도',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '單位流砂量圖',
    eNm: 'unit sediment graph',
    hNm: '단위유사량도',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '單位流砂量圖',
    eNm: 'unit sediment graph',
    hNm: '단위유사량도',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '單位操作',
    eNm: 'unit operation',
    explain:
      '물리적 변화가 되는 기본적인 조작으로써, 증발, 건조, 증류, 흡수, 추출, 분쇄, 혼합, 침전, 여과, 막분리 등의 조작행위가 해당됨',
    hNm: '단위조작',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單位重量',
    eNm: 'specific weight, unit weight',
    hNm: '단위중량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單位 浸透水',
    eNm: 'unit seepage force',
    hNm: '단위침투수압',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'unit process',
    explain:
      '단위공정과 동일한 용어로써, 상하수도 시설에서는 기능에 상관없이 전체 시스템을 구성하는 하나의 요소를 단위공정으로 칭함.',
    hNm: '단위프로세스',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'unit process',
    explain:
      '단위공정과 동일한 용어로써, 상하수도 시설에서는 기능에 상관없이 전체 시스템을 구성하는 하나의 요소를 단위공정으로 칭함.',
    hNm: '단위프로세스',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '單粒子沈降',
    eNm: 'discrete particle settling',
    hNm: '단입자침강',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單差接合',
    eNm: 'drop connection',
    hNm: '단차접합',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '單最頻分布',
    hNm: '단최빈분포',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '單最頻分布',
    hNm: '단최빈분포',
    rgsdt: '2025-05-26',
  },
  {
    cNm: '斷層',
    eNm: 'fault',
    explain: '외부의 힘을 받아서 지층이 끊어져 어긋난 지질구조',
    hNm: '단층',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷層',
    eNm: 'fault',
    explain: '외부의 힘을 받아서 지층이 끊어져 어긋난 지질구조',
    hNm: '단층',
    rgsdt: '2023-10-17',
  },
  {
    eNm: 'fault spring',
    explain: '두 암반의 이동에 의해 형성된 단층면을 통해 형성된 샘',
    hNm: '단층샘',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'fault spring',
    hNm: '단층샘',
    rgsdt: '2023-06-27',
  },
  {
    cNm: '單層濾過',
    eNm: 'single media filtration',
    hNm: '단층여과',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷層海岸',
    eNm: 'fault coast',
    explain: '해안선이 단층절벽으로 이루어진 해안',
    hNm: '단층해안',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '斷層湖',
    eNm: 'fault lake',
    explain: '지각변동으로 생긴 단층분지 내에 물이 괴어 생긴 호수.',
    hNm: '단층호',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '斷層湖',
    eNm: 'fault lake',
    explain: '지각변동으로 생긴 단층분지 내에 물이 괴어 생긴 호수.',
    hNm: '단층호',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '段波',
    eNm: 'abrupt wave, bore, surge, surge wave',
    explain: '하천에서 유량의 증가로 인하여 일정한 속도로 전달되는 파',
    hNm: '단파',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '短波輻射',
    eNm: 'short wave radiation',
    explain:
      '물체에서 전자기파 중 짧은 파장을 가지는 전자기파가 방출되어 주위의 매질을 통해 전파되는 과정과 그 중에 포함된 에너지 ',
    hNm: '단파복사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '短回流',
    eNm: 'short circuit',
    hNm: '단회류',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'single suction impeller',
    explain: '날개 차의 한쪽 편에서 유체를 흡입하는 것',
    hNm: '단흡입 임펠러',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'single suction (entry) pump',
    hNm: '단흡입 펌프',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Darcy’s law',
    explain: '토양과 같은 다공성 매체에서의 지하수의 유동을 나타내는 법칙',
    hNm: '달시의 법칙',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Darcy’s law',
    explain: '토양과 같은 다공성 매체에서의 지하수의 유동을 나타내는 법칙',
    hNm: '달시의 법칙',
    rgsdt: '2023-10-12',
  },
  {
    eNm: "Dalton's law of partial pressure",
    explain:
      '기체의 압력에 관한 법칙으로서 여러 가지 기체가 혼합되어 있을 시 각각의 기체가 가지는 압력의 합은 전체 압력과 같다는 이론',
    hNm: '달톤의 분압법칙',
    rgsdt: '2016-04-15',
  },
  {
    eNm: "Dalton's law of partial pressure",
    explain:
      '기체의 압력에 관한 법칙으로서 여러 가지 기체가 혼합되어 있을 시 각각의 기체가 가지는 압력의 합은 전체 압력과 같다는 이론',
    hNm: '달톤의 분압법칙',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '淡水',
    eNm: 'freshwater ',
    explain: '염분의 함유량이 적은 물',
    hNm: '담수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '湛水灌漑',
    eNm: 'ponding irrigation',
    explain: '논과 같은 농경지에서 일정 깊이 이상의 물을 담아 관개하는 방법',
    hNm: '담수관개',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '淡水綠潮',
    eNm: 'freshwater algae',
    explain: '연못, 호수, 논 등의 담수에서 서식하는 조류',
    hNm: '담수녹조',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '淡水綠潮',
    eNm: 'freshwater algae',
    explain: '연못, 호수, 논 등의 담수에서 서식하는 조류',
    hNm: '담수녹조',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '湛水面的',
    eNm: 'reservatoin surface',
    explain: '저수지 등에서 최고 수위일 때 수표면 면적',
    hNm: '담수면적',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '湛水法',
    eNm: 'tapoon, ponding method',
    hNm: '담수법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '淡水生態系',
    eNm: 'freshwater ecosystem',
    explain:
      '담수환경에 존재하는 생물 및 비생물적 구성요소들의 상호관계를 나타내는 용어',
    hNm: '담수생태계',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '淡水水頭',
    eNm: 'fresh-water head',
    explain: '지하수의 에너지를 순수한 물기둥의 높이로 표현한 것',
    hNm: '담수수두',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '湛水深',
    eNm: 'submerged depth',
    explain: '관개를 할 시 농장물에 적당한 최대수위까지 물을 채웠을 때의 수심',
    hNm: '담수심',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '淡水魚',
    eNm: 'fresh water fish',
    explain: '강이나 호소 등 민물에서 사는 어류',
    hNm: '담수어',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '淡水赤潮',
    eNm: 'fresh water red tide',
    explain: '담수 내 조류의 증가로 붉게 변하는 현상',
    hNm: '담수적조',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '淡水藻類',
    eNm: 'freshwater algae',
    explain: '연못, 호수, 논 등의 담수에서 서식하는 조류',
    hNm: '담수조류',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'freshwater plankton',
    hNm: '담수플랑크톤',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'freshwater plankton',
    explain:
      '강, 연못, 호수 등의 담수역에 서식하는 플랑크톤 등 부유생물의 총칭이다.\r\n\r\n',
    hNm: '담수플랑크톤',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '湛水解析',
    eNm: 'ponding analysis',
    hNm: '담수해석',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '淡水湖',
    eNm: 'freshwater lake',
    explain: '담수로 이루어진 호수',
    hNm: '담수호',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '淡水化 ',
    eNm: 'saline water conversation',
    explain:
      '바닷물로부터 염분을 포함한 용해물질을 제거하여 순도 높은 음용수 및 생활용수, 공업용수 등을 얻어내는 과정',
    hNm: '담수화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '擔體',
    eNm: 'carrier',
    explain:
      '생물반응조 내부에 미생물이 잘 증식하고 생장하도록 하기 위하여 부착 표면을 제공하는 매체(media)이며, 기질(substrate)과 미생물의 접촉 기회를 증진시키기 위한 목적도 있음',
    hNm: '담체',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '擔體添加活性汚泥法',
    eNm: 'carrier-added activated sludge process, hybrid suspended/fixed biomass system',
    explain:
      'BOD제거나 질산화의 촉진을 목적으로 포기조 내에 담체를 첨가한 처리법으로써 부유성장시스템과 부착성장시스템의 결합형에 해당함',
    hNm: '담체첨가활성슬러지법',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'carrier packing density',
    explain: '반응조 부피에 대한 담체 체적의 비',
    hNm: '담체충전율',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '當量濃度',
    eNm: 'equivalent concentration',
    explain: '용액 1L 속에 녹아 있는 용질의 g당량수를 나타낸 농도',
    hNm: '당량농도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大空隙',
    eNm: 'macropore',
    explain: '토양의 공극 중 그 크기가 75 μm이상인 것',
    hNm: '대공극',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大規格堤防',
    eNm: 'super levee',
    hNm: '대규격제방',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '大規格堤防',
    eNm: 'super levee',
    hNm: '대규격제방',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '大氣',
    eNm: 'atmosphere ',
    explain: '지구 중력에 의해 묶여있는 지구 주위를 둘러싸고 있는 기체',
    hNm: '대기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣',
    eNm: 'atmosphere ',
    explain: '지구 중력에 의해 묶여있는 지구 주위를 둘러싸고 있는 기체',
    hNm: '대기',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '大氣',
    eNm: 'atmosphere ',
    explain: '지구 중력에 의해 묶여있는 지구 주위를 둘러싸고 있는 기체',
    hNm: '대기',
    rgsdt: '2023-11-06',
  },
  {
    cNm: '大氣(混)濁度',
    eNm: 'atmospheric turbidity',
    explain: '대기의 탁한 정도',
    hNm: '대기(혼)탁도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣境界層',
    eNm: 'atmospheric boundary layer',
    explain: '기체대기와 고체지구 경계에 맞다아 형성된 대기층',
    hNm: '대기경계층',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣科學',
    eNm: 'atmospheric science',
    explain: '자연과 대기와의 상호 현상과 영향을 연구하는 학문',
    hNm: '대기과학',
    rgsdt: '2016-11-18',
  },
  {
    cNm: '大氣光',
    eNm: 'airglow',
    explain:
      '초고층대기에 있는 기체에 흡수된 태양복사에너지의 일부가 화학반응을 통해 복사에너지로 변형되면서 나타나는 발광현상',
    hNm: '대기광 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣圈',
    eNm: 'aerosphere',
    explain:
      '지표면 상단의 지구 중력에 묶여있는 지구를 둘러싸고 있는 기체로 이루어진 영역',
    hNm: '대기권',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣亂流',
    eNm: 'atmospheric turbulence',
    explain: '대기 순환에서 규모가 가장 작은 순환',
    hNm: '대기난류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: ' 大氣大循環',
    eNm: 'atmospheric general circulation ',
    explain:
      '지구 전체에 걸치는 규모의 대기운동으로 가장 규모가 큰 대기의 흐름',
    hNm: '대기대순환',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣大循環',
    eNm: 'atmospheric general circulation ',
    explain:
      '지구 전체에 걸치는 규모의 대기운동으로 가장 규모가 큰 대기의 흐름',
    hNm: '대기대순환',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '大氣輻射',
    eNm: 'atmospheric radiation',
    explain: '대기로부터 발생하는 적외선 복사',
    hNm: '대기복사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣輻射收支',
    eNm: 'atmospheric radiation budget',
    explain: '대기에 흡수된 에너지양과 대기복사를 통해 방출되는 양은  평행',
    hNm: '대기복사수지',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣分散',
    eNm: 'atmospheric dispersion',
    explain: '공기의밀도차와같은현상에의하여대기가분산(확산)되는과정',
    hNm: '대기분산',
    rgsdt: '2016-11-18',
  },
  {
    cNm: '大氣分散',
    eNm: 'atmospheric dispersion',
    explain: '공기의밀도차와같은현상에의하여대기가분산(확산)되는과정',
    hNm: '대기분산',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '大氣不透明度',
    eNm: 'atmospheric opacity',
    explain: '대기의 가시 정도를 수치화 하여 표현하는 방식',
    hNm: '대기불투명도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣散亂',
    eNm: 'atmospheric scatter',
    explain: '대기가 태양 복사 광선을 산란',
    hNm: '대기산란',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣濕度',
    eNm: 'air humidity, air moisture, atmospheric humidity',
    explain: '대기 중에 포함된 수분의 양을 말한다.',
    hNm: '대기습도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣安定度',
    eNm: 'atmospheric stability',
    explain:
      '평형 상태에 있는 대기를 약간 흐트러지게 놓았을 때 원래의 상태로 되돌아가려고 하거나 그것을 계기로 대기의 상태가 크게 변하려고 하는 정도',
    hNm: '대기안정도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣壓',
    eNm: 'atmospheric pressure',
    explain: '대기에 작용하는 중력에 의해 지표에 생긴 압력',
    hNm: '대기압',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣汚染',
    eNm: 'air pollution ',
    explain:
      '인위적인 발생물질이 생물이나 기물에 직접적으로 해를 끼칠 만큼 다량으로 대기 중에 존재하는 상태',
    hNm: '대기오염',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣汚染 防止施設',
    eNm: 'atmosphere pollution prevention establishment',
    explain: '배출되는 대기오염물질을 제거하거나 감소시키기 위한 시설',
    hNm: '대기오염 방지시설',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣汚染基準',
    eNm: 'air pollution standard',
    explain: '대기오염을 막기 위해 설정한 환경기준',
    hNm: '대기오염기준',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣汚染物質',
    eNm: 'atmosphere pollution matter',
    explain:
      '대기의 물질 중에서 인공적 또는 천연적으로 발생한 것으로 생물이나 물질에 악영향을 끼치는 미량물질',
    hNm: '대기오염물질',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'predictive model of air pollution ',
    explain:
      '대기오염물질의 확산 현상을 단순화하여 오염물질의 농도를 예측하기 위한 모델',
    hNm: '대기오염예측모델',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣汚染源',
    eNm: 'air pollution source',
    explain: '대기오염 발생 원인이 되는 장치나 시설',
    hNm: '대기오염원',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'air pollution control center ',
    explain: '오염준위를 알리는 일을 하는 측정기관',
    hNm: '대기오염제어센터',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣汚染指標',
    eNm: 'air pollution index',
    explain: '대기오염도를 표시하는 분석치',
    hNm: '대기오염지표',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣擾亂',
    eNm: 'atmosphere disturbance',
    explain: '대기에 분포해있는 파동요란',
    hNm: '대기요란',
    rgsdt: '2016-11-21',
  },
  {
    cNm: '大氣擾亂',
    eNm: 'atmosphere disturbance',
    explain: '대기에 분포해있는 파동요란',
    hNm: '대기요란',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '大氣凝結物',
    eNm: 'hydrometeor',
    explain: '대기 중의 물이나 얼음입자',
    hNm: '대기응결물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣-安定度',
    eNm: 'atmospheric stability',
    explain: '대기의 수직방향의 이동에 따르는 대기의 안정상태',
    hNm: '대기의 안정도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣質管理',
    eNm: 'air quality management',
    explain: '대기의 오염현황을 파악하고 대기의 질을 관리하는 행위',
    hNm: '대기질관리',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣窓',
    eNm: 'atmospheric window ',
    explain:
      '지구로부터 방출되는 장파 형태의 빛이 대기로 흡수되지 않고  방출되는 8~12㎛의 파장대',
    hNm: '대기창',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣現象',
    eNm: 'atmospheric phenomenon, meteor',
    explain:
      '대기권에서 일어나는 물리적 현상으로, 일반적으로 특정 지점에서 개인이 시각이나 청각을 통해 관찰할 수 있는 현상',
    hNm: '대기현상',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣擴散',
    eNm: 'atmospheric diffusiton',
    explain: '공기 밀도차에 의해 발생하는 분자확산',
    hNm: '대기확산',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣候',
    eNm: 'macroclimate ',
    explain:
      '한국 전체, 대륙, 때로는 지구 전체 등의 넓은 지역의 기후 또는 기후를 논하는 기후학의 분야',
    hNm: '대기후',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大氣吸收',
    eNm: 'atmospheric absorption',
    explain: '태양복사에너지의 여러 파장이 대기 성분에 의해 흡수되는 현상',
    hNm: '대기흡수',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'large dam',
    explain: '기초의 최저 심부에서 댐 정상까지 높이가 15m 이상인 댐',
    hNm: '대댐',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'large dam',
    explain: '기초의 최저 심부에서 댐 정상까지 높이가 15m 이상인 댐',
    hNm: '대댐',
    rgsdt: '2023-10-19',
  },
  {
    eNm: 'large dam',
    explain: '기초의 최저 심부에서 댐 정상까지 높이가 15m 이상인 댐',
    hNm: '대댐',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '對流',
    eNm: 'convection',
    explain: '열을 받은 물체의 물리적 이동에 의한 열의 전달 운동',
    hNm: '대류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流',
    eNm: 'convection',
    explain: '열을 받은 물체의 물리적 이동에 의한 열의 전달 운동',
    hNm: '대류',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '對流降水',
    eNm: 'convective precipitation',
    explain: '주위보다 온도가 높은 습한 공기의 상승운동에 의해 형성된 강수',
    hNm: '대류강수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流降雨',
    eNm: 'convective rainfall',
    explain: '주위보다 온도가 높은 습한 공기의 상승운동에 의해 형성된 강우현상',
    hNm: '대류강우',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流圈',
    eNm: 'troposphere',
    explain: '대기권의 최하층을 이루는 부분으로 기상현상이 일어나는 부분',
    hNm: '대류권',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流圈傳播 ',
    eNm: 'tropospheric propagation ',
    explain: '전파가 대류권의 영향을 받으면서 전파되는 현상',
    hNm: '대류권 전파',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流圈界面',
    eNm: 'tropopause',
    explain: '대류권과 성층권의 경계면',
    hNm: '대류권계면',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流圈散亂',
    eNm: 'troposcatter',
    explain: '전파가 대류권에서 산란이 발생하는 것',
    hNm: '대류권산란',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'tropospheric ozone',
    explain: '대기권 최하층인 대류권 내 존재하는 오존',
    hNm: '대류권오존',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流不安定',
    eNm: 'convective instability',
    explain:
      '상당온위가 상층으로 갈수록 낮아져 기층 전제가 상승하면서 층의 상태가 정역학적으로 불안정해지는 것',
    hNm: '대류불안정',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流上昇',
    eNm: 'convective lift',
    explain: '대기가 태양에 의해 데워져 상승',
    hNm: '대류상승',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流性 移動',
    eNm: 'convective transport',
    explain: '대류에 의한 물질의 이동',
    hNm: '대류성 이동',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流性降水',
    eNm: 'convective precipitation',
    explain: '주위보다 온도가 높은 습한 공기의 상승 운동에 의해 형성된  강수',
    hNm: '대류성강수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流性氣流',
    eNm: 'convection current',
    explain: '상층부와 하층부의 온도 차에 의해서 순환이 일어나는 것',
    hNm: '대류성기류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流細胞',
    eNm: 'convective cell',
    explain: '대기대순환에의해생기는6개의큰규모의대류현상',
    hNm: '대류세포',
    rgsdt: '2016-11-18',
  },
  {
    cNm: '對流循環',
    eNm: 'convectional circulation',
    explain: '공기의 상부와 하부의 온도 차에 의한 순환이 일어나는 것',
    hNm: '대류순환',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流安定',
    eNm: 'convective stability',
    explain: '공기가 수직적인 움직임을 할 수 있는 능력',
    hNm: '대류안정',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流溫度',
    eNm: 'convective temperature',
    hNm: '대류온도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流雲',
    eNm: 'convective cloud',
    explain:
      '대류성 구름이라고도 하며 하부가 데워져서 불안정해진 대기 중에 발생한 적운형 구름',
    hNm: '대류운',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流凝結高度',
    eNm: 'convective condensation level',
    explain:
      '지표 부근의 공기덩이가 지표의 가열로 에너지를 받은 후 단열적으로 상승하여 포화에 이르는 고도',
    hNm: '대류응결고도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流顚倒',
    eNm: 'convection overturn',
    explain: '유체의 밀도 차이에 의한 상층부와 하층부의 수직적인 순환',
    hNm: '대류전도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對流形降雨',
    eNm: 'convective precipitation',
    explain: '주위보다 온도가 높은 습한 공기의 상승 운동에 의해 형성된 강우',
    hNm: '대류형강우',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大陸(性)氣候',
    eNm: 'continental climate',
    explain:
      '기온의 일교차와 연교차가 크고, 여름에 기압이 낮아지고 강수가 집중되는 등의 특징을 보이는 기후 형태',
    hNm: '대륙(성)기후',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大陸氣團',
    eNm: 'continental air mass',
    explain:
      '넓은 대륙의 상공에서 공기가 장기간 정체하면서 지표면의 영향을 받아 그 지역의 특성을 띄는 큰 공기 덩어리',
    hNm: '대륙기단',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大陸分水嶺',
    eNm: 'continental divide',
    explain:
      '육지의 반대쪽을 향하여 서로 다른 바다로 흘러가는 강을 분리하는 가상의 선',
    hNm: '대륙분수령',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '大陸棚',
    eNm: 'continental shelf',
    explain: '해변에서 수심 약 200m까지 완만한 경사를 이루는 해저지형',
    hNm: '대륙붕',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大陸棚波',
    eNm: 'edge wave',
    explain: '해저가 경사진 지역에서 진행방향과 해안선이 평행을 이루는 파',
    hNm: '대륙붕파',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大陸性氣候',
    eNm: 'continental climate',
    explain:
      '기온의 일교차와 연교차가 크고, 여름에 기압이 낮아지고 강수가 집중되는 등의 특징을 보이는 기후 형태',
    hNm: '대륙성기후',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大陸楯狀地',
    eNm: 'continental shield',
    explain: '지각평형상태에 놓여있는 암석들의 집합체',
    hNm: '대륙순상지',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '大雪',
    eNm: 'heavy snow fall',
    explain: '겨울철에 눈이 한꺼번에 많이 내리는 현상',
    hNm: '대설',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大雪警報',
    eNm: 'heavy-snow warning, warning for heavy snow',
    explain:
      '기상청에서 24시간동안 내리는 눈의 적설량이 20cm이상으로 예상될때 발령하는 경보',
    hNm: '대설경보',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '帶水性試驗',
    eNm: 'aquifer test',
    explain:
      '동일 대수층에 양수정과 관측정을 설치하여 일정양의 물을 양수(또는 주입)하여 관측정에서 발생하는 수위변화를 관찰하는 시험',
    hNm: '대수성시험',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對數增殖',
    eNm: 'logarithmic growth',
    explain:
      '미생물 성장곡선에서 미생물이 최고의 속도로 성장하고 분열하는 시기',
    hNm: '대수증식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對數增殖期',
    eNm: 'exponential growth phase, ',
    explain:
      '미생물 성장곡선에서 미생물이 최고의 속도로 성장하고 분열하는 시기',
    hNm: '대수증식기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對數增殖期',
    eNm: 'exponential growth phase, ',
    explain:
      '미생물 성장곡선에서 미생물이 최고의 속도로 성장하고 분열하는 시기',
    hNm: '대수증식기',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '帶水層',
    eNm: 'aquifer',
    explain:
      '대수층은 물을 함유하고 있으며 일반적인 조건에서 관정이나 샘을 통해서 대량의 물을 공급할 수 있을 정도로 투수성과 저류성이 커서 경제적으로 개발에 이용할 수 있을 정도의 지하수를 배출할 수 있는 지층',
    hNm: '대수층',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '帶水層 鏡界面',
    eNm: 'aquifer boundary',
    explain: '대수층 주변 지층과 경계를 이루는 지역',
    hNm: '대수층 경계면',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '帶水層試驗',
    eNm: 'aquifer test',
    explain:
      '동일 대수층에 양수정과 관측정을 설치하여 일정양의 물을 양수(또는 주입)하여 관측정에서 발생하는 수위변화를 관찰하는 시험',
    hNm: '대수층시험',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'atmosphere circulation model',
    explain:
      '지구상의 3차원 공간의 기후 변화에 관련된 물리량을 예측하는 전지구적 수치예측모델',
    hNm: '대순환모델',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對岸距離',
    eNm: 'fetch',
    hNm: '대안거리',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '對岸距離',
    eNm: 'fetch',
    hNm: '대안거리',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '對岸景',
    hNm: '대안경',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '對岸景',
    hNm: '대안경',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '對岸景',
    hNm: '대안경',
    rgsdt: '2025-05-26',
  },
  {
    cNm: '大洋',
    eNm: 'ocean',
    explain: '세계 해양 중 특히 넓은 해역을 차지하는 대규모의 바다',
    hNm: '대양',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大洋旋回流',
    eNm: 'gyre',
    explain: '지구를 순환하는 대규모 해류',
    hNm: '대양선회류',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '對應',
    eNm: 'correspondence',
    hNm: '대응',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '對應水深',
    eNm: 'confrontation depth of water',
    explain:
      '하나의 비에너지는 상류조건과 사류조건에서 두 가지 수심을 가지는데 하나의 수심에 대해 대응하는 다른 수심',
    hNm: '대응수심',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '帶磁率',
    eNm: 'magnetic susceptibility',
    explain: '물질이 자화될 수 있는 정도',
    hNm: '대자율',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '帶磁率',
    eNm: 'magnetic susceptibility',
    explain: '물질이 자화될 수 있는 정도',
    hNm: '대자율',
    rgsdt: '2023-09-18',
  },
  {
    cNm: '大腸菌',
    eNm: 'Escherichia coli, E. coli',
    explain:
      '사람과 포유류의 장 내에 기생하고 있는 세균으로 Escherichia속 세균 중 하나',
    hNm: '대장균',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Escherichia coli O-157',
    explain:
      '대장균 표면에 있는 단백질 O항원의 여러 가지 혈청학적 타입 중 157번째로 발견된 것이라 하여 명명된 병원성 대장균의 한 종류. 장관 내 서식하며 설사나 복통을 일으키며, 전염성이 강하고 잠복기간이 김',
    hNm: '대장균 O-157',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'Escherichia coli O-157',
    explain:
      '대장균 표면에 있는 단백질 O항원의 여러 가지 혈청학적 타입 중 157번째로 발견된 것이라 하여 명명된 병원성 대장균의 한 종류. 장관 내 서식하며 설사나 복통을 일으키며, 전염성이 강하고 잠복기간이 김',
    hNm: '대장균 O-157',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '大腸菌群',
    eNm: 'coliform group',
    explain:
      '사람이나 동물과 같은 온혈동물의 장 속에 기생하고 있는 대장균과 그와 유사한 균의 총칭',
    hNm: '대장균군',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Escherichia coli phage',
    hNm: '대장균파지',
    rgsdt: '2016-11-25',
  },
  {
    eNm: 'Escherichia coli phage',
    hNm: '대장균파지',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '帶電粒子',
    eNm: 'charged particle',
    hNm: '대전입자',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'transition of dam',
    hNm: '대조 중간층',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大潮平均干潮位',
    eNm: 'low water ordinary spring tide, L.W.O.S.T',
    explain: '조석 차이가 가장 큰 시기에 해면이 가장 낮아진 수위의 평균',
    hNm: '대조평균 간조위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大潮平均滿潮位',
    eNm: 'high water ordinary spring tide, H.W.O.S.T',
    explain:
      '밀물에 의하여 가장 높게 형성된 수위들의 평균을 기준 수면으로부터의 높이로 나타낸 것',
    hNm: '대조평균 만조위',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'dea-cheung dam',
    explain: '대전광역시 대덕구 미호동에 위치한 금강수계의 다목적댐',
    hNm: '대청댐',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '代替水原',
    eNm: 'alternative water resource',
    explain: '비상시 사용할 수 있는 일상적으로 사용되지 않는 수자원',
    hNm: '대체수원',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '代表單位度',
    eNm: 'representative unitgraph',
    hNm: '대표단위도',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '代表單位度',
    eNm: 'representative unitgraph',
    hNm: '대표단위도',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '代表流域',
    eNm: 'representative basin',
    explain:
      '지구상의 여러 환경 속에서 유역에 대한 물순환 과정의 지식을 얻는데 있어 가장 적합한 대표적인 유역',
    hNm: '대표유역',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'macrozooplankton',
    explain: '여러 크기의 플랑크톤 중 그물로 채집할 수 있는 플랑크톤',
    hNm: '대형동물플랑크톤',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'macrophyte',
    explain:
      '인간의 눈에 의해 볼 수 있는 식물로 수생이끼, 양치류, 뿌리가 있는 식물 등',
    hNm: '대형수생식물',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'macroalgae',
    hNm: '대형조류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '大洪水',
    eNm: 'deluge',
    explain: '규모가 큰 홍수',
    hNm: '대홍수',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'dam',
    explain:
      '물을 저수하기 위하여 기존의 강이나 하천의 흐름을 막아 이수 및 치수 목적으로 건설된 수리구조물',
    hNm: '댐',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'design flood discharge',
    explain: '댐의 설계에 있어 설계기준에 적합한 홍수량',
    hNm: '댐 설계홍수유량',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'dam elerame',
    explain:
      '홍수로 인하여 댐에 유입된 물이 댐마루를 넘지 못하도록 여유분으로 설정한 설계홍수위와 댐마루표고의 높이 차이',
    hNm: '댐 여유고',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'crest length of dam',
    hNm: '댐길이',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'dam height',
    explain: '기초지반의 최저 지반고와 댐 최상단부의 표고 차이',
    hNm: '댐높이',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'heighting of dam',
    explain: '댐의 증고를 위하여 콘크리트로 이음하는 작업',
    hNm: '댐돋기',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'dam cest',
    hNm: '댐마루',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'volume of dam body',
    hNm: '댐부피',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Dambreak wave',
    hNm: '댐붕괴파',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'Dambreak wave',
    hNm: '댐붕괴파',
    rgsdt: '2023-09-14',
  },
  {
    eNm: 'dam slope',
    explain: '댐 경사부의 수평길이에 대한 수직길이의 비',
    hNm: '댐비탈기울기',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'heel of dam',
    hNm: '댐상류면단',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'dam and conduit type power',
    explain:
      '댐식과 수로식의 장단점을 보완한 혼합형으로 수로에 의한 낙차를 통해 전력을 얻을 수 있는 수력 발전소',
    hNm: '댐수로식 수력발전',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'dam and conduit type power',
    explain:
      '댐식과 수로식의 장단점을 보완한 혼합형으로 수로에 의한 낙차를 통해 전력을 얻을 수 있는 수력 발전소',
    hNm: '댐수로식 수력발전',
    rgsdt: '2023-10-17',
  },
  {
    eNm: 'dam and conduit type power',
    explain:
      '댐식과 수로식의 장단점을 보완한 혼합형으로 수로에 의한 낙차를 통해 전력을 얻을 수 있는 수력 발전소',
    hNm: '댐수로식 수력발전',
    rgsdt: '2023-10-17',
  },
  {
    eNm: 'dam gate',
    hNm: '댐수문',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'abutment of dam',
    hNm: '댐양단부',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'dam extra banking',
    explain: '댐마루에 침하량을 예측하여 안전을 위해 조금 더 쌓는 흙',
    hNm: '댐여성토',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'damper',
    explain:
      '공기의 통로인 덕트 내에 설치하여 공기의 흐름을 제어할 수 있는 공기 조절판',
    hNm: '댐퍼',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'ductile iron pipe(DIP)',
    explain:
      '용해 상태의 주철에 세륨이나 마그네슘을 첨가해서 만들 수 있는 주철관',
    hNm: '덕타일 주철관',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'bulk sediment',
    hNm: '덩어리 유사',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'bulk sediment',
    hNm: '덩어리 유사',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '被覆 ',
    eNm: 'canopy, cover',
    hNm: '덮개',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'deckless buttress dam',
    explain: '차수벽 및 부벽 등으로 이루어진 댐',
    hNm: '데클리스 버트레스 댐',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'delphi method',
    explain:
      '전문가의 직감과 판단으로 하는 미래 예측을 말하며, 대단히 예측하기 어려운 것을 앙케트를 반복하고 계속 내용을 정리해나가는 연구 방법',
    hNm: '델파이법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '導坑',
    eNm: 'pilot tunnel, heading, lateral shaft',
    hNm: '도갱',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '倒景',
    hNm: '도경',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '倒景',
    hNm: '도경',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '導管',
    eNm: 'conduit',
    explain:
      '생물학적 분해반응이나 부식, 산화 등 화학적으로 안정성이 높은 점토를 주원료로 하여 고온에서 제조된 관',
    hNm: '도관',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '鍍金工場廢水',
    eNm: 'plating industry wastewater',
    explain:
      '도금과 관련된 산업시설에서 발생되는 폐수를 칭하며 도금과정에서 물에 용해되어 배출되는 중금속이 함유된 폐수',
    hNm: '도금공장폐수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '鍍金廢水',
    eNm: 'metal plating wastewater',
    explain:
      '크롬 도금이나 동 도금 등 각종 도금공정에서 배출되는 것으로 도금의 종류에 따라 차이는 있지만 크롬, 동, 아연, 니켈 등의 중금속을 포함한 폐수 ',
    hNm: '도금폐수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '鍍金廢水',
    eNm: 'metal plating wastewater',
    explain:
      '크롬 도금이나 동 도금 등 각종 도금공정에서 배출되는 것으로 도금의 종류에 따라 차이는 있지만 크롬, 동, 아연, 니켈 등의 중금속을 포함한 폐수 ',
    hNm: '도금폐수',
    rgsdt: '2023-10-17',
  },
  {
    eNm: 'Donora episode',
    explain:
      '1948년 미국 펜실바니아주 피츠버그시의 도노라 시에서 발생한 대기오염 사건이디.',
    hNm: '도노라 사건',
    rgsdt: '2016-11-19',
  },
  {
    cNm: '到達時間',
    eNm: 'travel time',
    explain:
      '하천 등의 일정구간의 상류부에서 하류부까지 물이 유하하는 데 소요되는 시간',
    hNm: '도달시간',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '到達時間集水面積曲線法',
    eNm: 'concentration time-catchment area curve',
    hNm: '도달시간-집수면적 곡선법',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '到達時間集水面積曲線法',
    eNm: 'concentration time-catchment area curve',
    hNm: '도달시간-집수면적 곡선법',
    rgsdt: '2023-09-14',
  },
  {
    eNm: 'gutter',
    explain: '작고 좁은 개울',
    hNm: '도랑',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'trench digger',
    explain: '도랑 만들기 위해 땅을 갈고 파는 기계',
    hNm: '도랑굴착기',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '導流工',
    eNm: 'training dyke',
    explain:
      '하천의 합류점에서 원활한 흐름이 되게 하기 위한 하천시설물 혹은 공사',
    hNm: '도류공',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '導流構造物',
    eNm: 'training structure, guide bank, longitudinal dike',
    explain:
      '하천의 합류부, 하류부 등에 토사의 침전 등으로 인한 유수의 흐름 문제를 저감하기 위한 구조물로 유수의 방향, 유속 등을 조절하는 하천시설',
    hNm: '도류구조물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '導流壁',
    eNm: 'flow arrangement wall, training wall',
    explain:
      '물이 정체되는 사구역(dead space)가 형성되지 않고 균일하게 흐르도록 유도하기 위하여 배수지 등의 내부에 설치하는 벽',
    hNm: '도류벽',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '跳流砂',
    eNm: 'saltating load',
    hNm: '도류사',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '跳流砂',
    eNm: 'saltating load',
    hNm: '도류사',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '導流設備',
    eNm: 'training facility, flow arrangement facility',
    explain:
      '구조물의 사수역(dead space)을 없애고 물의 흐름 방향을 변경하거나 그 관성력을 약하게 하고 유속의 분포를 균일하게 하기 위한 설비',
    hNm: '도류설비',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '導流堤',
    eNm: 'training bank, training dike',
    explain:
      '하천의 하류부 혹은 합류지점에서 유수의 방향을 설정하기 위하여 설치하는 제방',
    hNm: '도류제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '導流板',
    eNm: 'baffle plate',
    explain:
      '반응조와 같은 구조물에서 물의 흐름을 균일하게 하거나 특별한 목적의 흐름을 형태를 유도하고자 하는 목적으로 조 내부에 설치하는 판',
    hNm: '도류판',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '塗抹培養',
    eNm: 'spread plate culture; smear culture',
    explain:
      '고체배지의 표면에 시료를 도말하여 시료에 존재하는 미생물을 동정 및 계수하는 것',
    hNm: '도말배양',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '塗覆裝鋼管',
    eNm: 'coated steel pipe',
    explain:
      '관의 내·외 양면이나 한쪽 면만을 도료 또는 도료와 복장제(覆裝劑)를 도포하여 방식처리 한 강관 ',
    hNm: '도복장강관',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '屠殺場廢水',
    eNm: 'slaughterhouse wastewater',
    explain: '가축의 도살, 내장제 해체, 세정 등의 작업 공정에서 배출되는 폐수',
    hNm: '도살장폐수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '導流工',
    eNm: 'aqueduct',
    explain:
      '상수도시설에서 취수 지점으로부터 정수장의 유입부(보통 착수정)까지의 암거',
    hNm: '도수거',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '導水管',
    eNm: 'conduct pipe',
    explain: '취수구로부터 수조입구까지의 물을 끌어들이는 관로.',
    hNm: '도수관',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '導水管',
    eNm: 'conduct pipe',
    hNm: '도수관',
    rgsdt: '2023-06-27',
  },
  {
    cNm: '導水管渠',
    eNm: 'aqueduct',
    hNm: '도수관거',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'length of hydraulic jump',
    hNm: '도수길이',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'length of hydraulic jump',
    hNm: '도수길이',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '導水路',
    eNm: 'conduit',
    explain:
      '저수지 등 수원에서 취수한 물을 정수장 유입부까지의 상수 원수를 보내기 위한 수로이며 취수관로는 포함되지 않음',
    hNm: '도수로',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '導水路',
    eNm: 'conduit',
    explain:
      '저수지 등 수원에서 취수한 물을 정수장 유입부까지의 상수 원수를 보내기 위한 수로이며 취수관로는 포함되지 않음',
    hNm: '도수로',
    rgsdt: '2023-10-12',
  },
  {
    cNm: '度數分布',
    eNm: 'frequency distribution',
    explain:
      '통계분석자료를 관측값에 따라 구간으로 분류하고 각 계급의 자료수, 즉 도수 분포를 나타낸 것 ',
    hNm: '도수분포',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '導水損失',
    eNm: 'conveyance loss',
    explain:
      '수원지에서 수요지로 물을 운반하는 수로에서 침투나 증발로 인해 손실되는 수량',
    hNm: '도수손실',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '都市計劃法',
    eNm: 'city planning law',
    explain:
      '도시의 건전한 발전과 질서있는 정비를 도모하고, 국토의 균형있는 발전과 공공복지의 증진에 기여하는 것을 목적으로 하는 법률',
    hNm: '도시계획법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '都市固形廢棄物',
    eNm: 'municipal solid waste',
    hNm: '도시고형폐기물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '都市固形廢棄物',
    eNm: 'municipal solid waste',
    hNm: '도시고형폐기물',
    rgsdt: '2023-10-12',
  },
  {
    cNm: '都市工學',
    eNm: 'urban engineering',
    explain: '도시에 관한 여러 가지의 문제를 공학적 관점에서 연구하는 학문분야',
    hNm: '도시공학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '都市氣候',
    eNm: 'city climate',
    explain:
      '도시의 중심부에 있어서 가옥이나 공장의 집중, 도로의 포장, 차량의 증가 등으로 인해 나타내는 특유한 국지기후',
    hNm: '도시기후',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '都市氣候',
    eNm: 'city climate',
    explain:
      '도시의 중심부에 있어서 가옥이나 공장의 집중, 도로의 포장, 차량의 증가 등으로 인해 나타내는 특유한 국지기후',
    hNm: '도시기후',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '都市氣候學',
    eNm: 'urban climatology',
    hNm: '도시기후학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '都市水文學',
    eNm: 'urban hydrology',
    explain: '도시의 물의 거동에 대한 연구를 하는 학문',
    hNm: '도시수문학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '都市熱섬',
    eNm: 'urban heat island',
    explain:
      '시가화된 도시의 중심이 주변 지대보다 기온이 높게 유지되는 현상이며 야간에도 기온이 떨어지지 않아 생활에 불편을 야기함',
    hNm: '도시열섬',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '都市雨水排水渠系統',
    eNm: 'urban storm drain system',
    explain:
      '도시 지역에서 우수의 유입을 토대로 치수와 이수 및 관리를 위하여 계획한 일련의 배수거 시설',
    hNm: '도시우수배수거계통',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '都市下水',
    eNm: 'municipal sewage',
    explain:
      '도시를 형성하는 주거지역에서 일상생활 중 배출되는 가정오수와 상업지역, 공공건물 및 공공시설 등에서 배출되는 오수가 기본 하수를 구성하며, 하수관거 상태에 따라 하수관에 유입되는 빗물을 포함하기도 함',
    hNm: '도시하수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '都市下水道',
    eNm: 'city sewer',
    explain:
      '시가지에서의 하수를 배제하기 위해서 지방공공단체가 관리하고 있는 하수도',
    hNm: '도시하수도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '都市河川',
    eNm: 'urban river',
    explain: '유역의 전부 혹은 대부분의 면적이 도시지역에 분포하는 하천',
    hNm: '도시하천',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '都市化',
    eNm: 'urbanization',
    explain:
      '인구가 집중되고 생활과 산업을 위한 시설물이 증가되어 점차 도시가 되어가는 변화과정이나 이동 현상',
    hNm: '도시화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '都市環境',
    eNm: 'urban environment',
    explain:
      '자연상태와 구분되는 도시의 자연과 생활 및 공간적 환경을 뜻하는 것으로 지형, 기후, 수자원, 식생과 동식물, 인구, 수질, 대기, 폐기물, 소음 및 진동, 교통, 경관 등을 다루는 포괄적 개념',
    hNm: '도시환경',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '跳躍',
    eNm: 'saltation',
    hNm: '도약',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '跳躍',
    eNm: 'saltation',
    hNm: '도약',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '陶磁器工場廢水',
    eNm: 'potter wastewater',
    hNm: '도자기공장폐수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '塗裝',
    eNm: 'painting',
    hNm: '도장',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'gymnasium and food processing wastewater',
    explain:
      '다량의 혈액을 함유하고, BOD가 높으며 동물의 미소화물 및 분변성분에 의한 부유물질도 다량 함유한 도장 및 식육가공 공장에서 배출되는 배수',
    hNm: '도장 및 식육 가공 공장폐수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '導電率',
    eNm: 'conductivity',
    hNm: '도전율',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'dosing tank',
    hNm: '도징탱크',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '導體',
    eNm: 'conductor',
    hNm: '도체',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '跳波',
    eNm: 'overtopping wave',
    explain: '높이 튀어오르는 파도',
    hNm: '도파',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Doppler shift',
    hNm: '도플러 편이',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'Doppler effect',
    explain:
      '파원과 관측자간의 상대속도에 따라 파동의 주파수가 다르게 전달되는 현상',
    hNm: '도플러 효과',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '超音波流速計',
    eNm: 'acoustic doppler velocity meter, ADVM',
    explain: '초음파의 도플러 변이를 이용하여 유속을 측정하는 유속계',
    hNm: '도플러방식 초음파유속계',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'doppler velocity-meter',
    explain: '초음파, 전자파 등의 도플러 효과를 이용하여 유속을 측정하는 기기',
    hNm: '도플러유속계',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '圖解法',
    eNm: 'ripple method',
    explain:
      '하천의 유출량을 구하기 위해 누가곡선을 그린 다음 이 곡선을 이용하여 유출량을 구해내는 방법',
    hNm: '도해법',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'detached breakwater',
    explain: '육지에 닿지 않고 바다에만 설치한 방파제',
    hNm: '도형 방파제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '獨立營養 窒酸化',
    eNm: 'autotrophic nitrification',
    explain:
      '생존을 위해 외부 유기물의 섭취에 의존하지 않고 암모늄을 아질산 및 질산으로 산화시키며 에너지와 영양분을 얻는 세균',
    hNm: '독립영양 질산화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '獨立營養 窒酸化',
    eNm: 'autotrophic nitrification',
    explain:
      '생존을 위해 외부 유기물의 섭취에 의존하지 않고 암모늄을 아질산 및 질산으로 산화시키며 에너지와 영양분을 얻는 세균',
    hNm: '독립영양 질산화',
    rgsdt: '2023-10-12',
  },
  {
    cNm: '獨立營養 窒酸化',
    eNm: 'autotrophic nitrification',
    explain:
      '생존을 위해 외부 유기물의 섭취에 의존하지 않고 암모늄을 아질산 및 질산으로 산화시키며 에너지와 영양분을 얻는 세균',
    hNm: '독립영양 질산화',
    rgsdt: '2023-10-13',
  },
  {
    cNm: '獨立營養生物',
    eNm: 'autotroph',
    explain:
      '무기물을 섭취하여 그것을 원료로 체내에 필요한 유기물을 생산하는 생물',
    hNm: '독립영양생물',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '獨立榮養細菌',
    eNm: 'autotrophic bacteria',
    explain:
      '다른 생명체에 의존하지 않고 생장하는 세균, 즉 생체화합물인 유기물을 필요로 하지 않고, 자연상태의 무기물만을 이용하여 에너지 섭취, 세포합성 그리고 신진대사를 달성하는 세균류',
    hNm: '독립영양세균',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '獨立粒子沈澱',
    eNm: 'independence particle precipitation',
    hNm: '독립입자침전',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '獨立沈澱',
    eNm: 'independent precipitation',
    explain:
      '제 1영역에 속하는 침전으로 부유입자의 농도가 낮고 응결되지 않는 독립입자로서 침전은 입자가 서로 응집하는 성질을 갖지 않을 때 입자의 침전은 독립입자의 자유침전으로 보아 독립입자의 침전이라고 함',
    hNm: '독립침전',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毒性',
    eNm: 'toxic, toxicity, virulence',
    explain:
      '보통 독이 있는 성분을 뜻하며, 생물학에서는 병원균이 질병을 일으킬 수 있는 능력이나 숙주에서 나타나는 증상의 심각성을 칭함',
    hNm: '독성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毒性等價濃度',
    eNm: 'toxic equivalency factor (TEF)',
    hNm: '독성등가농도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '毒性學',
    eNm: 'toxicology',
    explain:
      '독물의 기원과 물리적ㆍ화학적 성질 또는 독물의 검출, 독물로 인한 중독의 진단, 치료 및 예방 따위를 주로 연구하는 학문',
    hNm: '독성학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '蛇籠堰工法',
    eNm: 'stone method',
    explain:
      '물이 흐르는 계곡의 토사 유출이나 하천의 비탈면의 침식을 막기 위해 돌을 뭉쳐놓은 돌망태를 이용하는 공법',
    hNm: '돌망태공법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '突發洪水',
    eNm: 'flash flood, freshet',
    explain:
      '유역의 면적이 좁은 지역에 집중적인 강우현상이 일어날 때 하천에 유입되는 물의 양이 짧은 기간에 급증하여 잠시 나타나는 홍수.',
    hNm: '돌발홍수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '突發洪水警報',
    eNm: 'flash flood warning',
    hNm: '돌발홍수경보',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '突發洪水警報',
    eNm: 'flash flood warning',
    hNm: '돌발홍수경보',
    rgsdt: '2023-09-14',
  },
  {
    eNm: 'stone pitching break water',
    explain: '바깥은 장석으로 내부는 거친돌로 채운 방파제',
    hNm: '돌붙임 방파제',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'stoney   gate',
    explain: '롤러가 수문과 홈통 사이에 끼어있는 형식의 수문',
    hNm: '돌수문',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '突然變異',
    eNm: 'mutagenic, mutation',
    hNm: '돌연변이',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '突堤',
    eNm: 'jetty',
    hNm: '돌제',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '突堤',
    eNm: 'jetty',
    hNm: '돌제',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '突出水制',
    eNm: 'spur dike, wing levee',
    hNm: '돌출수제',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '突出水制',
    eNm: 'spur dike, wing levee',
    hNm: '돌출수제',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '突風',
    eNm: 'gust',
    explain: '10분이내에평균풍속보다5m/s이상불어오는강한바람',
    hNm: '돌풍',
    rgsdt: '2016-11-18',
  },
  {
    cNm: '突風',
    eNm: 'gust',
    explain: '10분이내에평균풍속보다5m/s이상불어오는강한바람',
    hNm: '돌풍',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '突風前線',
    eNm: 'gust front',
    explain: '하강기류와 상승기류 아래의 온난한 공기 사이에서 만들어지는 전선',
    hNm: '돌풍전선',
    rgsdt: '2016-11-21',
  },
  {
    cNm: '突風前線',
    eNm: 'gust front',
    explain: '하강기류와 상승기류 아래의 온난한 공기 사이에서 만들어지는 전선',
    hNm: '돌풍전선',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '突風前線',
    eNm: 'gust front',
    explain: '하강기류와 상승기류 아래의 온난한 공기 사이에서 만들어지는 전선',
    hNm: '돌풍전선',
    rgsdt: '2023-10-10',
  },
  {
    hNm: '동간 저류',
    rgsdt: '2016-11-23',
  },
  {
    hNm: '동간 저류',
    rgsdt: '2023-09-14',
  },
  {
    eNm: 'freezing method ',
    explain: '지반 중의 물을 동결시켜 붕괴나 용수의 누출을 방지하는 굴착공법',
    hNm: '동결공법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '凍結濃縮法',
    eNm: 'freeze concentration method',
    explain:
      '열에 약한 용질에 대하여 적용하는 농축으로 용매를 동결시켜 용질을 분리 농축하는 방법',
    hNm: '동결농축법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '凍結防止裝置',
    eNm: 'frosting prevention devices',
    explain:
      '관내 또는 시설물 내에서 물의 동결로 인한 파손피해를 막기 위해 설치한 장치',
    hNm: '동결방지장치',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '凍結性 土壤',
    eNm: 'frost-susceptible soil',
    explain:
      '동상(凍上, frost heaving)현상이 일어나기 좋은 조건을 가지고 있는 토양으로 대수층으로부터 모세관 현상으로 물이 상승하기 좋은 토양',
    hNm: '동결성 토양',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '凍結深度',
    eNm: 'freezing depth ',
    explain: '지반에서 동상현상이 미치지 못하는 땅의 깊이',
    hNm: '동결심도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '凍結**作用',
    eNm: 'frost wedging',
    explain:
      '암석내 불연속면내 얼음이 형성되어 암석을 강제로 벌어지게 하는 현상',
    hNm: '동결쐐기작용',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '凍結**作用',
    eNm: 'frost wedging',
    explain:
      '암석내 불연속면내 얼음이 형성되어 암석을 강제로 벌어지게 하는 현상',
    hNm: '동결쐐기작용',
    rgsdt: '2023-09-18',
  },
  {
    cNm: '凍結融解作用',
    eNm: 'frost action',
    explain:
      '물질 내부에 존재하는 수분의 반복적인 동결과 융해로 인해 토양이나 암석에서 발생하는 다양한 효과',
    hNm: '동결융해작용',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '凍結再融解法',
    eNm: 'freezing refusion process',
    explain:
      '슬러지를 동결하여 재 융해하면 탈수성과 침강성이 좋아지는 현상을 이용해서 탈수처리의 전처리로 사용하는 방법',
    hNm: '동결재융해법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '凍結劑',
    eNm: 'freezing mixture',
    explain: '온도를 0℃ 이하로 낮추기 위한 혼합제',
    hNm: '동결제',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '凍結指數',
    eNm: 'freezing index',
    hNm: '동결지수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '凍結浸透',
    eNm: 'frost penetration',
    explain:
      '지표근처 토양의 온도가 물의 동결온도 이하로 내려가 토양 내부의 수분이 지표로부터 얼어 내려가는 것',
    hNm: '동결침투',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '凍結風化作用',
    eNm: 'frost weathering',
    explain: '빙하지역이 아닌 추운 지역에서 발생하는 풍화작용',
    hNm: '동결풍화작용',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動力學',
    eNm: 'dynamics',
    explain: '힘, 물체의 운동, 가속에 관한 학문',
    hNm: '동력학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '堤頂',
    eNm: 'top of the dam, crest level of the dam',
    hNm: '동마루',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動物群',
    eNm: 'fauna',
    explain: '특정 지역 안에 서식하는 모든 동물개체들을 의미',
    hNm: '동물군',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'animal virus',
    explain: '바이러스 중 동물에 기생하여 살아가는 바이러스',
    hNm: '동물바이러스',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動物糞尿',
    eNm: 'excreta of animal manure',
    explain: '가축과 야생동물이 발생시키는 분뇨와 이의 처리산물',
    hNm: '동물분뇨',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '動物流行病性',
    eNm: 'epizootic disease',
    explain: '가축의 전염병이 계속하여 발생하는 것 ',
    hNm: '동물유행병성',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動物浮遊生物',
    eNm: 'zooplankton',
    explain: '식물플랑크톤을 먹이로 서식하는 플랑크톤',
    hNm: '동물플랑크톤',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '凍傷抑制層',
    eNm: 'non-frost susceptible base',
    hNm: '동상억제층',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '同素體',
    eNm: 'allotrope, allotrophy',
    explain: '원소가 같으나 모양과 성질이 다른 홑원소물질',
    hNm: '동소체',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動水傾斜',
    eNm: 'hydraulic gradient',
    explain:
      '동수경사는 두 지점의 지하수위의 차이를 두 지점간의 거리로 나눈 비를 말하며, 지하수의 이동을 일으키는 원동력',
    hNm: '동수경사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動水傾斜線',
    eNm: 'hydraulic grade line, H.G.L',
    explain:
      '수로를 따라 각 지점의 위치수두와 압력수두의 합을 수평기준면에서 연직으로 나타낸 점을 연결한 선으로 관로 문제를 이해하고 해결하는데 유용하게 사용ㅇㄹㅇㅇ',
    hNm: '동수경사선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動水傾斜線',
    eNm: 'hydraulic grade line, H.G.L',
    explain:
      '수로를 따라 각 지점의 위치수두와 압력수두의 합을 수평기준면에서 연직으로 나타낸 점을 연결한 선으로 관로 문제를 이해하고 해결하는데 유용하게 사용',
    hNm: '동수경사선',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '動水傾斜線',
    eNm: 'hydraulic grade line, H.G.L',
    explain:
      '수로를 따라 각 지점의 위치수두와 압력수두의 합을 수평기준면에서 연직으로 나타낸 점을 연결한 선으로 관로 문제를 이해하고 해결하는데 유용하게 사용할 수 있다. ',
    hNm: '동수경사선',
    rgsdt: '2023-10-12',
  },
  {
    cNm: '動水句配',
    eNm: 'hydraulic gradient',
    explain:
      '동수구배는 두 지점의 지하수위의 차이를 두 지점간의 거리로 나눈 비를 말하며, 지하수의 이동을 일으키는 원동력',
    hNm: '동수구배',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動水半徑',
    eNm: 'hydraulic radius, mean hydraulic depth, hydraulic mean radius',
    hNm: '동수반경',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動水壓',
    eNm: 'hydrodynamic pressure',
    explain:
      '관로 내부에 물이 차있거나 흐를 때 관로의 각 지점에 미치는 물의 압력',
    hNm: '동수압',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動水力學',
    eNm: 'hydrodynamics',
    explain:
      '움직이는 물에서 작용하는 힘을 알아보는 것으로, 유체입자의 변위와 속도 및 가속도로 유체의 운동을 기술하는 물의 흐름에 대한 운동학에 추가로 이들의 성질과 힘간의 관계를 다루는 학문',
    hNm: '동수역학',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動水力學的分散',
    eNm: 'hydrodynamic dispersion',
    hNm: '동수역학적 분산',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動水力學的 分散系數',
    eNm: 'coefficient of hydrodynamic dispersion',
    hNm: '동수역학적 분산계수',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '動壓',
    eNm: 'dynamic pressure',
    hNm: '동압',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動力學的相似',
    eNm: 'dynamic similarity',
    explain:
      '질량과 힘의 상사성을 말하는 것으로, 원형과 모형에서 2개의 운동에 내포된 여러 가지 대응하는 물체의 질량비가 같고 또 물체의 운동에 영향을 주는 어떤 힘이라도 그 힘들의 비가 같을 때 성립하는 상사(similarity)',
    hNm: '동역학적 상사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動搖跳水',
    eNm: 'oscillating jump',
    hNm: '동요도수',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '動搖跳水',
    eNm: 'oscillating jump',
    hNm: '동요도수',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '動搖跳水',
    eNm: 'oscillating jump',
    hNm: '동요도수',
    rgsdt: '2023-10-19',
  },
  {
    cNm: '動搖跳水',
    eNm: 'oscillating jump',
    hNm: '동요도수',
    rgsdt: '2023-10-13',
  },
  {
    cNm: '同位元素',
    eNm: 'isotope',
    explain: '원자번호는 같으나 원자량이 다른 원소',
    hNm: '동위원소',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動的洗掘',
    eNm: 'Live-bed scour',
    hNm: '동적세굴',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '動的洗掘',
    eNm: 'Live-bed scour',
    hNm: '동적세굴',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '動的洗掘',
    eNm: 'Live-bed scour',
    hNm: '동적세굴',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '動的吸入水頭',
    eNm: 'dynamic suction head',
    explain:
      '흡입실양정(actual suction head)과 흡입관 손실수두(head loss in the suction line)의 합',
    hNm: '동적흡입수두',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'kinematic viscosity',
    explain: '유체의 점성도를 같은 온도 조건에서 그 유체의 밀도로 나눈 것',
    hNm: '동점성',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'kinematic viscosity',
    explain: '유체의 점성도를 같은 온도 조건에서 그 유체의 밀도로 나눈 것',
    hNm: '동점성',
    rgsdt: '2023-10-16',
  },
  {
    cNm: '動粘性係數',
    eNm: 'dynamic viscosity',
    hNm: '동점성계수',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '動粘性係數',
    eNm: 'dynamic viscosity',
    hNm: '동점성계수',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '同定',
    eNm: 'identification',
    explain:
      '대상이 되는 생물개체의 특징을 조사하고, 기지(旣知)의 어떤 생물종 혹은 분류군과 일치하는지를 결정하는 작업',
    hNm: '동정',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '同定',
    eNm: 'identification',
    explain:
      '대상이 되는 생물개체의 특징을 조사하고, 기지(旣知)의 어떤 생물종 혹은 분류군과 일치하는지를 결정하는 작업',
    hNm: '동정',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '同定試驗',
    eNm: 'identity test',
    hNm: '동정시험',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '同定試驗',
    eNm: 'identity test',
    hNm: '동정시험',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '冬至',
    eNm: 'summer solstice',
    explain: '북반구에서 태양의 남중고도가 가장 낮은 날',
    hNm: '동지',
    rgsdt: '2016-11-21',
  },
  {
    cNm: '冬至',
    eNm: 'summer solstice',
    explain: '북반구에서 태양의 남중고도가 가장 낮은 날',
    hNm: '동지',
    rgsdt: '2023-10-10',
  },
  {
    cNm: '同質亂流',
    eNm: 'homogeneous turbulent',
    hNm: '동질난류',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '同質亂流',
    eNm: 'homogeneous turbulent',
    hNm: '동질난류',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '同次性',
    eNm: 'homogeneity',
    hNm: '동차성',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '同次性',
    eNm: 'homogeneity',
    hNm: '동차성',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '凍土現像',
    eNm: 'frozen-ground phenomena',
    explain: '지면의 온도가 0oC이하의 상태로 지하의 수분이 동결되는 현상',
    hNm: '동토현상',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '同化',
    eNm: 'anabolism, assimilation',
    explain:
      '생물이 자연계에 존재하는 무기물이나 저분자 유기물을 이용하여 고분자화합물을 합성하는 작용',
    hNm: '동화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '同化',
    eNm: 'anabolism, assimilation',
    explain:
      '생물이 자연계에 존재하는 무기물이나 저분자 유기물을 이용하여 고분자화합물을 합성하는 작용',
    hNm: '동화',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '앙用',
    eNm: 'assimilation',
    explain:
      '에너지를 이용하여 단순한 화합물을 복잡한 고분자 화합물로 변환시키는 생물체 내의 화학변화 현상',
    hNm: '동화작용',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '阡',
    eNm: 'ridge between fields, levee',
    explain: '흙으로 쌓여진 언덕이나 둑',
    hNm: '두렁',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '頭部侵蝕',
    eNm: 'headcut',
    hNm: '두부침식',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '頭部侵蝕',
    eNm: 'headcut',
    hNm: '두부침식',
    rgsdt: '2023-09-14',
  },
  {
    eNm: 'bank, levee',
    explain:
      '하천이나 호수의 물의 범람을 막고 물을 가두기 위해 흙이나 콘크리트 등으로 만든 구조물',
    hNm: '둑',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'bank heightening',
    explain: '저수지의 둑을 높이는 것',
    hNm: '둑 높임',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'heap up',
    explain: '흙돋움을 하여 지반을 높이는 작업',
    hNm: '둑돋기',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'levee crown',
    explain: '수리구조물의 가장 상부 부분',
    hNm: '둑마루',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'base of levee',
    explain: '제방의 횡단방향 시점과 끝점 사이의 구간',
    hNm: '둑자리',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'berm',
    explain: '축지, 옹벽, 제방 등에서 비탈과 비탈 사이의 평평한 구간',
    hNm: '둑턱',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '鈍化河川',
    eNm: 'sluggish stream',
    hNm: '둔화하천',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'girdle lamella',
    explain: '엽록체의 틸라코이드 배열의 한 형태로 둘레를 싸는 라멜라 층',
    hNm: '둘레라멜라',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'drum gate',
    explain: '부채꼴 모양의 단면의 수문을 가지는 여수로에 위치하는 수문의 일종',
    hNm: '드럼수문',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等價傾斜',
    eNm: 'equivalent gradient',
    explain:
      '하천에서 상·하류 구간별로 변하는 종단 경사를 전체 구간에서 대표하는 경사',
    hNm: '등가경사',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'equivalent length',
    hNm: '등가길이',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'equivalent length',
    hNm: '등가길이',
    rgsdt: '2023-09-14',
  },
  {
    eNm: 'equivalent per milinon, EPM',
    explain: '물 1kg이 함유하는 용질의 mg당량수',
    hNm: '등가백만분율',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等價溫度',
    eNm: 'equivalent temperature',
    hNm: '등가온도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等價粗度',
    eNm: 'equivalent roughness',
    explain:
      '개수로 별 하천의 횡단면에서 각기 다른조도를 해석의 용이함을 위하여 하나의 대표 값으로 나타낸 조도',
    hNm: '등가조도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等降水量線,等雨線',
    eNm: 'isohyet, equipluve, isomer',
    explain: '평면지도에서 강수량이 같은 지점을 연결한 선',
    hNm: '등강수량선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等降水量線圖',
    eNm: 'isohyetal map',
    explain: '강수량이 같은 지점을 연결한 선들을 나타낸 지도',
    hNm: '등강수량선도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等傾斜線',
    eNm: 'same inclination line',
    explain: '수평면에 대해 일정한 경사를 가지는 지표상의 선',
    hNm: '등경사선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等高線',
    eNm: 'contour lines ',
    explain: '지형도상에서 지표면의 해발고도가 같은 지점을 연결한 선',
    hNm: '등고선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等高線耕作',
    eNm: 'contour cultivation, contour farming',
    explain:
      '산과 같은 경사지에서 강우 시 빗물에 의한 토양의 유실을 방지하기 위해 등고선을 따라 작물을 재배하는 방법',
    hNm: '등고선 경작',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等高線灌漑 ',
    eNm: 'Contour irrigation',
    explain:
      '경사가 심한 지역에서 등고선을 따라 이랑을 만들고 물을 공급하는 방식',
    hNm: '등고선 관개',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等高線間隔',
    eNm: 'contour interval',
    explain: '인접한등고선이나타내는표고차(標高差)',
    hNm: '등고선간격',
    rgsdt: '2016-11-18',
  },
  {
    cNm: '等斷面水路',
    eNm: 'uniform channel',
    hNm: '등단면수로',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '燈臺',
    eNm: 'light house',
    explain: '선박을 안전하게 항 내로 유도하기 위한 시설',
    hNm: '등대',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '燈臺',
    eNm: 'light house',
    explain: '선박을 안전하게 항 내로 유도하기 위한 시설',
    hNm: '등대',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '等流',
    eNm: 'uniform flow',
    explain:
      '등류는 정류 중에서 거리에 따라 유속과 유적이 일정한 흐름으로, ∂V/∂t =0, ∂V/∂l=0가 성립하는 흐름',
    hNm: '등류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等流傾斜',
    eNm: 'normal slope',
    hNm: '등류경사',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等流水深',
    eNm: 'normal depth',
    explain:
      '등류 상태로 흐르는 흐름의 수심으로, 유량과 수로단면, 에너지경사가 주어지면 한 값으로 정의됨',
    hNm: '등류수심',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等流水位',
    eNm: 'normal stage',
    hNm: '등류수위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等流流量',
    eNm: 'normal discharge',
    explain:
      '등류상태 흐름의 유량을 말하며, 유량은 Manning 공식을 이용하여 연속방정식으로 구함',
    hNm: '등류유량',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等流流速',
    eNm: 'normal velocity',
    hNm: '등류유속',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等方性 ',
    eNm: 'isotropy ',
    explain:
      '한 지점에서 물질의 중요한 특성이 방향에 관계없이 모두 동일한 상태',
    hNm: '등방성 ',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等方性亂流',
    eNm: 'isotropic turbulence',
    hNm: '등방성난류',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等方性流體',
    eNm: 'isotropic fluid',
    explain: '방향에 따라 수리학적 성질이 달라지지 않는 유체',
    hNm: '등방성유체',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'isopercental',
    hNm: '등백분율',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等比增加法',
    eNm: 'geometric series method',
    explain:
      '급수인구의 추정방법의 하나로 연 평균 인구 증가율을 일정하게 보는 것',
    hNm: '등비급수법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等速沈降',
    eNm: 'uniform settling',
    hNm: '등속침강',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等速沈降速度',
    eNm: 'terminal setting velocity',
    hNm: '등속침강속도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等深線',
    eNm: 'isobath',
    explain: '해저 지형의 표현을 위해 같은 깊이의 점을 연결한 선',
    hNm: '등심선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等壓面',
    eNm: 'Equipotential of Area',
    hNm: '등압면',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '等壓面',
    eNm: 'Equipotential of Area',
    hNm: '등압면',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '等壓面',
    eNm: 'Equipotential of Area',
    hNm: '등압면',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '等壓線',
    eNm: 'isobar',
    explain: '같은 기압을 갖는 지점을 이어서 얻어지는 곡선',
    hNm: '등압선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等溫線',
    eNm: 'isotherm',
    explain: '일기도상에서 기온이 같은 지점을 연결한 등치선',
    hNm: '등온선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等溫位 ',
    eNm: 'equipotential temperature',
    hNm: '등온위',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等溫位線',
    eNm: 'isentrope',
    explain: '온위가 같은 지점을 연결한 선',
    hNm: '등온위선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等溫條件',
    eNm: 'Isothermal Condition',
    explain: '온도변화가없는열역학적조건',
    hNm: '등온조건',
    rgsdt: '2016-11-18',
  },
  {
    cNm: '等溫膨脹',
    eNm: 'isothermal expansion',
    explain: '기체의 온도가 일정한 상태에서 팽창하는 것',
    hNm: '등온팽창',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等溫平衡',
    eNm: 'isothermal equilibrium',
    explain:
      '일정 온도 하에서 화학 반응이 평형을 이른 경우 각 물질의 농도간의 관계를 나타내는 식',
    hNm: '등온평형',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等溫吸着線',
    eNm: 'adsorption isotherm',
    explain:
      '평형상태에서 흡착된 물질의 양과 흡착되지 않은 기체의 압력 또는 용액에 남아있는 물질의 농도와의 관계를 나타내는 곡선',
    hNm: '등온흡착선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等溫吸着式',
    eNm: 'isotherm adsorption equation',
    explain:
      '평형상태에서 흡착된 물질의 양과 흡착되지 않은 기체의 압력 또는 용액에 남아있는 물질의 농도와의 관계를 나타내는 식',
    hNm: '등온흡착식',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等雨量線',
    eNm: 'isohyetal line',
    explain:
      '우량의 분포를 알기위해 지도상에서 우량이 같은 지점을 연결하여 그린 선',
    hNm: '등우량선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等雨線圖',
    eNm: 'isohyetal map',
    explain: '등우선을 나타낸 지도',
    hNm: '등우선도',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等雨線法',
    eNm: 'isohyetal method',
    explain: '등우선 간의 면적을 구하여 유역의 평균 강우량을 산정하는 방법',
    hNm: '등우선법',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等雨線法',
    eNm: 'isohyetal method',
    explain: '등우선 간의 면적을 구하여 유역의 평균 강우량을 산정하는 방법',
    hNm: '등우선법',
    rgsdt: '2023-10-17',
  },
  {
    cNm: '等雨線補間法',
    eNm: 'isohyetal interpolation method',
    hNm: '등우선보간법',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '等雨線補間法',
    eNm: 'isohyetal interpolation method',
    hNm: '등우선보간법',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '等流量法',
    eNm: 'Equal Discharge Increment Method',
    hNm: '등유량법',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '等流量法',
    eNm: 'Equal Discharge Increment Method',
    hNm: '등유량법',
    rgsdt: '2023-09-14',
  },
  {
    cNm: '等積變化',
    eNm: 'isochoric change',
    hNm: '등적변화',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等電點',
    eNm: 'isoelectric point',
    explain:
      '양쪽성 전해질이나 콜로이드 입자 등이 가진 전하의 대수합이 0이 될 때의 상태를 용액의 수소이온지수 pH로 나타낸 것',
    hNm: '등전점',
    rgsdt: '2016-11-25',
  },
  {
    cNm: '等電點',
    eNm: 'isoelectric point',
    explain:
      '양쪽성 전해질이나 콜로이드 입자 등이 가진 전하의 대수합이 0이 될 때의 상태를 용액의 수소이온지수 pH로 나타낸 것',
    hNm: '등전점',
    rgsdt: '2023-09-12',
  },
  {
    cNm: '登震度',
    eNm: 'isoseismal',
    explain: '지진이 발생 후 진도가 같은 지역을 연결한 선',
    hNm: '등진도',
    rgsdt: '2016-11-23',
  },
  {
    cNm: '等値觀法',
    eNm: 'the equivalent pipe method',
    explain:
      '실제관 1개 또는 여러 개를 마찰손실이 같은 등치관으로 가정하고 관망을 해석하는 방법',
    hNm: '등치관법',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'equipotential line',
    explain: '지하수의 압력수두가 같은 점을 연이은 선',
    hNm: '등포텐셜선',
    rgsdt: '2016-04-15',
  },
  {
    cNm: '等風速線',
    eNm: 'isotach',
    explain: '일기도에서 풍속이 같은 곳을 연결한 선',
    hNm: '등풍속선',
    rgsdt: '2016-11-21',
  },
  {
    cNm: '等風速線',
    eNm: 'isotach',
    explain: '일기도에서 풍속이 같은 곳을 연결한 선',
    hNm: '등풍속선',
    rgsdt: '2023-10-10',
  },
  {
    eNm: 'Dethridge wheel flowmeter',
    hNm: '디드리지 유량계',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'Dethridge wheel flowmeter',
    hNm: '디드리지 유량계',
    rgsdt: '2023-09-14',
  },
  {
    eNm: 'diaminobenzidine method',
    explain: '시료의 세렌을 분석하기 위한 화학분석법',
    hNm: '디아미노벤지딘법',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'diazotization method',
    explain: '시료의 유기인 양을 파악하기 위한 분석방법',
    hNm: '디아조화법',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'Diethyl-p-phenylenediamine method',
    explain: '잔류염소 측정법',
    hNm: '디에틸-p-페닐렌디아민법',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'silver diethyldithiocarbamate method',
    explain: 'DDTC법으로도 불리우는 비소측정법',
    hNm: '디에틸디티오카바민산은법',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'dichloroacetic acid',
    explain: '아세트산의 메틸기의 수소를 염소로 치환한 형태의 화합물',
    hNm: '디클로로아세트산',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'diphenylamine reaction',
    explain: '질산염을 측정하기 위한 분석법',
    hNm: '디페닐아민반응',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'diphenylamine reaction',
    explain: '질산염을 측정하기 위한 분석법',
    hNm: '디페닐아민반응',
    rgsdt: '2023-09-19',
  },
  {
    eNm: 'diphenylcarbzaide method',
    explain: '흡광광도법을 사용하여 6가크롬을 측정하는 방법',
    hNm: '디페닐카바자이드법',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'deep well method',
    explain: '깊은 우물을 파서 양수함으로써 지하수의 수위를 낮추는 방법',
    hNm: '딥웰공법',
    rgsdt: '2016-11-23',
  },
  {
    eNm: 'edaphone',
    explain: '토양내부에 살고 있는 생물',
    hNm: '땅속생물',
    rgsdt: '2016-04-15',
  },
  {
    eNm: 'ground ice',
    hNm: '땅얼음',
    rgsdt: '2016-04-15',
  },
];

export default data_ko_da;
